### ISSUE TITLE
App crashes on "add integration" with bluetooth disabled since matter add-on is installed

### ISSUE THREAD

**Issue by probert94** [home-assistant/android#4867] opened 2024-12-03 05:56 UTC
**Home Assistant Android app version(s):** 2024.10.3-full

**Android version(s):** 13

**Device model(s):** Xiaomi Redmi Note 11 Pro 5G

**Home Assistant version:** 2024.11.3

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
I wanted to add my first Matter device (Tapo Smart Plug) and added the Matter Integration which also installed the Matter Server Add-On.
After that, whenever I clicked on "Add integration" the app crashed until I enabled Bluetooth.

**Companion App Logs:**
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.bluetooth.I e.BluetoothLeScannerstartScan(java.util.List, android.bluetooth.le.ScanSettings, android.bluetooth.le.ScanCallback)' on a null object reference
at com.wifiimprov.ImprovManagerfindDevices(Improv Manager.kt:243)
at io.homeassistant.companion.android.improv.ImprovRepositorylmpl.startScanning(ImprovRepositorylmpl. kt:65)
at io.homeassistant.companion.android.webview.WebViewPresenterImpl$startScanningForImprov$1$1.invokeSuspend(WebViewPresenterImpl.kt:488)
at kotlin.coroutines.jvm.internal.BaseContinuationlmpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTa sk.kt:101)
at kotlinx.coroutines.internal.LimitedDispatcher$Worker fun(LimitedDispatcherkt:113)  at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt: 89)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineSchedulerkt:589)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineSchedulerkt:823)
at kotlinx.coroutines.scheduling.CoroutineScheduler$WorkerrunWorker(CoroutineSchedulerkt:720) 

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by jpelgrom** [comment] 2024-12-03 06:00
Duplicate of #4761. This is unrelated to Matter, and is fixed if you switch to the app beta release.

**Closed by jpelgrom** 2024-12-03 06:00 UTC
Labels: bug

**Comment by probert94** [comment] 2024-12-03 06:10
@jpelgrom thank you for the information.
Unfortunately I did not find the other issue, probably because I thought it is related to Matter.
