### ISSUE TITLE
[ANDROID 7.0 and HA Android 2024.3.5]: Application cannot start on Android. Crashing and keeps asking to restart App

### ISSUE THREAD

**Issue by Softwaremaker** [home-assistant/android#4339] opened 2024-04-09 00:23 UTC
[ANDROID 7.0 and HA Android 2024.3.5]: Application cannot start on Android. Crashing and keeps asking to restart App

Was working in all previous version until the update of 2024.3.5

- All HA widgets cannot load anymore
- Bringing up HA 2024.3.5 on Android will crash the app. App will crash when starting
- Reinstalling HA 2024.3.5 on Android - Setting it up with credentials will go through by the App will crash when starting

Tried to side-load an earlier version and has **NO** problems described above but this is not the solution for me.

Any advice or workaround until the next version 2024.4.1 gets released on the Play Store ?

**Comment by dshokouhi** [comment] 2024-04-09 00:25
Duplicate of https://github.com/home-assistant/android/issues/4323 will be fixed in next release soon.

**Comment by dshokouhi** [comment] 2024-04-09 00:26
You can sideload the pre release APK from the releases section if you need the update

**Closed by dshokouhi** 2024-04-09 00:25 UTC
Labels: bug

**Comment by Softwaremaker** [comment] 2024-04-09 00:38
@dshokouhi Thank you ! I cannot deploy side loaded apps - do you know when the 2024.4.1will be released on the play store so I can update the users ? 

Thanks !

**Comment by dshokouhi** [comment] 2024-04-09 00:43
it just went live in the beta for the play store a couple hours ago, we will be sending it to prod shortly

**Comment by Softwaremaker** [comment] 2024-04-09 00:44
Thank you @dshokouhi
