### ISSUE TITLE
The Tracker can not work

### ISSUE THREAD

**Issue by steven52880** [home-assistant/android#1853] opened 2021-10-29 16:55 UTC
**Home Assistant Android version:**
 2021.10.0-full
**Android version:**
 Android 9
**Phone model:**
Redmi Note 8 Pro
**Home Assistant version:**
2021.10.6

**Description of problem:**

Hi, I tried hass today but the app can not get the gps data.

I have allowed the app to locate in settings, and I have turn the location sensors on. Other map apps can locate.
But the state of the "Background Location" is empty. All sensor data can be read exept the gps data. It shows "unavailable" or "unknow" in hass. 

I pasted all the logs containing "LocBroadcastReceiver" below.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
10-30 00:15:25.155 16511 16555 D LocBroadcastReceiver: Registering for zone based location updates
10-30 00:15:25.706 16511 16555 D LocBroadcastReceiver: Registering for location updates.
10-30 00:41:17.093 30173 30173 D LocBroadcastReceiver: Received location update.
10-30 00:15:25.978 16511 16511 D LocBroadcastReceiver: Not requesting accurate location, last accurate location was too recent

```

**Screenshot of problem:**

**Additional information:**

**Comment by steven52880** [comment] 2021-11-06 16:05
I find out GPSLogger can get the proper location and send it to hass. It can work without Google service. So why Google services necessary to the android app? Is there any way to use the location without Google service?

**Comment by dshokouhi** [comment] 2021-11-06 16:08
> So why Google services necessary to the android app?

Because Google makes developers lives very easy with API's that we can consume that take minimal effort compared to building things out by hand. But we are open source so you can submit a PR to update it.



> Is there any way to use the location without Google service?

No please see 

https://companion.home-assistant.io/docs/core/android-flavors

with that said I am closing as duplicate of #1511

**Closed by dshokouhi** 2021-11-06 16:08 UTC
Labels: bug, location-tracking
