### ISSUE TITLE
App closed, widget entities and service buttons are not updating/working 

### ISSUE THREAD

**Issue by freemann** [home-assistant/android#849] opened 2020-08-31 07:11 UTC
**Home Assistant Android version:**
2.3.0-306-full

**Android version:**
10.0.7

**Phone model:**
OnePlus 7pro
**Home Assistant version:**
0.114.3

**Last working Home Assistant release (if known):**
Unknown

**Description of problem:**
After closing the app on my phone, the widgets for entities and services buttons are not working anymore.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2020-08-31 12:40
Duplicate of #848 you need to keep the app running in the background.

**Closed by dshokouhi** 2020-08-31 12:40 UTC
Labels: bug
