### ISSUE TITLE
Pixel 4A : no location/zone update for days

### ISSUE THREAD

**Issue by cpainchaud** [home-assistant/android#1925] opened 2021-11-15 14:25 UTC
**Home Assistant Android version:** 2021.10.0-full

**Android version:** 12

**Phone model:** Pixel 4a

**Home Assistant version:** core-2021.10.6

**Last working Home Assistant release (if known):**

**Description of problem:**
This is my wife's phone, we have identical setup (Pixel4a , android 12, same app version and configurations). My phone sends location update 100% of the time, for my phone it can be days without a single update so she will remain Home or Away forever. I tried reinstalling the phone, reinstalling the app, change all sorts of settings.....

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

see attached log file
[homeassistant_companion_log_10-15-2021_15-20-19.txt](https://github.com/home-assistant/android/files/7539268/homeassistant_companion_log_10-15-2021_15-20-19.txt)
[homeassistant_companion_log_10-15-2021_15-0-53.txt](https://github.com/home-assistant/android/files/7539224/homeassistant_companion_log_10-15-2021_15-0-53.txt)

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2021-11-15 16:27
Most of these updates google was sending that device is hours old if not longer than current time so it makes sense for us to skip those. The second log has no location updates at all.

Try these steps and when you onboard make sure to click the location toggle and grant all permissions. Follow them precisely as reinstalling the app does not do the same thing we want to achieve which is to bypass autobackup.

https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

The issue here is that google is sending that device very old updates, we only accept updates that are 5 minutes old and we have no control over what google sends us. We can only process incoming data.

If the steps above dont help then check: https://companion.home-assistant.io/docs/troubleshooting/faqs/#location-is-not-updating-in-android-app

**Comment by cpainchaud** [comment] 2021-11-15 17:07
Yes  I have been wondering about the 1 hours old issue as it's happening a lot/all time like if a timezone thing was creating the issue. it's always exactly 1 hour old.... I will try more and more settings again just in case but I have already check all the existing FAQs and procedures, reinstalled phone, app, etc etc. What's really weird is that we have exactly same phone!

**Comment by dshokouhi** [comment] 2021-11-15 17:11
This is the second time you mentioned "reinstalling phone app"  please note that is NOT the same as clearing data and the steps outlined in the link.  Reinstalling the app triggers autobackup which is what we want to avoid, clearing data is the only way around the autobackup. The steps outlined should be followed in order without skipping a beat.

If you see its always exaclty one hour off try checking if you can update the timezone on teh device, I believe those are taken by the carrier or connected network. Might be worth a check if its that precise :)

**Comment by cpainchaud** [comment] 2021-11-15 17:17
Since I had to reconfigure everything and re-authorize application privileges for locations and others I didn't think any sort of data back occured. I will force a clear and try again following exactly that procedure.

I will investigate timezone settings as well, we are on same network but who knows ...

**Comment by cpainchaud** [comment] 2021-11-17 15:57
Ok so I followed the procedure and the old timestamp issue is still there:
``
11-17 14:49:31.818 21772 21772 D LocBroadcastReceiver: Skipping location update due to old timestamp 1637139355000 compared to 1637156971818
``

this is making no sense :D

**Comment by dshokouhi** [comment] 2021-11-17 16:03
unfortunately we can only work with the data that google sends to us, if this is all google is sending then there is not much we can do. Any luck with checking the time zone?  What happens if you open google maps on the device? Does it get a realistic location update then? Keep maps open for about 1 minute as we get updates every 30 seconds passively.

**Comment by cpainchaud** [comment] 2021-11-17 16:09
my wife and I do share our position on Google maps, i can clearly see where she is and it's not matching what HA at any time. 

when I open Maps and Waze on her phone and keep it open, position is correct. restarting the app won't change anything.

timezone is accurate

**Comment by dshokouhi** [comment] 2021-11-17 16:15
can you look at the logs when that happens as maps is open please? lets look at the timestamp then.

Also once you get those logs can you test if the data is correct when you use `request_location_update` https://companion.home-assistant.io/docs/notifications/notification-commands#request-location-updates

Then also test enabling high accuracy mode: https://companion.home-assistant.io/docs/core/location#high-accuracy-mode

Please note the last 2 tests use a GPS lock so this is only for comparison sake testing as background updates use googles fused location service which uses thigns like cell towers for cheaper (on battery) positioning.

**Comment by cpainchaud** [comment] 2021-11-17 16:19
Logs with Maps open (time 17h17)
[homeassistant_companion_log_10-17-2021_17-18-31.txt](https://github.com/home-assistant/android/files/7556216/homeassistant_companion_log_10-17-2021_17-18-31.txt)

**Comment by cpainchaud** [comment] 2021-11-17 16:23
I am not trying high accuracy mode, i have enabled it but state remains=False?

**Comment by dshokouhi** [comment] 2021-11-17 16:26
So the updates look like they are trying to be correct but are still hours off the correct time. However you can still see them increase in the amount of time you'd expect. 

This is still really odd. If you enable the timezone sensor under app configuration I assume it shows the correct timezone? Do other sensors like Next Alarm and Last Reboot give the correct time?

**Comment by cpainchaud** [comment] 2021-11-17 16:27
> > I am not trying high accuracy mode, i have enabled it but state remains=False?
> 
> you have to enable it under the background location sensor setting first

ok it's now enabled. I can see in the logs it's confirmed but it keeps hitting the "old timestamp" issue.

logs attached:
[homeassistant_companion_log_10-17-2021_17-26-31.txt](https://github.com/home-assistant/android/files/7556273/homeassistant_companion_log_10-17-2021_17-26-31.txt)

**Comment by cpainchaud** [comment] 2021-11-17 16:33
> So the updates look like they are trying to be correct but are still hours off the correct time. However you can still see them increase in the amount of time you'd expect.
> 
> This is still really odd. If you enable the timezone sensor under app configuration I assume it shows the correct timezone? Do other sensors like Next Alarm and Last Reboot give the correct time?

Tz sensor find Paris GMT+1 which is fine. Next alarm sensor is fine as well

**Comment by dshokouhi** [comment] 2021-11-17 16:37
ok last thing, in the logs....the current time mentioned is correct for your current time right (the second time in millis)? Also the location reported is what you would expect it to be? trying to confirm that the issue is that the timestamp sent with the location request is old

**Comment by cpainchaud** [comment] 2021-11-17 16:41
> ok last thing, in the logs....the current time mentioned is correct for your current time right (the second time in millis)? Also the location reported is what you would expect it to be? trying to confirm that the issue is that the timestamp sent with the location request is old

yes everything looks consistent in term of timestamps except for the location update which is  coming from the past :D

**Comment by dshokouhi** [comment] 2021-11-17 16:49
ok well lets see if anyone else has any ideas because im honestly not sure at this point, its very strange but seems device specific

this is the API that we are using to determine the time: https://developer.android.com/reference/android/location/Location.html#getTime()

Whats most odd is that when you enabled high accuracy mode which use GPS directly it still gave the old time

**Comment by cpainchaud** [comment] 2021-11-17 17:05
yes this is odd as my phone is same model, we are on same network and I never had this issue.

**Comment by cpainchaud** [comment] 2021-11-23 10:45
I may have some interesting pieces of information! My wife's been telling me that since she was playing a new game game, her phone had erratic bugs and issues (dropped phone calls, weird gps issues, reboots...). That game is from Niantic (Pokemon Go producer) called "Pikmin" which is about planting flowers and catching pikmins around a bit like Pokemon Go. We have uninstalled it 3 days ago and no issues so far, I am planning to reinstall it next week to confirm the behavior.

That game may trigger an OS level bug ...

**Comment by cpainchaud** [comment] 2021-11-26 09:43
@dshokouhi , it's confirmed what I said earlier, Niantic's new game Pikmin seems to trigger at OS level which has this weird "old timestamps associated with GPS coordinates" issue trigger in HA application.

**Comment by cpainchaud** [comment] 2021-11-26 09:47
It feels like the issue is widespread https://www.reddit.com/r/PikminBloomApp/comments/qqyf0s/warning_the_pikmin_bloom_app_will_interfere_with/

**Comment by dshokouhi** [comment] 2021-11-26 19:05
Thanks for checking on this @cpainchaud theres really nothing we can do if all we get are old updates when this app is installed. As this not anything we can solve in the app I am going to close this. Hopefully the app will be updated to avoid these odd issues.

**Closed by dshokouhi** 2021-11-26 19:05 UTC
Labels: bug, location-tracking
