### ISSUE TITLE
Wear OS - NFC tag read

### ISSUE THREAD

**Issue by hkusulja** [home-assistant/android#1829] opened 2021-10-24 18:17 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Please implement NFC read tag for Wear OS, so it can trigger action, like it persists for mobile app.

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by hkusulja** [comment] 2021-12-22 14:00
@dshokouhi can you please update status on this? Thank you

**Comment by dshokouhi** [comment] 2021-12-22 14:01
@hkusulja it will be ready when its ready.

**Comment by hkusulja** [comment] 2021-12-22 14:03
@dshokouhi of course, i just mean, is there some related git repo branch for this, does the team work on this, or is still pending etc.
Thank you anyhow !!

**Comment by dshokouhi** [comment] 2021-12-22 14:08
@hkusulja everybody is a volunteer. Unless you see a PR submitted assume people are working on whatever it is they want to work on. Volunteers dont need to give status updates.

With that said one thing we need to investigate is if this is even possible, we had a user on reddit mention that on Wear OS NFC is restricted to payments only. If that is the case then we cannot proceed with this change.

**Comment by hkusulja** [comment] 2022-01-09 10:57
Let's wait and see - https://issuetracker.google.com/issues/213599626

**Comment by garv3** [comment] 2022-04-23 09:21
We definitely need this!

**Comment by TBSniller** [comment] 2022-05-01 11:58
Someone on Reddit says it's possible to read tags using his own app on WearOS with Galaxy Watch 4: https://www.reddit.com/r/homeassistant/comments/p7dis0/does_anyone_know_if_there_is_home_assistant_app/h9v0vyz?utm_medium=android_app&utm_source=share&context=3
Would be lucky if he reads the comment and give us a bit insight.

**Comment by ShellAddicted** [comment] 2022-05-18 17:43
@TBSniller My mistake, Only the HCE stack is available.
For a reference implementation (not mine) see:
https://github.com/Lexycon/android-pn532-hce

**Comment by TBSniller** [comment] 2022-07-31 20:21
@ShellAddicted: Thanks for making clear and sharing an example!

**Comment by n00bcodr** [comment] 2022-08-07 06:16
Samsung Health App on my My Galaxy Watch 4 has the ability to read NFC tags, probably for scanning Gym equipment and to start appropriate workout. 

That would mean there is an option for other apps to use NFC on the watch, probably?

**Comment by dshokouhi** [comment] 2022-08-07 22:51
> Samsung Health App on my My Galaxy Watch 4 has the ability to read NFC tags, probably for scanning Gym equipment and to start appropriate workout. 
> 
> That would mean there is an option for other apps to use NFC on the watch, probably?

A Samsung app on a Samsung device might just be a special case. If it's supported on all wear OS devices then Google would have it documented.

They have yet to respond to the issue above.

**Comment by dshokouhi** [comment] 2022-10-10 14:19
> @dshokouhi , maybe that could help in the feature development:
> https://play.google.com/store/apps/details?id=com.contorra.golfpad
> I will dig a little in the next week to try...

Take a look at Google's update in the issue tracker

**Comment by grossqx** [comment] 2022-11-01 14:07
I'd be happy to test this on wearos 3 on a pixel watch if this issue ever gets any development.

**Comment by augustodinizl** [comment] 2022-11-24 11:40
@dshokouhi , it's possible to use the hce stack of wear os via the companion app (maybe with a new sort of "card" in the app) to simulate a nfc/rfid tag that already exists?

**Comment by Californian** [comment] 2023-01-31 01:39
Yeah I'm not sure what would prevent the use of HCE. It would mean that one's phone still needed to be in range in order for the scanning to work, but that would still cover some use cases.

I'm not sure why wearos devices either don't have secure elements (maybe power requirements), or why android requires one in the first place for basic NFC reads.

**Comment by dshokouhi** [comment] 2023-07-30 19:50
Going to close this request as the Google issue was also closed as intended behavior. Until a watch comes out with the proper hardware and feature we won't be able to work on this. Happy to revisit once that is the case

**Closed by dshokouhi** 2023-07-30 19:50 UTC
Labels: enhancement, Wear OS

**Comment by EnigmaticAnomaly** [comment] 2024-01-28 23:47
> @hkusulja everybody is a volunteer. Unless you see a PR submitted assume people are working on whatever it is they want to work on. Volunteers dont need to give status updates.
> 
> With that said one thing we need to investigate is if this is even possible, we had a user on reddit mention that on Wear OS NFC is restricted to payments only. If that is the case then we cannot proceed with this change.

your tone and demeanor is very rude. you think just because you're well known on these boards, and because you have some know-how that gives you the right to be condescending? Cuz it doesn't!!! Watch the way you to speak to people. Come off that high horse of yours and realize you ain't nobody special. jerk.
