### ISSUE TITLE
Connection error (connection timeout)

### ISSUE THREAD

**Issue by DerOeli** [home-assistant/android#567] opened 2020-04-23 07:17 UTC
Home Assistant Android version:
1.8.0-159
Android version:
10 (01.03.2020)
Phone model:
Google Pixel 3XL
Home Assistant version:
 0.108.8 on a Raspberry Pi
Last working Home Assistant release (if known):
way back around 0.106ish

Description of problem:
On two Pixel 3XLs I receive the error message, that the App is unable to connect.
After waiting for a few seconds or hitting refresh it usually works. 

As soon as Android kills the app sooner or later the problem reappears.

With the help of the discord channel, we think it might be a slow connection issue, but internet speed, mobile device, etc. should not be a reason.

**Comment by will-l-h** [comment] 2020-04-24 20:35
I've had this issue for months (I think pretty much as soon as I started using the Android Companion app in January).

Android version
1.8.0-144
Phone 
Pixel 3
HA
104 through 108.8 on docker in RasPi

Additional info
I only see this issue when on home wifi (so maybe my issue is somewhat different?) connecting through the companion app. If I turn off wifi and use the phone LTE connection with the app, I don't have the issue. I can open a chrome on the phone on wifi and there's no issue.

I have SSL setup with letsencrypt following directions from here
https://www.home-assistant.io/docs/ecosystem/certificates/lets_encrypt/
As it states there, following that setup means I can only connect via the domain name in my cert (which is a paid for domain name and not duckdns name). This means that I cannot provide an Internal Connection URL in the companion app since that doesn't match the cert.

**Comment by will-l-h** [comment] 2020-04-26 16:24
I fixed this issue by switching from the lets encrypt directions above (which worked fine for browser access with the public domain name on home wifi and LTE) to using nginx. Using the nginx setup, I'm now able to provide the http://192.168.x.x:8123 in the Internal Connection URL in the companion app (since the nginx approach allows me to access the local IP without https which would be an invalid cert versus the cert's domain name).

Unless this is something to do with my Orbi router (doesn't seem like the case since the browser works on home wifi); I think there is an issue somewhere in HA...

The nginx setup I followed:
https://community.home-assistant.io/t/nginx-reverse-proxy-set-up-guide-docker/54802

**Comment by make-all** [comment] 2021-03-01 01:22
not stale.

Even after latest change to switch between internal and external URLs, I get this problem on my home network.  In my case, immediately after coming into the Home network, HA is working, but some time later it gives timeouts until I toggle the WiFi off on my phone, attempt a connection using the External URL and toggle WiFi back on.

Both my internal and external networks have HTTPS enabled, with different DNS name (internal is IPv6 only, external is IPv4 only via a tunnel due to my mobile provider not supporting IPv6).  Both Urls work from my internal network, and any external network that supports IPv6 routing.

**Comment by dshokouhi** [comment] 2021-03-01 01:41
@make-all your issue is unrelated to this issue.  Can you please open a new issue with exact steps to reproduce the issue? Also take a look at logcat to see if the correct URL is being attempted, you will see the URL's printed.  Please note the app only attempts to make the URL switch when it comes back from the background.  If you kept the HA app open it will not know to switch until the next time the app is resumed.  If you see the small "reconnecting..." toast message then that is a frontend issue and not an app issue.   Also simply turning wifi back on does not auto switch to the internal URL unless you put the app in the background and opened it again after being connected to wifi.  This kinda sounds more like an internal networking issue than app issue if all you have to do is toggle wifi on and off.

**Comment by dshokouhi** [comment] 2021-03-04 23:53
For anyone else still having this issue please update both HA and the android app to the latest version and try again.   If you still have an issue after performing that please open a new issue and be sure to fill out the issue template and include logcat logs and a screenshot of the error.  We need to see the communication between the HA frontend and the app.  When you search logcat with `WebViewActivity` we will see all the communication including external bus messages.  Closing this now as the original issue has not been responded to in quite some months.

**Closed by dshokouhi** 2021-03-04 23:53 UTC
Labels: bug, webview
