### ISSUE TITLE
Text and icons illegible after scrolling down

### ISSUE THREAD

**Issue by silviudc** [home-assistant/android#1086] opened 2020-10-21 11:18 UTC
**Home Assistant Android version:** 2.5.0-full

**Android version:** 10

**Phone model:** Samsung Galaxy S10+

**Home Assistant version:** 0.116.4 

**Last working Home Assistant release (if known):**

**Description of problem:** Screen goes haywire after scrolling down and nothing is legible anymore. Restarting/reinstalling app does not fix it.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/17740184/96712692-66c35980-1397-11eb-9dde-674b2e9e5337.png)

**Additional information:**

**Comment by dshokouhi** [comment] 2020-10-21 12:31
Duplicate of #1031 and #965 More than likely you need to update Android System Webview

**Closed by dshokouhi** 2020-10-21 12:31 UTC
Labels: bug

**Comment by silviudc** [comment] 2020-10-21 12:47
Yeah all apps and webview are latest versions so it's not that, also Chrome works fine so it must be on the phone/app side of things.
It used to be working fine a few versions ago.

**Comment by dshokouhi** [comment] 2020-10-21 12:57
So you are not on a custom rom?  Can you check that your custom cards are all up to date?  did you previously update from an older version?

**Comment by silviudc** [comment] 2020-10-21 13:44
Yup on latest stock Samsung ROM and these are the custom cards I have which HACS is reporting aslatest:
![image](https://user-images.githubusercontent.com/17740184/96728315-e5c28d00-13ab-11eb-887e-bb3aeccc6a10.png)

**Comment by dshokouhi** [comment] 2020-10-23 17:07
Did this start after a specific HA update?

**Comment by silviudc** [comment] 2020-10-23 17:35
Yes but not sure when.
Good news though, today saw a new update for webview from the play store and I haven't been able to replicate the issue since this morning so looks good :)

**Comment by dshokouhi** [comment] 2020-10-23 17:36
what version of webview?

**Comment by silviudc** [comment] 2020-10-23 17:40
86.0.4240.110

**Comment by DavidFFerreira** [comment] 2020-10-23 19:29
Same issue here with Galaxy s9+ all things updated and without custom cards
