### ISSUE TITLE
Refresh of Identity Aware Proxy in Chrome instead of WebView

### ISSUE THREAD

**Issue by neruyzo** [home-assistant/android#3890] opened 2023-09-26 07:02 UTC
**Home Assistant Android app version(s):**  F-Droid 2023.8.2-minimal

**Android version(s):** 11

**Device model(s):** CAT S62 Pro

**Home Assistant version:** 2023.9.2

**Last working Home Assistant release (if known):** Not known

**Description of problem, include YAML if issue is related to notifications:** 

I created a [Kratos](https://github.com/ory/kratos) front-end client [Zelus](https://git.sr.ht/~mekyt/zelus) (with [Oathkeeper](https://github.com/ory/oathkeeper) proxy)  to replace my [Pomerium](https://github.com/pomerium/pomerium) setup with Google account I used previously because Google disallow WebView.

For the first authentication, the Android client detect the proxy and open a WebView for the identity verification and the authentication token works well. The problem is when it's time to refresh it, instead of opening it in a WebView, it is opened in Chrome (the default system web browser) and doesn't  share cookies with the Home Assistant app.

To reconnect in this case, I need to delete every data of the Home Assistant application, the application then use WebView for a fresh connection.

**Companion App Logs:** Not accessible when it's time to refresh

**Screenshot or video of problem:** None

**Additional information:** None

**Comment by dshokouhi** [comment] 2023-09-26 14:12
This looks to be a duplicate of some other bugs we have as the symptoms are exactly what those users mention

https://github.com/home-assistant/android/issues/2650
https://github.com/home-assistant/android/issues/151
https://github.com/home-assistant/android/issues/45

**Closed by dshokouhi** 2023-09-26 14:12 UTC
Labels: bug

**Comment by neruyzo** [comment] 2023-09-26 14:57
@dshokouhi thanks and sorry, I didn't find it or thought it was only a cloudflare problem because of the propose solution. But you say in the thread it is just not implemented https://github.com/home-assistant/android/issues/2650#issuecomment-1272661293.

The WebView authentication should locate in [AuthenticationFragment.kt](https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/onboarding/authentication/AuthenticationFragment.kt) but I don't find where the redirection with system browser happen. I will try to continue searching.
