### ISSUE TITLE
[Feature] Whitelisted zones for BLE bescon

### ISSUE THREAD

**Issue by cromefire** [home-assistant/android#3311] opened 2023-02-05 17:36 UTC
**Is your feature request related to a problem? Please describe.**

I like the idea of presence detection with the BLE beacon, but I think it's kinda scary to just send out a tracking beacon wherever you go. It's fine in my home, but not outside.

**Describe the solution you'd like**

Would be nice if you could white list a zone in which the beacon is sent (default can just stay always on, if no zone is provided).

**Describe alternatives you've considered, if any**

You could do it via automations Server Side, but I do have concerns about reliability and connection issues for example. If the phone looses connection and/or can't locate itself anymore it can just turn off the beacon, because no zone is set, server side because of those issues the message to turn it off might not reach the device.

**Additional context**

**Comment by dshokouhi** [comment] 2023-02-05 17:42
duplicate of https://github.com/home-assistant/android/issues/2867

**Closed by dshokouhi** 2023-02-05 17:42 UTC
Labels: enhancement

**Comment by cromefire** [comment] 2023-02-05 17:48
Ah sorry only searched for beacon which is missing in the other issue.
