### ISSUE TITLE
Back button behaves strangely while editing cards

### ISSUE THREAD

**Issue by federicoodorizzi** [home-assistant/android#527] opened 2020-03-24 19:52 UTC
**Home Assistant Android version:**
1.8.0-144
**Android version:**
10
**Phone model:**
Xiaomi Mi9T Pro
**Home Assistant version:**
Home Assistant 0.107.6
**Last working Home Assistant release (if known):**
Never saw this working properly before.
**Description of problem:**
Pressing the back button while editing a card doesn't exit the editing, but instead acts on the level underneath.
**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2020-03-24 19:54
@federicoodorizzi please do not delete the issue template, all requested information is required to help you out.  Please edit your post and add the template back with all requested info.

**Comment by dshokouhi** [comment] 2020-03-26 01:02
Thanks for providing the template @federicoodorizzi .  Do you experience the same behavior if you use Chrome on Android?

**Comment by federicoodorizzi** [comment] 2020-03-27 16:13
I just tried and I found the problem there as well. Should I post the issue somewhere else then? Thanks!

**Comment by dshokouhi** [comment] 2020-08-30 23:26
closing as duplicate of https://github.com/home-assistant/frontend/issues/5515

**Closed by dshokouhi** 2020-08-30 23:26 UTC
Labels: bug, webview
