### ISSUE TITLE
Sensor for Phone on or off

### ISSUE THREAD

**Issue by BenPru** [home-assistant/android#1025] opened 2020-10-08 22:53 UTC
**Is your feature request related to a problem? Please describe.**
I want to change my person state to "sleep" if my mobile phone is off.

**Describe the solution you'd like**
Detect the shutdown event and add a sensor for phone is on/off.

**Describe alternatives you've considered, if any**
Or reset existing sensors to unavailable or something else to allow a phone is off detection.

**Additional context**
Nothing

**Comment by dshokouhi** [comment] 2020-10-08 23:37
Duplicate of #411

**Closed by dshokouhi** 2020-10-08 23:37 UTC
Labels: enhancement

**Comment by BenPru** [comment] 2020-10-09 11:41
@dshokouhi I don't think this is a duplicate.
To react on the "shutdown event" and send phone power is off is not the same function as set entities to "unknown" when no update after x hours. If the phone has no network connection and doesn't update entities is a complete other case as a shutdown.
Can you please reopen my case?

**Comment by dshokouhi** [comment] 2020-10-09 15:12
> Or reset existing sensors to unavailable

This it is exactly what #411 is requesting, if the device was unable to communicate.  #411 mentions if the device went out of network or is just not `on` which covers all cases of when a device has not communicated.  That is the same thing here.

Now looking at the specific action you are talking about for the shut down event, it looks like apps are forbidden from running as a foreground which is exactly what we do when we attempt to update sensors.  So detecting the event AND reporting it back successfully may not be possible at all.

So with #411 it will account for all cases.

https://developer.android.com/reference/android/content/Intent.html#ACTION_SHUTDOWN
