### ISSUE TITLE
Add support for Android Auto / Car support

### ISSUE THREAD

**Issue by wesssup** [home-assistant/android#3033] opened 2022-11-03 08:57 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Allowing interaction inside your car with the app, for example, you could control your gate 

**Describe alternatives you've considered, if any**
No alternatives,  or on your phone but it's illegal to drive and use your phone. 

**Additional context**
Take a  look to : ](https://www.android.com/auto/)

**Comment by dshokouhi** [comment] 2022-11-03 13:37
duplicate of #791

**Closed by dshokouhi** 2022-11-03 13:37 UTC
