### ISSUE TITLE
Update Spinner is Broken

### ISSUE THREAD

**Issue by dougmaitelli** [home-assistant/android#4077] opened 2023-12-27 18:31 UTC
**Home Assistant Android app version(s):**

**Android version(s):** 14

**Device model(s):** Pixel 8 pro

**Home Assistant version:** 2023.12.3

**Last working Home Assistant release (if known):** N/A

**Description of problem, include YAML if issue is related to notifications:**

Since latest update for Android the updating spinner is broken on the UI.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

![Screenshot_20231227-102757.png](https://github.com/home-assistant/android/assets/1277391/0c0d5f4c-e164-4be0-93a3-13377c514157)

**Additional information:**

**Comment by dshokouhi** [comment] 2023-12-27 18:32
duplicate of https://github.com/home-assistant/frontend/issues/18976

**Closed by dshokouhi** 2023-12-27 18:32 UTC
Labels: bug
