### ISSUE TITLE
Wrong alarm clock time 

### ISSUE THREAD

**Issue by phyrz91** [home-assistant/android#1301] opened 2021-01-17 16:22 UTC
**Home Assistant Android version:**
2021.1.1-full

**Android version:**
10
**Phone model:**
Xiaomi Mi 9 SE(MIUi 12)
**Home Assistant version:**
2021.1.4
**Last working Home Assistant release (if known):**
-
**Description of problem:**
Hi, at first I wanted to thank you for a very good app, it gets better with each release. I have a problem with the alarm clock set in my smartphone. The application, using the sensor, transmits a completely different alarm clock time than the one I set on the smartphone. Currently, my alarm clock is set to 6 a.m. and the sensor informs that the next alarm will be at 11 p.m.

```

```

**Screenshot of problem:**
[http://imgur.com/3eHtakz](url)
[http://imgur.com/PbOu4ZS](url)
**Additional information:**

**Comment by dshokouhi** [comment] 2021-01-17 16:48
Duplicate of #748 #1190 #1211

**Closed by dshokouhi** 2021-01-17 16:48 UTC
Labels: bug
