### ISSUE TITLE
Actionable Notifications for WearOS

### ISSUE THREAD

**Issue by JosephAbbey** [home-assistant/android#4614] opened 2024-09-08 11:43 UTC
**Is your feature request related to a problem? Please describe.**
Currently if a notification with actions is sent to a WearOS device, the actions are not displayed on the watch. However if the same notification is sent to a phone, actions are displayed.

**Describe the solution you'd like**
Move the code that supports actionable notifications into common and support it on all 3 platforms. It seems to already be supported on android auto (I don't know about automotive) so it could be even simpler.

**Describe alternatives you've considered, if any**
Send all notification for Home Assistant from my phone to my watch and turn off the watch app notifications. This works but does not allow me to send separate notifications to my watch and phone and does not work when my phone is not connected to my watch by Bluetooth.

**Additional context**
I already added support for the notification_cleared event on WearOS so I am somewhat familiar with this part of the code base and may fix this myself if I have time.

Thanks!

**Comment by dshokouhi** [comment] 2024-09-08 16:28
duplicate of https://github.com/home-assistant/android/issues/3324

**Closed by dshokouhi** 2024-09-08 16:28 UTC
Labels: enhancement
