### ISSUE TITLE
App has stopped working on Android tablet

### ISSUE THREAD

**Issue by kongsted** [home-assistant/android#4330] opened 2024-04-06 19:50 UTC
**Home Assistant Android app version(s):**

**Android version(s):**
7.1.1

**Device model(s):**
Lenovo TB-X704F

**Home Assistant version:**
2024.3.5-Full

**Last working Home Assistant release (if known):**
previous release (don't knowing the version there was installed before the automatic update happened) 

**Description of problem, include YAML if issue is related to notifications:**
The app crashes every time I try to open it with the message "Home Assistant has stopped" (text translated from danish). 
I have tried to clear cache, data and reinstall the app including a number of restarts. 
After reinstall of the app, I'm able to open the app. It then says it failed to open, and I can click retry. Then it's starting the setup process. It can find the HomeAssistant server on the network, and I can type username + password. Next screen with the device name and location setting is also coming up. When I click continue on that page, the app is crashing again. And when I'm restart it afterwards, it is starting the setup wizard again (meaning no settings saved from previous attempt). 

All other apps are updated on the tablet, and no updates from Lenovo exist to the tablet. 

Home Assistant app has working flawless until the updated last night. 

**Companion App Logs:**
As I'm not able to get into the app, I can't get the log from the app. 
```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2024-04-06 20:01
duplicate of https://github.com/home-assistant/android/issues/4323 will be fixed soon in next release

**Closed by dshokouhi** 2024-04-06 20:01 UTC
Labels: bug
