### ISSUE TITLE
Notifications with pictures are historical in app

### ISSUE THREAD

**Issue by Arvics** [home-assistant/android#1273] opened 2021-01-03 21:13 UTC
**Home Assistant Android version:**
3.0.2-full
**Android version:**
11
**Phone model:**
Samsung S20+5G
**Home Assistant version:**
2020.12.2
**Last working Home Assistant release (if known):**
-
**Description of problem:**
In HA companion app notifications show historical pictures. In Android pop-up notifications and in Chrome, web browser access to HA are correct pictures.
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![3_Screenshots 20210104-093014_Home Assistant](https://user-images.githubusercontent.com/65485482/103488823-d6b08e80-4e74-11eb-8b43-d52fe145996b.jpg)

**Additional information:**
I didn't tested picture notifications on Android 10 before upgrade to Android 11, because, that time I still didn't use this notifications.

**Comment by dshokouhi** [comment] 2021-01-03 21:30
Since this is HA frontend notification panel and the app is only a webview to the frontend we may need to move this bug or open a new one with frontend team.  The app has no control over what pictures get displayed we just load the site.

**Comment by Arvics** [comment] 2021-01-03 21:39
But in website it was displayed correctly, only in Android app it show wrong. Also in computer, web browser I see correct pictures.

**Comment by dshokouhi** [comment] 2021-01-03 21:40
That doesnt matter here as the app just displays whatever is sent to us, we have no control of the HA frontend.  We just load it.  The screen you refer to is not built by the app, it is purely HA frontend.

**Comment by Arvics** [comment] 2021-01-03 21:43
Would you please help to move this report to frontend team? Or how to do it?

**Comment by dshokouhi** [comment] 2021-01-03 21:45
I am unable to move issues and the front end team actually asks for different information in their bug template: https://github.com/home-assistant/frontend/issues/new?labels=bug&template=BUG_REPORT.md

**Comment by dshokouhi** [comment] 2021-01-04 17:31
Closing as duplicate of https://github.com/home-assistant/frontend/issues/8079

**Closed by dshokouhi** 2021-01-04 17:31 UTC
Labels: bug
