### ISSUE TITLE
Modifying time helper through dashboard UI only allows entering a single digit

### ISSUE THREAD

**Issue by jtopian** [home-assistant/android#2841] opened 2022-09-02 03:27 UTC
**this issue is also present in he iPhone app**

**Home Assistant Android version:** 2022.8.0-minimal

**Android version:** 12

**Phone model:** Essential PH-1

**Home Assistant version:** 2022.8.7

**Last working Home Assistant release (if known):** been like this since I started using helpers.

**Description of problem:** I added a helper to set a time value, then added it to a dashboard. This gives me a text-based field in which to enter the desired time. However, I can only enter a single digit in each field, for example, trying to type "30" in the minutes part of the field will set the value to "03" as soon as I type the first digit. I have to copy/paste multi-digit values from another app in order to put them in correctly.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
When I click on the field, my keyboard appears:
![Screenshot_20220901-202334_Home Assistant](https://user-images.githubusercontent.com/1151586/188053074-4580c556-ee9c-4965-9f30-fdda1acb5277.png)
When I press "3" the keyboard disappears and the entry is set as "03":
![Screenshot_20220901-202339_Home Assistant](https://user-images.githubusercontent.com/1151586/188053094-c5572345-33d3-4b50-a7e9-29e35697101d.png)

**Additional information:**

**Comment by dshokouhi** [comment] 2022-09-02 03:55
As this issue is also present in the iPhone so it probably also exists in a browser on the same devices. This is most likely a frontend issue and not an app issue.

**Comment by jtopian** [comment] 2022-09-02 04:33
It actually seems to work okay in Firefox on the Android phone. Clunky, but doesn't immediately kick me out of the field.

**Comment by dshokouhi** [comment] 2022-09-02 05:26
The better test is Chrome as Webview is based off Chrome, either way though the app does not control this screen.

**Comment by jpelgrom** [comment] 2022-09-02 11:50
This appears to be a duplicate of home-assistant/frontend#11861, and should be resolved in the upcoming 2022.9 release.
@jtopian Would be great if you can test in Chrome or using 2022.9 to confirm.

**Comment by jtopian** [comment] 2022-09-02 12:05
Just tested, Chrome does present the issue. I guess we can close this as a duplicate, and I'll check when 2022.9 releases and update on the frontend issue if the problem isn't fixed.

**Closed** 2022-09-02 12:09 UTC
Labels: bug
