### ISSUE TITLE
Officially Support for AndroidTV

### ISSUE THREAD

**Issue by stbeep1** [home-assistant/android#1354] opened 2021-02-08 05:28 UTC
Will the HA app support Android tv officially? Do you guys have a timeline about that? Thank you. 

I have checked those issues related to the Android TV app for HA, but all of them were closed on GitHub. Thank you!

**Comment by dshokouhi** [comment] 2021-02-10 20:28
The android app is dependent on the HA frontend to support the TV interface.  As of now there is no support there so you will need to start by making your feature request there.  Only then can we accept and work on any such request.

We also do not do any timelines, we are all volunteers and work on what we want when we want.

Closing this as a duplicate of the other issues you mentioned as the reasons are already mentioned in https://github.com/home-assistant/android/issues/327

**Closed by dshokouhi** 2021-02-10 20:28 UTC
Labels: enhancement

**Comment by AleXSR700** [comment] 2023-09-17 17:26
Is it just about the remote control or about something else? BEcause I do have a mouse and keyboard hooked up to my tv but the app crashes after entering my credentials.
