### ISSUE TITLE
Companion App Freezing when opening calender

### ISSUE THREAD

**Issue by xTheDrop** [home-assistant/android#3506] opened 2023-05-02 11:57 UTC
The calender is not working within the mobile app. No matter if iam using IOS or Android devices the App keeps freezing while opening the calendar. Everything is updated to the newest Version.

**Comment by dshokouhi** [comment] 2023-05-02 13:58
Duplicate of https://github.com/home-assistant/frontend/issues/15094

**Closed by dshokouhi** 2023-05-02 13:58 UTC
