### ISSUE TITLE
App loads very slow after latest updates

### ISSUE THREAD

**Issue by VNRARA** [home-assistant/android#3482] opened 2023-04-19 20:55 UTC
**Home Assistant Android app version(s):**

**Android version(s):**
13 (oneui 5.1)
**Device model(s):**
Samsung G991B
**Home Assistant version:**
4.5
**Last working Home Assistant release (if known):**
idk
**Description of problem, include YAML if issue is related to notifications:**

App loads content very slow compared to browser or hass.agent. In webview debug it showed multiple pages being open for local ip AND domain. Removing cache and stopping the app didn't really do anything. (it would load up everything again and be stuck). But after removeinginternal ip and the wifi ssid inside the app it started working like normal again. 

Couldn't replicate the issue directly anymore. It might come back later if I put the internal ip again. 

**Companion App Logs:**

```
[homeassistant_companion_log_3-19-2023_22-47-7.txt](https://github.com/home-assistant/android/files/11277514/homeassistant_companion_log_3-19-2023_22-47-7.txt)

```

**Additional information:**

**Comment by dshokouhi** [comment] 2023-04-19 21:04
Looks to be a duplicate of #3396

**Closed** 2023-04-25 15:41 UTC
Labels: bug
