### ISSUE TITLE
Home Assistant companion app multiplatform on KMP

### ISSUE THREAD

**Issue by nick2525** [home-assistant/android#4424] opened 2024-05-29 17:07 UTC
It will be nice to have all features of Home Assistant companion app on Windows, Macos, Linux and mobile. It is very important that changes appear on all platforms at the same time. This can be achieved using this technology. [https://www.jetbrains.com/lp/compose-multiplatform/ 3](https://www.jetbrains.com/lp/compose-multiplatform/) In any case, you are writing a companion app for Android, but now even Google recommends using cross-platform code. And it’s easier to rewrite a companion app in Kotlin Multiplatform once, and you can always release it on all platforms at the same time [Android Developers Blog: Android Support for Kotlin Multiplatform to Share Business Logic Across Mobile, Web, Server, and Desktop Platforms](https://android-developers.googleblog.com/2024/05/android-support-for-kotlin-multiplatform-to-share-business-logic-across-mobile-web-server-desktop.html?m=1)

**Comment by dshokouhi** [comment] 2024-06-04 16:46
closing as duplicate of https://community.home-assistant.io/t/please-convert-code-for-mobile-app-into-kotlin-language/560791

**Closed by dshokouhi** 2024-06-04 16:46 UTC
Labels: enhancement
