### ISSUE TITLE
Automatically enable High Accuracy Mode when connected to Android Auto

### ISSUE THREAD

**Issue by bfayers** [home-assistant/android#3531] opened 2023-05-16 07:48 UTC
.

**Describe the solution you'd like**

Much like the ability to enable High Accuracy Mode when connected to certain Bluetooth devices, I want the ability to turn it on when connected to Android Auto.

**Describe alternatives you've considered, if any**

Considered usingbthe android auto sensor and a hass automation to send a notification command to enable/disable HA mode accordingly - seems a needless overcomplication and room for error.

**Comment by dshokouhi** [comment] 2023-05-16 21:45
duplicate of #1516

**Closed by dshokouhi** 2023-05-16 21:45 UTC
Labels: enhancement
