### ISSUE TITLE
Pico 4 VR Headset support

### ISSUE THREAD

**Issue by ASchneiderBR** [home-assistant/android#3358] opened 2023-02-21 18:36 UTC
**Is your feature request related to a problem? Please describe.**

I am experiencing issues with my Pico 4 VR headset Android app, as most sensors are marked as "unknown" after installing the app on the device. I would like to see improved support for the Pico 4 VR headset, similar to that of the Quest 2, where all sensors are functioning seamlessly.

**Describe the solution you'd like**

My desired solution is to have all Pico 4 VR headset sensors working seamlessly within the Android app, like the Quest 2. This would greatly improve the user experience and allow for creating great automations.

Thank you!

**Comment by dshokouhi** [comment] 2023-02-21 18:39
Please be more specific. What sensors are not working? Have you looked at the companion app logs to see if there is an issue? Are you certain Pico has this working in their android fork?

**Comment by dshokouhi** [comment] 2023-02-21 20:30
Please check Settings > Companion App > Manage Sensors

do you see proper states there? I think you are seeing the following issue and the sensors are actually updating as expected.

https://github.com/home-assistant/core/issues/79837

**Comment by ASchneiderBR** [comment] 2023-02-21 20:56
Yes, I can see their propper states when enabling the sensors, from inside the app itself.

Most sensors are shown as updated in the history before they become "unknown".

 I'll check out this other issue, thanks.

**Comment by dshokouhi** [comment] 2023-02-21 20:57
ok then this is a duplicate of the above issue, going to close now. If you find a sensor not working you will need to open a new issue with device logs so we can inspect.

**Closed by dshokouhi** 2023-02-21 20:57 UTC
Labels: enhancement, question, sensor-tracking
