### ISSUE TITLE
Option for location aware fingerprint lock. 

### ISSUE THREAD

**Issue by RoboMagus** [home-assistant/android#2797] opened 2022-08-16 12:33 UTC
**Is your feature request related to a problem? Please describe.**

As my HomeAssistant instance controls basically my entire home I quite like the fingerprint lock for the companion app, in case my phone falls in the wrong hands. However when at home I'd like to be able to access anything in the app without first having to unlock it. 

**Describe the solution you'd like**

It would be neat to have the option to bypass the lock at home based on e.g. Location,  wifi network,  internal HA url access, or even better: based on a HA sensor that says the fingerprint lock is OK to be bypassed. 

**Describe alternatives you've considered, if any**

-

**Additional context**

It's of course important to have this as an option and not enabled by default, as many users might also want to keep their kids locked out of certain features of the app.

**Comment by dshokouhi** [comment] 2022-08-16 13:09
Looks to be a duplicate of https://github.com/home-assistant/android/issues/840

**Comment by RoboMagus** [comment] 2022-08-16 13:50
Seems you're right. That one is so old already I never reached it when searching for related issues.

**Closed** 2022-08-16 13:53 UTC
Labels: enhancement
