### ISSUE TITLE
Android Power Menu: Button doesn't have device area information

### ISSUE THREAD

**Issue by yegle** [home-assistant/android#1558] opened 2021-05-22 06:51 UTC
**Home Assistant Android version:** 2021.5.1-full

**Android version:** Android 12 Beta1

**Phone model:** Pixel 4 XL

**Home Assistant version:** 2021.5.4

**Last working Home Assistant release (if known):**

**Description of problem:**

When adding control from Home Assistant to the Android Power Menu, the control widget does not have device area information.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
Button added via Home Assistant, no device area information
![image](https://user-images.githubusercontent.com/146133/119217450-293ec000-ba8f-11eb-8c7d-884ece6ff4e5.png)

Button added via Google Assistant, has room information
![image](https://user-images.githubusercontent.com/146133/119217487-630fc680-ba8f-11eb-8175-956969df6c8d.png)

**Additional information:**

**Comment by dshokouhi** [comment] 2021-05-22 08:28
Duplicate of #1372

**Closed by dshokouhi** 2021-05-22 08:28 UTC
Labels: bug
