### ISSUE TITLE
Buttons widget not worke from last Android update

### ISSUE THREAD

**Issue by Philippe12** [home-assistant/android#4065] opened 2023-12-19 07:41 UTC
**Home Assistant Android app version(s):**
2023.10.2-full

**Android version(s):**
14 with last update from 2023  december 5th (build number UQ1A.231205.015)

**Device model(s):**
Google Pixel 6a

**Home Assistant version:**
Core : 2023.12.3
Supervisor : 2023.11.6
User interface : 20231208.2

**Last working Home Assistant release (if known):**
Core : 2023.12.3
Supervisor : 2023.11.6
User interface : 20231208.2

**Description of problem, include YAML if issue is related to notifications:**
After last Android 14 update the button widget stop working. When I touch it no thing look like append.
I try to remove it and reinstall, at first time it work and after no thing append

**Companion App Logs:**

``` log
[12-19 08](tel:12-19 08):38:[20.085 28645 29115](tel:20.085 28645 29115) D LogcatReader: Read logcat for pid [28645](tel:28645)
[12-19 08](tel:12-19 08):38:[20.144 28645 29115](tel:20.144 28645 29115) D LogcatReader: Done reading logcat for pid [28645](tel:28645)
[12-19 08](tel:12-19 08):38:[22.781 28645 28645](tel:22.781 28645 28645) D IntegrationRepository: setAppActive(): false
[12-19 08](tel:12-19 08):38:[22.782 28645 28645](tel:22.782 28645 28645) D IntegrationRepository: setAppActive(): false
[12-19 08](tel:12-19 08):38:[22.816 28645 28645](tel:22.816 28645 28645) W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=[androidx.activity.OnBackPressedDispatcher](http://androidx.activity.onbackpresseddispatcher/)$Api33Impl$$ExternalSyntheticLambda0@37e[805](tel:805)f
[12-19 08](tel:12-19 08):38:[23.829 28645 28645](tel:23.829 28645 28645) D ButtonWidget: Broadcast received:
[12-19 08](tel:12-19 08):38:[23.829 28645 28645](tel:23.829 28645 28645) D ButtonWidget: Broadcast action: [io.homeassistant.companion.android.widgets.button.ButtonWidget](http://io.homeassistant.companion.android.widgets.button.buttonwidget/).CALL_SERVICE_AUTH
[12-19 08](tel:12-19 08):38:[23.829 28645 28645](tel:23.829 28645 28645) D ButtonWidget: AppWidgetId: 25
[12-19 08](tel:12-19 08):38:[23.829 28645 28645](tel:23.829 28645 28645) D ButtonWidget: Calling authentication, then configured service
[12-19 08](tel:12-19 08):38:[23.853 28645 28645](tel:23.853 28645 28645) D WidgetAuthenticationA: onCreate in WidgetAuthenticationActivity called
[12-19 08](tel:12-19 08):38:[23.891 28645 28645](tel:23.891 28645 28645) D Unlock  : onAuthenticationError -> 10 :: Authentification annulée
[12-19 08](tel:12-19 08):38:[23.891 28645 28645](tel:23.891 28645 28645) D WidgetAuthenticationA: Authentication canceled by user, closing activity
[12-19 08](tel:12-19 08):38:[23.894 28645 28645](tel:23.894 28645 28645) W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=[androidx.activity.OnBackPressedDispatcher](http://androidx.activity.onbackpresseddispatcher/)$Api33Impl$$ExternalSyntheticLambda0@39a[6886](tel:6886)
[12-19 08](tel:12-19 08):38:[23.906 28645 28645](tel:23.906 28645 28645) W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=[android.app.Activity](http://android.app.activity/)$$ExternalSyntheticLambda0@b[732](tel:732)fe5
[12-19 08](tel:12-19 08):38:[24.202 28645 28655](tel:24.202 28645 28655) W [mpanion.android](http://mpanion.android/): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~9_8TusHnogkRh0JJmx[200](tel:200)Q==/[com.google.android.marvin.talkback](http://com.google.android.marvin.talkback/)-Ai88ikBHsBOToKwl0gQ_LQ==/[base.apk](http://base.apk/)' with 1 weak references
[12-19 08](tel:12-19 08):38:[24.204 28645 28655](tel:24.204 28645 28655) W [mpanion.android](http://mpanion.android/): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~9_8TusHnogkRh0JJmx[200](tel:200)Q==/[com.google.android.marvin.talkback](http://com.google.android.marvin.talkback/)-Ai88ikBHsBOToKwl0gQ_LQ==/[split_config.arm64_v8a.apk](http://split_config.arm64_v8a.apk/)' with 1 weak references
[12-19 08](tel:12-19 08):38:[24.204 28645 28655](tel:24.204 28645 28655) W [mpanion.android](http://mpanion.android/): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~mmbl26CIS02YLyIh5S5bgw==/[com.deepl.mobiletranslator](http://com.deepl.mobiletranslator/)-SO-IHrEd9i2LQ79LFcF54w==/[base.apk](http://base.apk/)' with 1 weak references
[12-19 08](tel:12-19 08):38:[24.205 28645 28655](tel:24.205 28645 28655) W [mpanion.android](http://mpanion.android/): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~mmbl26CIS02YLyIh5S5bgw==/[com.deepl.mobiletranslator](http://com.deepl.mobiletranslator/)-SO-IHrEd9i2LQ79LFcF54w==/[split_config.arm64_v8a.apk](http://split_config.arm64_v8a.apk/)' with 1 weak references
[12-19 08](tel:12-19 08):38:[24.205 28645 28655](tel:24.205 28645 28655) W [mpanion.android](http://mpanion.android/): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~mmbl26CIS02YLyIh5S5bgw==/[com.deepl.mobiletranslator](http://com.deepl.mobiletranslator/)-SO-IHrEd9i2LQ79LFcF54w==/[split_config.xxhdpi.apk](http://split_config.xxhdpi.apk/)' with 1 weak references
[12-19 08](tel:12-19 08):38:[24.205 28645 28655](tel:24.205 28645 28655) W [mpanion.android](http://mpanion.android/): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~Pv9euMCKBwT1-pClPj_P5w==/[com.google.android.apps.translate](http://com.google.android.apps.translate/)-bjwPH0I0EIKtpc23LNTjCg==/[base.apk](http://base.apk/)' with 1 weak references
[12-19 08](tel:12-19 08):38:[24.206 28645 28655](tel:24.206 28645 28655) W [mpanion.android](http://mpanion.android/): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~MndwGwyb6A4aA4H-qVugIQ==/[org.wikipedia](http://org.wikipedia/)-dLytFvK0xRnz4RFx-[271](tel:271)dQ==/[base.apk](http://base.apk/)' with 1 weak references
[12-19 08](tel:12-19 08):38:[24.207 28645 28655](tel:24.207 28645 28655) W [mpanion.android](http://mpanion.android/): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~MndwGwyb6A4aA4H-qVugIQ==/[org.wikipedia](http://org.wikipedia/)-dLytFvK0xRnz4RFx-[271](tel:271)dQ==/[split_config.arm64_v8a.apk](http://split_config.arm64_v8a.apk/)' with 1 weak references
[12-19 08](tel:12-19 08):38:[24.207 28645 28655](tel:24.207 28645 28655) W [mpanion.android](http://mpanion.android/): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~MndwGwyb6A4aA4H-qVugIQ==/[org.wikipedia](http://org.wikipedia/)-dLytFvK0xRnz4RFx-[271](tel:271)dQ==/[split_config.xxhdpi.apk](http://split_config.xxhdpi.apk/)' with 1 weak references
[12-19 08](tel:12-19 08):38:[25.976 28645 28645](tel:25.976 28645 28645) D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: [1702971503781](tel:1702971503781), currentMillis: [1702971505976](tel:1702971505976))
[12-19 08](tel:12-19 08):38:[26.007 28645 28645](tel:26.007 28645 28645) D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: [1702971503781](tel:1702971503781), currentMillis: [1702971506007](tel:1702971506007))
[12-19 08](tel:12-19 08):38:[26.007 28645 28645](tel:26.007 28645 28645) D IntegrationRepository: setAppActive(): true
[12-19 08](tel:12-19 08):38:[26.840 28645 29115](tel:26.840 28645 29115) D LogcatReader: Read logcat
```

**Screenshot or video of problem:**

**Additional information:**

**Comment by jpelgrom** [comment] 2023-12-19 07:47
Do you have the option to require authentication checked, and does removing that option fix it? If so, this is a duplicate of #3893.

**Closed** 2023-12-20 17:25 UTC
Labels: bug, widget
