### ISSUE TITLE
Crash after login android 7

### ISSUE THREAD

**Issue by uowis** [home-assistant/android#3075] opened 2022-11-16 15:20 UTC
**Home Assistant Android version:**
beta 2914 23e65c49-full
**Android version:**
android 7
**Phone model:**
huawai SLA L22
**Home Assistant version:**
Home Assistant 2022.11.2

**Description of problem:**
App crash after login and after Device Name and localisation  setup screen

**Comment by dshokouhi** [comment] 2022-11-16 15:31
Are you able to get us the logs?

**Comment by dshokouhi** [comment] 2022-11-16 16:00
Also for some reason the device is missing here

**Comment by jpelgrom** [comment] 2022-11-16 17:05
Does this also happen with the latest stable version?

(It might be issue #2465 again as the dependency was updated.)

**Comment by jpelgrom** [comment] 2022-11-25 18:30
@uowis A new version of the app has been released which should fix this issue, could you download the latest version and let us know if the app works again? (assuming this is a duplicate of the issue I referred to in the last comment)

**Comment by ieguiguren** [comment] 2022-12-18 16:08
Home Assistant Android version:
2022.11.0-full
Android version:
android 7
Phone model:
Samsung Galaxy S6 (SM-G920F)
Home Assistant version:
  OS Version:               Home Assistant OS 9.4
  Home Assistant Core:      2022.12.6


Description of problem:
   I've set up an nginx reverse proxy on port 443 with Let's Encrypt keys and kept the plain HTTP  8123 port.
![image](https://user-images.githubusercontent.com/1809729/208272215-232b93ed-5725-42e4-a0c2-cd7d97928480.png)
![image](https://user-images.githubusercontent.com/1809729/208272235-c4a743a4-c0e1-4e58-9e35-66ea4539e2e7.png)

 - behavior: 
   
The app crashes. After starting the app, you can set the URL, in the next screen set the name and password and, then, activate the localization. After it, it complained of the _no valid  SSL's CA_. This doesn´t happen on an Android 12 phone with the same settings.
![image](https://user-images.githubusercontent.com/1809729/208272249-a5a5ac6c-94c5-4423-bc42-af32301e6c15.png)
This error says:
_It was not possible to connect to Home Assistant.
The SSL handshake was unsuccessful, please, ensure your certificate is valid._

HA logs:
2-12-18 01:29:33.533 ERROR (MainThread) [homeassistant.components.hassio.handler] /ingress/validate_session return code 401
2022-12-18 01:29:33.535 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /ingress/validate_session - 
2022-12-18 01:29:33.536 ERROR (MainThread) [homeassistant.components.hassio.handler] /ingress/validate_session return code 401
2022-12-18 01:29:33.537 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /ingress/validate_session - 

Althoug the logs says _error code 401_, the login credentials are correct as when I'm connected in the LAN, as it goes via plain HTTP, it works perfectly.

App log:
You may find the logcat from the moment when the localization page, leading to the error: https://pastebin.com/MaLwRcfS (sorry if there are logs no relevant though I tried to start and stop the logs capture just for the moment of the error).

**Comment by dshokouhi** [comment] 2022-12-18 17:19
The SSL error is actually something that needs to be solved by the user in this case. As you can see it works on Android 12 because each android device has its own set of trusted CAs and you may need to make your device trust the CA being used.  I don't think the 401 error you see is related to this but something else.  For this error 

> The app crashes. After starting the app, you can set the URL, in the next screen set the name and password and, then, activate the localization. After it, it complained of the _no valid SSL's CA_. This doesn´t happen on an Android 12 phone with the same settings.

This is not a crash but just an error message telling you the certificate is not valid.

Google does offer some tips on how to solve this issue on the certificate end, you may need to try and teach that device the missing CA or try to regenerate a certificate using a different provider. The app does allow for you to import things as mentioned in teh below link and some have found it helpful.

https://developer.android.com/training/articles/security-ssl#CommonProblems

As your error is not the same as the issue originally reported and since we did not hear from the original author I am going to close this issue now.

**Closed by dshokouhi** 2022-12-18 17:19 UTC
Labels: bug, question

**Comment by uowis** [comment] 2022-12-20 15:05
I have no crash on new release,... Thanks
