### ISSUE TITLE
Allow Android intent to open apps

### ISSUE THREAD

**Issue by Hellis81** [home-assistant/android#990] opened 2020-09-29 14:29 UTC
**Is your feature request related to a problem? Please describe.**
It would be great if you could send an actionable notification from HA and have a link to open an app

**Describe the solution you'd like**
Allow/enable android intents to open apps from HA companion app

**Describe alternatives you've considered, if any**
Not sure if there are any alternatives. 

**Additional context**

**Comment by dshokouhi** [comment] 2020-09-29 22:35
Actually this is a duplicate of #956 closing in favor of it

**Closed by dshokouhi** 2020-09-29 22:35 UTC
Labels: enhancement, notifications
