### ISSUE TITLE
Will not install on Android 5.0.1

### ISSUE THREAD

**Issue by aeklo** [home-assistant/android#538] opened 2020-04-02 11:30 UTC
**Home Assistant Android version:**
1.8.0-144 and 1.8.0-157
**Android version:**
5.0.1
**Phone model:**
Lenovo Tab3-710F
**Home Assistant version:**
0.107.7
**Last working Home Assistant release (if known):**
Don't know
**Description of problem:**
Android app will not install. Try again. Error 910.
**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**
Have tried two separate, identical devices. Both wiped and factory restored with latest available system update. Have run Home Assistant app on both before wiping (due to other reasons). Have tried different Google accounts.

**Comment by aeklo** [comment] 2020-04-02 12:24
Also tried APK install 1.8.0, 1.7.1, 1.7.0, 1.6.0 and 1.0.0, which does not work. Guess I'm out of options, and that this really is not an Home Assistant bug?
Btw: Other apps install fine.

**Comment by dshokouhi** [comment] 2020-04-02 17:28
@aeklo are you installing this from the play store? Does your device have google play services?  If you are installing via play store can you attach a screenshot of the error?

**Comment by dshokouhi** [comment] 2020-04-02 21:06
Thank you for the update! Are you able to provide the ADB logs when installing it?  You should be able to use a command like this.

```
logcat | grep io.homeassistant.companion.android
```

**Comment by aeklo** [comment] 2020-04-02 21:33
Not that steady in Android debugging, but I think I managed:

[homeassistant.txt](https://github.com/home-assistant/home-assistant-android/files/4423785/homeassistant.txt)

**Comment by aeklo** [comment] 2020-04-08 17:40
@dshokouhi did you have the chance to look into the log file?

**Comment by dshokouhi** [comment] 2020-04-08 17:44
@aeklo I wouldn't be able to fix this issue due to lack of understanding the cause. I was just helping out the developers to grab the info they will need once they start looking into the issue.  I am sure the log should be helpful to them.

**Comment by aeklo** [comment] 2020-04-08 18:38
I understand. Thanks for getting back to me.

**Comment by dshokouhi** [comment] 2020-08-11 00:46
Is this still an issue in the recent play store release? If it is can you check the `minimal` apk found on the release page on github?

**Comment by aeklo** [comment] 2020-08-12 22:10
Yes, unfortunately. Both the full and minimal apk fails with “app not installed”. I am about to give up on this one.

**Comment by dshokouhi** [comment] 2021-01-04 18:23
Looks like we had another user hit this same error and they have some new logs as well

https://community.home-assistant.io/t/cannot-install-app/251332/2

```
[01-03 22:06:32.661 27076:27076 I/Finsky]
[1] VerifyInstallTask.mF(6): Verification complete: id=3, package_name=io.homeassistant.companion.android

[01-03 22:06:34.464 27431:27467 D/PackageManager]
Renaming /data/app/vmdl1365252394.tmp to /data/app/io.homeassistant.companion.android-1

[01-03 22:06:34.471 27431:27467 D/PackageManager]
installNewPackageLI: Package{349cad9b io.homeassistant.companion.android}

[01-03 22:06:34.543 144:144 D/installd]
do_install : io.homeassistant.companion.android 10124 10124 default

[01-03 22:06:34.590 27431:27467 I/PackageManager]
Linking native library dir for /data/app/io.homeassistant.companion.android-1

[01-03 22:06:34.591 144:144 D/installd]
do_linklib : io.homeassistant.companion.android /data/app/io.homeassistant.companion.android-1/lib/arm 0

[01-03 22:06:34.592 27431:27467 I/PackageManager]
Perform pre-dex opt for package: io.homeassistant.companion.android

[01-03 22:06:34.597 27431:27467 I/art]
DexFile_isDexOptNeeded failed to open oat file ‘/data/dalvik-cache/arm/data@app@io.homeassistant.companion.android-1@base.apk@classes.dex’ for file location ‘/data/app/io.homeassistant.companion.android-1/base.apk’: Failed to open oat filename for reading: No such file or directory

[01-03 22:06:34.598 27431:27467 I/art]
DexFile_isDexOptNeeded failed to open oat file ‘/data/app/io.homeassistant.companion.android-1/arm/base.odex’ for file location ‘/data/app/io.homeassistant.companion.android-1/base.apk’: Failed to open oat filename for reading: No such file or directory

[01-03 22:06:34.598 27431:27467 I/PackageManager]
Running dexopt on: /data/app/io.homeassistant.companion.android-1/base.apk pkg=io.homeassistant.companion.android isa=arm vmSafeMode=false

[01-03 22:06:34.598 144:144 D/installd]
do_dexopt : /data/app/io.homeassistant.companion.android-1/base.apk 50124 1 io.homeassistant.companion.android arm 0

[01-03 22:06:34.774 27650:27650 I/dex2oat]
/system/bin/dex2oat --zip-fd=11 --zip-location=/data/app/io.homeassistant.companion.android-1/base.apk --oat-fd=12 --oat-location=/data/dalvik-cache/arm/data@app@io.homeassistant.companion.android-1@base.apk@classes.dex --instruction-set=arm --instruction-set-features=div --runtime-arg -Xms64m --runtime-arg -Xmx512m

[01-03 22:07:05.747 27650:27657 W/dex2oat]
Compilation of java.lang.Object io.homeassistant.companion.android.controls.HaControlsProviderService$refresh$1$run$$inlined$forEach$lambda$1.invokeSuspend(java.lang.Object) took 112.334ms

[01-03 22:07:06.734 144:144 E/installd]
DexInv: — END ‘/data/app/io.homeassistant.companion.android-1/base.apk’ — status=0x000b, process failed

[01-03 22:07:06.737 27431:27467 I/PackageManager]
Dexopt done on: io.homeassistant.companion.android

[01-03 22:07:06.750 144:144 D/installd]
do_remove : io.homeassistant.companion.android 0

[01-03 22:07:06.750 144:144 D/installd]
uninstall : io.homeassistant.companion.android

[01-03 22:07:06.819 27431:27467 W/PackageManager]
Package couldn’t be installed in /data/app/io.homeassistant.companion.android-1
com.android.server.pm.PackageManagerException: scanPackageLI
at com.android.server.pm.PackageManagerService.scanPackageDirtyLI(PackageManagerService.java:6191)
at com.android.server.pm.PackageManagerService.scanPackageLI(PackageManagerService.java:5500)
at com.android.server.pm.PackageManagerService.installNewPackageLI(PackageManagerService.java:10371)
at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:10926)
at com.android.server.pm.PackageManagerService.access$2800(PackageManagerService.java:236)
at com.android.server.pm.PackageManagerService$6.run(PackageManagerService.java:8818)
at android.os.Handler.handleCallback(Handler.java:815)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:194)
at android.os.HandlerThread.run(HandlerThread.java:61)
at com.android.server.ServiceThread.run(ServiceThread.java:46)

[01-03 22:07:07.286 27076:27076 E/Finsky]
[1] zkh.onReceive(15): Error -504 while installing io.homeassistant.companion.android: INSTALL_FAILED_DEXOPT: Package couldn’t be installed in /data/app/io.homeassistant.companion.android-1: scanPackageLI

[01-03 22:07:07.400 27076:27076 W/Finsky]
[1] rfp.d(4): IT: Install failure of io.homeassistant.companion.android (isid: E5Tkgqz7Q8ujMy78tbKqtQ): -504, Exception: n/a

[01-03 22:07:07.739 27076:27076 I/Finsky]
[1] xjt.a(18): Showing notification: [ID=io.homeassistant.companion.android, Tag=null, Title=Home Assistant sa nedá inštalovať, Message=Skúste to znova a ak to stále nefunguje, prezrite si bežné spôsoby odstránenia tohto problému., channelId=security-and-errors, targetType=1, returnCode=4, uiElementType=946]
```

**Comment by dshokouhi** [comment] 2021-01-18 17:24
User on the HA forums said 2021.1.1 installed successfully.  Going to close this bug now.  If the issue still exists please create a new one along with the new logs.

**Closed by dshokouhi** 2021-01-18 17:24 UTC
Labels: bug
