### ISSUE TITLE
Location tracking Problems in Beta Version

### ISSUE THREAD

**Issue by Sissi91** [home-assistant/android#2720] opened 2022-07-28 09:22 UTC
**Home Assistant Android version:**
Beta Version from 28.07.2022
**Android version:**
13
**Phone model:**
Pixel 5
**Home Assistant version:**
Home Assistant 2022.7.7
**Last working Home Assistant release (if known):**

**Description of problem:**
I use my phone to track if I (Person) am at home or not. Using "home" or "not_home".
Today I realised that something isn't working anymore. And I saw that my Phone isn't updating anymore.
After I quit my beta subscription of the android app and reinstalled the app, the problem was gone.
Before that I checked if the app had the permission to track my location, which it had.

You can see a Screenshot of my History of the past few days. On July 26th I left my home like they days before, but HA didn't noticed it anymore. Since then, the status was "home" until I changed to the non-beta version some minutes ago. So I think it is right to mention this problem before it will be released to the app in Playstore.
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/34167143/181470231-2d75e5f0-b8be-47ef-9397-43333c35e1a5.png)

**Additional information:**

**Comment by dshokouhi** [comment] 2022-07-28 14:22
In order to troubleshoot the issue we need the looks that are part of location troubleshooting. When you downgrade the app you probably enabled the correct sensors by clicking the location tracking toggle. I don't see any mention of you following our troubleshooting guide either so tough to tell if you really needed to downgrade.

**Comment by RoepLuke** [comment] 2022-08-01 16:18
I seem to have the same problem and I too first assumed that it had to do with the play store beta variant. But in my case (i am now back on stable from playstore) it is just the App Sensor Sync to HA that hangs up about every few days.

In the Dashboard (so server-side) the State of my device_tracker entity (gps-based) and its attributes hang at any state (for example "home").
But when i take a look at the sensor data in the Mobile App Settings they are correct.

When i see this happening i currently need to kill the App using the Android App Settings and start it again normally. Then it works again as if nothing had happened.

Will attach Screenshots and what is requested in the troubleshooting guide as soon as it happens again.

**Device Details:**
Android 11
Build RKQ1.210503.001
Fairphone 4
HA App 2022.6.0-full
HA Container 2022.7.6

**Comment by dshokouhi** [comment] 2022-08-02 17:29
@RoepLuke we need to see the companion app logs to confirm, most likely this issue is a duplicate of #2681 

The symptoms sure do sound the same but we need logs to verify if updates just stopped coming in.

If you like you can also test the proposed fix which will detect when the gap occurs and restart tracking.  Make sure to install the full debug APK from the link below.

https://github.com/home-assistant/android/actions/runs/2766579367

**Closed** 2022-08-03 22:07 UTC
Labels: bug, question, location-tracking
