### ISSUE TITLE
Android Companion App has bad element placement issues when system text size is increased

### ISSUE THREAD

**Issue by CoryAlbrecht** [home-assistant/android#2437] opened 2022-04-07 15:33 UTC
**Home Assistant Android version:**
2022.3.0-full

**Android version:**
11

**Phone model:**
Samsung Galaxy Tab 10

**Home Assistant version:**
2022.4.0

**Last working Home Assistant release (if known):**
Never

**Description of problem:**
When you change the system text size on Android, the company app text labels overlap, wrap weird, are cut off, or have other rendering issues.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

![image](https://user-images.githubusercontent.com/8172909/162236831-cf219df5-1fe5-452e-92a9-85d5ee0fd025.png)

**Additional information:**

**Comment by dshokouhi** [comment] 2022-04-07 15:36
do you see the same issue in chrome for android on the same device?

**Comment by CoryAlbrecht** [comment] 2022-04-16 15:35
> do you see the same issue in chrome for android on the same device?

No, I do not.

**Comment by dshokouhi** [comment] 2022-04-16 16:41
Despite this not being reproducible in Chrome, the app has no control over the look and feel of the HA frontend especially when it comes to font size like this. More than likely we will need the HA frontend team to address this issue.

Also looks like you had already started an issue which is similar and will probably impact this issue.  I suspect this is what you see when trying to reproduce in chrome right?  Nothing happens?

https://github.com/home-assistant/frontend/issues/12247

What the app could do is to allow for content scaling but again the HA frontend is responsible for how the elements should look when its scaled.

https://developer.android.com/reference/android/webkit/WebView#setInitialScale(int)

I think your request up above needs to be completed first before the app can take this on because if we do scaling you'll still hit the same overflow issues seen in the screenshots.

**Comment by dshokouhi** [comment] 2022-06-18 17:42
Closing until the noted frontend request is completed

**Closed by dshokouhi** 2022-06-18 17:42 UTC
Labels: bug, question, webview
