### ISSUE TITLE
Wear OS Bluetooth Transmitter stops reporting

### ISSUE THREAD

**Issue by Scags104** [home-assistant/android#3272] opened 2023-01-26 20:22 UTC
**Home Assistant Android version:** beta-3118-65692af5

**Home Assistant Wear OS version:** beta-3118-65692af5

**Android version:** 13

**Phone model:** Pixel 6

**Home Assistant version:** 2023.2.0b1

**Last working Home Assistant release (if known):** N/A

**Description of problem:**
In trying to enable room presence (espresense) given the new BLE transmitter sensor and the addition of the notifications to control transmit power etc., the transmit from the watch seems to work for a few seconds and then stop (only validated via MQTT explorer).

When this happens the beacon monitor sensors in HA do still list these IDs in the attributes so they are still broadcasting from what I can tell.
 
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
If logs are needed I can provide but should this be done from the watch? the phone app? the HA platform?
```

```

**Screenshot of problem:** N/A

**Additional information:**

**Comment by dshokouhi** [comment] 2023-01-26 20:24
This is actually a duplicate of https://github.com/home-assistant/android/issues/3159 as teh code is the same

**Closed by dshokouhi** 2023-01-26 20:24 UTC
Labels: bug
