### ISSUE TITLE
Template widget font color just black

### ISSUE THREAD

**Issue by DaZeroXB** [home-assistant/android#3466] opened 2023-04-09 05:56 UTC
**Home Assistant Android app version(s):** 
2023.3.0-full
**Android version(s):**
13
**Device model(s):**
Google Pixel 7 Pro
**Home Assistant version:**
2023.4.1
**Last working Home Assistant release (if known):**
n/a
**Description of problem, include YAML if issue is related to notifications:**
When using the template widget, the font color is just black when choosing "widget-theme" - "dynamic color".  It should reflect the custom user-personalized theme color of the user's android theme. For the entity widget, the font color is reflected as expected.

**Screenshot or video of problem:**
![image](https://user-images.githubusercontent.com/121690461/230756927-420b3178-b5df-416d-b81c-4380bc28d030.png)

**Additional information:**

**Comment by jpelgrom** [comment] 2023-04-09 06:10
This is by design. Large blocks of text don't use a primary/secondary color.

Compare it with, for example, Keep Notes single note, Google Drive suggested files and Gmail inbox widgets.

**Comment by DaZeroXB** [comment] 2023-04-09 06:29
Thanks @jpelgrom, checked the widgets you've mentionand and agree partially. The font size of the template widget is customizable and thus can be quite small. I still would prefer the colored variant. Maybe we just wait for other comments anda close the issue once the general opinion is that it should stay black.

**Comment by dshokouhi** [comment] 2023-04-09 06:51
I think my template widgets with dynamic theme look fine as is

![Screenshot_20230408-234934.png](https://user-images.githubusercontent.com/1634145/230758818-06796efe-6fd1-4d02-9d55-f05a058d198c.png)

**Comment by jpelgrom** [comment] 2023-04-09 07:01
Looks like it is actually themed with a fitting color, also visible in the screenshot above, but it's _very_ close to black/white most of the time:

https://github.com/home-assistant/android/blob/64ee62b8fa5c615b8fc45e6c237b34b6d89389ea/common/src/main/res/values-v31/colors.xml#L4

**Comment by dshokouhi** [comment] 2023-04-09 16:52
> Looks like it is actually themed with a fitting color, also visible in the screenshot above, but it's _very_ close to black/white most of the time:

Are you saying that it totally depends on the material theme the user chose as its quite evident in the screenshot above the font color is black?

**Comment by jpelgrom** [comment] 2023-04-09 17:09
> Are you saying that it totally depends on the material theme the user chose as its quite evident in the screenshot above the font color is black?

As the linked code shows, yes. Color picker on the initial screenshot doesn't give me 100% black but that might also be due to compression.

**Comment by jpelgrom** [comment] 2023-04-12 16:50
Closing this per above comment, it is tinted but depending on the theme may look black.

**Closed by jpelgrom** 2023-04-12 16:50 UTC
Labels: bug
