### ISSUE TITLE
AA favourites wihout connection to HA

### ISSUE THREAD

**Issue by woniol** [home-assistant/android#3984] opened 2023-10-29 22:11 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
When AA with favourites defined and executet without internet connection, no connection to HA server, only 'Navigatin' link is displayed. Would be nice to get info like 'no HA connection. Check your internet connection' and not to display 'Navigation'

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment] 2023-10-29 22:14
Looks to be a duplicate of #3830

**Comment by dshokouhi** [comment] 2023-10-30 15:21
closing in favor of the mentioned ticket. Whatever we decide to do with forced refresh and error messaging I think should be handled with the same fix.

**Closed by dshokouhi** 2023-10-30 15:21 UTC
Labels: enhancement, Android Auto
