### ISSUE TITLE
In app watchdog to notify when App is not connected to HA

### ISSUE THREAD

**Issue by iulko** [home-assistant/android#3785] opened 2023-08-11 19:31 UTC
**Is your feature request related to a problem? Please describe.**
I read alot of issues and feature request here and other places of people wanting to check if their HA instance is down. Ofc its very hard to implement because offline device cant send notification.

**Describe the solution you'd like**

What I would imagine is a notification from the app when it looses connection to the HA instance . If there is no constant connection to HA (sorry I dont know the inner working of the app) than we could setup number of seconds for a loop so app could ping the instance to check if its available.

This feature is great to see if somebody turn off our server, we lost internet connection etc

**Comment by jpelgrom** [comment] 2023-08-11 19:33
Closing, duplicate of #1033

**Closed by jpelgrom** 2023-08-11 19:33 UTC
Labels: enhancement
