### ISSUE TITLE
Next Alarm Name!

### ISSUE THREAD

**Issue by LorenzoVasi** [home-assistant/android#1308] opened 2021-01-21 22:07 UTC
**Is your feature request related to a problem? Please describe.**

Hi
it would be nice to add into the Next alarm sensor of the HA application an attribute where there's a name of next alarm (for example alarm_name: 'work')
In this way you can differentiate the specific alarm with other alarms

**Describe the solution you'd like**

Add attribute (if it's possible with Android API) alarm_name 
:-)

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment] 2021-01-21 22:13
Sorry we do not get the label set by the alarm in the Android API.  We do get the `package` which is already offered as an attribute.  Also this is a duplicate of #777

**Closed by dshokouhi** 2021-01-21 22:13 UTC
Labels: enhancement

**Comment by ybjlus** [comment] 2022-03-04 10:41
@dshokouhi Did android change/update anything (since this issue was created) which would make the name label possible? Because it would help out a lot if the name label would be included.
