### ISSUE TITLE
App stops registering touches

### ISSUE THREAD

**Issue by tristandegroof** [home-assistant/android#1216] opened 2020-11-27 17:20 UTC
**Home Assistant Android version:** 3.0.2-full

**Android version:** 11

**Phone model:** pixel 5

**Home Assistant version:** 0.118.3

**Last working Home Assistant release (if known):**

**Description of problem:** App somewhat regularly seems to stop registering touches. It is not that it crashes or is unresponsive: I can see information updating, but it just doesn't seem to register touches any more. Seems to happen more often when application has been minimized, or if you have swapped to a different one, but it doesn't happen always in that case, and it can happen also without that. Force closing the app and reopening it solves it.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**
I registered my current device and versions in this template, but have noticed it for some time, also on a different phone.

**Comment by dshokouhi** [comment] 2020-11-27 17:21
Few things to check:

check that android system webview is up to date
update all custom cards
try disbling all custom cards
see if issue is reproducible in chrome for android

**Comment by tristandegroof** [comment] 2020-12-01 11:24
So far haven't been able to reproduce the problem in chrome, but  since there is no exact sequence I keep trying both chrome and the app from time to time. 

Android system webview is at 86.0.4240.198. Custom cards are up to date, disabling them all I still need to test.

**Comment by dimatx** [comment] 2020-12-29 07:35
I also have this issue, exactly as described by OP.

I'm able to reproduce it pretty consistently by sending the app to the background and bring it back.

I am unable to reproduce this issue in Chrome web-based app on same phone.

Phone: Samsung Galaxy S20+
Android: 11
Home Assistant Android version: 3.0.2 and beta-541-bd4a98e-full
Home Assistant OS: 2020.12.1

**Comment by tristandegroof** [comment] 2020-12-29 08:26
> I'm able to reproduce it pretty consistently by sending the app to the background and bring it back.

Ah yes, you're right - the issue only seems to occur on sending to background/restore (in my case: swipe up to get to home screen, tap icon of hass app to reopen or swipe up + hold and go back to hass app), not when you back out of it by pressing back until the app closes (this seems to always close the app, as it always asks for fingerprint after doing that) or sending it to background by directly going to another app (via swipe up + hold-->app-->swipe up + hold-->hass app). 

Must be using either method subconciously, as I never correlated the behaviour :-) 

Still can't reproduce in chrome either, still not had a chance to test without custom cards (but is more feasible now that I can immediately reproduce :-) ). @dimatx: do you have any custom cards?

**Comment by dshokouhi** [comment] 2020-12-29 13:35
Why don't you guys also try [starting fresh](https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app) and also ensuring the app has proper access to run in the background.

**Comment by dimatx** [comment] 2020-12-30 05:40
> Why don't you guys also try [starting fresh](https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app) and also ensuring the app has proper access to run in the background.

A fresh start has helped so far. Thanks @dshokouhi. Didn't need to do much except clear out the app/tokens and reconnect. Hope that also works for you @tristandegroof !

**Comment by dshokouhi** [comment] 2021-01-09 23:20
Closing as clearing data solved the issue

**Closed by dshokouhi** 2021-01-09 23:20 UTC
Labels: bug

**Comment by tristandegroof** [comment] 2021-02-08 22:22
> Closing as clearing data solved the issue

Hi, I recently tried this out as I was finally able to upgrade my installation etc to latest version. Starting fresh does seem to solve the issue - until I re-enabled biometric authentication for the app. 
So the issue occurs with it enabled, and doesn't seem to occur with it disabled. Furthermore, if I wait until after the timeout after putting the app in background, so the biometric authentication promp re-appears, it also keeps registering touches. 
If i send the app to background and back to foreground before the timeout, it obviously doesn't prompt for re-authentication, but stops registering touches.

**Comment by dshokouhi** [comment] 2021-02-08 23:12
> > Closing as clearing data solved the issue
> 
> Hi, I recently tried this out as I was finally able to upgrade my installation etc to latest version. Starting fresh does seem to solve the issue - until I re-enabled biometric authentication for the app.
> So the issue occurs with it enabled, and doesn't seem to occur with it disabled. Furthermore, if I wait until after the timeout after putting the app in background, so the biometric authentication promp re-appears, it also keeps registering touches.
> If i send the app to background and back to foreground before the timeout, it obviously doesn't prompt for re-authentication, but stops registering touches.

biometrics issue is fixed in latest beta
