### ISSUE TITLE
Status bar color doesn't follow dark mode and gets reset after HA restart

### ISSUE THREAD

**Issue by barrymossel** [home-assistant/android#1357] opened 2021-02-10 11:53 UTC
**Home Assistant Android version:**
beta-580-5ee48f2

**Android version:**
Android 11

**Phone model:**
Pixel 5

**Home Assistant version:**
core-2021.2.2
supervisor-2021.02.6

**Last working Home Assistant release (if known):**

**Description of problem:**
When setting theme through frontend.set_theme (mode: light) the Android status bar gets the expected color. After a restart of Home Assistant, the status bar switches to the default color though (blue for Android light mode and black for Android dark mode). The theme itself stays the theme I set it too. Theme follows dark mode (mode: dark) as expected, but status bar does not. When status bar color changes to "default" theme (after restart) it follows the Android dark mode though.
Theme in profile is set to back-end selected (as that is used for following dark mode).

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**
When status bar has uses default color after HA restart and setting my **dark theme**

```
    - service: frontend.set_theme
      data:
        name: thuis-dark
        mode: dark

```
The status bar changes to the **light theme** primary color.

**Comment by dshokouhi** [comment] 2021-02-10 14:05
Duplicate of #272

**Closed by dshokouhi** 2021-02-10 14:05 UTC
Labels: bug

**Comment by barrymossel** [comment] 2021-02-10 14:42
@dshokouhi This addresses the current implementation that seems to be off and can be enhanced. The correct color is fetched after frontend.set_theme, but after a HA restart forgotten/reset. Seems like a bug. I guess the themecolor is stored somewhere, so why would that value change on a HA restart.

As for the dark mode: would it be possible to create an automation that calls frontend.set_theme with Android dark/light mode change as a trigger?
