### ISSUE TITLE
template service call

### ISSUE THREAD

**Issue by sbur83** [home-assistant/android#2666] opened 2022-07-10 04:13 UTC
**Is your feature request related to a problem? Please describe.**
Not a problem as such just a lack of functionality and semi related to the existing thermostat widget request.

What works: I created a template that shows the current temperature, set temperature, and mode of a climate component; I've also added service call buttons that set the HVAC mode to heat, cool etc. ... this works a treat thankyou :)

What doesn't work: I'm unable to make service calls to increase or decrease temperature tho and this would be really handy to do.

**Describe the solution you'd like**
I can see a few solutions to this and I'll start with the android related:

a.) Create a thermostat/ climate widget ...already in feature requests

b.) Allow for data templates with service call widget if possible so that an increase or decrease button can be added 
(maybe I am missing something, I can't get this working)
_eg. this is what I tried to do to increase with a button_
      Service: climate.set_temperature
      Hvac mode: {{states('climate.****') }}
      Target Temp Low: {{ (state_attr('climate.****', 'temperature')|round(0)) + 1 }}

c.) In the wrong place for this request but it would be cool if the climate component could have increment/ decrease temp service calls
    
Cheers, love your work

**Comment by dshokouhi** [comment] 2022-07-10 17:44
> b.) Allow for data templates with service call widget if possible so that an increase or decrease button can be added
> (maybe I am missing something, I can't get this working)
> _eg. this is what I tried to do to increase with a button_
> Service: climate.set_temperature
> Hvac mode: {{states('climate.****') }} Target Temp Low: {{ (state_attr('climate.****', 'temperature')|round(0)) + 1 }}

You can setup a script that handles any logic you desire and have that script execute, there is only 1 button to click so any templating can be done inside a script so the app does not need to be aware of it.  Alternatively you can setup 2 button widgets one for each action you want and change the icon to make sense and click on the appropriate widget.



> c.) In the wrong place for this request but it would be cool if the climate component could have increment/ decrease temp service calls

Yes thats a request for HA core.



> a.) Create a thermostat/ climate widget ...already in feature requests

Based on your goals this is actually duplicate of #2185

**Closed by dshokouhi** 2022-07-10 17:44 UTC
Labels: enhancement

**Comment by sbur83** [comment] 2022-07-10 21:37
> increment

Of course, why didn't I think of scripts; thanks dude.
