### ISSUE TITLE
Spamming mpanion.androi: Invalid ID 0x00000000. In log

### ISSUE THREAD

**Issue by bruvv** [home-assistant/android#1543] opened 2021-05-14 05:53 UTC
**Home Assistant Android version:**
beta-676-1468574-full

**Android version:**
11

**Phone model:**
OnePlus 7 pro

**Home Assistant version:**
2021.5.3

**Last working Home Assistant release (if known):**
Unknown

**Description of problem:**
See the trace back.
While debugging another issue that I had with sleep confidence not being update. I noticed the below error. After wiping the whole phone, the error persistent. 
I read online that is perhaps was related to my phone being set to dark mode, but it wasn't. Read online it had to do with language (mine is set to English(Netherlands)) that didn't solve it either.

Reinstalling the app didn't work and neither did wiping the phone. So I think it is related to home assistant. 

The below traceback is what can be seen in my home assistant android log. It keeps getting slammed every second for hundreds of lines. 

**Traceback**

```
05-14 07:46:33.970  5563  5563 E mpanion.androi: Invalid ID 0x00000000.
05-14 07:46:34.569  5563  5563 E mpanion.androi: Invalid ID 0x00000000.
05-14 07:46:34.570  5563  5563 E mpanion.androi: Invalid ID 0x00000000.
05-14 07:46:34.580  5563  5563 E mpanion.androi: Invalid ID 0x00000000.
05-14 07:46:34.602  5563  5563 I chatty  : uid=10288(io.homeassistant.companion.android) identical 4 lines
05-14 07:46:34.602  5563  5563 E mpanion.androi: Invalid ID 0x00000000.
05-14 07:46:34.615  5563  5563 E mpanion.androi: Invalid ID 0x00000000.
05-14 07:46:34.648  5563  5563 I chatty  : uid=10288(io.homeassistant.companion.android) identical 10 lines
05-14 07:46:34.648  5563  5563 E mpanion.androi: Invalid ID 0x00000000.
05-14 07:46:34.657  5563  5563 E mpanion.androi: Invalid ID 0x00000000.
05-14 07:46:34.659  5563  5563 I chatty  : uid=10288(io.homeassistant.companion.android) identical 2 lines
05-14 07:46:34.659  5563  5563 E mpanion.androi: Invalid ID 0x00000000.
05-14 07:46:34.668  5563  5563 E mpanion.androi: Invalid ID 0x00000000.
```

**Screenshot of problem:**
No issue just the log

**Additional information:**
Did a complete wipe of my phone and that didn't fix it either. My partner has the same phone, same app, same android version and that hasn't any weird error.

**Comment by dshokouhi** [comment] 2021-05-18 16:52
I dont think this is anything to worry about.  Furthermore we have no way to reproduce or even know what the actual issue. What is the actual issue here asides from log spam that could be out of our control? Any loss of functionality?

**Comment by bruvv** [comment] 2021-05-18 18:05
No issue apart from the spam. I can imagine that that will not benefit my battery though ;)?

**Comment by Dennis-Q** [comment] 2021-07-12 22:30
I got the same issue, unfortunately:

```
07-13 00:26:36.276 17832 17832 E mpanion.androi: Invalid ID 0x00000000.
07-13 00:26:36.276 17832 17832 E mpanion.androi: Invalid ID 0x00000000.
07-13 00:26:36.276 17832 17832 E mpanion.androi: Invalid ID 0x00000000.
07-13 00:26:36.276 17832 17832 E mpanion.androi: Invalid ID 0x00000000.
07-13 00:26:36.277 17832 17832 E mpanion.androi: Invalid ID 0x00000000.
07-13 00:26:36.277 17832 17832 E mpanion.androi: Invalid ID 0x00000000.
```

**Comment by Motik68** [comment] 2021-07-28 22:10
I just noticed the same issue.

**Comment by marcelmah** [comment] 2021-08-02 15:09
I have the same, OnePlus 8T Android 11 English (netherlands) dark mode.

**Comment by dshokouhi** [comment] 2021-08-02 15:26
Does this issue only show up if you guys have English (Netherlands) selected? What about English US? What issue asides from logging do you guys see?

**Comment by bruvv** [comment] 2021-08-02 15:29
@dshokouhi I played alot with the different languages but for me ti does not make any difference. perhaps @marcelmah or @Motik68 could test this too?

**Comment by Motik68** [comment] 2021-08-02 20:58
I use French and have the same behaviour.

**Comment by marcelmah** [comment] 2021-08-06 07:19
It looks like mine stopped generating this error.
I did update to 2021.8.2 (and all in between).

**Comment by bruvv** [comment] 2021-10-02 07:28
Just checked and this is still an issue.

**Comment by marcelmah** [comment] 2021-10-02 08:14
Same here

**Comment by vakilando** [comment] 2021-11-28 11:52
Same here. OnePlus 6, dark mode, german

**Comment by dshokouhi** [comment] 2022-02-05 18:16
Closing as these logs are not directly from the app and Android logs are chatty by nature. They are safe to ignore.

**Closed by dshokouhi** 2022-02-05 18:16 UTC
Labels: bug
