### ISSUE TITLE
Need a refresh button or pull-down function

### ISSUE THREAD

**Issue by ams3401** [home-assistant/android#2874] opened 2022-09-13 03:26 UTC
**Is your feature request related to a problem? Please describe.**
iiOS HA app has pull-down refresh function in the app which is very helpful when the dashboard doesn't load properly. I looked everywhere inside the Android App and could not find a way to mimic the same function. I had to clear cache in Android's App setting manually.

**Describe the solution you'd like**
Pull down to refresh or a refresh button in Application setting 

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment] 2022-09-13 03:28
duplicate of #31

**Closed by dshokouhi** 2022-09-13 03:28 UTC
Labels: enhancement

**Comment by ams3401** [comment] 2022-09-13 03:33
@dshokouhi Hi, that thread is almost 3 years old and got closed without any realistic solution. Has there been any update since?

**Comment by dshokouhi** [comment] 2022-09-13 03:37
If you read the thread it mentions that the HA frontend should be addressing concerns related to loading. If you find a bug you should file it with the frontend but make sure to first disable custom cards to rule them out as the issue. Also make sure Android system WebView is up to date and is Google's version from the play store, other WebView may have compatibility issues.

FWIW I do not see the need to refresh like that but I also do not use custom stuff. the dashboard loads fine all the time.
