### ISSUE TITLE
Vibration on Pixel 8

### ISSUE THREAD

**Issue by TrilIiard** [home-assistant/android#4003] opened 2023-11-06 13:48 UTC
**Home Assistant Android app version(s):**
2023.11.1
**Android version(s):**
14
**Device model(s):**
Google Pixel 8
**Home Assistant version:**
Core
2023.11.1
Supervisor
2023.10.1
Operating System
11.1
Frontend
20231030.1
**Last working Home Assistant release (if known):**
None
**Description of problem, include YAML if issue is related to notifications:**
Vibration doesnt work on Pixel 8

**Companion App Logs:**

```
11-06 14:40:45.810  9590 10081 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:40:45.812  9590 10081 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:40:45.958  9590 10081 D SensorReceiver: Nothing to update for server 1 (Home)
11-06 14:40:45.958  9590 10081 I SensorReceiver: Sensor updates and sync completed
11-06 14:40:53.590  9590  9590 D TrafficStats: tagSocket(98) with statsTag=0xffffffff, statsUid=-1
11-06 14:41:48.506  9590  9590 D TrafficStats: tagSocket(98) with statsTag=0xffffffff, statsUid=-1
11-06 14:41:48.508  9590  9590 D TrafficStats: tagSocket(98) with statsTag=0xffffffff, statsUid=-1
11-06 14:41:48.509  9590  9590 D TrafficStats: tagSocket(98) with statsTag=0xffffffff, statsUid=-1
11-06 14:41:48.510  9590  9590 D TrafficStats: tagSocket(98) with statsTag=0xffffffff, statsUid=-1
11-06 14:41:48.512  9590  9590 D TrafficStats: tagSocket(98) with statsTag=0xffffffff, statsUid=-1
11-06 14:41:48.517  9590  9590 D WebviewActivity: Matter commissioning status changed to NOT_STARTED
11-06 14:41:48.518  9590  9590 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:41:48.518  9590  9590 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:41:48.518  9590  9590 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 0, currentMillis: 1699278108518)
11-06 14:41:48.562  9590  9590 D LocBroadcastReceiver: Received location update.
11-06 14:41:48.564  9590  9590 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = false
11-06 14:41:48.565  9590  9628 D LocBroadcastReceiver: Last Location: 
11-06 14:41:48.565  9590  9628 D LocBroadcastReceiver: Coords:(51.2012441, 6.4424865)
11-06 14:41:48.565  9590  9628 D LocBroadcastReceiver: Accuracy: 100.0
11-06 14:41:48.565  9590  9628 D LocBroadcastReceiver: Bearing: 0.0
11-06 14:41:48.565  9590  9628 D LocBroadcastReceiver: Begin evaluating if location update should be skipped
11-06 14:41:48.565  9590  9628 D LocBroadcastReceiver: Received location that is 82 milliseconds old, 1699278108483 compared to 1699278108565 with source fused
11-06 14:41:48.565  9590  9628 D LocBroadcastReceiver: Duplicate location received, not sending to HA
11-06 14:41:48.612  9590  9628 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:41:48.614  9590  9621 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=97434ee5-b04b-4929-abe4-e938cad1682d, tags={ io.homeassistant.companion.android.websocket.WebsocketManager } ]
11-06 14:41:48.616  9590  9590 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:41:48.616  9590  9590 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 0, currentMillis: 1699278108616)
11-06 14:41:48.617  9590  9621 I WM-Processor: Moving WorkSpec (64c92c14-fde9-47f7-924e-0fbc1f28cb1e) to the foreground
11-06 14:41:48.622  9590 27577 D SensorWorker: Updating all Sensors in foreground.
11-06 14:41:48.623  9590  9590 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:41:48.623  9590  9590 D ServerConnectionInfo: Using external URL
11-06 14:41:48.623  9590  9590 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:41:48.623  9590 27577 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:41:48.623  9590  9590 D ServerConnectionInfo: Using external URL
11-06 14:41:48.645  9590  9590 I WM-SystemFgDispatcher: Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService (has extras) }
11-06 14:41:48.676  9590 27577 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:41:48.676  9590 27577 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:41:48.739  9590 27577 D SensorReceiver: Nothing to update for server 1 (Home)
11-06 14:41:48.740  9590 27577 I SensorReceiver: Sensor updates and sync completed
11-06 14:41:48.741  9590  9642 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=64c92c14-fde9-47f7-924e-0fbc1f28cb1e, tags={ io.homeassistant.companion.android.sensors.SensorWorker } ]
11-06 14:41:48.743  9590  9590 I WM-SystemFgDispatcher: Stopping foreground service
11-06 14:41:49.997  9590  9590 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.widget.PopupWindow$PopupDecorView$$ExternalSyntheticLambda0@bc2b16c
11-06 14:41:50.017  9590  9590 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.widget.PopupWindow$PopupDecorView$$ExternalSyntheticLambda0@5e13db1
11-06 14:41:52.698  9590 18346 D WebviewActivity: External bus {"type":"config_screen/show","id":73}
11-06 14:41:52.748  9590  9590 D IntegrationRepository: setAppActive(): false
11-06 14:41:52.748  9590  9590 D IntegrationRepository: setAppActive(): false
11-06 14:41:52.755  9590  9590 D SensorReceiver: Received intent: io.homeassistant.companion.android.UPDATE_SENSORS
11-06 14:41:52.757  9590  9625 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:41:52.785  9590  9625 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:41:52.785  9590  9625 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:41:52.825  9590  9625 D SensorReceiver: Nothing to update for server 1 (Home)
11-06 14:41:52.825  9590  9625 I SensorReceiver: Sensor updates and sync completed
11-06 14:41:52.860  9590  9590 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 0, currentMillis: 1699278112860)
11-06 14:41:52.915  9590  9625 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:41:52.934  9590  9590 D SettingsWearDetection: API unavailable for discovering nodes (no Wear)
11-06 14:41:52.957  9590 27375 D TrafficStats: tagSocket(503) with statsTag=0xffffffff, statsUid=-1
11-06 14:41:52.959  9590  9590 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 0, currentMillis: 1699278112959)
11-06 14:41:52.959  9590  9590 D IntegrationRepository: setAppActive(): true
11-06 14:41:52.969  9590  9590 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=androidx.activity.OnBackPressedDispatcher$Api34Impl$createOnBackAnimationCallback$1@b7f0a96
11-06 14:42:11.371  9590  9625 D LogcatReader: Read logcat for pid 9590
11-06 14:42:11.430  9590  9625 D LogcatReader: Done reading logcat for pid 9590
11-06 14:42:33.179  9590  9590 I ImeTracker: io.homeassistant.companion.android:39085d80: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT
11-06 14:42:34.064  9590  9590 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=androidx.activity.OnBackPressedDispatcher$Api34Impl$createOnBackAnimationCallback$1@66debc8
11-06 14:42:34.449  9590  9590 D TrafficStats: tagSocket(119) with statsTag=0xffffffff, statsUid=-1
11-06 14:42:34.780  9590  9590 D IntegrationRepository: setAppActive(): false
11-06 14:42:34.785  9590  9590 D WebviewActivity: Matter commissioning status changed to NOT_STARTED
11-06 14:42:34.786  9590  9590 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:42:34.787  9590  9590 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:42:34.787  9590  9590 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 1699278155780, currentMillis: 1699278154787)
11-06 14:42:34.915  9590  9625 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:42:34.915  9590  9630 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=e09756a6-394d-4e65-b0b9-631c36286fb5, tags={ io.homeassistant.companion.android.websocket.WebsocketManager } ]
11-06 14:42:34.918  9590  9630 I WM-Processor: Moving WorkSpec (eb587c9f-62cd-414d-9abe-25ade7000515) to the foreground
11-06 14:42:34.921  9590  9590 I WM-SystemFgDispatcher: Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService (has extras) }
11-06 14:42:34.928  9590  9628 D SensorWorker: Updating all Sensors in foreground.
11-06 14:42:34.929  9590  9628 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:42:34.944  9590  9590 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:42:34.944  9590  9590 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 1699278155780, currentMillis: 1699278154944)
11-06 14:42:34.949  9590  9590 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:42:34.949  9590  9590 D ServerConnectionInfo: Using external URL
11-06 14:42:34.950  9590  9590 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:42:34.950  9590  9590 D ServerConnectionInfo: Using external URL
11-06 14:42:34.978  9590  9590 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.app.Activity$$ExternalSyntheticLambda0@6dd8504
11-06 14:42:34.990  9590  9625 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:42:34.992  9590  9625 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:42:35.074  9590  9625 D SensorReceiver: Nothing to update for server 1 (Home)
11-06 14:42:35.074  9590  9625 I SensorReceiver: Sensor updates and sync completed
11-06 14:42:35.075  9590  9621 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=eb587c9f-62cd-414d-9abe-25ade7000515, tags={ io.homeassistant.companion.android.sensors.SensorWorker } ]
11-06 14:42:35.078  9590  9590 I WM-SystemFgDispatcher: Stopping foreground service
11-06 14:42:38.151  9590 18346 D WebviewActivity: External bus {"type":"haptic","payload":{"hapticType":"light"},"id":74}
11-06 14:42:38.154  9590  9590 D WebviewActivity: Processing haptic tag for light
11-06 14:42:39.103  9590 18346 D WebviewActivity: External bus {"type":"haptic","payload":{"hapticType":"light"},"id":75}
11-06 14:42:39.103  9590  9590 D WebviewActivity: Processing haptic tag for light
11-06 14:42:42.760  9590 18346 D WebviewActivity: External bus {"type":"haptic","payload":{"hapticType":"light"},"id":76}
11-06 14:42:42.760  9590  9590 D WebviewActivity: Processing haptic tag for light
11-06 14:42:43.996  9590 18346 D WebviewActivity: External bus {"type":"haptic","payload":{"hapticType":"light"},"id":77}
11-06 14:42:43.996  9590  9590 D WebviewActivity: Processing haptic tag for light
11-06 14:42:44.861  9590 18346 D WebviewActivity: External bus {"type":"haptic","payload":{"hapticType":"light"},"id":78}
11-06 14:42:44.861  9590  9590 D WebviewActivity: Processing haptic tag for light
11-06 14:42:45.608  9590 18346 D WebviewActivity: External bus {"type":"haptic","payload":{"hapticType":"light"},"id":79}
11-06 14:42:45.608  9590  9590 D WebviewActivity: Processing haptic tag for light
11-06 14:42:46.227  9590 18346 D WebviewActivity: External bus {"type":"haptic","payload":{"hapticType":"light"},"id":80}
11-06 14:42:46.228  9590  9590 D WebviewActivity: Processing haptic tag for light
11-06 14:42:46.876  9590 18346 D WebviewActivity: External bus {"type":"haptic","payload":{"hapticType":"light"},"id":81}
11-06 14:42:46.877  9590  9590 D WebviewActivity: Processing haptic tag for light
11-06 14:42:48.511  9590  9590 D LocBroadcastReceiver: Received location update.
11-06 14:42:48.512  9590  9590 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = false
11-06 14:42:48.513  9590  9625 D LocBroadcastReceiver: Last Location: 
11-06 14:42:48.513  9590  9625 D LocBroadcastReceiver: Coords:(51.2012441, 6.4424865)
11-06 14:42:48.513  9590  9625 D LocBroadcastReceiver: Accuracy: 100.0
11-06 14:42:48.513  9590  9625 D LocBroadcastReceiver: Bearing: 0.0
11-06 14:42:48.513  9590  9625 D LocBroadcastReceiver: Begin evaluating if location update should be skipped
11-06 14:42:48.513  9590  9625 D LocBroadcastReceiver: Received location that is 29 milliseconds old, 1699278168484 compared to 1699278168513 with source fused
11-06 14:42:48.513  9590  9625 D LocBroadcastReceiver: Duplicate location received, not sending to HA
11-06 14:42:48.682  9590 18346 D WebviewActivity: External bus {"type":"haptic","payload":{"hapticType":"light"},"id":82}
11-06 14:42:48.682  9590  9590 D WebviewActivity: Processing haptic tag for light
11-06 14:42:49.611  9590 18346 D WebviewActivity: External bus {"type":"haptic","payload":{"hapticType":"light"},"id":83}
11-06 14:42:49.611  9590  9590 D WebviewActivity: Processing haptic tag for light
11-06 14:42:52.846  9590  9590 D TrafficStats: tagSocket(239) with statsTag=0xffffffff, statsUid=-1
11-06 14:42:53.568  9590 18346 D WebviewActivity: External bus {"type":"config_screen/show","id":84}
11-06 14:42:53.585  9590  9590 D IntegrationRepository: setAppActive(): false
11-06 14:42:53.585  9590  9590 D IntegrationRepository: setAppActive(): false
11-06 14:42:53.592  9590  9590 D SensorReceiver: Received intent: io.homeassistant.companion.android.UPDATE_SENSORS
11-06 14:42:53.593  9590  9625 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:42:53.607  9590  9590 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 1699278155780, currentMillis: 1699278173607)
11-06 14:42:53.622  9590  9625 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:42:53.623  9590  9625 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:42:53.632  9590  9625 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-06 14:42:53.646  9590  9590 D SettingsWearDetection: API unavailable for discovering nodes (no Wear)
11-06 14:42:53.694  9590  9590 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 1699278155780, currentMillis: 1699278173694)
11-06 14:42:53.694  9590  9590 D IntegrationRepository: setAppActive(): true
11-06 14:42:53.695  9590  9590 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=androidx.activity.OnBackPressedDispatcher$Api34Impl$createOnBackAnimationCallback$1@b7f0a96
11-06 14:42:53.710  9590  9625 D SensorReceiver: Nothing to update for server 1 (Home)
11-06 14:42:53.710  9590  9625 I SensorReceiver: Sensor updates and sync completed
11-06 14:42:57.302  9590  9628 D LogcatReader: Read logcat for pid 9590

```

**Screenshot or video of problem:**

**Additional information:**
Uninstall and reinstall of the Home Assistent App doesnt solve the problem, Device Vibration still dont work on Pixel 8

**Comment by dshokouhi** [comment] 2023-11-06 14:02
Did you turn on vibrate in your user profile? Do you have touch feedback haptics set to something above 0?

**Comment by TrilIiard** [comment] 2023-11-06 17:38
Ohh, thanks for the hint. Didnt know that the haptic Feedback needs to be enabled, on all others phones i had the in App settings where never blocked by disabling system touch Vibration Feedback. Thats realy strange and anoying too haha. So is this a Bug or the way it should be?

**Comment by dshokouhi** [comment] 2023-11-06 17:39
> So is this a Bug or the way it should be?

as designed, the app respects device and user profile settings.

closing as this is working as intended

**Closed by dshokouhi** 2023-11-06 17:39 UTC
Labels: bug, question, webview
