### ISSUE TITLE
Battery drain on Android app

### ISSUE THREAD

**Issue by mrtoddles11** [home-assistant/android#1800] opened 2021-10-18 22:47 UTC
I just installed home assistant Android app last night. I look at my battery this afternoon and I'm already down at 14%! I investigate why and it turns out home assistant is just burning through battery. 

Let me know if you need me to pull more logs. But for now I need to uninstall. 

Is there anything I can do about this? Appreciate all your help! Love the project! 

![Screenshot_20211018-141645](https://user-images.githubusercontent.com/5711923/137816612-1bd81dbd-f6dd-4859-bc7a-2551068e4d82.png)

**Comment by dshokouhi** [comment] 2021-11-04 13:51
@mrtoddles11 without getting the requested information above we cant proceed to help out and diagnose the cause of battery drain here.

**Comment by M-Wahren** [comment] 2021-11-24 11:31
Just the last days i have noticed my battery being drained.
I'm running 2021.10.0-full version of the app
and currently on 2021.11.5 supervised OS

![Screenshot_20211124-112032_Device care](https://user-images.githubusercontent.com/34152713/143221682-37645371-6112-4bbc-8705-cdf1125f54b3.jpg)

**Comment by dshokouhi** [comment] 2021-11-24 14:41
@M-Wahren please provide more information as requested above your post. This is not enough to go by.

**Comment by M-Wahren** [comment] 2021-11-25 08:02
Absolutely!
I'm not running any Live camera views on my dashboard i don't have any widgets from the app.
This is my entire list of active sensors in the app.
 
![Screenshot_20211124-112504_Home Assistant](https://user-images.githubusercontent.com/34152713/143402348-d6dafb9c-4c5b-409c-8d13-32265fd05327.jpg)

**Comment by dshokouhi** [comment] 2021-11-25 09:09
> Absolutely!
> I'm not running any Live camera views on my dashboard i don't have any widgets from the app.

What are your location sensor settings like? Are you using high accuracy mode? If you check the device logs do you see any errors?

**Comment by M-Wahren** [comment] 2021-11-25 12:59
No I'm not using high accuracy, it is disabled.
device logs as in "Show and Share logs" in app or using development tools and checking using some adb tool?

**Comment by dshokouhi** [comment] 2021-11-25 17:05
> No I'm not using high accuracy, it is disabled.

The sensor is disabled but its a sensor setting under Background Location, same with the other setting I mentioned if you look under Single Accurate Location.

Yes device logs from Show and Share logs, try to get 10 minutes or more of data so we can see whats happening.  If we don't see anything glaring then we may just need to start fresh with the app.

**Comment by M-Wahren** [comment] 2021-11-26 12:28
Under Background Location the High accuracy mode is disabled also.
Under Single Accurate Location the "include in sensor update" is Disabled
[homeassistant_companion_log_10-26-2021_13-5-22_edited.txt](https://github.com/home-assistant/android/files/7608715/homeassistant_companion_log_10-26-2021_13-5-22_edited.txt)

**Comment by dshokouhi** [comment] 2021-11-26 19:18
Not seeing any errors, can you try to start fresh:

https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by M-Wahren** [comment] 2021-12-20 12:45
Sorry for not getting back..
I have not tried "starting Fresh" however the next day the problem seems to have gone away.
i haven't had a problem with battery drain since then.

**Comment by dshokouhi** [comment] 2021-12-20 15:34
ok closing this issue for now, if the issue comes back please open a new issue

**Closed by dshokouhi** 2021-12-20 15:34 UTC
Labels: question
