### ISSUE TITLE
Aplication hang in sensor history

### ISSUE THREAD

**Issue by PetrDubi** [home-assistant/android#3719] opened 2023-07-27 06:21 UTC
**Home Assistant Android app version(s):**
2023.7.5-full
**Android version(s):**
9 PPR1.180610.011
**Device model(s):**
Redmi 6
**Home Assistant version:**
2023.07.1
**Last working Home Assistant release (if known):**
First months od year 2023
**Description of problem, include YAML if issue is related to notifications:**

When I go to sensor history in application on Android 9 with last version application, then aplication hang, history is white (without graph) and aplication not react on any tap (I must close application in task manager). This problem was start before cca. last 3-4 months. When I open web page in Chrome on the same device, all is function without problem. Problem is not with every sensors, but some sensors mostly hang of application and sometimes function well and other sensors mostly function well and sometimes hang of aplication.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2023-07-27 06:31
This sounds like a frontend issue rather than an app issue have you checked for open issues there?

**Comment by PetrDubi** [comment] 2023-07-27 06:42
But this problem is only in android application. When I open homeassistant page on the same device in Chrome, all function is ok.
Now I was try delete all data in application, run application and log to homeassistant server and history on all problematic sensors function well. Then I was close application, run application, go to sensor history and application hang. Maybe is some problem with temporary data in application.

**Comment by dshokouhi** [comment] 2023-07-27 06:47
Is Android system WebView up to date?

**Comment by dshokouhi** [comment] 2023-07-27 06:50
Might be a duplicate of https://github.com/home-assistant/frontend/issues/17203

**Comment by PetrDubi** [comment] 2023-07-27 07:05
Android is up to date, all actualisations are installed.
In issue 17203 is problem only with version 2023.7 and in 2023.6 was ok, but my problem is in 2023.6, 2023.5, 2023.4...
My problem was starting after update application not after update Homeassistant and in web browsers is all ok on the computers and phones.
I waited if the problem would not solve the new version of the application but did not happen so.

**Comment by dshokouhi** [comment] 2023-07-27 07:13
We don't control what you see in the dashboard that is from the WebView which is why I asked if it is up to date. What version is yours? Should be similar if not same as chrome. Everything you see in the dashboard is from the frontend.

**Comment by PetrDubi** [comment] 2023-07-27 08:05
Weview is latest verison 114.0.5735.196 prom 26.6.2023.
The problem is mainly with sensors which shows power sensors (unit W) which are calculated in Homeassistant, but sometimes is problem with sensors which are not power (unit W) or which are not calculated.

**Comment by jbrepogmailcom** [comment] 2023-08-04 10:29
Same problem for me. I have updated Android 12 and the application is hardly usable. When going to sensor details (or search or many other places), the app freezes for about 20 seconds and Android OS wants to close it as unresponsive app.

When going to HA web UI on Brave on the same Android, it responds immediately.

I cannot wipe companion app settings as I have quite complex setup of location parameters.

I cannot use the companion app, I have to use web UI. I just use the app to send out phone sensor data.

**Comment by jbrepogmailcom** [comment] 2023-08-04 10:45
I have wiped data of webview and the app seems not freezing

**Comment by dshokouhi** [comment] 2023-08-05 19:14
I think this might be fixed in 2023.8?

**Comment by dshokouhi** [comment] 2023-09-06 23:24
Closing due to lack of responses, please make sure to update to HA core 2023.8 or later before confirming the issue. I would also double check HA frontend issues in case it got reintroduced.

**Closed by dshokouhi** 2023-09-06 23:24 UTC
Labels: bug, question, webview
