### ISSUE TITLE
Notification actions stopped working when image also defined

### ISSUE THREAD

**Issue by quazzie** [home-assistant/android#1188] opened 2020-11-12 10:52 UTC
```
service: notify.myself
data:
  message: Someone at the door
  data:
    image: "http://..../cameraimage.jpg"
    actions: 
      - action: "sayhi"
        title: "Say hi"
```

If I have an image, the image shows but no actions.
If I remove the image the actions show.

**Home Assistant Android version:**
3.0.1-full

**Android version:**
10 QKQ1.190828.002 (MIUI 12.0.2)

**Phone model:**
Pocophone f1

**Home Assistant version:**
0.117.6

**Last working Home Assistant release (if known):**

**Description of problem:**

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by JBassett** [comment] 2020-11-12 12:48
I am unable to reproduce:
![Screenshot_20201112-074739.png](https://user-images.githubusercontent.com/1051414/98942069-7841e200-24bb-11eb-815a-ddb0002983e2.png)

**Comment by quazzie** [comment] 2020-11-12 13:28
Hmm, what android version you got ?

**Comment by JBassett** [comment] 2020-11-12 13:31
Android 11 with a Pixel 24

**Comment by quazzie** [comment] 2020-11-12 13:49
```
title: Testing
message: Test
data:
  image: '/local/snapshots/entre_s.jpg'
  actions:
    - action: test
      title: Testing
```
![Screenshot_2020-11-12-14-43-50-501_com mi android globallauncher](https://user-images.githubusercontent.com/2979933/98948062-3f732e80-24f6-11eb-988e-42fce2ef504d.jpg)

```
title: Testing
message: Test
data:
  #image: '/local/snapshots/entre_s.jpg'
  actions:
    - action: test
      title: Testing
```
![Screenshot_2020-11-12-14-44-09-453_com mi android globallauncher](https://user-images.githubusercontent.com/2979933/98948068-426e1f00-24f6-11eb-912d-c99f8bcbdd8a.jpg)

**Comment by dshokouhi** [comment] 2020-11-12 15:37
I can't reproduce this either:

```
message: test
data:
  image: "/local/mr_neato.jpg"
  actions:
    - action: test
      title: test
```

![image](https://user-images.githubusercontent.com/1634145/98960837-c1913200-24b9-11eb-9b77-b861ff90500a.png)

It might be that you need to start fresh from the app: https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by quazzie** [comment] 2020-11-12 15:44
Hmm, just started fresh. Uninstalled beta version and went back to normal version.
After a ton of googling it might be something with MIUI 12 (Xiaomis android), found examples for youtube notification missing actions like watch later and so on on MIUI 12.

**Comment by MrAvana** [comment] 2020-11-15 07:17
I have the same problem. I have to either choose image or actions. Can't have both in a notification. Running MIUI 12 on a Redmi Note 7.

**Comment by MrAvana** [comment] 2020-11-15 14:22
I just tried it on a Samsung A20 running Android 10 and the problem also persists.

**Comment by MrAvana** [comment] 2020-11-21 17:12
I fixed the issue by updating to the latest version of miui.

**Comment by dshokouhi** [comment] 2021-02-11 16:48
Closing per above comment that updated OS fixed the issue.  If the bug still exists after this lets make sure to get on device logs during the time of the issue.

**Closed by dshokouhi** 2021-02-11 16:48 UTC
Labels: bug, notifications
