### ISSUE TITLE
Enable Dual Messenger feature

### ISSUE THREAD

**Issue by bombaata** [home-assistant/android#2108] opened 2022-01-04 10:04 UTC
Is it possible to enable a "dual messenger" feature in order to run multiple HA on Android device ?
Dual Messenger allows you to install a second copy of compatible apps.

Samsung phones have enabled this feature for apps like Telegram, Messenger or Whatsapp. Having HA in this list would be great !

I don't know how it works, I found [this](https://www.reddit.com/r/oneplus/comments/7s64ff/how_do_parallel_apps_work/) which might help.

**Comment by dshokouhi** [comment] 2022-01-04 13:38
You can use an app like Island to clone an app and use it like that, otherwise if you need to connect to more than one HA instance then this is a duplicate of #296 

there are no android specific features for what you are requesting....this is something a manufacturer does on their own.

**Closed by dshokouhi** 2022-01-04 13:38 UTC
