### ISSUE TITLE
Location tracking always pinging between zone and away then zone

### ISSUE THREAD

**Issue by blair287** [home-assistant/android#982] opened 2020-09-27 06:06 UTC
**Home Assistant Android version:**

beta-383-debeadb-full

**Android version:**

10

**Phone model:**

Oneplus 7

**Home Assistant version:**

114.4

**Last working Home Assistant release (if known):**

**Description of problem:**

I'm having this issue always home then away the. Home again and vice versa in the space on a few seconds.

![Screenshot_20200927-070040](https://user-images.githubusercontent.com/44187409/94357322-d3e11900-008f-11eb-86bb-86231fa15980.jpg)
![Screenshot_20200927-065441](https://user-images.githubusercontent.com/44187409/94357325-d5124600-008f-11eb-8352-b99b15d9983e.jpg)

The times it happened is within a few seconds of the first update which is always correct.

Is it not possible to add in a denounce accept the first result then stop further update for say 30 seconds. Although this would always solve it.

It's screwing up automations with this jumping back and forth sometimes in will go home away home away home all within 60 seconds and my home zone is 400m.

Happens to all the phones I have on HA 

Tado does location tracking too and I find it much more reliable and it has an option to disable WiFi tracking and only use GPS and cell tower which improves it a lot.

![Screenshot_20200927-070812](https://user-images.githubusercontent.com/44187409/94357360-4baf4380-0090-11eb-9723-ce10b4316f9f.jpg)
 As you can see from Tado it doesn't do zones only home or away but it is much more reliable not jumping all over the place same phone.

Some times home assistant app shows me home and away at the same time down to the same second not sure how that is possible.

Both Tado and HA have home zone at 400m.

Maybe a few months back I don't recall seeing this problem on any phones. 

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2020-09-27 23:13
Duplicate of #871

**Closed by dshokouhi** 2020-09-27 23:13 UTC
Labels: bug
