### ISSUE TITLE
Shopping List does not add items when pressing enter on keyboard

### ISSUE THREAD

**Issue by anLizard** [home-assistant/android#2680] opened 2022-07-15 11:20 UTC
**Home Assistant Android version:**
2022.6.0-full
**Android version:**
12
**Phone model:**
OnePlus 6
**Home Assistant version:**
2022.7.4
**Last working Home Assistant release (if known):**

**Description of problem:**
If there are already items in the shopping list, pressing enter on the keyboard does not add newly typed entries.
Instead, the cursor jumps to the next entry.
If there are no items in the shopping list already, this problem doesnt present.

How to reproduce:
1. Add items to empty shopping list, works as intended
2. Close and re-open app
3. Add additional item to shopping list with enter key on on screen keyboard
--> The item will not be added, instead, the cursor jumps to the next already entered item

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

https://user-images.githubusercontent.com/48686356/179213491-584b7eaf-409c-457f-9197-a28dcefd6101.mp4

**Additional information:**

**Comment by jpelgrom** [comment] 2022-07-15 11:31
Does this also happen when using Home Assistant in Chrome?

It's probably a frontend issue, duplicate of home-assistant/frontend#12849

**Comment by jpelgrom** [comment] 2022-07-15 16:30
Thanks for testing! Because this also happens in Chrome this isn't an app-related problem, so I'll close this issue. Please follow the issue I've linked in my previous comment for updates and/or add more information there to help the frontend devs.

**Closed as not planned by jpelgrom** 2022-07-15 16:30 UTC
Labels: bug
