### ISSUE TITLE
Excessive battery usage

### ISSUE THREAD

**Issue by bram2202** [home-assistant/android#1017] opened 2020-10-07 19:00 UTC
**Home Assistant Android version:**
2.5.0-full

**Android version:**
10

**Phone model:**
Xiaomi Mi 9T Pro

**Home Assistant version:**
0.115.6

**Last working Home Assistant release (if known):**

**Description of problem:**
Home assistant companion app excessive battery usage

**Traceback (if applicable):**

**Screenshot of problem:**
![photo_2020-10-07_20-44-23 bak](https://user-images.githubusercontent.com/6704538/95375505-04bb1c80-08e0-11eb-8f17-3eb9000855ed.jpg)
![photo_2020-10-07_20-44-26 bak](https://user-images.githubusercontent.com/6704538/95375506-0553b300-08e0-11eb-82e2-50496bb9d169.jpg)

**Additional information:**

I opened the app this morning (08:00) to start the radio, and a hour late to stop it.
Later in the day (20:43), the battery is almost empty.
According to the android battery management the app is responsible for 37% of the total use, 
while being active for 1 minute (Dutch: "Tijdens actief gebruik") and 0 minutes in the background (Dutch: "Wanneer op de achtergrond")

**Comment by dshokouhi** [comment] 2020-10-07 19:02
What sensors do you have enabled in the app?  At one point in time all sensors were enabled by default but we have since changed that.  I suggest you look into disabling some sensors you don't need to see if that helps out.  Personally I have all sensors enabled and I rarely see batter usage go over 3% but every device is different.

**Comment by bram2202** [comment] 2020-10-07 19:06
I did a clean install a while ago where all sensors where enabled, now all sensors are disabled except for the 5 of battery.

**Comment by dshokouhi** [comment] 2020-10-07 19:07
This looks like an edge case....without getting some type of logs it would be impossible to tell where the issue came from.  Especially since it reports 1 minute of usage.  Lets see if the trend continues on your device, maybe something just got stuck somewhere

**Comment by bram2202** [comment] 2020-10-07 19:10
This issue has been going on for a while now. (~5 weeks)
I originally ran the beta app, with the same issue, but switching to non-beta did not change a thing.

**Comment by dshokouhi** [comment] 2020-10-07 19:12
> This issue has been going on for a while now. (~5 weeks)

what version did you notice this start from?

**Comment by bram2202** [comment] 2020-10-07 19:14
I really have no idea, i did not check the version at the time of the switch.

**Comment by dshokouhi** [comment] 2020-10-07 19:21
what does the data usage for the app look like? maybe you had a video stream get stuck?

**Comment by JBassett** [comment] 2020-10-07 19:23
> what does the data usage for the app look like? maybe you had a video stream get stuck?

I was about to ask the same thing.  Do you have any live picture entity cards?

**Comment by bram2202** [comment] 2020-10-07 19:29
Yes, I have 3 live picture entity cards. 
I cant see the day-to-day data use of my apps, but in the period from 9 September till 7 October the app used:
- Total: 3.1 GB 
- Foreground: 200 MB
- Background 2.9 GB !

**Comment by dshokouhi** [comment] 2020-10-07 19:34
Thanks for confirming @bram2202 this is actually a duplicate of #979 so I am going to close this now.

In the meantime if you remove the live view option you should not hit this issue.  The frontend recently introduced a new setting "automatically close connection" in your HA user profile and it is on by default.  You can try and double check its enabled there to be certain but it seems that bug gets around the issue so we need to investigate it more.  Feel free to comment in the other bug leaving your card configuration to help out with troubleshooting.

**Closed** 2020-10-07 19:34 UTC
Labels: bug

**Comment by bram2202** [comment] 2020-10-08 13:56
@dshokouhi i remove the whole camera integration from the config and lovelace.
checked the ""automatically close connection" setting.
no real noticeable change:
![photo_2020-10-08_15-53-26](https://user-images.githubusercontent.com/6704538/95468267-a133fc00-097e-11eb-8953-7ee44ceac62b.jpg)

**Comment by dshokouhi** [comment] 2020-10-08 14:13
Check your data usage again

**Comment by bram2202** [comment] 2020-10-08 14:17
its gone up to
- Total: 4.07 GB
- Foreground: 242 MB
- Background 3.84 GB

**Comment by dshokouhi** [comment] 2020-10-08 14:22
So you either still have a live camera config, or you kept a camera open and put the app in the background. If you open a camera make sure to close the pop-up. Check the other issue for all that's been discussed on this topic of high data usage.

**Comment by bram2202** [comment] 2020-10-08 14:25
i have commented out all camera related line, restarted HA.
and even restarted my phone to be sure.
I will check the other issue.
