### ISSUE TITLE
Missing state_class values for several device sensors

### ISSUE THREAD

**Issue by DAVe3283** [home-assistant/android#3345] opened 2023-02-17 18:38 UTC
**Home Assistant Android app version(s):** 2023.1.1-full

**Android version(s):** 11

**Device model(s):** Sony XQ-BC62 (Xperia 1 III)

**Home Assistant version:** 2022.2.5

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

I enabled additional sensors for my phone, but when I did so, existing sensors started failing to generate statistics, showing the error `The state class '' of this entity is not supported.`.

This appears to be the same problem as #2439.

I find that if I enable different combinations of sensors, different (seemingly unrelated) sensors get their state_class back.
When I first enable a sensor, it shows `state_class: measurement` until it publishes the first value, at which point it may or may not lose the state_class.

After trying to get things working right again for far too long, I followed the [start fresh](https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app) steps, but as soon as I re-enabled more sensors the problem came back.

**Companion App Logs:**

```
--------- beginning of main
02-17 11:25:57.494  8911  8911 D SensorReceiver: Received intent: io.homeassistant.companion.android.UPDATE_SENSORS
02-17 11:25:57.496  8911 10440 D UrlRepository: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
02-17 11:25:57.496  8911 10440 D UrlRepository: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
02-17 11:25:57.646  8911  8951 D UrlRepository: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
02-17 11:25:57.691  8911 10440 D PressureSensor: Pressure sensor listener registered
02-17 11:25:57.715  8911 10440 D UrlRepository: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
02-17 11:25:57.778  8911  8911 D PressureSensor: Pressure sensor listener unregistered
02-17 11:25:58.087  8911  8911 D NextAlarm: Next alarm is scheduled by com.google.android.deskclock with trigger time 1676732400000
02-17 11:25:58.094  8911  8911 D SensorReceiver: Received intent: io.homeassistant.companion.android.UPDATE_SENSORS
02-17 11:25:58.095  8911 10440 D UrlRepository: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
02-17 11:25:58.095  8911 10440 D UrlRepository: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
02-17 11:25:58.243  8911  8951 D UrlRepository: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
02-17 11:25:58.276  8911 10440 D NextAlarm: Next alarm is scheduled by com.google.android.deskclock with trigger time 1676732400000
02-17 11:25:58.281  8911 10440 D UrlRepository: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
02-17 11:25:58.281  8911 10440 D UrlRepository: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
02-17 11:25:58.281  8911 10440 I chatty  : uid=10485(io.homeassistant.companion.android) DefaultDispatch identical 1 line
02-17 11:25:58.282  8911 10440 D UrlRepository: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
02-17 11:25:58.331  8911 10440 D PressureSensor: Pressure sensor listener registered
02-17 11:25:58.365  8911 10440 D UrlRepository: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
02-17 11:25:58.376  8911  8911 D PressureSensor: Pressure sensor listener unregistered
02-17 11:26:19.766  8911  8911 D LocBroadcastReceiver: Received location update.
02-17 11:26:19.769  8911  8911 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = false
02-17 11:26:19.769  8911  8911 D LocBroadcastReceiver: Last Location: 
02-17 11:26:19.769  8911  8911 D LocBroadcastReceiver: Coords:(43.censored, -116.censored)
02-17 11:26:19.769  8911  8911 D LocBroadcastReceiver: Accuracy: 19.383
02-17 11:26:19.769  8911  8911 D LocBroadcastReceiver: Bearing: 0.0
02-17 11:26:19.771  8911  8911 D UrlRepository: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
02-17 11:26:19.772  8911  8911 D LocBroadcastReceiver: Begin evaluating if location update should be skipped
02-17 11:26:19.773  8911  8911 D LocBroadcastReceiver: Received location that is 19 milliseconds old, 1676658379753 compared to 1676658379772 with source fused
02-17 11:26:19.773  8911  8911 D LocBroadcastReceiver: Duplicate location received, not sending to HA
02-17 11:26:50.957  8911  8911 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 1676658251704, currentMillis: 1676658410957)
02-17 11:27:19.782  8911  8911 D LocBroadcastReceiver: Received location update.
02-17 11:27:19.786  8911  8911 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = false
02-17 11:27:19.786  8911  8911 D LocBroadcastReceiver: Last Location: 
02-17 11:27:19.786  8911  8911 D LocBroadcastReceiver: Coords:(43.censored, -116.censored)
02-17 11:27:19.786  8911  8911 D LocBroadcastReceiver: Accuracy: 19.383
02-17 11:27:19.786  8911  8911 D LocBroadcastReceiver: Bearing: 0.0
02-17 11:27:19.787  8911  8911 D UrlRepository: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
02-17 11:27:19.787  8911  8911 D LocBroadcastReceiver: Begin evaluating if location update should be skipped
02-17 11:27:19.787  8911  8911 D LocBroadcastReceiver: Received location that is 22 milliseconds old, 1676658439765 compared to 1676658439787 with source fused
02-17 11:27:19.787  8911  8911 D LocBroadcastReceiver: Duplicate location received, not sending to HA
02-17 11:27:47.315  8911 10440 D LogcatReader: Read logcat for pid 8911
```

**Screenshot or video of problem:**
![image](https://user-images.githubusercontent.com/6894502/219753540-1021b19d-f8de-44c7-a3cf-da3c5c1d4dc2.png)

**Additional information:**

**Comment by dshokouhi** [comment] 2023-02-17 18:42
duplicate of https://github.com/home-assistant/core/issues/83716

I see you are on HA 2022.2, I would recommend updating to 2023.2 as there are additional fixes in there

**Closed by dshokouhi** 2023-02-17 18:42 UTC
Labels: bug

**Comment by DAVe3283** [comment] 2023-02-17 18:44
Sorry, I was on 2023.2.5, simply mistyped. Will monitor the other issue.
