### ISSUE TITLE
Entity ID is not saved into  buttons widget 

### ISSUE THREAD

**Issue by Philippe12** [home-assistant/android#3511] opened 2023-05-03 16:38 UTC
**Home Assistant Android app version(s):**

**Android version(s):**
13

**Device model(s):**
Pixel 6a

**Home Assistant version:**
2023.04.1

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
Entity ID is not saved into  buttons widget 

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by jpelgrom** [comment] 2023-05-03 16:42
How is this different from #3484? Your report doesn't include a lot of details.

**Comment by dshokouhi** [comment] 2023-05-03 17:42
Pretty sure its a duplicate of the above based on the title alone :)

**Comment by jpelgrom** [comment] 2023-05-13 10:11
Closing this as a bugfix for the other issue has been merged and there has been no response. If you're still experiencing issues with beta-9996 or newer, let us know!

**Closed by jpelgrom** 2023-05-13 10:11 UTC
Labels: bug, question
