### ISSUE TITLE
History page refreshing endlessly when entering an entity that does not exist

### ISSUE THREAD

**Issue by blottootto** [home-assistant/android#3314] opened 2023-02-07 21:15 UTC
**Home Assistant Android app version(s):**
2023.1
**Android version(s):**
Android 13
**Device model(s):**
SM-S901W (Samsung S22)
**Home Assistant version:**
2023.2.2
**Last working Home Assistant release (if known):**
Probably last version of 2022.
**Description of problem, include YAML if issue is related to notifications:**
In the Android app history tab I accidentally entered an entity that does not exist ("solar") and tried to request the history for it. Now when I navigate to the history tab it immediately tries to retrieve the history of the entity, but it does not exist. It result in the endless spinning loading circle (see screenshot).
I can't stop this by closing the app or navigating away from this history page. I'd probably have to wipe appdata/cache to fix this (guessing).

My best guess is that this is probably related to the new way the history tab info is "streamed". 

**Companion App Logs:**

[homeassistant_companion_log_1-7-2023_14-7-36.txt](https://github.com/home-assistant/android/files/10679450/homeassistant_companion_log_1-7-2023_14-7-36.txt)

**Screenshot or video of problem:**
![Screenshot_20230205_102701_Home Assistant](https://user-images.githubusercontent.com/38059907/217366561-a7d2ec53-873b-46f5-b45e-ed96d86bb7c1.jpg)

**Additional information:**
```Logger: homeassistant.components.recorder.util
Source: components/recorder/util.py:130
Integration: Recorder ([documentation](https://www.home-assistant.io/integrations/recorder), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+recorder%22))
First occurred: 5 February 2023 at 14:53:03 (11 occurrences)
Last logged: 14:06:52
Error executing query: Invalid entity ID solar

**Comment by dshokouhi** [comment] 2023-02-07 21:17
Do you see the same issue using chrome for android on the same device?

**Comment by blottootto** [comment] 2023-02-07 21:21
I can replicate it on any browser/phone/PC as long as the invalid entity is the only entity I'm searching for. If one valid entity is present it ignores the invalid one and presents a result.

**Comment by dshokouhi** [comment] 2023-02-07 21:23
Looks like a duplicate of https://github.com/home-assistant/frontend/issues/15386

**Closed** 2023-02-07 21:24 UTC
Labels: bug
