### ISSUE TITLE
Issue with power menu controls 

### ISSUE THREAD

**Issue by mf-social** [home-assistant/android#1153] opened 2020-11-06 19:16 UTC
**Home Assistant Android version:** latest out today 

**Android version:** R

**Phone model:** pixel 4

**Home Assistant version:** 117.4

**Last working Home Assistant release (if known):** NA

**Description of problem:** Trying add power menu controls, lots and lots of things are titled null. Can confirm everything in my homeassistant is named 😉 

**Screenshot of problem:**

![Screenshot_20201106-191230](https://user-images.githubusercontent.com/14824890/98405644-81b6ee80-2064-11eb-8241-69875f9fb943.png)

**Comment by dshokouhi** [comment] 2020-11-06 19:18
Fixed in #1151 and also duplicate of #1150 :)

**Closed by dshokouhi** 2020-11-06 19:18 UTC
Labels: bug
