### ISSUE TITLE
Add a widget for dedicated controlling and viewing accessories

### ISSUE THREAD

**Issue by S0ulf3re** [home-assistant/android#3884] opened 2023-09-21 19:46 UTC
**Is your feature request related to a problem? Please describe.**
Right now, on Android. The Home Assistant app doesn't have an easy way to view the state of and control your devices from the Home Screen. You either need to go onto the device controls of quick settings, or create dedicated service buttons for every single accessory you want to control. Which takes a lot of spaces on the home screen.

**Describe the solution you'd like**
An extra widget that is destined for controlling and scrolling through devices would be nice.

**Describe alternatives you've considered, if any**
Controlling devices from the home screen is definitely possible already with the existing service button widget, but that only lets you control it using a single service, you also have to then set an icon and worry about the font size and everything.

**Additional context**
My biggest idea for this widget is similar to the [new iOS 17 home widget](https://9to5mac.com/2023/06/12/ios-17-home-app-widgets/). Which lets you add up to 8 accessories, and control them all without opening the app.

**Comment by dshokouhi** [comment] 2023-09-21 19:49
Did you know you can control a single entity and view its state using the Entity State widget? This was added in a recent update to the app.

https://companion.home-assistant.io/docs/integrations/android-widgets#entity-state

**Comment by jpelgrom** [comment] 2023-09-21 21:04
Also possible duplicate of #1193 depending on what exactly is wanted

**Comment by dshokouhi** [comment] 2023-10-23 22:44
Closing due to lack of response from author

**Closed by dshokouhi** 2023-10-23 22:44 UTC
Labels: enhancement, question, widget
