### ISSUE TITLE
Adding power menu controls causes GPS to stay active

### ISSUE THREAD

**Issue by ingenium13** [home-assistant/android#1171] opened 2020-11-09 01:05 UTC
**Home Assistant Android version:** 3.0.1

**Android version:** 11

**Phone model:** Pixel 4 XL

**Home Assistant version:** 0.117.5

**Last working Home Assistant release (if known):** n/a, feature added in 3.0 and has had this issue since then

**Description of problem:** If power menu controls are added, then every time my phone is unlocked the GPS activates for 1+ minutes. It then will repeatedly come back on again while using the device. It's as though I had the Home Assistant app open and in the foreground the whole time (opening the app causes GPS to activate). If I remove all the Home Assistant power menu controls, then it reverts to the old behavior of only occasionally briefly triggering the GPS to get the device's location. I was using 2 lights and 1 scene as power menu controls

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2020-11-09 01:15
Duplicate of #1146 and this was actually fixed in #1160 the issue was that location was included as part of the sensor updates and that will now be an opt-in option.  Its currently available in the latest beta.  I think you were just noticing the power menu since thats when the screen turns on as that triggers the interactive sensor to update.

**Closed by dshokouhi** 2020-11-09 01:15 UTC
Labels: bug
