### ISSUE TITLE
next_alarm sensor is off by 1 hour.

### ISSUE THREAD

**Issue by stefanroelofs** [home-assistant/android#1449] opened 2021-03-23 11:02 UTC
**Home Assistant Android version:**
Latest version: 2021.3.1-full

**Android version:**
10 QKQ1.190825.002
MIUI Global 12.0.4

**Phone model:**
Xiaomi Mi 9T Pro Global Version

**Home Assistant version:**
Latest version: Home Assistant 2021.3.4

**Last working Home Assistant release (if known):**
/

**Description of problem:**
I use the Clock app (com.android.deskclock) to set an alarm.
Alarm is set for: 07:05
My time zone is GMT+1 (Amsterdam)

This is the info in the next_alam sensor:
state: 2021-03-24T**05**:05:0.000Z
local time: Wed Mar 24 **06**:05:00 GMT +01:00 2021
package: com.android.deskclock
time in milliseconds: 161656230000

So the time is off by 1 hour.
The time zone is set up correctly on my phone I think.
Anything I can do about this?

I have a colleague with the same phone model who has the exact same issue.

Thanks!

**Comment by dshokouhi** [comment] 2021-03-23 13:51
Duplicate of #1301 #1211 #1190 #1109

Basically to be expected with default xiaomi apps. Use Google clock app or sleep as Android. Certain apps are known to abuse the API and xiaomi is one of them. Samsung is another.

**Closed by dshokouhi** 2021-03-23 13:51 UTC
Labels: bug

**Comment by stefanroelofs** [comment] 2021-03-23 15:49
That's clear. 
Thanks so much for your response!

**Comment by patm80** [comment] 2021-12-13 12:44
Hey! Sorry to reopen this issue but I have exactly the same problem just not with a Xiaomi Phone. I have the Pixel 6 and am using the stock clock from Google.
Has anyone the same problem with a Pixel phone?

**Comment by dshokouhi** [comment] 2021-12-15 16:15
@patm80 if you have an issue create a new one instead of piggy backing off an old issue.  If you have any issues make sure to check `package` attribute and see what the offending app is as that might give a clue for you to fix.  You can also refer to the forums as we have several threads on troubleshooting or even pop in discord to ask.

**Comment by patm80** [comment] 2021-12-18 16:42
Hey @dshokouhi,
sorry you're right. I was able to get it to work now. The mistake was on my part in the understanding of the UTC timestamp.
Thanks anyways for your feedback!

Best, Patrick
