### ISSUE TITLE
Quick settings (tile) toggle service not work

### ISSUE THREAD

**Issue by Tux92** [home-assistant/android#3151] opened 2022-12-14 11:13 UTC
**Home Assistant Android version:**
2022.11.0-full

**Android version:** 
10

**Phone model:** 
OnePlus 5T

**Home Assistant version:** 
2022.12.3

**Last working Home Assistant release (if known):** 
I dont' know

**Description of problem:** 
I set a switch entity from sonoff add-on as quick setting (tile) so I think that click on tile toggle switch. But nothing happend, the state of sonoff entity doesn't change. Using simple button integration on lovelace I can toggle my sonoff device, so the add-on work and it seams to be a tile issue.

I try to create a script and connect Android tile to the script. It work only if I use turn on/off service, but no toggle service. But the problem is that with script i don't see entity status on tile.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
2022-12-14T10:40:06.764Z [INFO] HA emit call_service event: {"domain":"switch","service":"toggle","service_data":{"entity_id":["switch.10017c79fd"]}}
2022-12-14T10:40:06.974Z [WARN] Update device state to HA error, entityId: switch.10017c79fd, data: {"entity_id":"switch.10017c79fd","attributes":{"restored":false,"supported_features":0,"friendly_name":"Disattiva MarcoRotto"}}
```

**Screenshot of problem:**

**Additional information:**

**Comment by JugglerLKR** [comment] 2022-12-14 11:59
Similar issue:
https://community.home-assistant.io/t/android-13-device-controls-broken/502375
Home Assistant 2022.12.4
Supervisor 2022.11.2
Operating System 9.4 (local VM install)
Frontend 20221212.0
App beta-2982-956b26cc-full (latest available) (S22 Android 13 latest available)

Magic Home (flux_led) 0x41 device

video with problem https://i.imgur.com/y7RJ2Y6.mp4

Controls in Samsung Devices broken. Obvious things tried: updating HAOS and app, rebooting, clearing app cache, checking permissions. System logs are empty. Logcat logs show error.
As you can see, problem not with device itself, it works fine in app. Local wifi usage only.
`12-13 20:41:06.754 28864 28864 D ControlsProviderService: createPublisherFor mToken:android.os.BinderProxy@1689233, ControlIds:[light.controller_dimmable_033054]
12-13 20:41:06.754 28864 28864 D HaConProService: publisherFor [light.controller_dimmable_033054]
12-13 20:41:06.754 28864 28879 D HaConProService: request 100000
12-13 20:41:06.756 28864  3901 D UrlRepository: localUrl is: true, usesInternalSsid is: false, usesWifi is: true
12-13 20:41:06.756 28864  3901 D UrlRepository: Using external URL
12-13 20:41:06.757 28864  3900 D UrlRepository: localUrl is: true, usesInternalSsid is: false, usesWifi is: true
12-13 20:41:06.757 28864  3900 D UrlRepository: Using external URL
12-13 20:41:06.758 28864  3281 D TrafficStats: tagSocket(76) with statsTag=0xffffffff, statsUid=-1
12-13 20:41:06.758 28864  3901 D UrlRepository: localUrl is: true, usesInternalSsid is: false, usesWifi is: true
12-13 20:41:06.758 28864  3901 D UrlRepository: Using external URL
12-13 20:41:06.780 28864  3281 D WebSocketRepository: Websocket: onOpen
12-13 20:41:06.780 28864  3281 D WebSocketRepository: Websocket: onMessage (text)
12-13 20:41:06.782 28864  3281 D WebSocketRepository: Message number null received
12-13 20:41:06.783 28864  3901 D WebSocketRepository: Auth Requested
12-13 20:41:06.791 28864  3281 D WebSocketRepository: Websocket: onMessage (text)
12-13 20:41:06.792 28864  3281 D WebSocketRepository: Message number null received
12-13 20:41:06.793 28864  3901 D WebSocketRepository: Sending message 83: {type=supported_features, id=83, features={coalesce_messages=1}}
12-13 20:41:06.793 28864  3901 D WebSocketRepository: Sending message 84: {type=config/area_registry/list, id=84}
12-13 20:41:06.793 28864  3901 D WebSocketRepository: Message number 84 sent
12-13 20:41:06.794 28864  3946 D WebSocketRepository: Sending message 85: {type=config/device_registry/list, id=85}
12-13 20:41:06.794 28864  3946 D WebSocketRepository: Message number 85 sent
12-13 20:41:06.794 28864  3901 D WebSocketRepository: Sending message 86: {type=config/entity_registry/list, id=86}
12-13 20:41:06.794 28864  3901 D WebSocketRepository: Message number 86 sent
12-13 20:41:06.797 28864  3281 D WebSocketRepository: Websocket: onMessage (text)
12-13 20:41:06.799 28864  3281 D WebSocketRepository: Message number 83 received
12-13 20:41:06.801 28864  3281 D WebSocketRepository: Websocket: onMessage (text)
12-13 20:41:06.805 28864  3281 D WebSocketRepository: Message number 84 received
12-13 20:41:06.806 28864  3281 D WebSocketRepository: Message number 85 received
12-13 20:41:06.806 28864  3281 D WebSocketRepository: Message number 86 received
12-13 20:41:06.808 28864  3946 D UrlRepository: localUrl is: true, usesInternalSsid is: false, usesWifi is: true
12-13 20:41:06.808 28864  3946 D WebSocketRepository: Sending message 87: {type=subscribe_events, event_type=device_registry_updated, id=87}
12-13 20:41:06.809 28864  3946 D WebSocketRepository: Message number 87 sent
12-13 20:41:06.813 28864  3281 D WebSocketRepository: Websocket: onMessage (text)
12-13 20:41:06.814 28864  3281 D WebSocketRepository: Message number 87 received
12-13 20:41:06.816 28864  3479 D WebSocketRepository: Sending message 88: {type=subscribe_events, event_type=area_registry_updated, id=88}
12-13 20:41:06.816 28864  3479 D WebSocketRepository: Message number 88 sent
12-13 20:41:06.823 28864  3281 D WebSocketRepository: Websocket: onMessage (text)
12-13 20:41:06.824 28864  3281 D WebSocketRepository: Message number 88 received
12-13 20:41:06.825 28864  3898 D WebSocketRepository: Sending message 89: {type=subscribe_events, event_type=entity_registry_updated, id=89}
12-13 20:41:06.825 28864  3898 D WebSocketRepository: Message number 89 sent
12-13 20:41:06.830 28864  3281 D WebSocketRepository: Websocket: onMessage (text)
12-13 20:41:06.831 28864  3281 D WebSocketRepository: Message number 89 received
12-13 20:41:06.833 28864  3479 D WebSocketRepository: Sending message 90: {type=subscribe_entities, entity_ids=[light.controller_dimmable_033054], id=90}
12-13 20:41:06.834 28864  3479 D WebSocketRepository: Message number 90 sent
12-13 20:41:06.839 28864  3281 D WebSocketRepository: Websocket: onMessage (text)
12-13 20:41:06.841 28864  3281 D WebSocketRepository: Message number 90 received
12-13 20:41:06.841 28864  3281 D WebSocketRepository: Message number 90 received
12-13 20:41:06.842 28864  3897 D HaConProService: Sending 1 entities to subscriber
12-13 20:41:08.162 28864 28864 D ControlsProviderService: performControlAction mToken:android.os.BinderProxy@1689233, ControlId:light.controller_dimmable_033054
12-13 20:41:08.162 28864 28864 D HaConProService: Control: light.controller_dimmable_033054, action: android.service.controls.actions.BooleanAction@380781e
12-13 20:41:08.165 28864  3897 D UrlRepository: localUrl is: true, usesInternalSsid is: false, usesWifi is: true
12-13 20:41:08.190 28864  3897 E HaConProService: Unable to control or get entity information
12-13 20:41:08.190 28864  3897 E HaConProService: io.homeassistant.companion.android.common.data.integration.IntegrationException: Error calling integration request call_service
12-13 20:41:08.190 28864  3897 E HaConProService:       at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.callService(IntegrationRepositoryImpl.kt:253)
12-13 20:41:08.190 28864  3897 E HaConProService:       at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$callService$1.invokeSuspend(Unknown Source:15)
12-13 20:41:08.190 28864  3897 E HaConProService:       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-13 20:41:08.190 28864  3897 E HaConProService:       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
12-13 20:41:08.190 28864  3897 E HaConProService:       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
12-13 20:41:08.190 28864  3897 E HaConProService:       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
12-13 20:41:08.190 28864  3897 E HaConProService:       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
12-13 20:41:08.190 28864  3897 E HaConProService:       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
12-13 20:41:08.190 28864  3897 E HaConProService:       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
12-13 20:41:08.190 28864  3897 E HaConProService:       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)`

**Comment by Tux92** [comment] 2022-12-14 12:45
> Where are these logs from? Could you set up the tile with the switch again, and get the logs from the app's settings?
> 
> The app will use the service `switch.toggle`. Does this work correctly is you use it for example in the developer tools?
> 
> Buttons/scripts don't have an on/off state which is why you don't see the switch state when using those with a tile.

The logs I post before are from sonoff add-on.
Tile 2 is set up with switch, this is the logs from Settings > Companion App > Show and Share Logs:

```
12-14 13:36:44.058  9652  9652 I Surface : opservice is null false
12-14 13:36:52.880  9652 10986 D ViewRootImpl[SettingsActivity]: windowFocusChanged hasFocus=false inTouchMode=true
12-14 13:36:52.880  9652  9652 I Surface : opservice is null false
12-14 13:36:53.860  9652  9652 D TileExtensions: Tile: tile_1 is in view
12-14 13:36:53.860  9652  9652 D TileExtensions: Attempting to set tile data for tile ID: tile_1
12-14 13:36:53.861  9652  9652 D TileExtensions: Tile: tile_2 is in view
12-14 13:36:53.861  9652  9652 D TileExtensions: Attempting to set tile data for tile ID: tile_2
12-14 13:36:53.864  9652 12029 D UrlRepository: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
12-14 13:36:53.864  9652 12029 D UrlRepository: Using external URL
12-14 13:36:53.865  9652 12029 D UrlRepository: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
12-14 13:36:53.865  9652 12029 D UrlRepository: Using external URL
12-14 13:36:53.865  9652 10320 D UrlRepository: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
12-14 13:36:53.865  9652 10320 D UrlRepository: Using external URL
12-14 13:36:53.865  9652 10320 D UrlRepository: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
12-14 13:36:53.865  9652 10320 D UrlRepository: Using external URL
12-14 13:36:53.952  9652  9652 D TileExtensions: Tile data set for tile ID: tile_1
12-14 13:36:54.175  9652  9652 D TileExtensions: Tile data set for tile ID: tile_2
12-14 13:36:55.245  9652  9652 D TileExtensions: Attempting to set tile data for tile ID: tile_2
12-14 13:36:55.249  9652 10320 D UrlRepository: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
12-14 13:36:55.250  9652 10320 D UrlRepository: Using external URL
12-14 13:36:55.253  9652 10320 D UrlRepository: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
12-14 13:36:55.253  9652 10320 D UrlRepository: Using external URL
12-14 13:36:55.345  9652  9652 D TileExtensions: Tile data set for tile ID: tile_2
12-14 13:36:55.349  9652  9652 D TileExtensions: Click detected for tile ID: tile_2
12-14 13:36:55.350  9652  9652 D TileExtensions: Attempting to set tile data for tile ID: tile_2
12-14 13:36:55.353  9652 12029 D UrlRepository: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
12-14 13:36:55.353  9652 12029 D UrlRepository: Using external URL
12-14 13:36:55.354  9652 12029 D UrlRepository: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
12-14 13:36:55.354  9652 12029 D UrlRepository: Using external URL
12-14 13:36:55.419  9652  9652 D TileExtensions: Tile data set for tile ID: tile_2
12-14 13:36:55.424  9652 10320 D UrlRepository: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
12-14 13:36:55.496  9652 10320 D TileExtensions: Service call sent for tile ID: tile_2
12-14 13:36:57.019  9652 10986 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@a93343b[SettingsActivity]
12-14 13:36:57.021  9652 10986 D ViewRootImpl[SettingsActivity]: windowFocusChanged hasFocus=true inTouchMode=true
12-14 13:36:57.022  9652  9652 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 1671021336476, currentMillis: 1671021417022)
12-14 13:36:57.834  9652 10320 D LogcatReader: Read logcat for pid 9652
```
The toggle service doesn't work correctly also on Developer tools, this is Home assistant core log:

```
Logger: homeassistant.helpers.service
Source: helpers/service.py:637
First occurred: 12:53:14 (7 occurrences)
Last logged: 13:41:28

Unable to find referenced entities switch.10017c79fd or it is/they are currently not available
```

But default button integration with default action will work well. I wonder if that control use turn_on/off service instead of toggle.

**Comment by dshokouhi** [comment] 2022-12-14 14:43
> The toggle service doesn't work correctly also on Developer tools, this is Home assistant core log:
> 
> ```
> Logger: homeassistant.helpers.service
> Source: helpers/service.py:637
> First occurred: 12:53:14 (7 occurrences)
> Last logged: 13:41:28
> 
> Unable to find referenced entities switch.10017c79fd or it is/they are currently not available
> ```

I believe we have seen this before. Is this a custom integration? You may need to take this issue up with them as HA core should default to the proper service call based on if the `switch` is considered `on`.

https://developers.home-assistant.io/docs/core/entity/switch#toggle

**Comment by Tux92** [comment] 2022-12-14 15:07
> Is this a custom integration? You may need to take this issue up with them as HA core should default to the proper service call based on if the `switch` is considered `on`.
> 
> https://developers.home-assistant.io/docs/core/entity/switch#toggle

No, this is the official addon of ewelink sonoff (https://ewelink.cc/ewelink-works-with-home-assistant/)

So you think the problem is only on the ewelink addon that  do not use proper service?

**Comment by dshokouhi** [comment] 2022-12-14 15:27
Based on the error yes, and while it may be an official add on by the company its not a core integration so still custom.

**Comment by Tux92** [comment] 2022-12-14 16:35
For now I found this big workaround.
I configure an input boolean helper and toggle with quick settings this helper.
Then I set up 2 automation:
1. The first when input helper status change, turn on or off sonoff device
2. The second when sonoff status change and input helper isn't synced update input boolen helper

Luckily I use only 2 quick settings. ;)

**Comment by dshokouhi** [comment] 2022-12-14 18:22
Closing this issue as a duplicate of https://github.com/home-assistant/android/issues/1954 which looks to be the same issue as its the same add-on with identical error.

**Closed by dshokouhi** 2022-12-14 18:22 UTC
Labels: bug, question
