### ISSUE TITLE
Implement Zoom feature from iOS into Android Companion app

### ISSUE THREAD

**Issue by kimme1024** [home-assistant/android#1481] opened 2021-04-05 12:52 UTC
**Is your feature request related to a problem? Please describe.**
I'm having 2 tablets that I use as a HA-dashboard with the Android Companion app. Both have the exact same screen resolution.
However 1 tablet resizes my dashboard (in panel mode) perfectly so everything looks clean. The other tablet doesn't resize the dashboard so the bottom part is cut. Therefore I have to scroll down to view the rest of my content.

**Describe the solution you'd like**
I guess this issue is caused by the amount of different display sizes used in Android devices but the main feature of panel mode is to automatically fit the cards to the display and this doesn't happen. In iOS there's feature in settings use preset zoom percentages. This might not solve the issue itself but it would give the user a bit more room to fit the content on the screen.

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment] 2021-04-05 13:11
Duplicate of #1117

**Closed by dshokouhi** 2021-04-05 13:11 UTC
Labels: enhancement

**Comment by kimme1024** [comment] 2021-04-05 13:28
No it isn't a duplicate. I'm not talking about seperate card zooms like a videostream. I'm talking about the complete dashboard view. I temporarily solved it by changing the smallest width in android developer options but this makes the tablets menus unusable and slows down the tablet's performance a lot.

**Comment by dshokouhi** [comment] 2021-04-05 14:00
> No it isn't a duplicate. I'm not talking about seperate card zooms like a videostream. I'm talking about the complete dashboard view. I temporarily solved it by changing the smallest width in android developer options but this makes the tablets menus unusable and slows down the tablet's performance a lot.

Did you read the linked the issues in the duplicate to see it is indeed zooming the entire screen for the request?
