### ISSUE TITLE
App crashes when pressing add integration buttton

### ISSUE THREAD

**Issue by drlauridsen** [home-assistant/android#4793] opened 2024-11-08 12:41 UTC
**Home Assistant Android app version(s):**
2024.10.3-full
**Android version(s):**
14
**Device model(s):**
SAMSUNG S24
**Home Assistant version:**
2024.11.0
**Last working Home Assistant release (if known):**
2024.10.4
**Description of problem, include YAML if issue is related to notifications:**
As soon as I press +Integration button, app closes - and this is every time. So not able to add integration with app.
![Screenshot_20241108_133211_Home Assistant](https://github.com/user-attachments/assets/e3d52e88-a62a-45ce-a204-6bb754116c66)

Cleared cache multiple times - does not help.
No errors, app just closes.
Did not change anything in app, it started happening after updating core to .11

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2024-11-08 15:31
duplicate of #4782 and #4761

this is fixed in the apps beta release

**Closed by dshokouhi** 2024-11-08 15:31 UTC
Labels: bug
