### ISSUE TITLE
When activating a new sensor the initial sensor state is never set in HA

### ISSUE THREAD

**Issue by frimtec** [home-assistant/android#3584] opened 2023-06-14 10:00 UTC
**Home Assistant Android app version(s):**
2023.6.0-full

**Android version(s):**
13

**Device model(s):**
Pixel 7

**Home Assistant version:**
2023.06.1

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
When activating a sensor in the companion app for the first time, the current sensor value is not set on the sensors entity in HA and the state value is "unknown". 
As soon as the sensor in the companion app  changes his value the next time, the entity in HA will be updated to the correct value the first time.
This is not so nice for sensors which do not change very often, as the HA entity keeps "unknown" until the sensor changes (can be days or even longer).
Would it be possible to always send the sensor state to HA when a sensor is activated in the companion app?

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![activated-sensor](https://github.com/home-assistant/android/assets/3511114/f9b0daa3-0513-4cfe-94e6-d7fc8cbeaf20)
![State-unknown-even-after-1h](https://github.com/home-assistant/android/assets/3511114/4b89c7e0-2bad-49b3-a93d-40298c4171b4)

**Additional information:**

**Comment by dshokouhi** [comment] 2023-06-14 13:49
Duplicate of https://github.com/home-assistant/core/issues/79837

**Closed** 2023-06-14 13:49 UTC
Labels: bug
