### ISSUE TITLE
Wear OS Shortcuts Tile - Update Icons

### ISSUE THREAD

**Issue by maxrhys** [home-assistant/android#3931] opened 2023-10-12 07:34 UTC
**Is your feature request related to a problem? Please describe.**

Wear OS shortcut tile does not update entity icon when it changes. No visual feedback if the state changed.

**Describe the solution you'd like**

Wear OS Shortcuts tile should update the entity icon to reflect icons that change based on states.

**Describe alternatives you've considered, if any**

Alternatively for switches illuminate the background of the icon when state is on.

**Additional context**

**Comment by jpelgrom** [comment] 2023-10-12 10:28
Duplicate of #2045. System limitations on updating tiles make this tricky if not impossible, although there have recently been updates that we might be able to (ab)use.

**Closed by jpelgrom** 2023-10-12 10:28 UTC
Labels: enhancement
