### ISSUE TITLE
App freezes after using device back button 

### ISSUE THREAD

**Issue by Corneloues** [home-assistant/android#1294] opened 2021-01-13 22:24 UTC
**Home Assistant Android version:**
3.0.2-full

**Android version:**
11

**Phone model:**
Galaxy S20 Ultra 5G

**Home Assistant version:**
2020.12.2

**Last working Home Assistant release (if known):**

**Description of problem:**
The app freezes/becomes unresponsive if the device back button is used instead of the HA navigation controls. 

The only option is to close the app by swiping it away from the list of applications after pressing the Overview button. 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2021-01-13 22:26
Please try first starting fresh to see if the issue is resolved:

https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by RouNNdeL** [comment] 2021-01-16 15:48
@dshokouhi I'm having the same exact issue on Samsung Galaxy S10+. I reset the app, as per the document you linked.
- Android version: 10 - One UI 2.5
- HA App version: 3.0.2-full
- HA Core version: 2021.1.3

**Comment by dshokouhi** [comment] 2021-01-16 17:09
Do you guys see the same issues in chrome for android?  Is Android System Webview up to date?

**Comment by RouNNdeL** [comment] 2021-01-16 17:15
I actually managed to replicate the issue 100% consistently. In my case it's not related to the back button, but the app losing focus, by either going home or to the recent's page. The bug is only present when fingerprint lock is enabled. To answer the question, chrome works fine.

**Comment by dshokouhi** [comment] 2021-01-16 17:18
Sounds like a duplicate of: https://github.com/home-assistant/android/issues/1290

Clearing data should fix the issue.  We are not able to reproduce the error so we would need to see an error log with an actual error to fix the issue.

**Comment by RouNNdeL** [comment] 2021-01-16 17:22
Clearing data only fixes the issue in the sense that it disabled the fingerprint login. Enabling it back, it still does not work, any way I could get the logs for you?

**Comment by dshokouhi** [comment] 2021-01-16 17:23
yea we need the logs from when the app crashes at that point.  Get us the full logs in addition to the search mentioned during the time period.

**Comment by RouNNdeL** [comment] 2021-01-16 17:44
I've filtered by the error tag, an those two log lines appear every time the app loses focus

```
01-16 18:41:23.830   568  1786 E BufferQueueProducer: [io.homeassistant.companion.android/io.homeassistant.companion.android.webview.WebViewActivity$_32419#0] disconnect: not connected (req=1)
01-16 18:41:23.863  1038  3896 E WindowManager: win=Window{4452d36 u0 io.homeassistant.companion.android/io.homeassistant.companion.android.webview.WebViewActivity} destroySurfaces: appStopped=true win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=8 caller=com.android.server.wm.AppWindowToken.destroySurfaces:1248 com.android.server.wm.AppWindowToken.destroySurfaces:1229 com.android.server.wm.AppWindowToken.notifyAppStopped:1284 com.android.server.wm.ActivityRecord.activityStoppedLocked:2776 com.android.server.wm.ActivityTaskManagerService.activityStopped:2513 android.app.IActivityTaskManager$Stub.onTransact:2280 android.os.Binder.execTransactInternal:1056 
```

Full log: https://pastebin.com/MSrPaHhi

**Comment by gregsheremeta** [comment] 2021-01-18 12:00
I have multiple Fire HD 10 tablets that are wall mounted and very rarely interacted with, and they've started freezing in the last week or so. The tablet is responsive, but the HA dashboard just stops updating. I wonder if some background app gets focus for a second.

**Comment by dshokouhi** [comment] 2021-01-18 17:21
> I've filtered by the error tag, an those two log lines appear every time the app loses focus
> 
> ```
> 01-16 18:41:23.830   568  1786 E BufferQueueProducer: [io.homeassistant.companion.android/io.homeassistant.companion.android.webview.WebViewActivity$_32419#0] disconnect: not connected (req=1)
> 01-16 18:41:23.863  1038  3896 E WindowManager: win=Window{4452d36 u0 io.homeassistant.companion.android/io.homeassistant.companion.android.webview.WebViewActivity} destroySurfaces: appStopped=true win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=8 caller=com.android.server.wm.AppWindowToken.destroySurfaces:1248 com.android.server.wm.AppWindowToken.destroySurfaces:1229 com.android.server.wm.AppWindowToken.notifyAppStopped:1284 com.android.server.wm.ActivityRecord.activityStoppedLocked:2776 com.android.server.wm.ActivityTaskManagerService.activityStopped:2513 android.app.IActivityTaskManager$Stub.onTransact:2280 android.os.Binder.execTransactInternal:1056 
> ```
> 
> Full log: https://pastebin.com/MSrPaHhi

I don't see a crash but it also appears you still had the filter enabled which hides certain errors.  We need to see everything.



> I have multiple Fire HD 10 tablets that are wall mounted and very rarely interacted with, and they've started freezing in the last week or so. The tablet is responsive, but the HA dashboard just stops updating. I wonder if some background app gets focus for a second.

This sounds more like a frontend issue than an app issue.

**Comment by RouNNdeL** [comment] 2021-01-18 17:35
>  I don't see a crash but it also appears you still had the filter enabled which hides certain errors. We need to see everything.

The full log is just straight up `adb logcat | grep io.homeassistant > file.log`. How else do you want my to filter it? Btw, the apps does not crash in the android sense, it just freezes and becomes unresponsive.

**Comment by dshokouhi** [comment] 2021-01-18 18:05
`grep` is a filter and if the crash/error happens outside the app like in the systems own biometrics we may not see the error.  Without being able to reproduce or a error log its going to be tough to fix.  You said you tried to clear data already, have you tried a full uninstall and reinstall of the app? The other user said the biometric issue went away after clearing data so its possible we just need to fully clear the bad data

**Comment by RouNNdeL** [comment] 2021-01-18 18:33
Cleared data, uninstalled, cleared data again (my server address recovered from a cloud backup apparently). The issue still exists, when the session timeout is >0, if it's 0, the biometrics prompt will appear everytime and it works after unlocking. Can you provide an e-mail or some place where I can send full logs? I do not exactly feel confident publishing the full logcat publicly online.

**Comment by dshokouhi** [comment] 2021-01-24 04:58
> The issue still exists, when the session timeout is >0

Can you provide the exact steps you take to reproduce this issue? This tiny bit of information is actually pretty helpful. 

If we can reproduce then we may not need the logs.  You can also upload the logs to google drive and grant access to those who request access which would be coming from myself or another developer when we get a chance to look.

**Comment by RouNNdeL** [comment] 2021-01-24 09:35
Sure. From a fresh install (I also tried to install in the Samsung's 'sandbox' - Security Folder, same issue):
- Login to the HA instance (external url, with 2fa)
- Open App Configuration
- Enable *Lock App* with 0 session time out
- Use the home button to 'quit' the app
- Open the app again, confirm the biometrics, the app does work
- Change the session timeout to something > 0, ex. 60
- Again quit with the home button
- Open the app, either from recent's or from the launcher
- The app is frozen, and needs to be removed from recent's to work again

**Comment by dshokouhi** [comment] 2021-01-25 20:41
Thanks looks like I am able to reproduce this with the steps provided.  Does the app become functional again once the time out is reached?

**Comment by RouNNdeL** [comment] 2021-01-26 23:36
Yes, as long as I'm out of the app for the full duration of timeout and then comeback. After solving the biometric's challange the app is fully functional again.

**Closed** 2021-01-27 14:53 UTC
Labels: bug, settings
