### ISSUE TITLE
NFC tag not always accepted

### ISSUE THREAD

**Issue by antoweb** [home-assistant/android#1251] opened 2020-12-15 18:04 UTC
## The problem

the nfc tag is not always accepted.  I need to open the home assistant app. 

## Environment

- Home Assistant Core release with the issue: 
- Last working Home Assistant Core release (if known): 
- Operating environment (OS/Container/Supervised/Core): HASSOS/hassio
- Integration causing this issue: 
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by frenck** [comment] 2020-12-22 13:50
Transferring this issue into the android issues tracker, as I suspect to be an issue on that end.

**Comment by dshokouhi** [comment] 2020-12-22 15:30
@antoweb can you confirm the app has access to run in the background? We will also need a screenshot of the error along with the app version.

**Comment by antoweb** [comment] 2020-12-22 19:42
Yes Home Assistant App is allowed in backgorund zero restriction (smarthpone xiaomi mi 9 lite) and no battery save. The screenshot is not easy to save because the error message is very fast

**Comment by dshokouhi** [comment] 2020-12-22 19:51
Our toast error messages are designed to show up as long as the system allows which is actually about 5-10 seconds.  Can you get us the logs from the device?

https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs

there should be an error along with the toast

**Comment by antoweb** [comment] 2020-12-25 17:36
Attaché Is the errore screenshot, unfortuntely i cant sensi logcat because Is not configurare the permissione with adb command. Maybe next tima
![IMG_20201225_183348](https://user-images.githubusercontent.com/32364871/103139793-27d7ba00-46e0-11eb-91c9-de333afb0c31.jpg)

**Comment by dshokouhi** [comment] 2020-12-26 22:40
We would need to see the error log as we have added debug statements to see what the cause of this error is.  So far it seems either the android system returns null for the tag data or the app was unable to send the notification to HA. The logs will tell us which of the 2 possible outcomes it can be.

**Comment by antoweb** [comment] 2020-12-30 10:57
Just few minutes ago received error. attached is log from logcat and the screenshot of error
![photo_2020-12-30_11-52-06](https://user-images.githubusercontent.com/32364871/103347050-1f8fce00-4a96-11eb-9b56-488be5b91200.jpg)
[logcat_12-30-2020_11-31-23.txt](https://github.com/home-assistant/android/files/5753952/logcat_12-30-2020_11-31-23.txt)

**Comment by dshokouhi** [comment] 2020-12-30 17:51
Looking at the logs it seems that this error happens before the service call gets sent to HA as I do not see the following log line:

https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/nfc/TagReaderActivity.kt#L79

as the error we see is: 

https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/nfc/TagReaderActivity.kt#L53

So for some reason it seems that this call fails sometimes: 

https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/util/UrlHandler.kt#L23-L30

Why it fails I am not sure yet.

**Comment by antoweb** [comment] 2020-12-30 20:37
I am attaching this log as the automation this time did not work, while the previous log referred to an error but the automation had worked
[logcat_12-30-2020_20-26-44.txt](https://github.com/home-assistant/android/files/5755641/logcat_12-30-2020_20-26-44.txt)

**Comment by dshokouhi** [comment] 2020-12-30 20:49
Looks like sometimes it gets the TAG ID but seems like it could be failing sending it over to HA as well.  I dont see the log message for a successful call to HA.

**Comment by dshokouhi** [comment] 2020-12-30 20:57
yes it is failing to send the data successfully to HA.  Does this happen on or off wifi? Anything else you can tell us about when its successful or not?  I am unable to reproduce this so I wonder if this is a manufacturer issue.  One thing you can do also is to check dontkillmyapp.com and see if there something else you can do to keep the app running in the background.  That could very well be the issue too that the system kills the app before it can make the call successfully in the background.  Do things like sensors and location update all the time?

**Comment by antoweb** [comment] 2020-12-30 20:59
Hello, it was outside wifi, i call tag in 4g mobile connection. Sensors and location is uodated regularly because i have setup in my xiaomi no power saving and no restriction for Homa Assistant companion and autostart on, also all permission are granted

**Comment by antoweb** [comment] 2020-12-30 21:09
All setting suggested from dontkillmyapp.com was done in mi xiaomi

**Comment by dshokouhi** [comment] 2020-12-31 19:39
And you don't see any HA errors as the time of this error?  What we know is that the call to HA is failing for whatever reason.

**Comment by antoweb** [comment] 2020-12-31 19:47
Sorry bit i use by diano outside home and never checked RealTime HA log

**Comment by dshokouhi** [comment] 2021-01-02 05:31
Logs are really important especially when trying to debug a connection issue.

**Comment by antoweb** [comment] 2021-01-02 07:40
Yes i know, in fact i see Always logs when there Is a problema, but in this case Is very difficult because the errore appears when i am outside home

**Comment by antoweb** [comment] 2021-01-02 11:58
Attached are logact log from home assistant app and Home Assistant log portion. The errore was received near time 10:32 this morning
[new 1.txt](https://github.com/home-assistant/android/files/5760200/new.1.txt)
[logcat_01-02-2021_10-32-29.txt](https://github.com/home-assistant/android/files/5760202/logcat_01-02-2021_10-32-29.txt)

**Comment by dshokouhi** [comment] 2021-01-02 23:44
So in this log just before the app fails to send the event data to HA we can see the device is attempting to stop the app.

```
[01-02 10:32:23.249 1581:1699 W/UsageStatsService]
Failed to note usage stop
java.lang.IllegalArgumentException: Unable to stop usage for io.homeassistant.companion.android, not in use
	at com.android.server.usage.AppTimeLimitController.noteUsageStop(AppTimeLimitController.java:955)
	at com.android.server.usage.UsageStatsService.reportEvent(UsageStatsService.java:558)
	at com.android.server.usage.UsageStatsService$H.handleMessage(UsageStatsService.java:879)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

Which is then followed by some type of denial (not certain if this is related):

```
[01-02 10:32:23.258 545:545 E/SELinux]
avc:  denied  { find } for interface=vendor.qti.hardware.servicetracker::IServicetracker sid=u:r:system_server:s0 pid=1581 scontext=u:r:system_server:s0 tcontext=u:object_r:default_android_hwservice:s0 tclass=hwservice_manager permissive=0
```

So this does appear to be the system killing the app before its able to make the call to HA which is why it fails just after this error with

```
[01-02 10:32:23.259 6245:6245 E/TagReaderActivity]
Unable to handle url (nfc): https://www.home-assistant.io/tag/d1afa924-520b-48c1-88ef-2bc4ad1eda52
io.homeassistant.companion.android.common.data.integration.IntegrationException
	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.scanTag(IntegrationRepositoryImpl.kt:233)
	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$scanTag$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:55)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by tetienne** [comment] 2021-03-08 12:59
FYI, I got the same issue with my OnePlus5 on Android 10.

**Comment by romanerasmus** [comment] 2021-04-01 16:52
Same issue with xiaomi MI, exactly same errors when app is closed.

**Comment by dshokouhi** [comment] 2021-04-01 16:58
So we just had a very large logging improvement merged in to the latest beta.  We came to find out some of the logging exceptions were not there. Can someone here please load the latest beta (641) from github releases tab and get us the logs when this error appears? The error I pointed out up above should now have additional information pertaining to the actual cause of the error.

There is now a new Log viewer inside App Configuration so you can view the logs and grab the text without needing an additional app or anything :) Thanks a lot to @chriss158 for this feature!

**Comment by dshokouhi** [comment] 2021-08-03 14:12
Closing due to lack of response

**Closed by dshokouhi** 2021-08-03 14:12 UTC
Labels: bug
