### ISSUE TITLE
Unable to Register Application on Android

### ISSUE THREAD

**Issue by ParadoxRus** [home-assistant/android#558] opened 2020-04-17 21:57 UTC
Home Assistant Android version:
1.8.0-144

Android version:
Android 10 QP1A.190711.020

Phone model:
Redmi Note 8 Pro

Home Assistant version:
Home Assistant Core 0.107.7
installed on dietPi 6.28.0 on RasberryPi 4

Description of problem:
I've got the same problem as a closed "Unable to Register Application #417"
I am unable to access Home Assistant by Android smartphone, it gets stuck in the screen with the "Unable to Register Application" message.
Plz check to ensure you have the mobile_app integration enabled on your home assistant instance.

Things I have try:
    Restarting HA.
    Reinstalling the app
    Grant all permissions to the app
    Disable battery optimization for the app.
    Enable GPS
    write mobile_app: directly in configuration.yaml vs default_config:

# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:
automation:
cloud:
config:
frontend:
history:
logbook:
map:
mobile_app:
person:
ssdp:
sun:
system_health:
updater:
zeroconf:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
# base_url: example.duckdns.org:8123

# Text to speech
tts:
- platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

discovery:

Additional information:
I have the stock MIUI version with Google Services installed the same problem I also have on Samsung A5. In HA logs I do not see anything.
I connect in my local network with the url like http://serverip:8123 (in my other device this works and in phone browser too)

**Comment by dshokouhi** [comment] 2020-04-17 22:54
@ParadoxRus #417 was closed because it had to do with HA integration.  It required users to clear data in the app.  Delete the HA integration and restart HA.  Then when you login it would work.  

Did you install the app via google play store?

Does your other device have MIUI on it or a stock ROM?

**Comment by dshokouhi** [comment] 2020-04-17 22:56
Also this is a possible duplicate of #446

**Comment by ParadoxRus** [comment] 2020-04-18 14:00
> 
> 
> @ParadoxRus #417 was closed because it had to do with HA integration. It required users to clear data in the app. Delete the HA integration and restart HA. Then when you login it would work.
> 
> Did you install the app via google play store?
> 
> Does your other device have MIUI on it or a stock ROM?

You can see above
_Things I have try:
Restarting HA.
Reinstalling the app
Grant all permissions to the app
Disable battery optimization for the app.
Enable GPS_

What does it mean: _ Delete the HA integration and restart HA. _ 
How should I do it?

app installed via Google Play
another device that I have - it's Samsung with stock ROM

**Comment by ParadoxRus** [comment] 2020-04-18 14:01
> 
> 
> Also this is a possible duplicate of #446

No, it's not the same bug as  #446

**Comment by ParadoxRus** [comment] 2020-04-19 11:24
Hot news:
I installed another ROM on MiNote8Pro - Indonesia (was Global):
9 PRP1.180610.011 (MIUI 11.0.2.0(PGGIDXM)) and problem was resolved.
But Samsung A8 with stock ROM still doesn't work :(

**Comment by heystge** [comment] 2020-04-27 16:37
Same issue here.....

On my wifes Iphone it is functioning very well, but also on the Samsung S8 of my daughter.

My Samsung S10+still gives the same error message.......

very strange..... I've removed all the entries related to the S10+ in the Known_devices file, but no difference. it's somewhere blocking this device. Allthough browsing to the homeassistant ip address from my phone works fine.

**Comment by rradar** [comment] 2020-05-15 19:57
I have the same issue. The official home assistant android app just starts with the screen:

> **Unable to Register Application on Android**
> Please check to ensure you have the mobile_app Integration enabled on your home assistant instance.
> [Retry]

I installed [HA Client](https://github.com/estevez-dev/ha_client) on the same phone on the other hand it worked right away :thinking:

**Comment by jef-pearlman** [comment] 2020-05-28 22:12
I'm having what looks like the same problem on a Kindle Fire 10 HD (9th gen) with sideloaded Google Play store. Some details:

- I've been using a LetsEncrypt certificate w/duckdns.org ddns for a month or so.
- The client works perfectly on my other devices (Pixel 3, BlackBerry Key2, multiple browsers), and always has.
- I can pull up versions, but everything is up to date as of today. Some versions:
  - HassOS 3.13
  - Supervisor 224
  - Core 0.110.3
  - Android App: 1.9.0-167
  - Fire OS 7.3.1.2
- All the other Play Store apps I've installed work fine.
- When home (like now), the duckdns.org hostname resolves to the host's internal address.

Let me know if there's any other info I can provide. Thanks!

**Comment by SeLLeRoNe** [comment] 2020-06-07 18:10
My father is actually facing the same issue on his brand new phone (first installation of the App, so I would assume not historical data anywhere).

Huawai P40 Pro
Android 10.1.0
App v 1.9.0.-167

All permissions has been granted to the App.

**Comment by edofullin** [comment] 2020-07-12 18:32
Same issue on Xiaomi Mi9, Android 10 and MiUI 12 EU

No logs on Home Assistant, working on any phone but mine.

**Comment by SeLLeRoNe** [comment] 2020-07-12 19:07
That's odd, my gf has a Mi 9T Pro and there it is working just fine

**Comment by edofullin** [comment] 2020-07-13 08:13
> That's odd, my gf has a Mi 9T Pro and there it is working just fine

It has been working fine for a long time for me too
I suspect it stopped working with MIUI 12 but I'm not sure.

I'm in the process of compiling from source hoping adb logcat has useful information

**Comment by edofullin** [comment] 2020-07-13 19:33
Compiled with the mock service file and tried getting logcato output:

The problem is still there, this is what I get when I touch "Retry":

```
2020-07-13 21:31:11.964 2079-2218/? I/MiuiNetworkPolicy: updateUidState uid = 10094, uidState = 7
2020-07-13 21:31:11.964 2079-2218/? I/MiuiNetworkPolicy: updateMLUid uid:10094,old:5,new:7
2020-07-13 21:31:11.964 2079-2218/? I/MiuiNetworkPolicy: isMLEnabled state:5,uid:10094,connect:CONNECTED
2020-07-13 21:31:11.964 2079-2218/? I/MiuiNetworkPolicy: isMLEnabled state:7,uid:10094,connect:CONNECTED
    
    --------- beginning of system
2020-07-13 21:31:12.687 2079-2115/? V/DisplayPowerController: Brightness [13] reason changing to: 'automatic [ dim ]', previous reason: 'automatic'.
2020-07-13 21:31:12.696 1924-3279/? D/FOD: updateHBMOverlayTarget brightness=91, mSupportMulExpo=1
2020-07-13 21:31:12.696 1924-3279/? D/FOD: Alpha=0.851819 mBrightnessBackup=91, mTargetBrightness=1, backlight=91, mFodSystemBacklight=10
2020-07-13 21:31:12.697 814-902/? E/DisplayFeatureHal: hhn real brightness 71
2020-07-13 21:31:12.702 1924-2211/? D/FOD: updatePccLevel PCC=0, r=0.718761, g=0.600252, b=0.455818
2020-07-13 21:31:12.720 1924-3279/? D/FOD: updateHBMOverlayTarget brightness=50, mSupportMulExpo=1
2020-07-13 21:31:12.720 1924-3279/? D/FOD: Alpha=0.874000 mBrightnessBackup=50, mTargetBrightness=1, backlight=50, mFodSystemBacklight=10
2020-07-13 21:31:12.720 814-902/? E/DisplayFeatureHal: hhn real brightness 58
2020-07-13 21:31:12.723 1924-2211/? D/FOD: updatePccLevel PCC=0, r=0.582026, g=0.486062, b=0.369104
2020-07-13 21:31:12.728 1924-3279/? D/FOD: updateHBMOverlayTarget brightness=13, mSupportMulExpo=1
2020-07-13 21:31:12.728 1924-3279/? D/FOD: Alpha=0.891131 mBrightnessBackup=13, mTargetBrightness=1, backlight=13, mFodSystemBacklight=10
2020-07-13 21:31:12.729 814-902/? E/DisplayFeatureHal: hhn real brightness 51
2020-07-13 21:31:12.739 1924-2211/? D/FOD: updatePccLevel PCC=0, r=0.449276, g=0.375199, b=0.284918
2020-07-13 21:31:12.778 2079-2115/? V/DisplayPowerController: Brightness [100] reason changing to: 'automatic', previous reason: 'automatic [ dim ]'.
2020-07-13 21:31:12.797 1924-3279/? D/FOD: updateHBMOverlayTarget brightness=42, mSupportMulExpo=1
2020-07-13 21:31:12.798 1924-3279/? D/FOD: Alpha=0.877936 mBrightnessBackup=42, mTargetBrightness=1, backlight=42, mFodSystemBacklight=10
2020-07-13 21:31:12.799 814-902/? E/DisplayFeatureHal: hhn real brightness 56
2020-07-13 21:31:12.800 1924-1930/? D/FOD: updatePccLevel PCC=0, r=0.554717, g=0.463255, b=0.351785
2020-07-13 21:31:12.811 1924-3279/? D/FOD: updateHBMOverlayTarget brightness=83, mSupportMulExpo=1
2020-07-13 21:31:12.811 1924-3279/? D/FOD: Alpha=0.856411 mBrightnessBackup=83, mTargetBrightness=1, backlight=83, mFodSystemBacklight=10
2020-07-13 21:31:12.811 814-902/? E/DisplayFeatureHal: hhn real brightness 68
2020-07-13 21:31:12.813 1924-1930/? D/FOD: updatePccLevel PCC=0, r=0.691384, g=0.577389, b=0.438456
2020-07-13 21:31:12.826 1924-3279/? D/FOD: updateHBMOverlayTarget brightness=100, mSupportMulExpo=1
2020-07-13 21:31:12.827 1924-3279/? D/FOD: Alpha=0.846500 mBrightnessBackup=100, mTargetBrightness=1, backlight=100, mFodSystemBacklight=10
2020-07-13 21:31:12.827 814-902/? E/DisplayFeatureHal: hhn real brightness 74
2020-07-13 21:31:12.840 1924-2032/? D/FOD: updatePccLevel PCC=0, r=0.749968, g=0.626314, b=0.475608
2020-07-13 21:31:12.853 1897-2045/? I/SDM: HWCDisplayBuiltIn::parseOutputBuffer: w 1080 h 2340 stride 1088 size 10186752 Bpp 4
2020-07-13 21:31:12.854 1897-2045/? D/SDM: HWCDisplayBuiltIn::parseBrightness: out partial brightness:8.000000, (r, g, b): { 178.000000, 148.000000, 112.000000 }
2020-07-13 21:31:12.854 1897-2045/? I/libsensor-C2SNotifier: NotifySensorThread will begin for SendClientRGB !
2020-07-13 21:31:12.855 1897-2045/? I/libsensor-C2SNotifier: SendMsgThread has begin for SendClientRGB !
2020-07-13 21:31:12.855 1897-22932/? I/libsensor-C2SNotifier: SendMsgThread threadLoop starting !
2020-07-13 21:31:12.855 1897-22932/? I/libsensor-C2SNotifier: Sensor: notify type: 5, value: -5
2020-07-13 21:31:12.856 1897-22932/? I/libsensor-C2SNotifier: SendMsgThread threadLoop correct and msg have been send !
2020-07-13 21:31:12.945 2321-2845/? D/NetworkController.MobileSignalController(3): 4G level = 4
2020-07-13 21:31:13.021 1897-2045/? I/SDM: HWCDisplayBuiltIn::parseOutputBuffer: w 1080 h 2340 stride 1088 size 10186752 Bpp 4
2020-07-13 21:31:13.022 1897-2045/? D/SDM: HWCDisplayBuiltIn::parseBrightness: out partial brightness:11.000000, (r, g, b): { 192.000000, 161.000000, 122.000000 }
2020-07-13 21:31:13.022 1897-2045/? I/libsensor-C2SNotifier: NotifySensorThread will begin for SendClientRGB !
2020-07-13 21:31:13.023 1897-2045/? I/libsensor-C2SNotifier: SendMsgThread has begin for SendClientRGB !
2020-07-13 21:31:13.023 1897-22940/? I/libsensor-C2SNotifier: SendMsgThread threadLoop starting !
2020-07-13 21:31:13.023 1897-22940/? I/libsensor-C2SNotifier: Sensor: notify type: 5, value: -5
2020-07-13 21:31:13.024 1897-22940/? I/libsensor-C2SNotifier: SendMsgThread threadLoop correct and msg have been send !
2020-07-13 21:31:13.187 1897-2045/? I/SDM: HWCDisplayBuiltIn::parseOutputBuffer: w 1080 h 2340 stride 1088 size 10186752 Bpp 4
2020-07-13 21:31:13.189 1897-2045/? D/SDM: HWCDisplayBuiltIn::parseBrightness: out partial brightness:11.000000, (r, g, b): { 192.000000, 161.000000, 122.000000 }
2020-07-13 21:31:13.189 1897-2045/? I/libsensor-C2SNotifier: NotifySensorThread will begin for SendClientRGB !
2020-07-13 21:31:13.189 1897-2045/? I/libsensor-C2SNotifier: SendMsgThread has begin for SendClientRGB !
2020-07-13 21:31:13.189 1897-22943/? I/libsensor-C2SNotifier: SendMsgThread threadLoop starting !
2020-07-13 21:31:13.190 1897-22943/? I/libsensor-C2SNotifier: Sensor: notify type: 5, value: -5
2020-07-13 21:31:13.190 1897-22943/? I/libsensor-C2SNotifier: SendMsgThread threadLoop correct and msg have been send !
2020-07-13 21:31:13.280 21238-22937/io.homeassistant.companion.android.debug E/FirebaseInstanceId: Failed to get FIS auth token
    java.util.concurrent.ExecutionException: com.google.firebase.installations.FirebaseInstallationsException
        at com.google.android.gms.tasks.Tasks.zzb(Unknown Source:61)
        at com.google.android.gms.tasks.Tasks.await(Unknown Source:23)
        at com.google.firebase.iid.zzt.zzb(com.google.firebase:firebase-iid@@20.1.5:54)
        at com.google.firebase.iid.zzt.zza(com.google.firebase:firebase-iid@@20.1.5:72)
        at com.google.firebase.iid.zzs.run(Unknown Source:12)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: com.google.firebase.installations.FirebaseInstallationsException
        at com.google.firebase.installations.FirebaseInstallations.doNetworkCall(com.google.firebase:firebase-installations@@16.2.1:350)
        at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationInternal$0(com.google.firebase:firebase-installations@@16.2.1:323)
        at com.google.firebase.installations.FirebaseInstallations$$Lambda$5.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919) 
2020-07-13 21:31:13.287 559-559/? I/hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
2020-07-13 21:31:13.295 2079-4367/? D/CompatibilityInfo: mCompatibilityFlags - 0
2020-07-13 21:31:13.295 2079-4367/? D/CompatibilityInfo: applicationDensity - 440
2020-07-13 21:31:13.296 2079-4367/? D/CompatibilityInfo: applicationScale - 1.0
2020-07-13 21:31:13.297 559-559/? I/hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
2020-07-13 21:31:13.316 559-559/? I/hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
2020-07-13 21:31:13.321 2079-5291/? D/CompatibilityInfo: mCompatibilityFlags - 0
2020-07-13 21:31:13.321 2079-5291/? D/CompatibilityInfo: applicationDensity - 440
2020-07-13 21:31:13.321 2079-5291/? D/CompatibilityInfo: applicationScale - 1.0
2020-07-13 21:31:13.323 559-559/? I/hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
2020-07-13 21:31:13.355 1897-2045/? I/SDM: HWCDisplayBuiltIn::parseOutputBuffer: w 1080 h 2340 stride 1088 size 10186752 Bpp 4
2020-07-13 21:31:13.356 1897-2045/? D/SDM: HWCDisplayBuiltIn::parseBrightness: out partial brightness:11.000000, (r, g, b): { 192.000000, 161.000000, 122.000000 }
2020-07-13 21:31:13.356 1897-2045/? I/libsensor-C2SNotifier: NotifySensorThread will begin for SendClientRGB !
2020-07-13 21:31:13.357 1897-2045/? I/libsensor-C2SNotifier: SendMsgThread has begin for SendClientRGB !
2020-07-13 21:31:13.358 1897-22947/? I/libsensor-C2SNotifier: SendMsgThread threadLoop starting !
2020-07-13 21:31:13.358 1897-22947/? I/libsensor-C2SNotifier: Sensor: notify type: 5, value: -5
2020-07-13 21:31:13.358 1897-22947/? I/libsensor-C2SNotifier: SendMsgThread threadLoop correct and msg have been send !
2020-07-13 21:31:13.378 559-559/? I/hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
2020-07-13 21:31:13.381 559-559/? I/hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
2020-07-13 21:31:13.392 21238-21238/io.homeassistant.companion.android.debug E/IntegrationPresenter: Couldn't get FirebaseInstanceId
    java.io.IOException: FIS_AUTH_ERROR
        at com.google.firebase.iid.zzu.then(com.google.firebase:firebase-iid@@20.1.5:16)
        at com.google.android.gms.tasks.zzd.run(Unknown Source:5)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
        at java.lang.Thread.run(Thread.java:919)
2020-07-13 21:31:13.550 2079-2218/? I/MiuiNetworkPolicy: bandwidth: 3 KB/s, Max bandwidth: 2239 KB/s
2020-07-13 21:31:13.552 1010-1010/? W/adbd: timeout expired while flushing socket, closing
2020-07-13 21:31:14.898 21238-21355/io.homeassistant.companion.android.debug I/n.android.debu: System.exit called, status: 1
2020-07-13 21:31:14.898 21238-21355/io.homeassistant.companion.android.debug I/AndroidRuntime: VM exiting with result code 1, cleanup skipped.
2020-07-13 21:31:14.933 2079-2202/? W/InputDispatcher: channel '4413bb2 io.homeassistant.companion.android.debug/io.homeassistant.companion.android.onboarding.OnboardingActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
2020-07-13 21:31:14.933 2079-2202/? E/InputDispatcher: channel '4413bb2 io.homeassistant.companion.android.debug/io.homeassistant.companion.android.onboarding.OnboardingActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2020-07-13 21:31:14.950 2079-5291/? I/ActivityManager: Process com.google.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0 (pid 21744) has died: fore BTOP
2020-07-13 21:31:14.951 2481-2481/? I/Zygote: Process 21744 exited cleanly (0)
2020-07-13 21:31:14.951 2079-2110/? W/libprocessgroup: Failed to open process cgroup uid 99038 pid 21744: Permission denied
2020-07-13 21:31:14.951 2079-2110/? E/libprocessgroup: Error encountered killing process cgroup uid 99038 pid 21744: Permission denied
2020-07-13 21:31:14.955 559-559/? I/hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.servicetracker@1.0::IServicetracker/default in either framework or device manifest.
2020-07-13 21:31:14.956 2079-5291/? I/AutoStartManagerService: MIUILOG- Reject RestartService packageName :io.homeassistant.companion.android.debug uid : 10351
2020-07-13 21:31:14.957 2079-4904/? D/ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=568, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10351] ], android.os.BinderProxy@5a114c)
2020-07-13 21:31:14.957 2079-4375/? D/ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=569, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND Uid: 10351] ], android.os.BinderProxy@466b595)
2020-07-13 21:31:14.957 2079-2825/? D/ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=567, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10351] ], android.os.BinderProxy@14ce6aa)
2020-07-13 21:31:14.957 2079-2227/? D/NsdService: Client disconnected
```

I hope this is useful, there are no logs on home assistant.
Let me know if you need further testing

**Closed** 2020-07-20 13:13 UTC
Labels: bug
