### ISSUE TITLE
NFC Reader with two Home Assistant instances

### ISSUE THREAD

**Issue by McFranky** [home-assistant/android#2133] opened 2022-01-10 11:39 UTC
**2022.1.1-full:**

**Android V12**

**Samsung S21**

**2021.12.8**

**Description of problem:**
I have two instances of the Home Assistance App on my phone (personal and working). This works really great! But if I scan a NFC-Tag, only the personal instance recognize the tag. Is it possible to deactivate the NFC Function in the app (setup), so that only the other instance (working) looks for NFC tags?

Thanks
Frank

**Comment by dshokouhi** [comment] 2022-01-10 15:32
Duplicate of #296

**Closed** 2022-01-10 15:32 UTC
Labels: bug
