### ISSUE TITLE
When using the Energy distribution card in dashboard, android-companion app crashes after serval hours.

### ISSUE THREAD

**Issue by HAuser2019** [home-assistant/android#2529] opened 2022-05-14 18:02 UTC
**Home Assistant Android version:**
2022.3.0-full

**Android version:**
10

**Phone model:**
ALL_TAB15RK3288A10PoEv2
https://shop.allnet.de/media/pdf/0b/d9/85/193134-Datenblatt.pdf

**Home Assistant version:**
core-2022.5.4

**Last working Home Assistant release (if known):**
core-2021.1.1 when energycards where not invented yet.

**Description of problem:**
Hi!

Oke I didn't have a clue how to bug report this, because I got no errors, so this took me weeeeeeks to figure out why the companion app crashes 2 times a day or even at random times and dissapears to the background or the display starts weird image scrambling and flashing the display. Also the processor of the Android10 tablet gets hot.
I removed one element at a time from the lovelace/dashboard, and it appears when the Energy distribution card is not not continuesly in het main home display, the app doesn't crash anymore. So it seems...there is something with this engergy distribution card I think....

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
Need to arrange a screenshot. I removed the card, because don't want the app to crash (bad for WAF factor)

**Additional information:**
You need the place specifically the Energy distribution card on your own dashboard main page with a few other cards around it (so not the autogen lovelace), and just let it sit there overnight without touching it, the next morning it is crashed.

**Comment by dshokouhi** [comment] 2022-05-15 17:58
can you double check that your device is using googles version of android system webview and that is up to date from the play store? If you look at the companion app logs we also print the package name and version to verify that you are on the latest.

Can you reproduce using Chrome for android on teh same device?

**Comment by HAuser2019** [comment] 2022-05-15 18:38
-It is called "Android System Webview" by Google LCC in the appstore (just updated again,always using the latest). So think this is oke.
-According to the log webview version 101.0.4951.61
-The problem i chrome...hmm I believe not...but tested that very long ago. I'll add the "energy distribution card" back to my dashboard and run it on chrome instead of the compansion app overnight. And see what it does...to be coninued.

**Comment by HAuser2019** [comment] 2022-05-16 20:33
Oke, tested it with chromebrowser over night, and during day without touching. Back of tablet gets hotter but it doens't crash! Tested it tonight again with the companion app, the companion app dasboard freezed within 2 hours (also hot back of the tablet). I can send you a shot of the freezed dasboard (this time it didn't crash with spectecular visuals, but different behaviour everytime, if I have a spectecular crash again I can send you a screenshot). So the funny thing is dat the dasboard animations are now freezed (at that moment of freeze the tablet speaker made a "tick" sound) but the buttons in the dasboard still work! But I cannot acces the HA menubar (I always use the sidebar hidden) anymore...so I cannot send you a crash report, I have to quit te app now...

**Comment by HAuser2019** [comment] 2022-05-18 20:31
Oke, well I don't have spectecular crash foto's. It seems the app juist quits after serval hours. The error easy replicateable on my side, since I added the card to my dashboard. Dit you see the error also? Is there anything that I can do?

**Comment by jpelgrom** [comment] 2022-05-23 18:31
Would you be able to get the logs for the crash? That will tell us why the app has crashed.

You'd have to use an app like 'Logcat Reader' or connect to a computer with Android Studio on it to view the logs using logcat. Search for something like `FATAL EXCEPTION: main Process: io.homeassistant.companion.android` in the log.
Alternatively, download the latest beta version [from the releases on GitHub](https://github.com/home-assistant/android/releases/tag/beta-2316-f2ccd865) (use the file with `full` in the name), after the app has crashed go to Settings > Companion app > Show and share logs > tap on 'Recent crash' at the top of the screen. It will replace the current version of the app but you will continue receiving updates from the Play Store when they become available

**Comment by HAuser2019** [comment] 2022-05-24 18:47
Hi I go for the "Alternatively" option and NOW installed the full beta-2316-f2ccd865.apk from a USB-stick in the tablet.
After it goes down I will search for the "Recent crash" option in the logs... (button aint there now, maybe it will magically appear?). I'll come back to you when I have the log.

**Comment by jpelgrom** [comment] 2022-05-24 18:50
> button aint there now, maybe it will magically appear?

Yes, the button will only be visible if the app has recorded a crash in the last 12 hours

**Comment by HAuser2019** [comment] 2022-05-25 07:45
Hmm it crashed last night (effectively removing the app from the foreground to a background process is what is like in practical) but no button is appeared.... i've send the log to home assistant. Does that work for you?

**Comment by HAuser2019** [comment] 2022-05-26 19:16
A crashed app video!: https://www.dropbox.com/s/mt4p1ix3kevqr6r/IMG_4276.MOV?dl=0
After this video the app quit....

But after the crash I restart there there is no "recent crash" button....Below the log after I restarted the app again....
Did you manage to repoduce it yourself? Since it seems so easy to do so....

```
--------- beginning of main
05-26 20:50:32.649 24525 24525 I chatty  : uid=10120(io.homeassistant.companion.android) expire 1 line
05-26 20:50:32.731 24525 24525 I FirebaseInitProvider: FirebaseApp initialization successful
05-26 20:50:32.735 24525 24525 D WM-WrkMgrInitializer: Initializing WorkManager with default configuration.
05-26 20:50:32.759 24525 24571 I DynamiteModule: Considering local module com.google.android.gms.measurement.dynamite:55 and remote module com.google.android.gms.measurement.dynamite:72
05-26 20:50:32.759 24525 24571 I DynamiteModule: Selected remote version of com.google.android.gms.measurement.dynamite, version >= 72
05-26 20:50:32.760 24525 24571 V DynamiteModule: Dynamite loader version >= 2, using loadModule2NoCrashUtils
05-26 20:50:32.798 24525 24525 D Sentry  : io.sentry.auto-init read: false
05-26 20:50:32.798 24525 24525 I Sentry  : Retrieving auto-init from AndroidManifest.xml
05-26 20:50:32.857 24525 24571 I mpanion.androi: Waiting for a blocking GC ClassLinker
05-26 20:50:32.886 24525 24571 I mpanion.androi: WaitForGcToComplete blocked ClassLinker on ClassLinker for 29.523ms
05-26 20:50:32.950 24525 24525 I pool-12-thread-: type=1400 audit(0.0:2311): avc: denied { read } for name="version" dev="proc" ino=4026532026 scontext=u:r:untrusted_app:s0:c120,c256,c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=1 app=io.homeassistant.companion.android
05-26 20:50:32.950 24525 24525 I pool-12-thread-: type=1400 audit(0.0:2312): avc: denied { open } for path="/proc/version" dev="proc" ino=4026532026 scontext=u:r:untrusted_app:s0:c120,c256,c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=1 app=io.homeassistant.companion.android
05-26 20:50:32.952 24525 24525 I pool-12-thread-: type=1400 audit(0.0:2313): avc: denied { getattr } for path="/proc/version" dev="proc" ino=4026532026 scontext=u:r:untrusted_app:s0:c120,c256,c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=1 app=io.homeassistant.companion.android
05-26 20:50:33.011 24525 24594 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
05-26 20:50:33.149 24525 24597 I FA      : App measurement initialized, version: 63020
05-26 20:50:33.149 24525 24597 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
05-26 20:50:33.149 24525 24597 I FA      : To enable faster debug mode event logging run:
05-26 20:50:33.149 24525 24597 I FA      :   adb shell setprop debug.firebase.analytics.app io.homeassistant.companion.android
05-26 20:50:33.227 24525 24597 I FA      : Tag Manager is not found and thus will not be used
05-26 20:50:33.409 24525 24525 I WebViewFactory: Loading com.google.android.webview version 101.0.4951.61 (code 495106130)
05-26 20:50:33.501 24525 24525 I cr_WVCFactoryProvider: Loaded version=101.0.4951.61 minSdkVersion=29 isBundle=true multiprocess=false packageId=2
05-26 20:50:33.514 24525 24574 W mpanion.androi: Long monitor contention with owner main (24525) at boolean android.os.BinderProxy.transactNative(int, android.os.Parcel, android.os.Parcel, int)(BinderProxy.java:-2) waiters=0 in android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() for 121ms
05-26 20:50:33.514 24525 24606 I cr_VariationsUtils: Failed reading seed file "/data/user/0/io.homeassistant.companion.android/app_webview/variations_seed_new"
05-26 20:50:33.516 24525 24606 I cr_VariationsUtils: Requesting new seed from IVariationsSeedServer
05-26 20:50:33.523 24525 24525 I cr_LibraryLoader: Successfully loaded native library
05-26 20:50:33.524 24525 24525 I cr_CachingUmaRecorder: Flushed 8 samples from 8 histograms.
05-26 20:50:33.657 24525 24525 I WM-SystemFgDispatcher: Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService (has extras) }
05-26 20:50:33.805 24525 24525 I chatty  : uid=10120(io.homeassistant.companion.android) identical 108 lines
05-26 20:50:33.806 24525 24525 I WM-SystemFgDispatcher: Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService (has extras) }
05-26 20:50:33.808 24525 24525 I WM-SystemFgDispatcher: Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService (has extras) }
05-26 20:50:33.809 24525 24525 I Choreographer: Skipped 61 frames!  The application may be doing too much work on its main thread.
05-26 20:50:33.938 24525 24525 W mpanion.androi: Accessing hidden method Landroid/content/res/Resources$Theme;->getKey()Landroid/content/res/Resources$ThemeKey; (greylist-max-o, reflection, denied)
05-26 20:50:34.043 24525 24587 I mali_so : [File] : hardware/rockchip/mali_so/driver/product/base/src/mali_base_kbase.c; [Line] : 876; [Func] : base_context_deal_with_version_affairs_rk_ext;
05-26 20:50:34.043 24525 24587 I mali_so : arm_release_ver of this mali_so is 'r18p0-01rel0', rk_so_ver is '13@0'.
05-26 20:50:34.043 24525 24587 D mali_so : [File] : hardware/rockchip/mali_so/driver/product/base/src/mali_base_kbase.c; [Line] : 881; [Func] : base_context_deal_with_version_affairs_rk_ext;
05-26 20:50:34.043 24525 24587 D mali_so : current process is NOT sf, to bail out.
05-26 20:50:34.068 24525 24587 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
05-26 20:50:34.086 24525 24587 W Gralloc3: mapper 3.x is not supported
05-26 20:50:34.090 24525 24587 D GRALLOC-ROCKCHIP: RK_GRAPHICS_VER=commit-id:344c4dd
05-26 20:50:34.107 24525 24587 D         : set stream to NULL
05-26 20:50:34.110 24525 24587 I chatty  : uid=10120(io.homeassistant.companion.android) RenderThread identical 1 line
05-26 20:50:34.111 24525 24587 D         : set stream to NULL
05-26 20:50:34.115 24525 24587 I OpenGLRenderer: Davey! duration=1326ms; Flags=1, IntendedVsync=261458170246580, Vsync=261459186913206, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=261459192652255, AnimationStart=261459192679672, PerformTraversalsStart=261459193697880, DrawStart=261459451369338, SyncQueued=261459458071255, SyncStart=261459458786130, IssueDrawCommandsStart=261459459092088, SwapBuffers=261459495095422, FrameCompleted=261459497465797, DequeueBufferDuration=8516000, QueueBufferDuration=1078000, 
05-26 20:50:34.125 24525 24525 D SensorReceiver: Received intent: android.media.RINGER_MODE_CHANGED
05-26 20:50:34.129 24525 24525 D SensorReceiver: Sensor audio_sensor corresponding to received event android.media.RINGER_MODE_CHANGED is disabled, skipping sensors update
05-26 20:50:34.147 24525 24525 D UrlRepository: localUrl is: false and usesInternalSsid is: false
05-26 20:50:34.147 24525 24525 D UrlRepository: Using external URL
05-26 20:50:34.151 24525 24525 D UrlRepository: localUrl is: false and usesInternalSsid is: false
05-26 20:50:34.170 24525 24576 D UrlRepository: localUrl is: false and usesInternalSsid is: false
05-26 20:50:34.367 24525 24539 I mpanion.androi: Background concurrent copying GC freed 27782(1239KB) AllocSpace objects, 13(668KB) LOS objects, 24% free, 4753KB/6338KB, paused 365us total 221.705ms
05-26 20:50:34.637 24525 24525 I Choreographer: Skipped 47 frames!  The application may be doing too much work on its main thread.
05-26 20:50:34.686 24525 24578 D UrlRepository: localUrl is: false and usesInternalSsid is: false
05-26 20:50:34.686 24525 24578 D WebSockManager: Starting to listen to Websocket
05-26 20:50:34.698 24525 24525 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@5cb6041
05-26 20:50:34.700 24525 24587 D         : set stream to NULL
05-26 20:50:34.758 24525 24579 I WM-Processor: Moving WorkSpec (4d4e21cf-8c30-43c8-925e-6c6c6eb1fe9d) to the foreground
05-26 20:50:34.782 24525 24656 D UrlRepository: localUrl is: false and usesInternalSsid is: false
05-26 20:50:34.782 24525 24656 D UrlRepository: Using external URL
05-26 20:50:34.786 24525 24525 I cr_VariationsUtils: Loaded seed with age 173978s
05-26 20:50:34.807 24525 24656 D UrlRepository: localUrl is: false and usesInternalSsid is: false
05-26 20:50:34.807 24525 24656 D UrlRepository: Using external URL
05-26 20:50:35.087 24525 24662 W mpanion.androi: Long monitor contention with owner main (24525) at void com.android.webview.chromium.WebViewChromiumFactoryProvider.k(boolean)(chromium-TrichromeWebViewGoogle.aab-stable-495106130:320) waiters=0 in android.webkit.CookieManager com.android.webview.chromium.WebViewChromiumFactoryProvider.getCookieManager() for 257ms
05-26 20:50:35.159 24525 24662 D WebSocketRepository: Websocket: onOpen
05-26 20:50:35.161 24525 24662 D WebSocketRepository: Websocket: onMessage (text)
05-26 20:50:35.237 24525 24539 I mpanion.androi: Background concurrent copying GC freed 41287(2030KB) AllocSpace objects, 4(140KB) LOS objects, 24% free, 6144KB/8193KB, paused 7.210ms total 492.023ms
05-26 20:50:35.277 24525 24525 D RenderScript HIDL Adaptation: IRenderScriptDevice::getService()
05-26 20:50:35.279 24525 24525 D RenderScript HIDL Adaptation: IRenderScriptDevice::getService() returned 0x0
05-26 20:50:35.279 24525 24525 D RenderScript HIDL Adaptation: Using Fallback Path.
05-26 20:50:35.304 24525 24525 D         : Successfully queried cache dir: /data/user_de/0/io.homeassistant.companion.android/code_cache
05-26 20:50:35.304 24525 24525 D RenderScript: Setting cache dir: /data/user_de/0/io.homeassistant.companion.android/code_cache
05-26 20:50:35.333 24525 24525 I System.out: recordForce value 5
05-26 20:50:35.336 24525 24525 D WebviewActivity: Current webview package com.google.android.webview and version 101.0.4951.61
05-26 20:50:35.457 24525 24662 D WebSocketRepository: Message number null received: {"type":"auth_required","ha_version":"2022.5.5"}
05-26 20:50:35.458 24525 24662 D WebSocketRepository: Websocket: onMessage (text)
05-26 20:50:35.458 24525 24656 D WebSocketRepository: Auth Requested
05-26 20:50:35.459 24525 24662 D WebSocketRepository: Message number null received: {"type":"auth_ok","ha_version":"2022.5.5"}
05-26 20:50:35.462 24525 24656 D WebSocketRepository: Sending message 1: {type=mobile_app/push_notification_channel, webhook_id=672e1e769ad604f39e3060d1261d5f852ab6f805571f8ec57005be8f0e557f86, support_confirm=true, id=1}
05-26 20:50:35.466 24525 24656 D WebSocketRepository: Message number 1 sent
05-26 20:50:35.472 24525 24662 D WebSocketRepository: Websocket: onMessage (text)
05-26 20:50:35.478 24525 24662 D WebSocketRepository: Message number 1 received: {"id":1,"type":"result","success":true,"result":null}
05-26 20:50:35.591 24525 24539 I mpanion.androi: Background young concurrent copying GC freed 31306(1981KB) AllocSpace objects, 2(40KB) LOS objects, 14% free, 6976KB/8193KB, paused 343us total 132.469ms
05-26 20:50:35.790 24525 24681 E chromium: [ERROR:simple_index_file_posix.cc(36)] opendir /data/user/0/io.homeassistant.companion.android/cache/WebView/Default/HTTP Cache/Code Cache/wasm: No such file or directory (2)
05-26 20:50:35.790 24525 24680 E chromium: [ERROR:simple_index_file_posix.cc(36)] opendir /data/user/0/io.homeassistant.companion.android/cache/WebView/Default/HTTP Cache/Code Cache/js: No such file or directory (2)
05-26 20:50:35.790 24525 24681 E chromium: [ERROR:simple_index_file.cc(577)] Could not reconstruct index from disk
05-26 20:50:35.790 24525 24680 E chromium: [ERROR:simple_index_file.cc(577)] Could not reconstruct index from disk
05-26 20:50:35.807 24525 24525 I Choreographer: Skipped 67 frames!  The application may be doing too much work on its main thread.
05-26 20:50:35.848 24525 24587 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
05-26 20:50:35.940 24525 24587 I OpenGLRenderer: Davey! duration=1254ms; Flags=1, IntendedVsync=261460068226639, Vsync=261461184893261, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=261461190311672, AnimationStart=261461190337047, PerformTraversalsStart=261461196931631, DrawStart=261461234144506, SyncQueued=261461237278756, SyncStart=261461237655006, IssueDrawCommandsStart=261461237820672, SwapBuffers=261461321236464, FrameCompleted=261461322671173, DequeueBufferDuration=14281000, QueueBufferDuration=487000, 
05-26 20:50:35.949 24525 24587 I OpenGLRenderer: Davey! duration=1263ms; Flags=1, IntendedVsync=261460068226639, Vsync=261461184893261, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=261461190311672, AnimationStart=261461190337047, PerformTraversalsStart=261461196931631, DrawStart=261461323567464, SyncQueued=261461324917006, SyncStart=261461325425673, IssueDrawCommandsStart=261461325533298, SwapBuffers=261461329802423, FrameCompleted=261461332383381, DequeueBufferDuration=158000, QueueBufferDuration=1289000, 
05-26 20:50:35.950 24525 24525 I WM-SystemFgDispatcher: Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService (has extras) }
05-26 20:50:36.030 24525 24576 D SensorWorker: Updating all Sensors.
05-26 20:50:36.035 24525 24574 I WM-Processor: Moving WorkSpec (55595d77-2e34-47dd-8abd-f211258255e1) to the foreground
05-26 20:50:36.060 24525 24587 W libEGL  : EGLNativeWindowType 0x81b2c348 disconnect failed
05-26 20:50:36.066 24525 24525 D UrlRepository: localUrl is: false and usesInternalSsid is: false
05-26 20:50:36.067 24525 24525 D UrlRepository: Using external URL
05-26 20:50:36.096 24525 24525 I WM-SystemFgDispatcher: Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService (has extras) }
05-26 20:50:36.102 24525 24681 E chromium: [ERROR:directory_reader_posix.cc(42)] opendir /data/user/0/io.homeassistant.companion.android/cache/WebView/Crashpad/attachments/49b0609b-d7ca-42de-961d-4e134411d44c: No such file or directory (2)
05-26 20:50:36.131 24525 24681 W chromium: [WARNING:minidump_to_upload_parameters.cc(67)] duplicate annotation name ptype, discarding value browser
05-26 20:50:36.145 24525 24587 D         : set stream to NULL
05-26 20:50:36.507 24525 24709 D         : set stream to NULL
05-26 20:50:36.584 24525 24709 I chatty  : uid=10120(io.homeassistant.companion.android) Chrome_InProcGp identical 2 lines
05-26 20:50:36.590 24525 24709 D         : set stream to NULL
05-26 20:50:36.591 24525 24732 D WebviewActivity: External bus {"type":"config/get","id":1}
05-26 20:50:36.594 24525 24709 D         : set stream to NULL
05-26 20:50:36.601 24525 24709 D         : set stream to NULL
05-26 20:50:36.603 24525 24525 D WebviewActivity: externalBus({"id":1,"type":"result","success":true,"result":{"hasSettingsScreen":true,"canWriteTag":false,"hasExoPlayer":true}});
05-26 20:50:36.622 24525 24587 D         : set stream to NULL
05-26 20:50:36.622 24525 24525 D UrlRepository: localUrl is: false and usesInternalSsid is: false
05-26 20:50:36.623 24525 24525 D UrlRepository: Using external URL
05-26 20:50:36.625 24525 24587 D         : set stream to NULL
05-26 20:50:36.629 24525 24525 I chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read properties of null (reading '0')", source: http://192.168.66.66:8123/?external_auth=1 (1)
05-26 20:50:36.631 24525 24587 D         : set stream to NULL
05-26 20:50:36.634 24525 24587 I chatty  : uid=10120(io.homeassistant.companion.android) RenderThread identical 1 line
05-26 20:50:36.636 24525 24587 D         : set stream to NULL
05-26 20:50:36.637 24525 24525 D WebviewActivity: Callback null
05-26 20:50:36.640 24525 24525 E WebviewActivity: Cannot set status bar color 0. Skipping coloring...
05-26 20:50:36.641 24525 24525 E WebviewActivity: Cannot set navigation bar color 0. Skipping coloring...
05-26 20:50:36.641 24525 24587 D         : set stream to NULL
05-26 20:50:37.031 24525 24576 D SensorReceiver: Nothing to update
05-26 20:50:37.042 24525 24580 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=55595d77-2e34-47dd-8abd-f211258255e1, tags={ io.homeassistant.companion.android.sensors.SensorWorker } ]
05-26 20:50:37.438 24525 24732 D WebviewActivity: External bus {"type":"connection-status","payload":{"event":"connected"},"id":2}
05-26 20:50:37.511 24525 24709 D         : set stream to NULL
05-26 20:50:37.513 24525 24709 I chatty  : uid=10120(io.homeassistant.companion.android) Chrome_InProcGp identical 1 line
05-26 20:50:37.519 24525 24709 D         : set stream to NULL
05-26 20:50:37.805 24525 24732 D WebviewActivity: External bus {"type":"theme-update","id":3}
05-26 20:50:38.585 24525 24525 D WebviewActivity: Color from webview is "#3593bc-SPACER-rgba(208, 208, 208)"
05-26 20:50:38.585 24525 24525 D WebviewActivity: Color from webview is "#3593bc-SPACER-rgba(208, 208, 208)"
05-26 20:50:38.586 24525 24576 D WebViewPresenterImpl: Try getting color from webview color "#3593bc".
05-26 20:50:38.587 24525 24576 I WebViewPresenterImpl: Found color -13265988.
05-26 20:50:38.590 24525 24576 D WebViewPresenterImpl: Try getting color from webview color "rgba(208, 208, 208)".
05-26 20:50:38.592 24525 24576 W WebViewPresenterImpl: Could not get color from webview.
05-26 20:50:38.592 24525 24576 W WebViewPresenterImpl: java.lang.IllegalArgumentException: Unknown color
05-26 20:50:38.592 24525 24576 W WebViewPresenterImpl: 	at android.graphics.Color.parseColor(Color.java:1400)
05-26 20:50:38.592 24525 24576 W WebViewPresenterImpl: 	at io.homeassistant.companion.android.webview.WebViewPresenterImpl.parseColorWithRgb(WebViewPresenterImpl.kt:230)
05-26 20:50:38.592 24525 24576 W WebViewPresenterImpl: 	at io.homeassistant.companion.android.webview.WebViewPresenterImpl.access$parseColorWithRgb(WebViewPresenterImpl.kt:25)
05-26 20:50:38.592 24525 24576 W WebViewPresenterImpl: 	at io.homeassistant.companion.android.webview.WebViewPresenterImpl$parseWebViewColor$2.invokeSuspend(WebViewPresenterImpl.kt:205)
05-26 20:50:38.592 24525 24576 W WebViewPresenterImpl: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
05-26 20:50:38.592 24525 24576 W WebViewPresenterImpl: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
05-26 20:50:38.592 24525 24576 W WebViewPresenterImpl: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
05-26 20:50:38.592 24525 24576 W WebViewPresenterImpl: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
05-26 20:50:38.592 24525 24576 W WebViewPresenterImpl: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
05-26 20:50:38.592 24525 24576 W WebViewPresenterImpl: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
05-26 20:50:38.592 24525 24576 W WebViewPresenterImpl: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
05-26 20:50:38.592 24525 24576 W WebViewPresenterImpl: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
05-26 20:50:38.592 24525 24576 W WebViewPresenterImpl: Couldn't get color.
05-26 20:50:38.593 24525 24525 E WebviewActivity: Cannot set navigation bar color 0. Skipping coloring...
05-26 20:50:39.125 24525 24709 D         : set stream to NULL
05-26 20:50:39.192 24525 24709 I chatty  : uid=10120(io.homeassistant.companion.android) Chrome_InProcGp identical 10 lines
05-26 20:50:39.199 24525 24709 D         : set stream to NULL
05-26 20:50:39.207 24525 24587 D         : set stream to NULL
05-26 20:50:39.492 24525 24587 I chatty  : uid=10120(io.homeassistant.companion.android) RenderThread identical 7 lines
05-26 20:50:39.497 24525 24587 D         : set stream to NULL
05-26 20:50:39.504 24525 24709 D         : set stream to NULL
05-26 20:50:39.662 24525 24709 I chatty  : uid=10120(io.homeassistant.companion.android) Chrome_InProcGp identical 4 lines
05-26 20:50:39.667 24525 24709 D         : set stream to NULL
05-26 20:50:40.766 24525 24709 D         : set stream to NULL
05-26 20:50:41.082 24525 24709 I chatty  : uid=10120(io.homeassistant.companion.android) Chrome_InProcGp identical 25 lines
05-26 20:50:41.092 24525 24709 D         : set stream to NULL
05-26 20:50:41.120 24525 24587 D         : set stream to NULL
05-26 20:50:41.123 24525 24587 I chatty  : uid=10120(io.homeassistant.companion.android) RenderThread identical 1 line
05-26 20:50:41.129 24525 24587 D         : set stream to NULL
05-26 20:50:41.217 24525 24709 D         : set stream to NULL
05-26 20:50:42.072 24525 24709 I chatty  : uid=10120(io.homeassistant.companion.android) Chrome_InProcGp identical 28 lines
05-26 20:50:42.077 24525 24709 D         : set stream to NULL
05-26 20:50:42.348 24525 24587 D         : set stream to NULL
05-26 20:50:42.351 24525 24587 I chatty  : uid=10120(io.homeassistant.companion.android) RenderThread identical 1 line
05-26 20:50:42.359 24525 24587 D         : set stream to NULL
05-26 20:50:42.368 24525 24525 I chromium: [INFO:CONSOLE(94)] "Error getting Image Colors Error: Fail to load image: http://192.168.66.66:8123/api/media_player_proxy/media_player.appletv_woonkamer?token=5d55ded2d82ea0978881ee83bbeefac3738abc62e0f4bd387fdf8e5b36ca9cf4&cache=Music114/v4/a5/38/57/a53857b2-a738-1bfb-f4be-0b975365d881/CRV_MS_368x368.jpeg", source: http://192.168.66.66:8123/frontend_latest/2fd4553c.js (94)
05-26 20:50:42.543 24525 24709 D         : set stream to NULL
05-26 20:50:43.228 24525 24709 I chatty  : uid=10120(io.homeassistant.companion.android) Chrome_InProcGp identical 13 lines
05-26 20:50:43.236 24525 24709 D         : set stream to NULL
05-26 20:50:43.605 24525 24732 D WebviewActivity: External bus {"type":"config_screen/show","id":4}
05-26 20:50:43.649 24525 24525 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@791d745
05-26 20:50:43.710 24525 24525 D UrlRepository: Using external URL
05-26 20:50:43.714 24525 24525 I chatty  : uid=10120(io.homeassistant.companion.android) identical 2 lines
05-26 20:50:43.715 24525 24525 D UrlRepository: Using external URL
05-26 20:50:43.825 24525 24587 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
05-26 20:50:44.101 24525 24587 D         : set stream to NULL
05-26 20:50:44.107 24525 24587 I chatty  : uid=10120(io.homeassistant.companion.android) RenderThread identical 3 lines
05-26 20:50:44.109 24525 24587 D         : set stream to NULL
05-26 20:50:44.325 24525 24656 D SensorWorker: Updating all Sensors.
05-26 20:50:44.343 24525 24574 I WM-Processor: Moving WorkSpec (0103af64-68f8-4d92-af04-e273d5231f4d) to the foreground
05-26 20:50:44.437 24525 24525 I WM-SystemFgDispatcher: Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService (has extras) }
05-26 20:50:44.590 24525 24587 W libEGL  : EGLNativeWindowType 0x811d84a8 disconnect failed
05-26 20:50:44.844 24525 24539 I mpanion.androi: Background concurrent copying GC freed 28601(1442KB) AllocSpace objects, 0(0B) LOS objects, 24% free, 7908KB/10MB, paused 149us total 355.287ms
05-26 20:50:45.190 24525 24656 D SensorReceiver: Nothing to update
05-26 20:50:45.192 24525 24580 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=0103af64-68f8-4d92-af04-e273d5231f4d, tags={ io.homeassistant.companion.android.sensors.SensorWorker } ]
05-26 20:50:51.675 24525 24587 D         : set stream to NULL
05-26 20:50:53.888 24525 24587 D         : set stream to NULL
05-26 20:50:53.902 24525 24525 E mpanion.androi: Invalid ID 0x00000000.
05-26 20:50:54.040 24525 24656 D LogcatReader: Read logcat for pid 24525

```

**Comment by jpelgrom** [comment] 2022-05-30 18:07
If the app doesn't show a button for the crash, you'll have to get the crash log using logcat, either using the mentioned app or a computer (or did you disable crash reporting in the app settings?). Without a log, we won't be able to continue and find the source of the crash. The log you posted after restarting the app unfortunately cannot show any details from before the app start like a crash.

Your video does show some visual glitches but this isn't really something that is managed by the app. I haven't been able to reproduce flickering like in the video or a crash with a demo setup in ~3.5 hours.

**Comment by HAuser2019** [comment] 2022-05-30 18:29
This visual glitch is only sometimes. Most of the "crashes" just make the app just dissapear/close sudden after like say...halve a or somewhere in the middle of the night.
I did not disable the crash report settings. Oke I'll dive in the the logcat thing....

**Comment by HAuser2019** [comment] 2022-05-31 18:15
Hmm it is too complex with logcat. I've done my best to report it, shown the video. Think I leave it like this, until other users report the error I just don't use the specific type: energy-distribution card anymore.

**Comment by dshokouhi** [comment] 2022-07-22 15:45
Closing this issue due to lack of information, the logs that are requested are needed in order to continue forward.

**Closed by dshokouhi** 2022-07-22 15:45 UTC
Labels: bug, webview
