### ISSUE TITLE
Next alarm sensor return wrong time - Galaxy S10+

### ISSUE THREAD

**Issue by N1c093** [home-assistant/android#1190] opened 2020-11-13 06:38 UTC
**Home Assistant Android version:**
3.0.2

**Android version:**
Android 10

**Phone model:**
Galaxy S10+ / SM-G975F

**Home Assistant version:**
0.117.6

**Last working Home Assistant release (if known):**

**Description of problem:**
The sensor for "next alarm" is some minutes wrong at Galaxy S10+. With the Galaxy S7 Edge everything works fine.

For example: Setting the alarm clock to 07:00:00am will result in 05:55:01am (UTC) as the value of the next alarm sensor. (see Screenshot) The sensor should be the at 06:00:00am (UTC)

I don't know if this problem can be fixed inside the HA app or if this is a bug from Samsung

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

![image](https://user-images.githubusercontent.com/59510296/99036411-e8b33680-2581-11eb-93eb-8f7322959d93.png)

**Additional information:**

**Comment by dshokouhi** [comment] 2020-11-13 15:47
Duplicate of #1085 Samsung apps are known for doing these funky things with the AlarmManager API, you will need to use something like the Google Clock app or Sleep as Android as those apps do not send incorrect time.  What you are seeing is Samsung setting this alarm time via the API so we can't prevent that.

**Closed by dshokouhi** 2020-11-13 15:47 UTC
Labels: bug
