### ISSUE TITLE
Wear OS: Support ranged value complications

### ISSUE THREAD

**Issue by oscarb** [home-assistant/android#4228] opened 2024-02-25 20:47 UTC
**Is your feature request related to a problem? Please describe.**

I love that I can put entities from Home Assistant as a complication on my Pixel Watch. However, some entities and sensors are best visualized using a progress bar, be it the electricity price, speaker volume or some temperature.

**Describe the solution you'd like**

I'd like Home Assistant to support [Ranged Value Complications](https://developer.android.com/design/ui/wear/guides/surfaces/complications). 
![image](https://github.com/home-assistant/android/assets/17575446/bd50aa7e-41ad-4780-9549-232bb7f4987e)

I imagine that when setting up a complication of this type, from the same screen where you click to choose entity there would be two more options: *choose min value* and *choose max value*. These two would open up a number picker that can be operated by touch or the crown.

The progress bar would then use these values together with the state value to show progress. 

Obviously this would make the most sense to use with entities where the state is a numerical value.

**Describe alternatives you've considered, if any**

N/A

**Additional context**

An example use case would be to use this watch face together with an entity tracking the screen time of the TV or some other device, so you can easily glance on your watch to see how much you've used and have left :) 

![image](https://github.com/home-assistant/android/assets/17575446/210984f1-84a3-4f7d-835a-50a3ab545f45)

**Comment by dshokouhi** [comment] 2024-02-25 20:55
duplicate of #3091

**Closed by dshokouhi** 2024-02-25 20:55 UTC
