### ISSUE TITLE
Pinch-zoom panels (very useful for floor-plan)

### ISSUE THREAD

**Issue by pove** [home-assistant/android#1532] opened 2021-04-28 15:11 UTC
**Is your feature request related to a problem? Please describe.**
I have a panel tab containing a picture-elements card to configure a floorplan. It shows awesome on desktop and tablet, but impossible to use it on mobile app, the card is resized to a very small size and all the entities are together.

**Describe the solution you'd like**
It would be great if we can pinch to zoom the panel card (containing the floorplan) to be able to see all the entities.

**Describe alternatives you've considered, if any**
I have discover this [pinch-zoom from GoogleChromeLabs](https://github.com/GoogleChromeLabs/pinch-zoom) and it looks pretty much what I would like. It will only zoom the card, not all the app elements (tool-bar, etc...).

**Additional context**
I have tested my HA on the Android Chrome and used the "Settings > Accesibility > Force enable zoom", and I can see a posible issue: when zoom, all the entities elements are zooming the same way as the floor-plan, so the problem persist.
However, I have try with the "Desktop site" option of Chrome and you have a more large card now (so the entities are separated enough) that you can pinch to zoom.

**Comment by dshokouhi** [comment] 2021-04-28 15:13
Duplicate of #1117

**Closed by dshokouhi** 2021-04-28 15:13 UTC
Labels: enhancement

**Comment by pove** [comment] 2021-04-28 15:19
I have created a new one because what you mention [here](https://github.com/home-assistant/android/issues/1117#issuecomment-813507841):

> For those seeing this issue please note this isn't just to zoom on a particular card or video stream, its to zoom into the entire HA frontend.

**Comment by dshokouhi** [comment] 2021-04-28 15:22
zooming is still zooming...to zoom in on a specific card you will want the HA frontend to support that so the app can benefit from it.

**Comment by pove** [comment] 2021-04-28 15:26
I totally understand, I will track [#1117](https://github.com/home-assistant/android/issues/1117), thank you. And you are correct, perhaps I should create a request on the HA Lovelace community forum.

**Comment by pove** [comment] 2021-04-29 16:01
I have found a temporary workaround that allows to see big landscape floorplans on the mobile App. I use card-mod to set the min-width of the picture elements cards at 1000px. In this way, you will see a good size floorplan and will be able to swipe horizontally all along the width to see all of it.

```
style: |
    ha-card {        
     min-width: 1000px !important;
    }
```
