### ISSUE TITLE
Biometrics - Unrecognised fingprint force closes the app

### ISSUE THREAD

**Issue by smcue** [home-assistant/android#1402] opened 2021-03-05 15:39 UTC
**Home Assistant Android version:**
2021.3.1-full

**Android version:**
11

**Phone model:**
Pixel 2 XL

**Home Assistant version:**
core-2021.3.1

**Last working Home Assistant release (if known):**

**Description of problem:**

When using fingerprint biometrics that is not registered/recognised on the device, the app will forcibly close instead of giving the user the option to try again. This is unexpected behaviour for biometrics entry on Android, and as is considered substandard accessibility wise. The biometrics flyout prompt should remain even if the fingerprint is not recognised, and should show 'Not recognised', instead, rather than exit the app. 

**Traceback:**

```
2021-03-05 15:29:21.461 1572-3473/? I/ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.homeassistant.companion.android/.launch.LaunchActivity bnds=[736,1410][989,1703]} from uid 10052
    
    --------- beginning of main
2021-03-05 15:29:21.461 1572-1595/? D/EventSequenceValidator: IntentStarted during UNKNOWN. Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.homeassistant.companion.android/.launch.LaunchActivity bnds=[736,1410][989,1703] }
    java.lang.Throwable: EventSequenceValidator#getStackTrace
        at com.google.android.startop.iorap.EventSequenceValidator.logWarningWithStackTrace(EventSequenceValidator.java:260)
        at com.google.android.startop.iorap.EventSequenceValidator.onIntentStarted(EventSequenceValidator.java:106)
        at com.android.server.wm.LaunchObserverRegistryImpl.handleOnIntentStarted(LaunchObserverRegistryImpl.java:139)
        at com.android.server.wm.LaunchObserverRegistryImpl.lambda$veRn_GhgLZLlOHOJ0ZYT6KcfYqo(Unknown Source:0)
        at com.android.server.wm.-$$Lambda$LaunchObserverRegistryImpl$veRn_GhgLZLlOHOJ0ZYT6KcfYqo.accept(Unknown Source:10)
        at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:292)
        at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
        at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
        at com.android.server.ServiceThread.run(ServiceThread.java:44)
2021-03-05 15:29:21.534 1572-3459/? I/ActivityTaskManager: START u0 {cmp=io.homeassistant.companion.android/.webview.WebViewActivity (has extras)} from uid 11719
2021-03-05 15:29:21.632 1572-3472/? D/ConnectivityService: requestNetwork for uid/pid:11719/2875 NetworkRequest [ TRACK_DEFAULT id=9681, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 11719 AdministratorUids: [] RequestorUid: 11719 RequestorPackageName: io.homeassistant.companion.android] ]
2021-03-05 15:29:21.633 1572-1894/? D/WIFI_AWARE_FACTORY: got request NetworkRequest [ TRACK_DEFAULT id=9681, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 11719 AdministratorUids: [] RequestorUid: 11719 RequestorPackageName: io.homeassistant.companion.android] ] with score 60 and providerId 5
2021-03-05 15:29:21.633 1572-1762/? D/WifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=9681, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 11719 AdministratorUids: [] RequestorUid: 11719 RequestorPackageName: io.homeassistant.companion.android] ] with score 60 and providerId 5
2021-03-05 15:29:21.633 1572-1762/? D/UntrustedWifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=9681, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 11719 AdministratorUids: [] RequestorUid: 11719 RequestorPackageName: io.homeassistant.companion.android] ] with score 60 and providerId 5
2021-03-05 15:29:21.633 2370-2370/? D/PhoneSwitcherNetworkRequstListener: got request NetworkRequest [ TRACK_DEFAULT id=9681, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 11719 AdministratorUids: [] RequestorUid: 11719 RequestorPackageName: io.homeassistant.companion.android] ] with score 60 and providerId 5
2021-03-05 15:29:21.633 1572-1895/? D/Ethernet: got request NetworkRequest [ TRACK_DEFAULT id=9681, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 11719 AdministratorUids: [] RequestorUid: 11719 RequestorPackageName: io.homeassistant.companion.android] ] with score 60 and providerId 5
2021-03-05 15:29:21.668 1572-1600/? I/ActivityTaskManager: Displayed io.homeassistant.companion.android/.webview.WebViewActivity: +207ms
2021-03-05 15:29:21.717 1572-1572/? D/BiometricService: Package: io.homeassistant.companion.android Authenticator ID: 0 Modality: 2 Reported Modality: 2 Status: 1
2021-03-05 15:29:21.718 1572-1572/? V/FingerprintService: startAuthentication(io.homeassistant.companion.android)
2021-03-05 15:29:21.718 1572-1572/? V/FingerprintService: starting client AuthenticationClientImpl(io.homeassistant.companion.android) targetUserId: 0 currentUserId: 0 cookie: 237707434/237707434
2021-03-05 15:29:21.719 2875-2875/? I/WM-SystemFgDispatcher: Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService (has extras) }
2021-03-05 15:29:21.733 1572-1572/? W/FingerprintService: client io.homeassistant.companion.android is authenticating...
2021-03-05 15:29:21.828 2875-4588/? I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=74eb3e9f-09b0-4987-9f63-747023359c52, tags={ io.homeassistant.companion.android.sensors.SensorWorker } ]
2021-03-05 15:29:21.832 1572-1794/? D/ConnectivityService: releasing NetworkRequest [ TRACK_DEFAULT id=9681, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 11719 AdministratorUids: [] RequestorUid: 11719 RequestorPackageName: io.homeassistant.companion.android] ] (release request)
2021-03-05 15:29:41.287 1572-1572/? V/FingerprintService: onAuthenticated(false), ID:0, Owner: io.homeassistant.companion.android, isBP: true, listener: com.android.server.biometrics.fingerprint.FingerprintService$BiometricPromptServiceListenerImpl@daf150, requireConfirmation: false, user: 0
2021-03-05 15:29:41.323 1572-1572/? E/FingerprintService: Stopping background authentication, top: com.google.android.apps.nexuslauncher currentClient: io.homeassistant.companion.android
2021-03-05 15:29:41.383 1572-2274/? D/ConnectivityService: requestNetwork for uid/pid:11719/2875 NetworkRequest [ TRACK_DEFAULT id=9686, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 11719 AdministratorUids: [] RequestorUid: 11719 RequestorPackageName: io.homeassistant.companion.android] ]
2021-03-05 15:29:41.384 1572-1895/? D/Ethernet: got request NetworkRequest [ TRACK_DEFAULT id=9686, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 11719 AdministratorUids: [] RequestorUid: 11719 RequestorPackageName: io.homeassistant.companion.android] ] with score 60 and providerId 5
2021-03-05 15:29:41.384 1572-1894/? D/WIFI_AWARE_FACTORY: got request NetworkRequest [ TRACK_DEFAULT id=9686, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 11719 AdministratorUids: [] RequestorUid: 11719 RequestorPackageName: io.homeassistant.companion.android] ] with score 60 and providerId 5
2021-03-05 15:29:41.384 1572-1762/? D/WifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=9686, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 11719 AdministratorUids: [] RequestorUid: 11719 RequestorPackageName: io.homeassistant.companion.android] ] with score 60 and providerId 5
2021-03-05 15:29:41.385 1572-1762/? D/UntrustedWifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=9686, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 11719 AdministratorUids: [] RequestorUid: 11719 RequestorPackageName: io.homeassistant.companion.android] ] with score 60 and providerId 5
2021-03-05 15:29:41.385 2370-2370/? D/PhoneSwitcherNetworkRequstListener: got request NetworkRequest [ TRACK_DEFAULT id=9686, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 11719 AdministratorUids: [] RequestorUid: 11719 RequestorPackageName: io.homeassistant.companion.android] ] with score 60 and providerId 5
2021-03-05 15:29:41.389 1572-1572/? W/FingerprintService: client io.homeassistant.companion.android is no longer authenticating
2021-03-05 15:29:41.392 1572-1572/? V/FingerprintService: handleError(client=io.homeassistant.companion.android, error = 5)
2021-03-05 15:29:41.392 1572-1572/? V/FingerprintService: Done with client: io.homeassistant.companion.android
2021-03-05 15:29:41.401 1572-2712/? W/ActivityTaskManager: Duplicate finish request for r=ActivityRecord{5210003 u0 io.homeassistant.companion.android/.webview.WebViewActivity t1707 f}}
2021-03-05 15:29:41.412 2875-2875/? I/WM-SystemFgDispatcher: Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService (has extras) }
2021-03-05 15:29:41.434 1572-2274/? W/ActivityManager: Foreground service started from background can not have location/camera/microphone access: service io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService
2021-03-05 15:29:41.661 2875-2943/? I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=9b91e261-3227-443c-8716-d025266d38b9, tags={ io.homeassistant.companion.android.sensors.SensorWorker } ]
2021-03-05 15:29:41.675 1572-1794/? D/ConnectivityService: releasing NetworkRequest [ TRACK_DEFAULT id=9686, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 11719 AdministratorUids: [] RequestorUid: 11719 RequestorPackageName: io.homeassistant.companion.android] ] (release request)
2021-03-05 15:29:46.885 1572-1794/? D/ConnectivityService: releasing NetworkRequest [ TRACK_DEFAULT id=9607, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 11719 AdministratorUids: [] RequestorUid: 11719 RequestorPackageName: io.homeassistant.companion.android] ] (release request)
```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2021-03-05 16:28
This might be caused by https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt#L731 as we are explicitly closing the activity to prevent access to the HA frontend.  Will need to see if removing this allows the user to retry again.  I know that the android system has an internal lockout feature if too many attempts are made.

**Closed** 2021-03-08 13:57 UTC
Labels: bug, webview
