### ISSUE TITLE
Light theme button not working on galaxy s20+

### ISSUE THREAD

**Issue by ivanpilev** [home-assistant/android#779] opened 2020-08-16 19:44 UTC
**Home Assistant Android version:**
2.2.0-269-full
**Android version:**
10
**Phone model:**
galaxy s20+(SM-G986F)
**Home Assistant version:**
0.114
**Last working Home Assistant release (if known):**
The one before this one 
**Description of problem:**
Light theme button not working. Basically it's the same as auto. There is no light theme if the phone is set to dark mode(theme). If the phone is on light mode (theme) dark theme is working fine. The "dark auto theme" is not the same as dark theme since a lot of the highlights are missing. 
**Traceback (if applicable):**

```

```

**Screenshot of problem:**
https://photos.app.goo.gl/6h2HvhFbMn618SSbA
**Additional information:**

**Comment by dshokouhi** [comment] 2020-08-16 19:55
duplicate of #773

**Closed by dshokouhi** 2020-08-16 19:55 UTC
Labels: bug
