### ISSUE TITLE
Android App starts extremly slow

### ISSUE THREAD

**Issue by vbueschken** [home-assistant/android#4145] opened 2024-01-20 10:30 UTC
**Android version(s):**
Android 14
**Device model(s):**
Samsung A54
**Home Assistant version:**
Home Assistant: 2024.103
Android App: 2023.12.4-full
**Last working Home Assistant release (if known):**
nit sure
**Description of problem, include YAML if issue is related to notifications:**

The Android starts extrem slowly. it take also a long time to load dashboards ..
After stopping the app and deleting the cache, everything works fine.
After a couple of days, the same problem starts again.

**Comment by jpelgrom** [comment] 2024-01-20 10:37
Duplicate of #3396

**Closed by jpelgrom** 2024-01-20 10:37 UTC
Labels: bug
