### ISSUE TITLE
Alarm sensor - wrong value

### ISSUE THREAD

**Issue by andrewjswan** [home-assistant/android#1211] opened 2020-11-23 08:58 UTC
**Home Assistant Android version:** 3.0.2-full

**Android version:** 10

**Phone model:** Xiaomi Mi 9Lite

**Home Assistant version:** 0.118.2

**Last working Home Assistant release (if known):** - 

**Description of problem:** Wrong time in Alarm sensor

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

https://i.piccy.info/i9/c1fe83a8e48c0293418a16ec74a7caa8/1606121337/26270/1406613/63097Screenshot_2020_11_23_10_50_27_893_io_homeassistant_companion_android_800.jpg

https://i.piccy.info/i9/db9cf9885e21e40331306613d82b697d/1606121382/21401/1406613/Screenshot_2020_11_23_10_50_40_937_com_android_deskclock_800.jpg

**Additional information:**

On screenshot Alarm time - 00:00:00 but in my phone first alarm 06:00

**Comment by dshokouhi** [comment] 2020-11-23 15:27
Duplicate of #1190 and #1085 xiaomi is known to send these invalid values for the alarm api. You will need to use an app like google clock app that reports valid times.

https://github.com/home-assistant/android/issues/1190#issuecomment-726838788

**Closed by dshokouhi** 2020-11-23 15:28 UTC
Labels: bug

**Comment by andrewjswan** [comment] 2020-11-23 15:36
@dshokouhi my phone use com.android.deskclock bu HA Android app get value from com.xiaomi.calendar - its wrong.

**Comment by dshokouhi** [comment] 2020-11-23 15:40
@andrewjswan then you need to make use of the Next Alarm sensor setting found in App configuration and set an allow list.  Xiaomi apps are known for this incorrect behavior.

**Comment by dshokouhi** [comment] 2020-11-23 15:41
also `com.android.deskclock` is not the google clock app, so that app will also return incorrect time, you need to use: https://play.google.com/store/apps/details?id=com.google.android.deskclock

which is the actual google clock app.

**Comment by andrewjswan** [comment] 2020-11-23 17:06
I add to allow list deskclock but not have value :(

пн, 23 нояб. 2020 г., 17:40 Daniel Shokouhi <notifications@github.com>:

**Comment by andrewjswan** [comment] 2020-11-23 17:09
I wait 3 days, no update :(

**Comment by dshokouhi** [comment] 2020-11-23 17:13
You need to understand that it waits for literally the next scheduled alarm set by the app in the allow list.  It really depends on how many apps on your device are setting alarms for this sensor to work.  There is not much we can do asides from these recommendations.  If it keeps picking up your calendar events then you will want to consider using a different calendar app that does not abuse the Next Alarm API.  Google Calendar does not interfere with this API.  Unfortunately a lot of apps and manufacturers like to abuse it.
