### ISSUE TITLE
WorkManager jobs are continuously running in the foreground leading battery drain and increased temps

### ISSUE THREAD

**Issue by vad710** [home-assistant/android#1983] opened 2021-12-01 21:35 UTC
**Home Assistant Android version:**
2021.10.0-full (versionCode=761)

**Android version:**
12

**Phone model:**
Pixel 6 Pro

**Home Assistant version:**

**Description of problem:**
There seems to be a bug causing WorkManager requests to be scheduled and cancelled very quickly in a short period of time. Particularly requests that are likely using `setForegroundAsync` causing a foreground service to run consuming more battery and/or causing heat. I do not have specific steps to reproduce, but some of the reviews in the play-store are mentioning heavy background usage which is likely related.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

Please feel free to reach out to me directly to review some private logs.

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2021-12-01 22:06
> Particularly requests that are likely using `setForegroundAsync` causing a foreground service to run consuming more battery and/or causing heat.

we are not using `setForegroundAsync` but just `setForeground` 

https://github.com/home-assistant/android/blob/master/common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorWorkerBase.kt#L48



> but some of the reviews in the play-store are mentioning heavy background usage which is likely related.

more than likely those users have enabled all sensors including BLE transmitter without realizing how much battery is being used by the transmitter. Without a bug report and proper logs we can only guess what the issue is. If a user for example enables Last Notification without an allow list then yes they will experience heavy battery drain and an icon that appears to be visible at all times.

We can only continue with this report if we get proper debug logs, also what troubleshooting steps have you tried? Have you tried starting fresh? https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by dshokouhi** [comment] 2021-12-01 22:07
For the record I have every sensor enabled with sane defaults for an allow list and I experience no battery drain or high battery temperature. I am on a Pixel 6 Pro latest beta version.

**Comment by vad710** [comment] 2021-12-22 18:10
Thanks for the detailed follow up @dshokouhi!
>If a user for example enables Last Notification without an allow list then yes they will experience heavy battery drain and an icon that appears to be visible at all times.

Any thoughts of changing the defaults to be a bit more conservative when it comes to power drain? potentially guide the user to select sensors or to turn off invisible sensors by default?

I am still looking into getting you a log.

Thank you!

**Comment by dshokouhi** [comment] 2021-12-22 18:11
> Any thoughts of changing the defaults to be a bit more conservative when it comes to power drain? potentially guide the user to select sensors or to turn off invisible sensors by default?

Thats the aim for these 2 PRs actually :)

#2037 and #2038

**Comment by dshokouhi** [comment] 2022-01-12 03:55
Closing this issue now as this should be fixed now that the above 2 PRs are merged and released.

**Closed by dshokouhi** 2022-01-12 03:55 UTC
Labels: bug, sensor-tracking

**Comment by vad710** [comment] 2022-01-12 21:18
Thanks @dshokouhi ,
When you have a chance, could you please ping me at first.last@ gee mail dot com ? (name info here: https://github.com/vad710)

Thank you!
