### ISSUE TITLE
Incorrect scaling compared to mobile browsers

### ISSUE THREAD

**Issue by CM000n** [home-assistant/android#638] opened 2020-06-22 18:02 UTC
**Home Assistant Android version:**
Version 1.9.0-167

**Android version:**
Android 10 (V2.340)

**Phone model:**
Nokia 7.2

**Home Assistant version:**
0.111.4

**Description of problem:**

**Traceback (if applicable):**
Hi everyone, I have reworked the last days with Lovelace frontend using the Button Card in combination with Dbuits Homekit Panel Card. I am quite satisfied with the result.
However, I noticed that when using the Android App my Button Card tiles are only displayed in two columns:
<img src="https://user-images.githubusercontent.com/7945681/85320363-3dff8600-b4c3-11ea-850e-d861d7081829.png" width="250">

On the same device they are displayed in three columns in Mobile Chrome or Edge:
<img src="https://user-images.githubusercontent.com/7945681/85320380-435cd080-b4c3-11ea-89d4-219ccf725efd.jpeg" width="250">

What could be the reason for this, and how could we use a three-column layout in the Mobile App as well?
I have a Nokia 7.2 with 6.3 inch and 2240 x 1080 pixel resolution. My girlfriend has a Xiaomi Mi A3 with 6.1 inch and a resolution of 720 x 1,560 pixels.  **System Webview is version 83.0.4103.106** on both devices . The behaviour is the same on both devices with the official Home Assistant app. Compared to browsers, the screen size is not fully utilized or does not scale properly.

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2020-07-05 00:29
Duplicate of #276

**Closed by dshokouhi** 2020-07-05 00:29 UTC
Labels: bug, webview
