### ISSUE TITLE
Multiple server support 

### ISSUE THREAD

**Issue by Nornode** [home-assistant/android#565] opened 2020-04-21 17:03 UTC
**Is your feature request related to a problem? Please describe.**
I'm frustrated that I can't use one app for two homeassistant deployments(servers). 

**Describe the solution you'd like**
Please support multiple home assistant servers in one app and make it easy to switch in-between them.

**Describe alternatives you've considered, if any**
Parallel app space but homeassistant app isn't supported. 

**Additional context**
I know it might be an edge case to be able to support two servers but you could also use it for testing two versions of home assistant and so on. 
I got one homeassistant at home one homeassistant at the cottage... 
Using Android.

**Comment by dshokouhi** [comment] 2020-04-21 17:16
Duplicate of #296 in the meantime until things change you can create a separate profile on your android device so you can login to another instance.

**Closed by dshokouhi** 2020-04-21 17:16 UTC
Labels: enhancement
