### ISSUE TITLE
Does this app has hard coded dependencies on google services?

### ISSUE THREAD

**Issue by rradar** [home-assistant/android#599] opened 2020-05-19 22:31 UTC
**Home Assistant Android version:**
1.8.0

**Android version:**
8.1

**Phone model:**
Samsung S7

**Home Assistant version:**
0.109

**Last working Home Assistant release (if known):**
-

**Description of problem:**
Is their any known/wanted hard coded dependencies of google services? 

I having trouble to get this app running in my phone (check #558 for details).

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/34582688/82384693-4aa63f80-9a28-11ea-897e-a45cd181a91c.png)

**Additional information:**
I installed [HA Client](https://github.com/estevez-dev/ha_client) on the same phone on the other hand it worked immediately without problems

**Comment by dshokouhi** [comment] 2020-05-19 22:38
This app requires google play services to work:

https://companion.home-assistant.io/docs/getting_started/getting-started

Closing as duplicate of #358 #231

**Closed by dshokouhi** 2020-05-19 22:38 UTC
Labels: bug

**Comment by rradar** [comment] 2020-05-19 22:39
What a shame :cry:

**Comment by JonnyHaystack** [comment] 2020-05-25 10:40
Yes, this is most disappointing :disappointed: this really goes against the spirit of Home Assistant imo. I went to the effort of using Home Assistant and other open-source solutions for home automation and avoided any cloud-based/proprietary products, and yet we are expected to install Google's proprietary rootkit on our phones? Why was it done this way?

**Comment by balloob** [comment] 2020-05-25 18:05
Have a look at the other issues for your answer.
