### ISSUE TITLE
iBeacons stops transmitting or patchy transmission

### ISSUE THREAD

**Issue by Mikescotland** [home-assistant/android#4204] opened 2024-02-15 03:52 UTC
**Home Assistant Android app version(s):**

**Android version(s):**
Android 11
Android 12
**Device model(s):**
Huawei Mate x20 5G
Oppo Find x2 Neo 5G

**Home Assistant version:**
2024.2.1
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
Android App stops randomly sending iBeacon, despite "Transmitting" status. Very laggy, takes 2 minutes for espresence to register beacon after turning on. Installed BeaconScope based on Android Beacon Library and works very well with same settings (1Hz, Low Power) and it's being discovered by espresence and HA in 1-2 seconds after turning on. 
I can see from issues many people have/ had same problem and it has not been resolved 

**Companion App Logs:**
Absolutely nothing in the logs regarding BLE . the only thing is
AwareLog: DynBufManager: endFling hash null
```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2024-02-15 03:53
Duplicate of #3159

**Closed** 2024-02-15 03:53 UTC
Labels: bug
