### ISSUE TITLE
Home Assistant app crashes One UI

### ISSUE THREAD

**Issue by EmilZackrisson** [home-assistant/android#2286] opened 2022-02-15 00:06 UTC
I got my new S22 Ultra today and I tried the new Device Control in the drop down menu. But when I tried to click on a device från home assistant the whole phone hangs and stops working. The only way to get back to the homescreen is to reboot the phone.

**Comment by dshokouhi** [comment] 2022-02-15 00:09
Hi thanks for the issue, this issue seems to be missing the template that gets presented when a new issue is created. It contains important information like what device and app version is used among other thing. We would need all the requested information from there, if you could create a new issue and copy the template and fill that in here that would be great. 

Also did you just click on an item in device controls or long press an item here?

possible duplicate of #2251

**Comment by dshokouhi** [comment] 2022-02-15 17:58
duplicate of #2287

**Closed by dshokouhi** 2022-02-15 17:58 UTC
Labels: bug
