### ISSUE TITLE
"alarm_stream" on Pixel 4XL behave like a just regular notification

### ISSUE THREAD

**Issue by expend20** [home-assistant/android#1427] opened 2021-03-11 14:34 UTC
**Home Assistant Android version:**

2021.3.1-full

**Android version:**

11, last update 5 of March

**Phone model:**

Pixel 4 XL - buggy / Pixel 3a XL - not buggy

**Home Assistant version:**

core-2021.3.1

**Last working Home Assistant release (if known):**

**Description of problem:**

Hello! First of all thank you for an amazing job you've done, I really enjoy HA and HA Android app everyday in my regular life.

But I've encountered a small issue, which might be a bug. I have two Pixels in my house hold: 3a XL and 4 XL. I leverage [critical notification feature](https://companion.home-assistant.io/docs/notifications/critical-notifications/) for my urgent notifications which supposed to even wake me at night. For example next script is used to **ring my 3a XL until I stop it**.

```
service: notify.mobile_app_pixel_3a_xl
data:
  title: "Wake up!"
  message: "The house is on fire and the cat's stuck in the dryer!"
  data:
    ttl: 0
    priority: high
    channel: alarm_stream
```

And it works perfectly fine for 3a XL. 
However for 4XL the same script is **only making regular notification in the status bar without making my phone ring**

```
service: notify.mobile_app_pixel_4_xl
data:
  title: "Wake up!"
  message: "The house is on fire and the cat's stuck in the dryer!"
  data:
    ttl: 0
    priority: high
    channel: alarm_stream
```

This is a real bummer to me. Is there anything I can do about it? 

Thanks in advance!

**Comment by dshokouhi** [comment] 2021-03-11 14:36
What is the volume level of the alarm stream?

**Comment by expend20** [comment] 2021-03-11 14:39
> What is the volume level of the alarm stream?

You mean this one? 
![image](https://user-images.githubusercontent.com/36543551/110803871-53525580-8288-11eb-8699-a3cd49e4caa5.png)

**Comment by expend20** [comment] 2021-03-11 14:49
Alarm volume adjuster in android works indeed for the "channel: alarm_stream" message, if it's higher the notification sounds higher. But it's really a notification sound, not an alarm one which is invoked by the Clock android native app for example). 
I assume the bug might be when HA app invokes an alarm, confusing notification with an alarm, could that be possible?

**Comment by dshokouhi** [comment] 2021-03-11 14:50
Cam you check if there is a default alarm ringtone set? Also we will need the device logs that include the notification message data. The link in the template can you help you get us that data.

**Comment by dshokouhi** [comment] 2021-03-11 15:02
Also are you saying the notification sound is coming from the alarm stream itself?

**Comment by expend20** [comment] 2021-03-11 15:06
> Cam you check if there is a default alarm ringtone set?

Yep, it is set:
![image](https://user-images.githubusercontent.com/36543551/110807709-ff497000-828b-11eb-8e81-37ff981596f0.png)

> Also we will need the device logs that include the notification message data.
Give me some time, I'm trying... :)

> Also are you saying the notification sound is coming from the alarm stream itself?
Yep, I think it is exactly the problem

**Comment by expend20** [comment] 2021-03-11 15:36
> Give me some time, I'm trying... :)

Actually I didn't find the way to see the logs. I installed Logcat Reader, started it, gave it permission with adb `adb shell pm grant com.dp.logcatapp android.permission.READ_LOGS` and whey I send the notification I can't see anything related to homeassistant. Any hints? Ty

**Comment by dshokouhi** [comment] 2021-03-11 15:42
> Yep, I think it is exactly the problem

actually this is not a bug or an issue.  The reason why you see this is because for whatever reason your device is reporting the default alarm ringtone as your notification ringtone, unless of course you accidentally changed the channel settings becuase once changed it can't be changed back.

https://github.com/home-assistant/android/blob/6109ce466ca06c121bfb324d41960918733557ae/app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt#L1026

Here you can see we request the ringtone of type alarm and if your device gives us a different ringtone and it still comes out the alarm stream then the feature is working as intended.  Have you tried clearing data in the app to see if that corrects the issue?

> and whey I send the notification I can't see anything related to homeassistant. Any hints? Ty

First search by: `MessagingService` find the date/time of the notification data, then follow the timestamp.  You can't do a broad search here.  But honestly its working if you hear a sound come out of hte alarm stream, your device is just reporting the wrong one to the app and we can't cahnge that because we request the alarm one specfically.

As  you have confirmed the sound comes out of the alarm stream I am goinig to close this issue now, the default sound is out of our control here.  Especially if its an actual sound clip being played through the alarm stream.

Feel free to comment back with the logs so maybe we can help you troubleshoot why your device is doing this.

**Closed by dshokouhi** 2021-03-11 15:42 UTC
Labels: bug

**Comment by expend20** [comment] 2021-03-11 16:41
Hellyeah, you made it! 
The problem disappeared after clearing cache/data of the app. Thank you @dshokouhi for extremely fast and thorough answers! The root of the behavior might be related to backup/restore procedure which the device was undergone recently. Keywords for search: backup, cloud, google drive

**Comment by dshokouhi** [comment] 2021-03-11 16:47
simple solutions are always the best :), thanks for reporting!
