### ISSUE TITLE
Time input component lets dissapear keyboard after first digit input

### ISSUE THREAD

**Issue by liquidacid** [home-assistant/android#2399] opened 2022-03-24 09:45 UTC
**Home Assistant Android version:**
2022.3.0-full

**Android version:**
11

**Phone model:**
Samsung Galaxy S10

**Home Assistant version:**
2022.3.7

**Last working Home Assistant release (if known):**
Before the UI update

**Description of problem:**
If in the app i try to change a Time helper the keyboard disappears as soon as i put in the first digit. When i for example want to change the input to 13:14 i have to click the hour input twice to first put in a 1 and then a 3, also for the minutes this behaviour is there.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
A screenshot is hard to make i think. If you cannot reproduce this issue i can make a screencapture if needed.

**Additional information:**

**Comment by dshokouhi** [comment] 2022-03-24 11:47
Does this issue exist in chrome for Android on the same device?

**Comment by liquidacid** [comment] 2022-03-24 12:14
No, this only happens in the app, if i do the same thing in Chrome on Android it works perfectly.

**Comment by dshokouhi** [comment] 2022-03-24 14:33
duplicate of https://github.com/home-assistant/frontend/issues/11945

**Closed by dshokouhi** 2022-03-24 14:33 UTC
Labels: bug

**Comment by liquidacid** [comment] 2022-03-24 15:05
hmm i only see this behaviour in the app so i'd put it here. On browsers it works fine

**Comment by nikipore** [comment] 2022-03-27 08:07
Just because you don't see in in the Android version of Chrome it doesn't mean it works fine "in browsers" per se. I found [home-assistant/frontend#11945](https://github.com/home-assistant/frontend/issues/11945) using Chrome on Mac. It is also there in Safari on Mac and in the iOS app.
