### ISSUE TITLE
Last notification sensor doesn't handle grouped notifications well

### ISSUE THREAD

**Issue by cryptk** [home-assistant/android#4585] opened 2024-08-16 20:11 UTC
**Home Assistant Android app version(s):**

**Android version(s):**
14

**Device model(s):**
Pixel 7 Pro

**Home Assistant version:**
2024.8.1

**Last working Home Assistant release (if known):**
unknoen

**Description of problem, include YAML if issue is related to notifications:**
The Last Notification sensor seems to work great for individual notifications, but if an app sends a second notification and Android groups them together, then the sensor appears to report data about the notification group rather than the newly added notification. This makes it difficult to automate things based on incoming notifications as you need to ensure to always dismiss a notification before another arrives.

Here is a mildly redacted (removing real names, etc) payload of the sensor as seen within NodeRed (so it's JSON rather than Yaml)

```json
{
    "payload": "net.smarttag.parentapp",
    "data": {
        "entity_id": "sensor.<REDACTED>_pixel_7_pro_last_notification",
        "old_state": {
            "entity_id": "sensor.<REDACTED>_pixel_7_pro_last_notification",
            "state": "<REDACTED> loaded bus 060",
            "attributes": {
                "android.appInfo": "ApplicationInfo{7822416 net.smarttag.parentapp}",
                "android.bigText": "<REDACTED> loaded bus <REDACTED>",
                "android.infoText": "null",
                "android.largeIcon": "null",
                "android.progress": 0,
                "android.progressIndeterminate": false,
                "android.progressMax": 0,
                "android.reduced.images": true,
                "android.remoteInputHistory": "null",
                "android.showChronometer": false,
                "android.showWhen": true,
                "android.subText": "null",
                "android.template": "android.app.Notification$BigTextStyle",
                "android.text": "<REDACTED> loaded bus <REDACTED>",
                "android.title": "LOADED: <REDACTED> was picked up",
                "androidx.core.app.extra.COMPAT_TEMPLATE": "androidx.core.app.NotificationCompat$BigTextStyle",
                "category": "null",
                "channel_id": "fcm_fallback_notification_channel",
                "group_id": "null",
                "is_clearable": true,
                "is_ongoing": false,
                "package": "net.smarttag.parentapp",
                "post_time": 1723837062699,
                "icon": "mdi:bell-ring",
                "friendly_name": "<REDACTED>' Pixel 7 Pro Last notification"
            },
            "last_changed": "2024-08-16T19:37:50.998323+00:00",
            "last_reported": "2024-08-16T19:37:50.998323+00:00",
            "last_updated": "2024-08-16T19:37:50.998323+00:00",
            "context": {
                "id": "01J5EB4FMP6558CGN39650Y6H8",
                "parent_id": null,
                "user_id": null
            }
        },
        "new_state": {
            "entity_id": "sensor.<REDACTED>_pixel_7_pro_last_notification",
            "state": "net.smarttag.parentapp",
            "attributes": {
                "android.appInfo": "ApplicationInfo{7cf8a62 net.smarttag.parentapp}",
                "android.reduced.images": true,
                "category": "null",
                "channel_id": "fcm_fallback_notification_channel",
                "group_id": "ranker_group",
                "is_clearable": true,
                "is_ongoing": false,
                "package": "net.smarttag.parentapp",
                "post_time": 1723837871656,
                "icon": "mdi:bell-ring",
                "friendly_name": "<REDACTED>' Pixel 7 Pro Last notification"
            },
            "last_changed": "2024-08-16T19:51:21.616645+00:00",
            "last_reported": "2024-08-16T19:51:21.616645+00:00",
            "last_updated": "2024-08-16T19:51:21.616645+00:00",
            "context": {
                "id": "01J5EBX78GMM4SSSYT9P2BW2EH",
                "parent_id": null,
                "user_id": null
            },
            "timeSinceChangedMs": 5
        }
    },
    "topic": "sensor.<REDACTED>_pixel_7_pro_last_notification",
    "child": "net.smarttag.parentapp",
    "_msgid": "4b8c185bde0ee366"
}
```

Hopefully you can see that the "old_state" has the full notification data but the "new_state" only has information about the newly created grouped notification rather than the new notification that was grouped with the original one. Ideally what would be sent is the data about the second notification (which is mostly the same as the first one, just for my other child) rather than the notification group.  Alternatively, if the grouped notification data included data about all of the notifications within it, that could work, but I think the former would be preferred.

**Companion App Logs:**

N/A

**Screenshot or video of problem:**

N/A

**Additional information:**

**Comment by dshokouhi** [comment] 2024-08-16 20:14
duplicate of https://github.com/home-assistant/android/issues/3364

the sensor reports the last received notification which in this case is the grouped notification that indeed does not have all data

in the meantime the active notification count sensor will contain the required data

**Closed by dshokouhi** 2024-08-16 20:14 UTC
Labels: bug

**Comment by cryptk** [comment] 2024-08-16 20:22
Apologies, I looked through at least 6 different issues trying to find a workaround or solution and somehow I missed that one.
