### ISSUE TITLE
Seperate/ exclude calender from next_alarm sensor 

### ISSUE THREAD

**Issue by maltemosler** [home-assistant/android#1207] opened 2020-11-20 10:00 UTC
**Is your feature request related to a problem? Please describe.**
I am using the next_alarm sensor to synchronize my android alarm clock with my smart home to automatically start heating, turning the covers up,simulating sunrise and stuff like that. 

The problem is that the next_alarm sensor also includes all entrys of my calender. 
That means if I have a entry like meeting at 17:00 or even someones birthday the automation triggers and my waking up scene turns on. 

I  litterally shit myself because the covers turned in the evening up 

**Describe the solution you'd like**
Split the next_alarm sensor into 2 sensors like:
-     next_alarm
-     next_calendar_alarm

This solution could break some users automations if they use the next_alarm with calenders but I think that would be the best solution

**Describe alternatives you've considered, if any**
An alternative would be to give the user the rights to change the alarm source. 
This shouldn't break any automations

**Additional context**
Don't know if this Information is neccessary and this behaviour is based on my Phone but I am using an Samsung Galaxy M31 with Android 10

**Comment by dshokouhi** [comment] 2020-11-20 14:50
Duplicate of #1190 and #1085 

You need to use an app that makes good use of the API

https://github.com/home-assistant/android/issues/1190#issuecomment-726838788

**Closed by dshokouhi** 2020-11-20 14:50 UTC
Labels: enhancement
