### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by Wojciechgc** [home-assistant/android#3430] opened 2023-03-20 11:47 UTC
**Describe the solution you'd like**
Could you make it possible to connect to multiple Home Assistant instances in the app? I know it's possible on iOS, it would be very useful to see this feature implemented on Android.

**Describe alternatives you've considered, if any**
I have tried using dual messenger apps to duplicate the companion app but some display ads when opening the duplicated Home Assistant and work poorly, where some don't work with Home Assistant at all.

**Comment by jpelgrom** [comment] 2023-03-20 11:56
Duplicate of #296

This is currently in beta, [join the beta channel](https://play.google.com/apps/testing/io.homeassistant.companion.android) or wait a little longer for a stable release :)

**Closed** 2023-03-20 11:56 UTC
Labels: enhancement
