### ISSUE TITLE
Add support for Android 13 lock screen controls without unlocking the phone

### ISSUE THREAD

**Issue by fortinj1354** [home-assistant/android#2810] opened 2022-08-21 05:55 UTC
**Is your feature request related to a problem? Please describe.**
Android 12 changed the Quick Access Device Controls feature on the lock screen to require unlocking the phone for any state changes. 

**Describe the solution you'd like**
Android 13 has now added a new property, isAuthRequired, to allow specific controls to be interacted with while the phone is still locked. The app should add the ability for users to mark specific entities as not requiring auth so they can be used from the lock screen.

**Describe alternatives you've considered, if any**
There's not really alternatives other than the current state, which requires unlocking the phone for any device controls.

**Additional context**
https://developer.android.com/reference/android/service/controls/Control#isAuthRequired()
https://blog.esper.io/android-13-deep-dive/#control_without_auth

**Comment by fortinj1354** [comment] 2022-08-21 05:57
Sorry in advance if this is a dupe, I didn't see any existing issues/PRs that matched and couldn't find any references in the code to this feature (especially since Android 13 just went stable last week).

**Comment by dshokouhi** [comment] 2022-08-21 06:16
Duplicate of #2381

**Closed by dshokouhi** 2022-08-21 06:16 UTC
Labels: enhancement
