### ISSUE TITLE
External Home Assistant URL is limited to host:port and doesn't allow to provide path

### ISSUE THREAD

**Issue by mkowalczuk** [home-assistant/android#3041] opened 2022-11-04 23:30 UTC
**Home Assistant Android version:**
beta-2862-66bc2603-full

**Android version:**
12

**Phone model:**
OnePlus 9 Pro

**Home Assistant version:**
2022.10.5

**Last working Home Assistant release (if known):**
N/A

**Description of problem:**
External Home Assistant URL is limited to host:port and doesn't allow to provide path of the HA installation.
For example if I set the external HA URL to:
`https://example.com/homeassistant/`
it gets trimmed to:
`https://example.com/`
It's limiting flexibility of HA installation on the web server or possibility to use a "secret" URL, e.g. that skips additional OAuth2 authentication normally required when accessing the HA server using `/` path. 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
N/A

**Screenshot of problem:**
N/A

**Additional information:**
N/A

**Comment by dshokouhi** [comment] 2022-11-04 23:33
Looks to be a duplicate of #1651 ?

**Closed** 2022-11-05 12:27 UTC
Labels: bug
