### ISSUE TITLE
phone_last_notification Sensor recorder error

### ISSUE THREAD

**Issue by tiaanv** [home-assistant/android#1275] opened 2021-01-04 09:13 UTC
I'm not 100% sure this issue belongs to the Android app.  It could be very specific to my environment, or it could be an issue that needs to be addressed in recorder.

When logging the **phone_last_notification** sensor to the MySQL DB through recorder, the state value has some hex char values in it (not sure why) for som notifications.  When the insert statement in recorder executes, it fails due to the hex vals/chars being deemed invalid/illegal.

Andoid App Version: 3.0.2-full
HA version: 2020.12.7

```
Logger: homeassistant.components.recorder
Source: components/recorder/__init__.py:465
Integration: Recorder (documentation, issues)
First occurred: 9:16:38 (66 occurrences)
Last logged: 11:01:33

Error in database connectivity during commit: (MySQLdb._exceptions.OperationalError) (1366, "Incorrect string value: '\\xF0\\x9F\\x91\\x8D\\xF0\\x9F...' for column `homeassistant`.`states`.`state` at row 1") [SQL: INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created, old_state_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)] [parameters: ('sensor', 'sensor.tiaan_phone_last_notification', '👍🏻', '{"android.appInfo": "ApplicationInfo{94be48d com.whatsapp}", "android.infoText": "null", "android.largeIcon": "null", "android.people.list": "[androi ... (305 characters truncated) ... d83c\\udffb", "android.title": "Jaco Waterson", "package": "com.whatsapp", "friendly_name": "Tiaan-Phone Last Notification", "icon": "mdi:bell-ring"}', 291366756, datetime.datetime(2021, 1, 4, 7, 16, 37, 916674, tzinfo=datetime.timezone.utc), datetime.datetime(2021, 1, 4, 7, 16, 37, 916674, tzinfo=datetime.timezone.utc), datetime.datetime(2021, 1, 4, 7, 16, 37, 916674, tzinfo=datetime.timezone.utc), 263029172)] (Background on this error at: http://sqlalche.me/e/13/e3q8). (retrying in 3 seconds)
```

**Comment by dshokouhi** [comment] 2021-01-04 16:11
Duplicate of #1024 to solve this please follow https://github.com/home-assistant/android/issues/1204#issuecomment-740214468

**Closed by dshokouhi** 2021-01-04 16:11 UTC
