### ISSUE TITLE
WearOS - Selecting entity to use in complication needs to be faster

### ISSUE THREAD

**Issue by sepodele** [home-assistant/android#2688] opened 2022-07-18 07:36 UTC
**Is your feature request related to a problem? Please describe.**

The new WearOS complication feature is awesome but when I change between watch faces I have to reselect what entities I want to use in the complication. When you have 1000 entities, scrolling through the list takes forever.

**Describe the solution you'd like**

1. Groups (Automations, Binary Sensor, Buttons, etc.) should be collapsed, not expanded by default.
2. Favorites set in the companion app are not shown here. It should be and it should be a group itself sorted before the other groups.
3. A search option to find the entity you need fast.

**Comment by Vedeneb** [comment] 2022-07-20 17:18
Can confirm this, for me it's even worse: I can't select any entity because the app just freezes after loading the list of entities. After 30 seconds or so the app finally crashes. Currently in the cleanup process of my home assistant instance with more than 1000 entities as well :)

**Comment by dshokouhi** [comment] 2022-07-21 17:58
> After 30 seconds or so the app finally crashes.

Can you please open a new issue and get us the crash logs from this experience? We should not be crashing the app.

**Comment by sygys** [comment] 2022-08-02 13:06
The wear part of the app is crashing and lagging all the time for me. no matter what i do. its due to the large amount of entities i have. They can never be loaded all into the watch. it tries to load the entities and after some time it crashes back to the main menu on my galaxy watch 4. the approach here in the wear app is all wrong. it tries to load all entities from home assistant. In my case this means it tries to load 2800 entities and show them in a list. this is never going to work on a watch. 

we need to either being able to select entities in the browser or in the phone app that will be shown in the wear app. or it shouldnt load all the entities but only a part of the, or hell maybe make a search function in which you send a search request to home assistant on the phone to give only a select few results in a list on the watch. this wear app is fun if you are a beginning user with 100 entities but its plain useless when you have people like me with their whole home automated.

**Comment by dshokouhi** [comment] 2022-08-02 17:16
> The wear part of the app is crashing and lagging all the time for me. no matter what i do. its due to the large amount of entities i have. They can never be loaded all into the watch. it tries to load the entities and after some time it crashes back to the main menu on my galaxy watch 4. the approach here in the wear app is all wrong. it tries to load all entities from home assistant. In my case this means it tries to load 2800 entities and show them in a list. this is never going to work on a watch.

Please get us the logs so we can see the cause of the crash, there are other users who also have a high amount of entities and the selection of entities loads fine for them. Also that is a bug and not a feature request so it should be filed separately with the requested information.  You will need to access logcat from the watch to do this.



> we need to either being able to select entities in the browser or in the phone app that will be shown in the wear app.

This is a separate feature request to be able to select from the phone, if possible as complications are a bit different.



> or it shouldnt load all the entities but only a part of them, or hell maybe make a search function in which you send a search request to home assistant on the phone to give only a select few results in a list on the watch.

We dont know if the cause is too many entities yet as we need to see a crash log, so lets not assume that is the cause until we see the logs.  This request is about adding a search feature ;)



> this wear app is fun if you are a beginning user with 100 entities but its plain useless when you have people like me with their whole home automated.

I have a pretty robust setup with over 1600 entities and its not useless to me and many others. Lets be mindful that everyone contributing to the Wear OS app is a volunteer doing so on their own time.



> I guess the best approach here would be to being able to select entities that you want to show on your watch and leave the rest be. so maybe a settingspage where you can search and add entities in the browser that will be active and loaded on the watch. This will fix allot of the lag problems and crashes.

I think the suggestion to show favorite entities first will help a lot here. I am sure the favorite entities selected for the home screen will be desireable entities in other locations.  You can already select favorite entities from the phone so that is a bit faster.



> I understand this is a very early alpha version. But who in the name came up with the idea to load all entities like this via a Bluetooth connection on a smartwatch

Lets try to be nice to our volunteers please, there is no reason to make anyone feel bad because you disagree with the approach. Our contributors have dedicated many free hours of their own time to provide features for others to enjoy. We need to see the logs to see the cause of the failure.

**Comment by sygys** [comment] 2022-08-11 08:20
I'll be nice next time. But I can't believe that there are people with 2800 entities that do not have this problem... I will post a log if I can find how. For now here is the problem I have with selecting an entity. This happens with both the widget as the watchface. This is exactly what the post starter means I guess. Normally it's terrible slow bit with over 2800 entities I guess the memory on the watch isn't sufficient. It shouldn't load all entities but instead give a search bar after the phone app should do the work and just send the search results back to the watch. Or make an option to being able to typ the entity manually. 

https://youtu.be/MAEtD3F2PhI

**Comment by leroyboerefijn** [comment] 2022-08-16 05:29
In your video you see that the loading of entities is actually quite quick (the moment the button stops showing loading is the moment when all entities are loaded). So no problem in the decision to load all entities I would say.

I do agree that it looks extremely slow on your watch. So the problem is most likely displaying so much at the same time. For this, the current feature request might help! We can also have another look to see if we can optimize anything else in the rendering (Compose).

**Comment by dshokouhi** [comment] 2022-09-06 02:56
Now that #2804 has been merged we are going to close this issue. For the search feature please create a new feature request for that as those changes are a bit more involved. Selecting an entity should be faster now with the changes already done.

**Closed by dshokouhi** 2022-09-06 02:56 UTC
Labels: enhancement, Wear OS
