### ISSUE TITLE
Android app lags after several days of use, clear cache solves the problem

### ISSUE THREAD

**Issue by gitlaman** [home-assistant/android#3916] opened 2023-10-05 07:48 UTC
As the title says, the app lags after several days of using with lots of notifications. 

First i thought that auto restart the Home assistant will solve the problem but id does not, i started using auto cache cleaner on daily basis and now the app is working correctly.

After several days the app lags to the point that sometimes refuses to connect to the server, after cleaning the cache it works and responds quickly, i tried on Samsung Note 9 and Samsung S22 Ultra.

If it is possible please add auto cache cleaner as option.

Thanks

**Comment by dshokouhi** [comment] 2023-10-05 13:39
Duplicate of https://github.com/home-assistant/android/issues/3396

**Closed by dshokouhi** 2023-10-05 13:39 UTC
Labels: bug

**Comment by jpelgrom** [comment] 2023-10-05 14:10
(clear cache force stops the app, which is why it is a duplicate and not a fix)
