### ISSUE TITLE
Certain Android App sensors not reporting state_class

### ISSUE THREAD

**Issue by illuzn** [home-assistant/android#4045] opened 2023-12-11 13:07 UTC
**Home Assistant Android app version(s):** 2023.10.2-full

**Android version(s):** 13

**Device model(s):** Xiaomi Mix Fold 2

**Home Assistant version:** 2023.12.0

**Last working Home Assistant release (if known):** N/A

**Description of problem, include YAML if issue is related to notifications:** The sensors in the app which report battery_level, battery_temperature and battery_power do not report any state_class - I believe these should be `measurement`.

This may apply to more sensors but these are the ones I have activated that are reporting this issue.

This results in the following recorder error in the long term statistics: `The state class '' of this entity is not supported.`

**Companion App Logs:**

N/A

**Screenshot or video of problem:** N/A

**Additional information:** N/A

**Comment by jpelgrom** [comment] 2023-12-11 13:13
Duplicate of home-assistant/core#83716 - this should sort itself out if you wait for a bit, or permanently once fixed in core.

**Closed by jpelgrom** 2023-12-11 13:13 UTC
Labels: bug
