### ISSUE TITLE
Seems like some sensors are not showing state anymore after 2021-03 release

### ISSUE THREAD

**Issue by jvalst** [home-assistant/android#1395] opened 2021-03-04 08:06 UTC
**Home Assistant Android version:**
2021.3.1

**Android version:**
11

**Phone model:**
Samsung S20+

**Home Assistant version:**
Home Assistant 2021.3.0

**Last working Home Assistant release (if known):**
Home Assistant 2021.2.x

**Description of problem:**
I'm using some sensors of my mobile in the front-end. Things like Mobile Data / Bluetooth binary sensors. Those were working in the February Home Assistant, but seems like not working anymore since the new update. They show "off" while they're on. Also the Wi-fi / Don'tDisturb are shown as "unknown". The weird part here, is that my Girlfriend has a Samsung S9 where the Wi-fi is shown as expected. Don't Disturb not working either. Things like GPS / Battery level are working well on both devices. 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by holdestmade** [comment] 2021-03-04 13:32
Same here

**Comment by dshokouhi** [comment] 2021-03-04 14:09
Please get us the crash logs as indicated in the issue template.

**Comment by jvalst** [comment] 2021-03-04 14:14
Pfoe, that's some advanced stuff. I can try to give some more information tonight.

**Comment by dshokouhi** [comment] 2021-03-04 14:28
I hope you guys also tried the basic troubleshooting steps as outlined in the docs. Like seeing if you just have corrupt data. There was also a HA core release at the same time so downgrading is another thing to try. As of now I can't reproduce this. So we need more to go by.

**Comment by jvalst** [comment] 2021-03-04 14:47
Ok, ty for the effort at least. I'll give some things a try tonight. Yesterday things worked fine at least, after upgrading to latest Home Assistant I've some missing / wrong states.

**Comment by holdestmade** [comment] 2021-03-04 14:59
Solved it, if you click on Enable Sensors in the app it turns on all the sensor, this makes them appear in HA.
I had to go back and disable the ones I didn't need in the app

**Comment by jvalst** [comment] 2021-03-04 15:06
> Solved it, if you click on Enable Sensors in the app it turns on all the sensor, this makes them appear in HA.
> I had to go back and disable the ones I didn't need in the app

Thanks a lot! Same fix here. Seems like something needed to re-initialize or something. I had tried to restart phone / HA already, but not putting all sensors on. Maybe a feature request would be to also toggle all sensors off again. 

I got an popup for permission as well when putting all the sensors on. So maybe that was the bottleneck. I'll see if when I just enable that permission on my Girlfriends phone will fix it without toggling the sensors itself.

**Comment by dshokouhi** [comment] 2021-03-04 15:11
> EDIT - disabling sensors in the app does not seem to remove them from HA - I'll try a HA restart

Sensors don't removed currently, you'll need to manually remove.



> I got an popup for permission as well when putting all the sensors on. So maybe that was the bottleneck.

Yup permissions are required for sensors, seems if they were working before your device removed the permission.

Closing as this was not an app issue but probably missing permission or sensor not enabled.

**Closed by dshokouhi** 2021-03-04 15:11 UTC
Labels: bug

**Comment by jvalst** [comment] 2021-03-05 07:37
Just the additional info. At my girlfriends phone, only enabling all the phone permissions didn't solve the issue. Really needed to enable all sensors, and disabling them one by one again. Once I pressed that enable all button, instantly the sensors where updated. 👍

**Comment by holdestmade** [comment] 2021-03-05 10:00
I tried restarting HA and the disabled entities in the app still appear in HA

**Comment by jvalst** [comment] 2021-03-05 10:02
Yeah correct, those entities are still in HA. But not updating anymore because I disabled them in the app. At least the sensors I need are updating again. If you want to get rid of the HA entities, you need to manually remove them as what dshokouhi said.
