### ISSUE TITLE
unsupported stateclass

### ISSUE THREAD

**Issue by Hoekeren** [home-assistant/android#2223] opened 2022-02-01 11:11 UTC
![unsupported stateclass](https://user-images.githubusercontent.com/33251946/151958338-df3b9a6b-4665-4ca6-8d8c-3aa6964dd2f4.PNG)

**Comment by dshokouhi** [comment] 2022-02-01 13:33
Duplicate of #2168 and https://github.com/home-assistant/core/issues/63730

Follow these steps to fix the issue: https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Closed by dshokouhi** 2022-02-01 13:33 UTC
