### ISSUE TITLE
Inject http headers to all requests to the HA

### ISSUE THREAD

**Issue by Meister1977** [home-assistant/android#3306] opened 2023-02-03 16:27 UTC
**Is your feature request related to a problem? Please describe.**

I would like to set up Cloudflare zero trust before my HA. It works for the browsers, but doesn't work with the Android app.

**Describe the solution you'd like**

I would add a feature to add request headers to all requests to the ha server.
It would be good, if on the page, where I can enter the url, there will be a Advanced options where I can add multiple request headers, and later all of them will be injected the API calls. 

**Describe alternatives you've considered, if any**

App should handle SSO.

**Additional context**

https://developers.cloudflare.com/cloudflare-one/identity/service-tokens/

**Comment by dshokouhi** [comment] 2023-02-03 16:29
duplicate of https://github.com/home-assistant/android/issues/2650

**Closed by dshokouhi** 2023-02-03 16:29 UTC
Labels: enhancement

**Comment by Meister1977** [comment] 2023-02-03 16:39
Sorry, tried to find similar.
