### ISSUE TITLE
Next Alarm Inaccurate when Apps Excluded

### ISSUE THREAD

**Issue by bkaufx** [home-assistant/android#2857] opened 2022-09-06 01:51 UTC
**Home Assistant Android version:**
beta-2646-84aa4454-full

**Android version:**
12

**Phone model:**
Samsung s10

**Home Assistant version:**
2022.8.7

**Last working Home Assistant release (if known):**

**Description of problem:**
For the Next Alarm sensor: if an excluded app sets the next alarm, then the Home Assistant Companion App does nothing and the Next Alarm sensor keeps its previous value.  This is not accurate because the Home Assistant Companion App now has no idea when the next alarm will be for an allowed app.  The sensor should become unavailable or unknown when the next alarm is an excluded app.

One situation where this actually presents as a bug: The next alarm is currently set from an allowed app, and there is another later alarm set in an excluded app.  The Next Alarm sensor in the Home Assistant Companion App currently has the value from the allowed app.  If the alarm in the allowed app is turned off, nothing happens to the Next Alarm sensor.  The Next Alarm sensor keeps the same value even though the alarm was turned off because the next alarm is now from an excluded app.  Any automation triggered by the Next Alarm time will all execute at the time the alarm was set for even though I turned off the alarm.

It's probably fine if the Home Assistant Companion App assumes that the previously set alarm time is still valid as long as the alarm is AFTER the next alarm time from an excluded app, but the Home Assistant Companion App really needs to clear the Next Alarm sensor if the next alarm from an excluded app is after the current sensor value.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2022-09-06 01:55
This is actually expected behavior as you may only see the state once. Its recommended to remove alarms from other apps. I see that you have a samsung device you'll want to remove events from the alarm clock and the calendar. 

Also a duplicate of many others  https://github.com/home-assistant/android/issues/748 https://github.com/home-assistant/android/issues/1190 https://github.com/home-assistant/android/issues/1211

**Closed by dshokouhi** 2022-09-06 01:55 UTC
Labels: bug

**Comment by daniele-athome** [comment] 2022-09-07 19:45
You could use the "Package" attribute of the next alarm sensor and consider the value in HA (in automations, template sensors, etc.) only from the alarm clock application you use:

```
state_attr('sensor.mobile_app_next_alarm', 'Package') == 'com.chen.deskclock'
```

**Comment by bkaufx** [comment] 2022-09-07 19:56
I didn't do a good job of explaining.  What happens is that I turn off an alarm from the app I want, but the Next Alarm sensor doesn't change.  This can't be filtered because the package attribute is the correct value for the app I want, but the time is invalid because it is the time of an alarm I turned off.  When that time comes, all my automations execute even though I turned off the alarm.  There is no indication of whether the Next Alarm is actually going off or if it was turned off before the indicated time, which is what I would need to filter on (nor would it make sense to have this IMO).

The Home Assistant companion App needs to do something different when an excluded app is the next alarm.  Instead of doing nothing, it either needs to go unavailable or show the next alarm for an included app.

**Comment by dshokouhi** [comment] 2022-09-07 20:03
> The Home Assistant companion App needs to do something different when an excluded app is the next alarm. Instead of doing nothing, it either needs to go unavailable

heres the issue with that. The app has 0 control over when any other app decides to use this API. There are cases where an app can set an alarm every 30 seconds. Now imagine if we change the alarm and the state only shows for 30 seconds. That won't allow you to add an offset or anything. As a user you have control over those apps to stop using them. Some apps also like to set random times for the alarm as well which is why we don't recommend those apps and recommend users to stop using them.

As a user you can stop using the apps that alter this data or just stop using the allow list and filter by `package` like mentioned above.

The app is just going to report the data from the API and you can accept them all or skip certain updates. There are too many variables to account for otherwise. To get things to work properly for you I suggest you remove the alarms from the other apps so it can function as intended.

> show the next alarm for an included app.

Unfortunately that is not how the API works, the API only returns the next scheduled alarm and thats it and that can be set by any app.

**Comment by bkaufx** [comment] 2022-09-07 20:05
Couldn't you at least make the sensor value unavailable if the current value is BEFORE the next alarm?  In that case you know 100% that the value is invalid.

**Comment by dshokouhi** [comment] 2022-09-07 20:08
That will result in issues when device and cell network are off by timing, it makes more sense for your use case to either stop using those apps or dont use the allow list and filter by the provided `package` attribute.

**Comment by bkaufx** [comment] 2022-09-07 20:09
Alright, seems like a bug to me but I understand that solution and I'm fine with it so I'll just drop it.

**Comment by daniele-athome** [comment] 2022-09-07 20:18
@bkaufx I don't think there is a way to get that information from Android. Maybe the HA app could act on getNextAlarmClock [1] returning null and set the sensor as unavailable (and I think it already does that), but you can only get the next alarm from whatever app set it last - the whitelist is known to the HA app only.

[1] https://developer.android.com/reference/android/app/AlarmManager#getNextAlarmClock()

**Comment by jpelgrom** [comment] 2022-09-07 20:40
> Couldn't you at least make the sensor value unavailable if the current value is BEFORE the next alarm? In that case you know 100% that the value is invalid.

> That will result in issues when device and cell network are off by timing

I don't quite follow how this could create issues if the device time is off?

If i understand the request correctly, rephrasing it to be a bit more technical: if `nextAlarmClock` returns a value but that isn't for an app on the allowlist, could the sensor state be changed to `unavailable`?

This will allow you to know if the value is 'updated' or not, which with the current behaviour isn't possible.

|scenario|current state behaviour|proposed state behaviour|
|-----|-----|-----|
|next alarm is for an app on the allowlist / all are allowed|[time for next alarm]|[time for next alarm]|
|next alarm is for an app _not_ on the allowlist|state doesn't change!|`unavailable`|
|no next alarm|`unavailable`|`unavailable`|

**Comment by bkaufx** [comment] 2022-09-07 20:44
I get that, and admittedly at first did have some confusion about how the API works (and maybe still do, so definitely correct me if I am wrong about it below).  The issue I have is that the sensor value doesn't clear when it contains a known invalid value.  If the next alarm value received from the API is for an android package that is not on the Allow List, then in my opinion the Next Alarm sensor value should go unavailable.  The fact that it keeps the old time that is now known to be invalid by the Home Assistant Companion App makes it impossible to reliably use the Next Alarm sensor with the Allow List feature enabled.

In the case where the next alarm from the API is both after the current Next Alarm sensor value and also from an app that is not on the Allow List, I believe you know for 100% certain that the current Next Alarm sensor value is invalid.  If the value was still valid then it would be the next alarm received from the API.  So I think that handles concerns for the situation where times are off.

I honestly can't see any valid use for the Allow List on the Next Alarm sensor.  In my understanding and based on the above recommendations, the only way to exclude apps and have the Next Alarm sensor be reliable is to either not use those apps in android in the first place, or to filter them out manually when triggering automations without the Allow List being used.

Regarding @dshokouhi's argument that you might not know the next alarm time until 5 minutes before an alarm, thus making it impossible to do offsets or whatever, that is still the case if the Allow List is used.  Filtering out an app using the Allow List still, as I understand from the explanation in this thread and my experimentation, results in the next alarm being unknown until potentially a minute or two before the alarm no matter if my recommendation is adopted or not.  I can't see any difference between implementing my recommendation and not except that if my recommendation is adopted then the Next Alarm sensor can reliably be used with the Allow List feature.

@jpelgrom you basically are correct about my recommendation.

**Comment by daniele-athome** [comment] 2022-09-07 20:53
Ok I think I now get your intent right. The idea sounds good. HA devs what do you think? Is there something we are not seeing?

**Comment by bkaufx** [comment] 2022-09-07 21:18
I personally am fine with going unavailable in that case, because if you are using the Allow List (or even if you are using multiple apps that set the next alarm whether you are using allow list or not) you have to know that you may not catch things in time to do whatever automation you want.  That is currently the case when the Allow List is used and always will be, even though it works in your specific example.  The more realistic case of your example is that the alarm clock app setting an alarm to 6:00 would never be seen in the Next Alarm sensor in the first place since the 5:00 thing would already exist more than likely (e.g., from a calendar invite you didn't realize was going to interrupt your alarm sensor).

But your example does get to the heart of @dshokouhi's concern about not being able to do offsets in automations. In your example, if you wanted to do something 1.5 hours before the alarm it would not work with my recommendation because the alarm would be invalid at the time you would want the alarm to execute.  I personally would be okay with that, but as a compromise I would also be okay with going unavailable only if the next alarm from the API is both not on the allow list and also after the current next alarm sensor.   I don't believe that this case has the same concern from your example.  This solves my issue where the Next Alarm sensor matches the current time, but I had previously disabled the alarm at that time.

**Comment by dshokouhi** [comment] 2022-09-08 00:38
Personally I think that if we change the behavior then it needs to be a setting that is not default as this sensor has been out for some time. The only time an issue happens here is when users do not understand how the API or their devices work. For pixel users we don't have extra apps adding alarms in places unexpectedly by default.  This issue really only impacts a small subset of manufacturers and apps that use the API in unexpected ways. In most cases where the API is not abused the sensor behaves as described in the docs and no stale state is kept. This will also be considered a breaking change for this sensor as the `unavailable` state will happen in different situations and more frequently.

IMHO I prefer not to manipulate the data and only send events when we care about them, just like we do for Last Notification and current sensor behavior. The app does not care about what the value is that was previously sent, it only sends values that we care for. We already print to the logs when we don't send an update in an effort to help the user understand why the state is stale and not updating.

> I honestly can't see any valid use for the Allow List on the Next Alarm sensor.

You will want to read up on the next alarm sensor issues to better understand the history and how certain features came to be but when you have apps that trigger every 30 seconds (which indeed there are apps like that) you start to get a lot of events generated. So skipping events completely is valid but nobody is forced to use the allow list if they don't want to.  I think the use case described is more of an edge case and if the user really wants data to be presented in a certain way then its best for them to avoid the allow list and automate around the raw data as they see fit.

The best way to think of this API is in a very literal sense. It only contains data for the next scheduled alarm and thats it, it does not know about previous events or future events only the next event in line. For that reason is why there is an allow list and not all users need to use it. It depends on things from device to device and user to user so consuming unfiltered data might be best for some and not so good for others.

**Comment by bkaufx** [comment] 2022-09-08 00:44
I really appreciate your time and explanation.  For my case, I will be fine to just not use the Allow List and filter by Package in my automation triggers instead.
