### ISSUE TITLE
Pixel 4a/Android 13: OutOfMemoryError

### ISSUE THREAD

**Issue by chairstacker** [home-assistant/android#2849] opened 2022-09-04 20:54 UTC
**Home Assistant Android version:**
2022.8.0

**Android version:**
13

**Phone model:**
Pixel 4a

**Home Assistant version:**
Home Assistant 2022.8.7

**Last working Home Assistant release (if known):**
N/A

**Description of problem:**
HA App reezes and needs to be closed/re-started.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
2022-09-03 08:36:45.082: java.lang.OutOfMemoryError: Failed to allocate a 136 byte allocation with 1408816 free bytes and 1375KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
at android.os.Parcel.nativeReadString8(Native Method)
at android.os.Parcel.readString8NoHelper(Parcel.java:3092)
at android.os.Parcel$ReadWriteHelper.readString8(Parcel.java:493)
at android.os.Parcel.readString8(Parcel.java:3071)
at android.os.Parcel.createString8Array(Parcel.java:1761)
at android.content.pm.ApplicationInfo.(ApplicationInfo.java:2085)
at android.content.pm.ApplicationInfo.(Unknown Source:0)
at android.content.pm.ApplicationInfo$1.lambda$createFromParcel$0(ApplicationInfo.java:2053)
at android.content.pm.ApplicationInfo$1$$ExternalSyntheticLambda0.readRawParceled(Unknown Source:0)
at android.os.Parcel.readSquashed(Parcel.java:2708)
at android.content.pm.ApplicationInfo$1.createFromParcel(ApplicationInfo.java:2053)
at android.content.pm.ApplicationInfo$1.createFromParcel(ApplicationInfo.java:2050)
at android.content.pm.ComponentInfo.(ComponentInfo.java:247)
at android.content.pm.ActivityInfo.(ActivityInfo.java:1770)
at android.content.pm.ActivityInfo.(Unknown Source:0)
at android.content.pm.ActivityInfo$1.createFromParcel(ActivityInfo.java:1762)
at android.content.pm.ActivityInfo$1.createFromParcel(ActivityInfo.java:1760)
at android.os.Parcel.readTypedObject(Parcel.java:3947)
at android.app.IApplicationThread$Stub.onTransact(IApplicationThread.java:492)
at android.os.Binder.execTransactInternal(Binder.java:1285)
at android.os.Binder.execTransact(Binder.java:1244)
```

**Screenshot of problem:**
N/A

**Additional information:**
As discussed in the HA Forum:
https://community.home-assistant.io/t/android-13-issues-app-or-device/456708/13

**Comment by dshokouhi** [comment] 2022-09-05 17:47
Hmm I am not really sure what could be the cause of this. I suspect maybe bad data from the device upgrade to android 13 in the app? Not sure what to make of it but I would try to [start fresh](https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app) so you are not force stopping the app as much.

I know starting fresh means you won't be able to test a fix (if we find one) but I also wouldn't want the app to remain in that bad state because background services will also stop working as a result.

**Comment by chairstacker** [comment] 2022-09-05 20:35
Will Step 2 "Clear Storage or App data in Android app" affect my widgets?

**Comment by dshokouhi** [comment] 2022-09-05 20:38
It will reset all app data including widgets and sensors.

**Comment by chairstacker** [comment] 2022-09-05 20:49
Is there any way to back up or copy all widget configurations?

**Comment by dshokouhi** [comment] 2022-09-05 21:10
no there is no way to back up the current widgets, we did just get a feature request for that in #2844

**Comment by chairstacker** [comment] 2022-09-07 01:57
Quik Update:
I went through the 'start fresh' process as suggested and had the app up and running again - everything seemed to work fine.
Added a widget to the home screen and was impressed how quickly the switch reacted to me pushing the 'Service Button' widget.
Added a 3 more widgets to start replicating my original setup when I noticed that app was starting wo have issues again - tried to capture info from the 'Recent Crash' tab but it wasn't available under Settings > Companion App > Show and Share Logs.

Deleted the widgets again and the application started to run stable again.
Hate to have to give up on the widgets but will do that for now. 

Not sure, though, if it's 'just the widgets' or the combination of me using the Nova Launcher V7.0.57 and widgets.

**Comment by dshokouhi** [comment] 2022-09-08 02:22
> Added a 3 more widgets to start replicating my original setup when I noticed that app was starting wo have issues again - tried to capture info from the 'Recent Crash' tab but it wasn't available under Settings > Companion App > Show and Share Logs.

What do you mean the app started to have issues? It started to crash? The Recent Crash tab doesn't always work but it makes a best effort. Which widgets are you adding? There shouldn't be any errors when adding multiple widgets.

**Comment by chairstacker** [comment] 2022-09-08 02:28
Correct, the app started to crash just like before - and on Android 12 as well, btw.  This is not just an Android 13 thing for me.
I added two Service Button widgets and two template widgets in total in order to start recreating the 'dashboard' I showed in the Home Assistant Forum.

**Comment by dshokouhi** [comment] 2022-09-08 02:35
Weird I just tried adding 2 button widgets and 2 template widgets and I don't see any crashing like that. I also don't use a custom launcher.

We did have some improvements to the template widgets in a recent beta version of the app, would you be willing to try the beta?

**Comment by chairstacker** [comment] 2022-09-08 02:43
Sure - it seems like the crashing stops as soon as I remove the widgets again.

I had one issue before, though:
When I tried to find out what was going on, I downloaded the 2022.6.0 and even the 2022.2.0 versions to replace the 2022.8.0 one. But I couldn't install them on my Pixel or my tablet - the OS claimed the files were corrupted, which I'm pretty sure they were not.
So, if I need to downgrade from the beta to 2022.8.0 for any reason it might cause some issue.

Which beta do you recommend I try?

**Comment by dshokouhi** [comment] 2022-09-08 02:46
When you do a downgrade you may need to uninstall before reinstalling. Did you make sure to grab the APKs off the github release tab?

I would always recommend the latest beta :)

**Comment by jpelgrom** [comment] 2023-07-25 21:04
Closing this due to no more reports and a lot of changes. If anyone is still experiencing this please create a new issue.

**Closed by jpelgrom** 2023-07-25 21:04 UTC
Labels: bug
