### ISSUE TITLE
Incorrect timezone when system settings set to automaticaly

### ISSUE THREAD

**Issue by kgksoft** [home-assistant/android#4129] opened 2024-01-12 07:33 UTC
Harmony OS 3.0 (Huawei mate 20 x)
Home assistant android version: 2023.12.4-full

If my android time-zone setting "Set automaticaly": ON home assistant in history page using UTC time
If "Set automaticaly": OFF (and set gmt+2) home assistant work properly 

![image](https://github.com/home-assistant/android/assets/954568/98449066-5e53-4274-b6cd-b88d3b193778)
![image](https://github.com/home-assistant/android/assets/954568/380f3ca5-87bf-4145-981a-c5b0cc299427)

**Comment by dshokouhi** [comment] 2024-01-12 15:10
We dont manipulate any data here, I think this might be a device specific issue. Not sure we can fix this.

https://github.com/home-assistant/android/blob/master/common/src/main/java/io/homeassistant/companion/android/common/sensors/TimeZoneManager.kt#L48

**Comment by jpelgrom** [comment] 2024-01-12 15:18
> We dont manipulate any data here, I think this might be a device specific issue. Not sure we can fix this.

I don't think this has to do with the time zone sensors? Nothing about it in the description or screenshot.

@kgksoft Do you see the same issue when viewing the history in Chrome on your device?

**Comment by dshokouhi** [comment] 2024-01-12 15:19
> I don't think this has to do with the time zone sensors? Nothing about it in the description or screenshot.

hahha oops I saw timezone and immediately thought of the sensor 😅  yea I agree most likely a frontend issue

**Comment by kgksoft** [comment] 2024-01-12 15:40
> > We dont manipulate any data here, I think this might be a device specific issue. Not sure we can fix this.
> 
> I don't think this has to do with the time zone sensors? Nothing about it in the description or screenshot.
> 
> @kgksoft Do you see the same issue when viewing the history in Chrome on your device?

Chrome on device work properly. Bug only in android application HA

**Comment by dshokouhi** [comment] 2024-01-12 15:49
> Chrome on device work properly. Bug only in android application HA

can you check that android system webview is upto date and is Googles version from the play store?

**Comment by kgksoft** [comment] 2024-01-12 15:54
> > Chrome on device work properly. Bug only in android application HA
> 
> can you check that android system webview is upto date and is Googles version from the play store?

Android System WebView: 117.0.5938.60
Huawei WebView: 12.1.2.323

**Comment by dshokouhi** [comment] 2024-01-12 15:55
I think this might be a duplicate of https://github.com/home-assistant/frontend/issues/19318

The app does not control what timezone is shown when viewing HA frontend.

**Comment by kgksoft** [comment] 2024-01-12 16:17
> > > Chrome on device work properly. Bug only in android application HA
> > 
> > 
> > can you check that android system webview is upto date and is Googles version from the play store?
> 
> Android System WebView: 117.0.5938.60 Huawei WebView: 12.1.2.323

Upgraded Android System WebView
to 120.0.6099.210
but nothing changed

**Comment by dshokouhi** [comment] 2024-02-12 18:07
I am still not sure if this is a duplicate of the linked frontend issue but this is not an error the app can solve.

**Comment by kgksoft** [comment] 2024-02-12 18:20
Bug still exist. Strange that it not reproduced in android chrome

**Comment by dshokouhi** [comment] 2024-02-12 18:25
I understand the issue still exists but it cannot be fixed the app, the app does not control the timezone sent to the frontend.

**Comment by kgksoft** [comment] 2024-02-12 18:42
Application - server side ? I'm about android app (home assistant app from play market). Timezone on android app device incorrect reading or interpretation. 
"System automatic" - i must enter time range in UTC and its interpreteted server as local time, but android app show range in utc time.
Example:
i want show history from 9:00 to 12:00 in local time (+2).
I must enter range from 7:00..10:00 in input fields. Server sending me data from 9 to 12, but HA android app show time in history page as 7:00 .. 10:00. And i must understanding it as 9:00..12:00

**Comment by kgksoft** [comment] 2024-02-12 18:57
![image](https://github.com/home-assistant/android/assets/954568/4d964698-07ee-4079-ad64-9e38be4d8575)
but now time pickers missing
home assistant: 2024.1.5-full
android system webview: 120.0.6099.210

**Comment by dshokouhi** [comment] 2024-02-16 16:29
Closing as this cannot be fixed in the app, please open a new issue with the HA frontend and make sure to fill out hte issue template completely.

https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml

**Closed by dshokouhi** 2024-02-16 16:29 UTC
Labels: bug, question, sensor-tracking
