### ISSUE TITLE
Wrong next_alarm sensor value - 1h earlier

### ISSUE THREAD

**Issue by Masterz69** [home-assistant/android#4226] opened 2024-02-24 18:56 UTC
**Home Assistant Android app version(s):**
2024.1.5-full

**Android version(s):**
14 UKQ1.23091.001

**Device model(s):**
Xiaomi Redmi Note 12

**Home Assistant version:**
2024.2.2

**Last working Home Assistant release (if known):**
n/a

**Description of problem, include YAML if issue is related to notifications:**
HA OS and mobile with Companion App configured same time zone GMT+2.
Problem is: App & HA demonstrate next alarm time for 1 hour earlier.

Phone next alarm is set for 09:00 GMT+2, but App show 08:00 GMT+2.

**Companion App Logs:**
[homeassistant_companion_log_1-24-2024_20-54-48.txt](https://github.com/home-assistant/android/files/14394113/homeassistant_companion_log_1-24-2024_20-54-48.txt)

**Screenshot or video of problem:**
![Screenshot 2024-02-24 203702](https://github.com/home-assistant/core/assets/15225823/f92ac672-1b16-40f8-8190-593843773501)
![Screenshot_2024-02-24-20-48-48-034_io homeassistant companion android](https://github.com/home-assistant/android/assets/15225823/641a5cbe-8094-4d50-b972-55d1b348f208)
![Screenshot_2024-02-24-20-49-02-221_com android deskclock](https://github.com/home-assistant/android/assets/15225823/cdac0caa-5425-46ed-a0c6-cd9566a43266)

**Additional information:**

**Comment by dshokouhi** [comment] 2024-02-24 18:59
The date and time provided is what we get from the API.  Xiaomi stock apps are known not to report correct time so its best to avoid them.

Duplicate of https://github.com/home-assistant/android/issues/748 https://github.com/home-assistant/android/issues/799 https://github.com/home-assistant/android/issues/1085 https://github.com/home-assistant/android/issues/1109

**Closed by dshokouhi** 2024-02-24 18:59 UTC
Labels: bug

**Comment by Masterz69** [comment] 2024-02-24 19:09
Thank You for support.
Just installed Goggle Clock App - now next alarm looks fine.

Hope this case documented will help someone.

![Screenshot 2024-02-24 210759](https://github.com/home-assistant/android/assets/15225823/4203a074-0313-4f6f-b948-c640c5a1b844)
