### ISSUE TITLE
No text, entities, templates, notifications after Core 2024.11 upgrade 

### ISSUE THREAD

**Issue by 2senel** [home-assistant/android#4796] opened 2024-11-09 11:47 UTC
**Home Assistant Android app version(s):**2024.11.2-full

**Android version(s):** OneUI 6.1.- Android 14

**Device model(s):** S24, Galaxy Tab s9

**Home Assistant version:**2024.11

**Last working Home Assistant release (if known):**2024.10

**Description of problem, include YAML if issue is related to notifications:**

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

After the upgrade of Core to 2024.11 Android Version looks like attached. Also, the beta version from Play store. Same behaviour on two devices l, both Samsung (S24 and Galaxy tab S9) running Oneui 6.1

![Screenshot_20241109_124659_Home Assistant](https://github.com/user-attachments/assets/59c95d55-8174-420b-847c-5b4e622b77ba)
![Screenshot_20241109_124654_Home Assistant](https://github.com/user-attachments/assets/2eccae9e-c551-4ce1-86a8-302fc9ba359b)
![Screenshot_20241109_124647_Home Assistant](https://github.com/user-attachments/assets/8a68741d-15dd-4a62-b863-884ed0c3a544)

Web interface is fine, though.

**Comment by dshokouhi** [comment] 2024-11-09 16:29
This screen is not controlled by the app. Have you tried restarting the app and or updating Android system WebView? I'm unable to reproduce here too.

**Comment by 2senel** [comment] 2024-11-09 17:50
Update WebView via Play store? If so, there are no recent updates available. Also, no system nor Play Services updates.

Restarting app - yes, even force close, delete all data

Restarting HA - yes, multiple times.

Strange is that is works completely fine in the browser, even on the same devices. Just the app is showing nothing. Even more strange, two devices are affected. Sadly, I don't have any other device to test with the app.

**Comment by 2senel** [comment] 2024-11-09 18:21
Another glitch I've just noticed - I can't see release notes on the update screen:

![Screenshot_20241109_191938_Home Assistant](https://github.com/user-attachments/assets/0862e301-3668-4bcb-94d6-b30d3f95c795)
![Screenshot_20241109_191932_Chrome](https://github.com/user-attachments/assets/4f5d2097-b3c1-441e-b8f0-5b00036a4743)

**Comment by dshokouhi** [comment] 2024-11-09 18:50
please try the start fresh steps to rule out a cache/bad data issue https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by 2senel** [comment] 2024-11-09 19:17
Just tried and still same, sadly.

**Comment by jpelgrom** [comment] 2024-11-09 19:22
> can you please try and remove the custom stuff to rule out an issue with them? they need to be disabled completely including removing references from the dashboard resources

You can use safe mode for this

**Comment by 2senel** [comment] 2024-11-09 19:56
Still same, even in the safe mode, this time screenshots from tablet (yet again device deleted from integrations, deleted data, added from scratch):

![Screenshot_20241109_205107_Home Assistant](https://github.com/user-attachments/assets/d2248f22-53f6-40c7-aac6-15d5e8974dd2)
![Screenshot_20241109_205104_Home Assistant](https://github.com/user-attachments/assets/caf5eb1a-e8fc-4eaf-b85e-1bff2ace0483)
![Screenshot_20241109_205100_Home Assistant](https://github.com/user-attachments/assets/586e048b-a126-4427-9e26-191c03c51660)
![Screenshot_20241109_205043_Home Assistant](https://github.com/user-attachments/assets/2ad5315e-ab36-43cc-b126-6828f786a606)

Just to point out, on the s9 I haven't received Nov android uodate, so there's no this new Samsung max restriction feature yet. I was suspecting this also, but apparently this is not the case.

**Comment by dshokouhi** [comment] 2024-11-09 20:03
Have you updated HA core to 2024.11.1 yet?

**Comment by 2senel** [comment] 2024-11-09 20:06
Yes, today morning before I created this bug.

**Comment by dshokouhi** [comment] 2024-11-09 20:08
ok this still feels like a frontend bug honestly as the app does not control any of these screens

**Comment by dshokouhi** [comment] 2024-11-15 00:56
Closing in favor of the linked frontend issue

**Closed by dshokouhi** 2024-11-15 00:56 UTC
Labels: bug, question, webview
