### ISSUE TITLE
The page loads correctly in the browser, but not in the app when you configure the local path in the views。

### ISSUE THREAD

**Issue by xiejian25** [home-assistant/android#2363] opened 2022-03-11 03:24 UTC
**Home Assistant Android version:**
version: 2022.2.1
**Android version:**
Android 10
**Phone model:**
SM-N9760
**Home Assistant version:**
core-2022.2.9
**Last working Home Assistant release (if known):**

**Description of problem:**
The page loads correctly in the browser, but not in the app when you configure the local path（Such as：/energy） in the views。
for example：
#lovelace.yaml
title: HOME
views:
  - title: local path
    path: url
    type: panel
    badges: []
    cards:
      - type: iframe
        url: /energy
        aspect_ratio: 50%

The page is displayed properly in the browser，
However, the page is Unable to display properly only in the APP.
And I've tried all the app versions.
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2022-03-11 03:33
Can you check if Android system WebView is up to date? Also when you checked the browser did you check in chrome for Android on the same device? Can you also get us the logs?

**Comment by xiejian25** [comment] 2022-03-11 03:59
It is displayed properly in the browser on all devices：such as on my mobile phone，my Android pad，No matter what ndroid version。
just only displayed normally only in the Home Assistant APP。

**Comment by dshokouhi** [comment] 2022-03-11 04:02
Ok still waiting to hear if Android System Webview is up to date and also the logs for the template. This is probably a HA frontend issue but need to confirm webview compatibility first.

**Comment by xiejian25** [comment] 2022-03-11 04:07
> 
so sorry，I've made a mistake：
the bug is：
it just only Unable to display properly in the Home Assistant APP

**Comment by dshokouhi** [comment] 2022-03-11 04:09
I understand that but I still need the information I mentioned in my previous 2 posts otherwise we cannot proceed.

**Comment by Duke-Box** [comment] 2022-03-12 15:12
Hi,

I too am experiencing a similar issue.
Since upgrading my core HA to 2022.3.x from 2022.2.9 I have noticed that my HA companion for android App does not display my dashboards correctly.

This ONLY happens on the HA App, if I use a browser on the same device it displays correctly.

I suspect the issue is with the new HA core UI.
I use card-mod to display a sensor template for time in the header of the dashboard in place of the menu button. This is not displaying on the HA App. If I change the theme to "default" the menu button does not appear either. 
It does on any browser I use though.

The Android System Webview version is 99.0.4844.58 
And I have logs from the HA App - if you need them let me know.
Here is the Yaml stuff which works on any browser, just not the HA App.
```
# card-mod header stuff
  card-mod-theme: light-no-appbar
  header-height: 40px
  card-mod-root-yaml: |
    .: |
      ha-menu-button {
        display: none !important;
      }

      ha-button-menu {
        color: transparent;
      }

      ha-button-menu::before {
        content: "{{states('sensor.local_time')}}";
        color: var(--text-primary-color);
        visibility: visible;
        position: relative;
        font-size: 18px;
        top: 25px;
        white-space: nowrap;
      }
```
Mike

**Comment by dshokouhi** [comment] 2022-03-12 16:15
Card-mod is a custom card. We will not be troubleshooting custom cards and that is completely separate from the issue at hand.

**Comment by Duke-Box** [comment] 2022-03-12 22:48
I understand card-mod is a custom component and is outside your support sphere.
I apologise for confusing you.

However I used it as an example!
I also stated that using the HA "default" theme exposes the same issues in rendering a dashboard in your HA App .
This is easily reproducible just by selecting the theme in the user profile and noting the menu button isn't there.
That fact that the menu button is not there is the issue!

**Comment by dshokouhi** [comment] 2022-03-12 22:50
> That fact that the menu button is not there is the issue!

Yes but still unrelated to this issue. Please create a new issue.

**Comment by Duke-Box** [comment] 2022-03-12 22:53
Sorry i thought it was.
I thought the issue was HA App was not rendering a dashboard correctly when other browsers were.
I thought it just needed renaming.

But if you prefer I create another issue then I will.
Cheers

**Comment by dshokouhi** [comment] 2022-03-12 22:57
Can you both of you guys share screenshots of what you are seeing so we can compare and determine what's going on?

**Comment by Duke-Box** [comment] 2022-03-12 23:00
No problem - just need to give me a few hours as its early morning here.
thanks
Mike

**Comment by Duke-Box** [comment] 2022-03-12 23:17
OK,

This as it is displayed in Edge on the phone - note the time on the RHS - this is where the menu button is normally but is replaced by card-mod as described earlier.

[HA theme in a browser on Android device](https://user-images.githubusercontent.com/38861692/158038205-72628f86-88c8-4ec4-bcad-15afda1c0f99.jpg)

This is the same on HA App - not the lack of the clock on the RHS.
This is the default them but modified to show the sensor time. It replaces the menu button. The menu button is not visible if i did the same thing using the "default" theme .
![HA them in HA App on Android](https://user-images.githubusercontent.com/38861692/158038311-32eedc31-0344-4d9e-8186-da0eadb20961.jpg)


I think I explained that earlier didn't I?

Thanks
Mike

**Comment by dshokouhi** [comment] 2022-03-12 23:26
@Duke-Box what about without card-mod, I would like to see the issue happening in a stock environment without custom stuff please.  Closer to example given in the issue where the user is placing an HA core component in the panel.  It is not standard HA behavior to change the menu button.

**Comment by Duke-Box** [comment] 2022-03-12 23:30
Yes - sure no problem, I will do that using the default theme.
But it will be tomorrow before i can do that.
Thanks for your patience.

**Comment by Duke-Box** [comment] 2022-03-13 10:27
Hi,

As requested.
Here is the stock HA "default" theme rendered using the phone browser.
Note the menu icon (3 dots) on the RHS of the header.

![HA default theme in android browser](https://user-images.githubusercontent.com/38861692/158055158-73a6d1d4-065b-43d8-94bb-b2e0065d2ae1.jpg)

Here is the same thing but displayed in the HA App.
No menu button. 

![HA default them in HA App](https://user-images.githubusercontent.com/38861692/158055236-332b4a8b-7fbc-47e2-8813-270bc9d60099.jpg)

Mike

**Comment by dshokouhi** [comment] 2022-03-15 14:51
you still have card-mod enabled right? All you did was change the theme?

**Comment by Duke-Box** [comment] 2022-03-15 14:59
Yes but the card-mod yaml is in my theme not in the stock theme.
The card mod code worked perfectly in the HA App until I upgraded HA Core to 2022.3.x
I upgraded from 2022.2.9 to 2022.3.3 and it was then it stopped displaying correctly.
I only noticed really because there is a lot of chatter in the HA Core blog about the UI changes in 2022.3 and how it affects rendering in browsers. After updating to 2022.3, I was checking my themes and noticed the HA App didn't display what was correctly displayed in other browsers.

**Comment by dshokouhi** [comment] 2022-03-15 15:03
You need to completely remove card-mod in order for us to troubleshoot, we do not look at custom cards or custom components.



> The card mod code worked perfectly in the HA App until I upgraded HA Core to 2022.3.x
> I upgraded from 2022.2.9 to 2022.3.3 and it was then it stopped displaying correctly.

This means its not an app issue but HA core issue then and also completely unrelated to this issue as the user is reporting 2022.2.9 has their bug.  Please file an issue on the HA frontend.

**Comment by Duke-Box** [comment] 2022-03-15 15:08
OK - noted
my last comment is, it only manifests itself in the HA App, nowhere else hence me looking here for support.

**Comment by dshokouhi** [comment] 2022-03-15 15:09
thats fine there are frontend issues that are only visible in the app, the telltale sign is when the issue gets introduced by a HA core update instead of an app update.

**Comment by dshokouhi** [comment] 2022-04-27 19:44
Closing this issue as the original author did not respond back

**Closed by dshokouhi** 2022-04-27 19:44 UTC
Labels: bug, question, webview
