### ISSUE TITLE
Last notification sensor not saving in HA due to emojis

### ISSUE THREAD

**Issue by jesserockz** [home-assistant/android#1204] opened 2020-11-19 03:59 UTC
**Home Assistant Android version:** `3.0.2-full`

**Android version:** `10`

**Phone model:** `Moto One Vision`

**Home Assistant version:** `0.118.0`

**Last working Home Assistant release (if known):**

**Description of problem:**
I just received a push notification from a sudoku game and it seems like emojis in the notification message are added to the state which is not supported by the HA database schema.

**Traceback (if applicable):**

```text
Error in database connectivity during commit: (MySQLdb._exceptions.OperationalError) 
(1366, "Incorrect string value: '\\xF0\\x9F\\x8E\\x89' for column `hassio`.`states`.`state` at row 1") 
[SQL: INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created, old_state_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)] 
[parameters: ('sensor', 'sensor.visionist_last_notification', 'Be the first one in the world to solve today’s new puzzle🎉', '{"android.appInfo": "ApplicationInfo{de8a77b sudoku.puzzle.free.game.brain}", "android.infoText": "null", "android.largeIcon": "Icon(typ=BITMAP size= ... (627 characters truncated) ... ficationCompat$BigPictureStyle", "package": "sudoku.puzzle.free.game.brain", "friendly_name": "visionist Last Notification", "icon": "mdi:bell-ring"}', 218697670, datetime.datetime(2020, 11, 19, 3, 22, 11, 674862, tzinfo=datetime.timezone.utc), datetime.datetime(2020, 11, 19, 3, 22, 11, 674862, tzinfo=datetime.timezone.utc), datetime.datetime(2020, 11, 19, 3, 22, 11, 674862, tzinfo=datetime.timezone.utc), 208339691)] 
(Background on this error at: http://sqlalche.me/e/13/e3q8). (retrying in 3 seconds)
```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2020-11-19 04:13
I am pretty sure emojis are able to be saved but we have seen some cases where certain emojis dont play well.  I have not seen this error using the default SQL database.  Postmates sends a lot of emojis and they all render and save just fine, even show up in my template sensor.

**Comment by jesserockz** [comment] 2020-11-19 04:32
Ok maybe some "break" it then. 
But the recorder in HA keeps retrying to save this bad state over and over probably until I restart HA (have not yet restarted it) now even though the state has now changed to something else.

**Comment by dshokouhi** [comment] 2020-11-19 04:53
This error is probably occurring in cases where the emoji does not render properly, we had a similar report in discord as well and we could not reproduce it.  What happens if you send yourself the same emoji using another app like a chat app, does the error show up again?  When we performed the same test the error was not visible.  Also let us know the recorder you are using too please as it does not appear to be the default.

**Comment by jesserockz** [comment] 2020-11-19 06:45
Hmm, I am using the [mariadb](https://hub.docker.com/_/mariadb) docker image with `db_url: mysql://user:pass@ip/hassio?charset=utf8`

I get a similar error if I send the 🎉 in a sms to myself, the entity state updates correctly, also it stops all following states from being save to the database, so no data is being saved at all and I guess its being queued up behind this one?

**Comment by Mincka** [comment] 2020-11-19 09:31
Looks related to mariadb support and the charset type:
https://stackoverflow.com/a/39465494

Maybe you could just try to use something like that first:
`db_url: mysql://user:pass@ip/hassio?charset=utf8mb4`

It may be already supported by the addon:
https://github.com/home-assistant/hassio-addons/blob/d5806064840861b62f10115941185a534d60f279/mariadb/rootfs/etc/my.cnf.d/mariadb-server.cnf#L9

**Comment by dshokouhi** [comment] 2020-12-01 13:51
Looking at the [`recorder`](https://www.home-assistant.io/integrations/recorder/#custom-database-engines) docs seems we may need to update them based on the findings here.  @jesserockz can you please try @Mincka suggestion above to see if it solves the issue?

**Comment by dshokouhi** [comment] 2020-12-07 22:18
The recorder docs have now been updated and a new fix will be in the next HA core release. Going to close this now.  You may need to recreate the DB for the fix to get applied on existing installs: 

https://discord.com/channels/330944238910963714/427516175237382144/785627526512508958

If you still have an issue after updating the recorder statement and HA core then we can revisit although it may ultimately be a core issue.

**Closed by dshokouhi** 2020-12-07 22:18 UTC
Labels: bug, sensor-tracking

**Comment by jesserockz** [comment] 2020-12-07 23:17
Thanks, I have been way too busy to try this out over the past few weeks. 
I ended up disabling the sensor but will give it another shot when I get a chance.
