### ISSUE TITLE
Buttons are triggered when going to the home menu

### ISSUE THREAD

**Issue by TobiasG-DE** [home-assistant/android#2315] opened 2022-02-24 22:22 UTC
**Home Assistant Android version:**
2022.2.1-full
**Android version:**
12
**Phone model:**
Samsung S21 Ultra 5G
**Home Assistant version:**
2022.2.9
**Last working Home Assistant release (if known):**
---
**Description of problem:**
When going back to the home menu by dragging up from the bottom of the screen, screen components that are located in the app are triggered, for example buttons can be pressed even when they should not. There should be a safe screen zone for this where buttons do not trigger while going back to the home menu.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

https://user-images.githubusercontent.com/39413320/155617402-f724e359-b2d9-4760-87d8-02296007217f.mp4

**Additional information:**

**Comment by dshokouhi** [comment] 2022-02-24 23:00
I assume this issue also exists in Chrome for android?

**Comment by dshokouhi** [comment] 2022-02-24 23:02
this is similar to https://github.com/home-assistant/android/issues/1594 where a user confirmed it happens in the browser on the same device which would mean its a HA frontend issue as the app does not control swipe targets

**Comment by TobiasG-DE** [comment] 2022-02-25 20:18
Then thats likely the case, yeah

**Comment by dshokouhi** [comment] 2022-02-25 20:23
> Then thats likely the case, yeah

So you do see the issue in chrome for Android on the same device?

**Comment by TobiasG-DE** [comment] 2022-02-26 14:02
The issue does not replicate in google chrome on the same device

**Comment by dshokouhi** [comment] 2022-02-26 15:19
Actually this is a duplicate of https://github.com/home-assistant/frontend/issues/10348

It's related to all swipe gestures.

**Closed by dshokouhi** 2022-02-26 15:20 UTC
Labels: bug, webview
