### ISSUE TITLE
clear_notification command not working when several notifications are shown

### ISSUE THREAD

**Issue by ScratMan** [home-assistant/android#1435] opened 2021-03-16 08:09 UTC
**Home Assistant Android version:**
2021.3.1-full

**Android version:**
11

**Phone model:**
Oppo Find X2 Pro (ColorOS 11)
Xiaomi Mi 9 (MIUI 12.0.4)

**Home Assistant version:**
core-2021.3.2
Python 3.9 virtual env

**Last working Home Assistant release (if known):**
None

**Description of problem:**
I'm using an automation that notify user's mobile apps that some windows are opened. When the window is closed, the notification is cleared on all the mobile apps. It works perfectly when a single window is opened and closed. But when two windows are opened, it creates two notifications, and when the windows are closed, only one notification is cleared, the second one remains on the phones until manually dismissed.

I made the automation below to reproduce the issue. One notification is created, and cleared after 5 seconds, then a second notification is created with a different tag, and then cleared after 5 seconds. Then the first notification is created again ; 5 seconds later the second notification is created ; 5 seconds later the first notification is successfully cleared, but 5 seconds later the second notification is not cleared as expected .

`alias: Notifications Test
description: Creates and clear one or multiple notifications on mobile app
trigger: []
condition: []
action:
  - service: notify.notify
    data:
      title: Test notification
      message: Create notification 1
      data:
        ttl: 0
        priority: high
        tag: tag_one
        color: yellow
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: notify.notify
    data:
      title: Test notification
      message: clear_notification
      data:
        ttl: 0
        priority: high
        tag: tag_one
        color: yellow
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: notify.notify
    data:
      title: Test notification
      message: Create notification 2
      data:
        ttl: 0
        priority: high
        tag: tag_two
        color: green
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: notify.notify
    data:
      title: Test notification
      message: clear_notification
      data:
        ttl: 0
        priority: high
        tag: tag_two
        color: green
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: notify.notify
    data:
      title: Test notification
      message: Create notification 1
      data:
        ttl: 0
        priority: high
        tag: tag_one
        color: yellow
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: notify.notify
    data:
      title: Test notification
      message: Create notification 2
      data:
        ttl: 0
        priority: high
        tag: tag_two
        color: green
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: notify.notify
    data:
      title: Test notification
      message: clear_notification
      data:
        ttl: 0
        priority: high
        tag: tag_one
        color: yellow
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: notify.notify
    data:
      title: Test notification
      message: clear_notification
      data:
        ttl: 0
        priority: high
        tag: tag_two
        color: green
mode: parallel
max: 10
`

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
[logcat_03-16-2021_09-04-02.txt](https://github.com/home-assistant/android/files/6147050/logcat_03-16-2021_09-04-02.txt)

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2021-03-17 18:38
@ScratMan your logs are actually incomplete here.  We should see the notification payloads for each notification coming in the logs.  You may need to remove the search for `homeassistant` so we can see all the data. 

Also when I get multiple notifications with separate tags they all clear on their own and I normally have 2 notifications that are persistent.  Have you checked notification history to see if all of the notifications came through?

**Comment by ScratMan** [comment] 2021-03-18 17:36
> @ScratMan your logs are actually incomplete here. We should see the notification payloads for each notification coming in the logs. You may need to remove the search for `homeassistant` so we can see all the data.
> 
New log attached

> Also when I get multiple notifications with separate tags they all clear on their own and I normally have 2 notifications that are persistent. Have you checked notification history to see if all of the notifications came through?

The create notifications appear in the history, but the clear_notification does not, so impossible to know if the app received the command correctly.

**Comment by dshokouhi** [comment] 2021-03-18 17:53
> The create notifications appear in the history, but the clear_notification does not, so impossible to know if the app received the command correctly.

If you don't see that then it means your device did not receive them, are you checking the history in the App Configuration or the one provided by android? The command itself will only show in the app and not in androids builtin feature.  Now the logs do indicate you received each notification and command.  They also indicate that our code had attempted to clear the last notification but I did not see android responding that it removed the notification.

@chriss158  think you can help with this one?  Seems like the user can easily reproduce and the logs look to be correct

**Comment by ScratMan** [comment] 2021-03-18 22:43
I looked in the Android's history.
I just checked in the app, and the notifications and clear commands are there.

**Comment by dshokouhi** [comment] 2021-03-18 23:33
@ScratMan thanks for confirming. I found some time to try and replicate based on the provided steps however I was unable to reproduce it personally. Have you tried clearing data and trying again to see if that fixes the issue?

**Comment by chriss158** [comment] 2021-03-19 11:52
I've created the script from @ScratMan. But i can also not reproduce this issue. 

I also noticed this issue with my car notifications. When i'm  in my car, i'll send 5 notifications with a 1 second delay. When i'm leaving my car, i send the clear_notification command to remove the notifications. But sometimes. 1-2 notification will be not removed. Till today i thought, this would be a problem in my node-red flow.

**Comment by dshokouhi** [comment] 2021-03-19 16:38
@chriss158 so one thing that I noticed is that it seems when the call to cancel the notification is made successfully we see the following logcat from Android

```
[03-18 18:27:42.318 30758:30758 I/NLService]
********** onNOtificationRemoved
```

In the attached logs you see this all the time except for the last one.  I wonder if we need to add some debug logs to our overriding of the cancel operation to see if there is some unexpected data.  Maybe some variable is coming in with unexpected data which causes us to skip the operation for some reason?

**Comment by chriss158** [comment] 2021-03-19 21:40
I've added some debug logs in the attached APK. 
@ScratMan 
Can you try and upload the debug log?

[app-full-debug.zip](https://github.com/home-assistant/android/files/6174153/app-full-debug.zip)

**Comment by chriss158** [comment] 2021-03-21 21:48
Link for APK with Logs: https://github.com/home-assistant/android/suites/2310147699/artifacts/48491678

**Comment by dshokouhi** [comment] 2021-03-21 21:52
> Link for APK with Logs: https://github.com/home-assistant/android/suites/2310147699/artifacts/48491678

Debug APKs built from the actions do not have notifications actually, there is a firebase pop-up so they can skip the registration since it will fail

**Comment by chriss158** [comment] 2021-03-21 21:56
Ah you are right, no notifications here. So we need to wait till its merged to master? Should be anyway a good thing to have some more logs.

**Comment by dshokouhi** [comment] 2021-03-21 21:58
yea more logs is always better to have :)

**Comment by ScratMan** [comment] 2021-03-24 17:23
> @ScratMan Can you reproduce this with your script everytime?

Yes. I can launch the automation from the app or from the web Lovelace, the effect is the same.

**Comment by dshokouhi** [comment] 2021-03-24 18:38
@ScratMan we have added some debug logs in the latest beta https://github.com/home-assistant/android/releases/tag/beta-624-3639d42

If you can please update to this version and then reproduce the issue and get us the logs as we should be able to pin down where the issue is now with the new logs.  You will need to grab the full version from the download section.

It is safe to install over the app and normal production updates will resume in April, you won't be able to downgrade without clearing data.

**Comment by ScratMan** [comment] 2021-03-24 20:21
Hi, here is a new log with the beta. I could reproduce the issue the same way.
[
[logcat_03-24-2021_21-16-40.txt](https://github.com/home-assistant/android/files/6200252/logcat_03-24-2021_21-16-40.txt)
](url)

**Comment by chriss158** [comment] 2021-03-24 20:39
Thanks @ScratMan 
I see a possible problem in the logs regarding groups. I assume you don't use a group named "ranker_group". I think this group is generated by the system. Maybe this group is the problem here. But i need to investigate further.

**Comment by ScratMan** [comment] 2021-03-24 20:49
I didn't create this group.

**Comment by dshokouhi** [comment] 2021-03-24 20:51
Looks to be system generated: https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/services/core/java/com/android/server/notification/GroupHelper.java#39

**Comment by ScratMan** [comment] 2021-03-24 21:05
I installed the beta app on my Pixel C tablet running LineageOS 17.1, and the notifications are cleared correctly. So the issue really seems to be system related.

[logcat_03-24-2021_22-01-05.txt](https://github.com/home-assistant/android/files/6200446/logcat_03-24-2021_22-01-05.txt)

**Comment by chriss158** [comment] 2021-03-24 23:30
I could reproduce this issue and fixed it in the PR #1452 

Thanks @ScratMan for the logs and testing 👍

**Closed** 2021-03-28 17:04 UTC
Labels: bug, notifications

**Comment by ScratMan** [comment] 2021-04-01 13:08
Issue confirmed fixed in beta 637, but not yet in official app release 2021.3.1 from Play Store.
https://github.com/home-assistant/android/releases/tag/beta-637-94e1f15

**Comment by dshokouhi** [comment] 2021-04-01 14:20
> Issue confirmed fixed in beta 637, but not yet in official app release 2021.3.1 from Play Store.
> https://github.com/home-assistant/android/releases/tag/beta-637-94e1f15

Beta builds get pushed to the play store every Saturday night. Releases get cut around the same time HA core has a release that comes out of the beta.
