### ISSUE TITLE
Complications do not update on WearOS 5.0 when the screen turns on

### ISSUE THREAD

**Issue by DaZeroXB** [home-assistant/android#4811] opened 2024-11-13 10:56 UTC
**Home Assistant Android / WearOS app version(s):**

2024.10.3 / 2024.10.3

**Android / WearOS version(s):**

15 / 5.0

**Device model(s):**

Google Pixel 7 Pro / Google Pixel Watch 2 / 3

**Home Assistant version:**

2024.10

**Last working Home Assistant release (if known):**

-

**Description of problem, include YAML if issue is related to notifications:**

I just updated to WearOS 5.0 and since then the complications are not updating any longer on any display event. The only way to update the complication is by clicking on it.

If reported a similar issue 1.5 years back (https://github.com/home-assistant/android/issues/3592) where the auto-update is not working on **AOD + TTW**. At least for **AOD off + TTW on** it was working or by clicking or rotating the crown if the watch was in **AOD on** mode. After the update no combination at all is working. I assume that Google my introduced a new event within WearOS that could be used for HA in order to update the complication automatically. I would highly appreciate if a DEV can have a look into it and hopefully comes up with a fix.

If you need further information / testing I will be glad to support.

Thank you and kind regards,
Martin

**Additional information:**

**Comment by dshokouhi** [comment] 2024-11-13 15:10
are you using the stock watch faces?

**Comment by dshokouhi** [comment] 2024-11-13 15:33
hmm looks like this is an issue with stock watch faces on a pixel watch 3, unfortunately i do not recall this working on initial software as i dont normally use complications

**Comment by dshokouhi** [comment] 2024-11-13 16:36
i believe I may have a fix for this but it requires testing. If you are able to test you will need to sideload both the full version of the phone app and also the Wear app. This will allow you to login and setup the complication. These are the debug builds of the app and are safe to install side by side production. They have a different icon (red) to make it easily distinguishable. I recommend giving a unique device name so you can easily remove after the test. I am not certain this will work but its worth a shot based on teh developer docs.

https://github.com/home-assistant/android/actions/runs/11821226323

youll need to extract the archive here to get the APKs to sideload

i should be able to test tonight or tomorrow night but in case we can get feedback early wanted to submit it here.

**Comment by DaZeroXB** [comment] 2024-11-13 19:05
Managed to sideload both, the phone and wear app, but unfortunately it is also not working. I run both instances in parallel and have added complications for both instances on the same watchface. However, each is only updating if you click on it. Clicking or rotating the crown or waking up the display is not updating the complications.
Further, I tried on a stock watchface and a custom one that I've created with Samsung Watch Face Studio. Same behaviour.
Any further ideas? Please also try on your
![PXL_20241113_185547156 (1)](https://github.com/user-attachments/assets/5f2c5c65-62e6-49a5-a79e-f47c0ef5f75a)
![PXL_20241113_190419347](https://github.com/user-attachments/assets/f151b25a-7cb0-44d5-a72e-e485d308a569)

**Comment by dshokouhi** [comment] 2024-11-13 19:26
> Any further ideas? Please also try on your

Thanks for testing! If its not working for you then it wont for me when I am able to test later. I had 2 approaches in mind, second approach is similar to our sensor worker. Additionally I added a log so we can see if the app is even being told to update the complication. If you are able to test before I am here is the action (no need to update the phone if you have the other debug version still installed on it): 

https://github.com/home-assistant/android/actions/runs/11824200259

**Comment by DaZeroXB** [comment] 2024-11-13 20:52
Unfortunately now I am struggling to connect your 2nd build of the wear app with the RED home assistant app. I uninstalled the previous RED wear app and installed the new one, but when I start the app on the watch, no instances were found. I did already delete all "Pixel Watch" devices in HA however, If i open the RED HA app and go to "companion app" -> "Wear OS settings" it still shows to connect "pixel watch 2" even though it no longer exists within HA devices...
![Screenshot_20241113-215043](https://github.com/user-attachments/assets/b66896c6-ac96-4efa-addf-bcb110fc33ab)

**Comment by dshokouhi** [comment] 2024-11-13 20:57
if you have both debug builds still, try restarting both phone and watch the connection seems backed up

**Comment by dshokouhi** [comment] 2024-11-13 20:58
> it still shows to connect "pixel watch 2" even though it no longer exists within HA devices...

this is not from HA, this is the watch connected to the phone

**Comment by DaZeroXB** [comment] 2024-11-13 21:18
had to uninstall and install the new build of the phone app as well. managed to establish the connection, however unfortunately still not working :( updates only on tap of the complication itself. Where can I find the logs you mentioned earlier?
Btw, this test was done on my Pixel Watch 2, tomorrow I will get the Pixel Watch 3 and I can check if it behaves the same.
I hope you still have other ideas.

**Comment by dshokouhi** [comment] 2024-11-13 21:21
> Where can I find the logs you mentioned earlier?

that would be in logcat, if you are familiar with it you can filter by `ComplicationReceiver` and we can see if the intent shows up there



> Btw, this test was done on my Pixel Watch 2, tomorrow I will get the Pixel Watch 3 and I can check if it behaves the same.
> I hope you still have other ideas.

thats the watch I have, I'll have to take a look when i can hook up the watch to the debugger. Was hopeful it would be a simple fix as the interactive sensor on Wear OS still receives that intent.

**Comment by DaZeroXB** [comment] 2024-11-13 21:30
okay, i am not familiar with logcat. Since its already late in europe anyway, I would appreciate if you can investigate once you have some time to spare. Thank you Daniel for your great support on that! Looking forward to hearing from you.

**Comment by dshokouhi** [comment] 2024-11-13 21:33
yup its a valid issue, just dont have the time currently to connect to debugger and troubleshoot. Thanks for testing the previous attempts 🙏 !

**Comment by dshokouhi** [comment] 2024-11-13 23:25
found time to test this and think i found the issue with no changes needed.

@DaZeroXB after the Wear OS 5 update that came out again yesterday did you start the app one time? That is actually required for the app to register the intent and get updates. If teh app crashes then we will lose that intent registration. The app needs to be started at least one time after device reboot, app crash or app update.

Testing now the only time the complication stops updating is if the app was crashed in the background and this is similar from before. if i start the app and put it in the background without closing it updates as expected.

The same goes for sensors here too.

If you start the app and put it in teh background is it working again? Anytime you see it stop working I assume if you start the app it will not open as if it were in the background.

**Comment by DaZeroXB** [comment] 2024-11-14 06:28
Can confirm, starting the app on PW indeed fixes the issue. However, sometimes the connection breaks up again after a while. After again opening the app it works. 

Unfortunately, the complications are still not updating with AOD on and TTW on (tilting wrist). Do you see a chance to dig into this once more? Maybe you can find a workaround/hack for this as well, would really appreciate that!

**Comment by dshokouhi** [comment] 2024-11-14 06:33
> However, sometimes the connection breaks up again after a while. After again opening the app it works.

probably caused by #3325 which is what made me realize where the issue may be coming from. The best workaround there is to add favorite entities and enable the "Show only favorites" option in settings. That will avoid the crash.

> Unfortunately, the complications are still not updating with AOD on and TTW on (tilting wrist). Do you see a chance to dig into this once more?

you mean in reference to https://github.com/home-assistant/android/issues/3592 ? theres nothing the app can do if the OS does not send us updates. Thats demonstrated even more in this issue :)

closing as this not an issue

**Closed by dshokouhi** 2024-11-14 06:33 UTC
Labels: bug, Wear OS

**Comment by DaZeroXB** [comment] 2024-11-14 07:38
> you mean in reference to #3592 ? theres nothing the app can do if the OS does not send us updates. Thats demonstrated even more in this issue :)
> 
yes I mean this reference, however I think it is worth giving it another look since the evaluation was done 1.5 years ago on Wear OS 3.5 and Pixel Watch 1. Maybe the API has changed and there are other possibilities/tricks that can be done with the latest API level of Wear OS 5.0. Would you mind to just have a short look again on that?

**Comment by dshokouhi** [comment] 2024-11-14 07:43
There are no other tricks that can be done an app receiving an intent is a core part of Android. You will need to wait for Google to fix the issue themselves on this one. Chances are high nothing has changed as is the case with issues like #3976 which was introduced in Wear OS 4. Some of these are deliberate to save battery life is the assumption.

**Comment by DaZeroXB** [comment] 2024-11-14 08:05
I see, unfortunately google is not caring at all. I am really frustrated since I've created a bug report long time ago https://issuetracker.google.com/issues/288303230 
Anyway, thanks for your help!

**Comment by dshokouhi** [comment] 2024-11-14 08:07
i have had issues get resolved within a month, and some that have sit for years as well. I feel your frustration. I have given that issue a +1 hopefully it gets worked on.
