### ISSUE TITLE
App is not listed in recent-apps overview, if opened through a shortcut

### ISSUE THREAD

**Issue by baracoder** [home-assistant/android#4306] opened 2024-03-28 16:22 UTC
**Home Assistant Android app version(s):** 2024.1.5-full (Play Store)

**Android version(s):** 15

**Device model(s):** Pixel 8, Pixel 6

**Home Assistant version:**
Core 2024.3.3
Supervisor 2024.03.1
Operating System 12.1
Frontend 20240307.0

**Last working Home Assistant release (if known):** Not known

**Description of problem, include YAML if issue is related to notifications:**
App is not listed in recent-apps overview, if first time opened through a shortcut. 

**Companion App Logs:**

```
TODO
```

**Screenshot or video of problem:**
https://drive.google.com/file/d/17o4I3Az-zRYCVZeS-4YlBBhnKQkzjFdW/view?usp=sharing

**Additional information:**

To reproduce:

1. Create a shortcut
2. Make sure app is closed from recent-apps view
3. Open app through shortcut
4. Swipe to last used app
5. Swipe up for recent used apps -> Home Assistant App is not listed or removed instantly
6. Close/Stop Home Assistant App
7. Reopen through main App Icon
8. Swipe to last used app -> Home Assistant App stays in recently used apps

Problem might be related to #3781 or #2805

**Comment by dshokouhi** [comment] 2024-03-28 16:24
this is intentional and a duplicate of teh issues mentioned, shortcuts do not add to recent app view by design

**Closed by dshokouhi** 2024-03-28 16:24 UTC
Labels: bug

**Comment by baracoder** [comment] 2024-03-28 16:30
@dshokouhi please check again. I don't think this part is intentional: Using the main app icon, the app does not persist in recent apps, if a shortcut was used to open it first time. Maybe it is more obvious from the video.

**Comment by baracoder** [comment] 2024-03-28 16:58
Thank you for checking again. I get it, that shortcuts should not have their own entries in recent apps, but my point is, that the main app "inherits" this behavior, if the app is closed/stopped (swiped away) and the shortcut is used first. If the main icon is used first, the behavior is as expected and in line to the intended change.

**Comment by dshokouhi** [comment] 2024-03-28 17:28
i hear what you are saying but this is out of control for the app and might just be launcher behavior
