### ISSUE TITLE
App Shortcuts not stored

### ISSUE THREAD

**Issue by Grumblezz** [home-assistant/android#1560] opened 2021-05-22 09:30 UTC
**Home Assistant Android version:** 2021.5.1-full

**Android version:** 9

**Phone model:** Samsung

**Home Assistant version:** core-2021.5.5

**Last working Home Assistant release (if known):**

**Description of problem:**
With in the app your are able to create application shortcuts (https://companion.home-assistant.io/docs/integrations/android-shortcuts/). When creating those I noticed several issues:
1. Shortcut data (like icons) are not stored when using the Back Arrow in the app.
2. When using a space in the Label, then the shortcut can't be created. Is this a correct behavior? If so, please make that visible to the user.
3. Updating the Label 'destroys' all other shortcuts, and making making the feature impossible to use.
4. When all shortcut details are filled in the create shortcut remains greyed out. After use the Back Arrow and going back to the shortcuts then the Create option becomes available

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

**Screenshot of problem:**
![20210522_115517](https://user-images.githubusercontent.com/74052665/119222531-28d91000-baf5-11eb-9613-21a5fd3622c5.jpg)
![20210522_115826](https://user-images.githubusercontent.com/74052665/119222540-2f678780-baf5-11eb-85ca-1fb7cbaa6d95.jpg)

**Additional information:**

**Comment by dshokouhi** [comment] 2021-05-22 13:25
This issue has multiple issues combined into one. Please create one bug per issue. You also need to provide steps to reproduce instead of just a brief description. We do not store icons so that is correct behavior. Labels can indeed have a space so not sure what the issue is there. Updating the label doesn't "destroy" other shortcuts either. Closing this issue so we don't compound too many in one issue. Please be more precise so we can fix the issues.

**Closed by dshokouhi** 2021-05-22 13:25 UTC
Labels: bug
