### ISSUE TITLE
Geocoded location unknown on OnePlus 7T until it is rebooted but goes back to unknown after a short period of time

### ISSUE THREAD

**Issue by dnedeltchev** [home-assistant/android#2225] opened 2022-02-02 00:17 UTC
**Home Assistant Android version:**
2022.1.1-full
**Android version:**
11
**Phone model:**
OnePlus 7T
**Home Assistant version:**
core-2021.12.10
Home Assistant OS 7.2
supervisor-2022.01.1 stable
**Last working Home Assistant release (if known):**

**Description of problem:**
Geocoded location is only available after the phone is rebooted. It stays there for an hour or so and then goes to unknown. Other Android phones are OK. I have seen this reported somewhere in the community forums again with OnePlus but can't recall what model, so it may be OnePlus related.
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**
I have followed all suggestions I could find, turning off and on location services, enabling high accuracy, etc. Nothing helps. Once the phone is rebooted, geocoded location is available for an hour and then disappears. Other Android phones are OK like Samsung A22, Huawei P10 Lite.

**Comment by dshokouhi** [comment] 2022-02-02 00:45
Did you try looking at the companion app logs when the issue happens to see if there is a failure? 

https://github.com/home-assistant/android/blob/master/app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt#L82

The state of this sensor is entirely dependent on the Android API and Google location tracking service. If it fails or the address is simply unknown we send that state.

https://github.com/home-assistant/android/blob/master/app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt#L107

You can also enable debug logging for the `mobile_app` integration to look at the webhook data coming in. If you see `uknown` then that state is correct.

**Comment by dnedeltchev** [comment] 2022-02-02 12:29
Thanks Daniel,

Would the below in configuration.xml enable debug for the mobile_app
integration?

logger:
  logs:
    # log level for MQTT integration
    homeassistant.components.mobile_app: debug

It's tricky to catch exactly when it happens. Last night I rebooted my
device, geocoded location popped up and then I waited for 30 min and
nothing happened. In the morning I saw that the change to unknown happened
after 37 min. But I will see if I can catch it next time. Will the debug
logs be available in the companion app or will they be in home assistant?

Many thanks for your help!

**Comment by dshokouhi** [comment] 2022-02-02 15:49
> Will the debug logs be available in the companion app or will they be in home assistant?

I actually asked you to check both.

**Comment by dnedeltchev** [comment] 2022-02-02 16:29
Hi Daniel, Debug in HA enabled. Phone rebooted, geolocation is now showing. I will now sit and watch it until it goes to unknown and grab logs. I am looking at the logs right now, while I have geocoded location, and in the companion app I see duplicate location received. Not sending to HA, check if service high accuracy is running, it’s false I have this disabled, and then the same logs a minute later. HA still shows correct geocoded location. I will keep you posted.  From: Daniel ShokouhiSent: 02 February 2022 15:49To: home-assistant/androidCc: dnedeltchev; AuthorSubject: Re: [home-assistant/android] Geocoded location unknown on OnePlus 7T until it is rebooted but goes back to unknown after a short period of time (Issue #2225) Will the debug logs be available in the companion app or will they be in home assistant?I actually asked you to check both.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by dshokouhi** [comment] 2022-02-02 16:33
> Debug in HA enabled. Phone rebooted, geolocation is now showing. I will now sit and watch it until it goes to unknown and grab logs. I am looking at the logs right now, while I have geocoded location

You should now see all webhook data being being logged in the HA core logs. You will see the state of sensors being transferred.



> and in the companion app I see duplicate location received. Not sending to HA, check if service high accuracy is running, it’s false I have this disabled, and then the same logs a minute later.

you can ignore the lines starting with `LocBroadcastReceiver` as those are for the device tracker and not the geocoded location sensor.

**Comment by dnedeltchev** [comment] 2022-02-02 18:37
HA logs just show the state changing to unknown. I can’t see any errors there other than the state changing which is as you said coming from Android. Sadly, though, the companion app logs rolled over just at that particular time! Grrr! So I can’t see what’s happening on the Android side just at that moment. However, I do see the latitude and longitude in the logs of the app being reported correctly. Then I see LocBroadcastReceiver: Location update sent successfully. But you said I should ignore those LocBroadcastReceiver events. Does this make sense? What should I be looking in the app logs? Or in the HA logs? Anything I can filter on? Many thanks for your help! From: Daniel ShokouhiSent: 02 February 2022 16:34To: home-assistant/androidCc: dnedeltchev; AuthorSubject: Re: [home-assistant/android] Geocoded location unknown on OnePlus 7T until it is rebooted but goes back to unknown after a short period of time (Issue #2225) Debug in HA enabled. Phone rebooted, geolocation is now showing. I will now sit and watch it until it goes to unknown and grab logs. I am looking at the logs right now, while I have geocoded locationYou should now see all webhook data being being logged in the HA core logs. You will see the state of sensors being transferred.and in the companion app I see duplicate location received. Not sending to HA, check if service high accuracy is running, it’s false I have this disabled, and then the same logs a minute later.you can ignore the lines starting with LocBroadcastReceiver as those are for the device tracker and not the geocoded location sensor.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by dshokouhi** [comment] 2022-02-02 18:47
> Sadly, though, the companion app logs rolled over just at that particular time! Grrr! So I can’t see what’s happening on the Android side just at that moment. 

You can use an app like Logcat Reader and grant the special USB permissions to look at the history of logs to see if there is an error. If there is no error then simply the API did not return an address. 

> However, I do see the latitude and longitude in the logs of the app being reported correctly.

Are you saying the attributes of the sensor contain latitude and longitude when this issue occurs? If thats the case then its an API issue and not much the app can do in those cases, we simply dont get the pretty address for the state so we send unknown.



> Then I see LocBroadcastReceiver: Location update sent successfully. But you said I should ignore those LocBroadcastReceiver events. Does this make sense?

These are for the device tracker which doesn't have anything to do with the geocode API. Keep in mind you are looking at the logs as a whole so you should expect to see logging from all parts of the application here.



> What should I be looking in the app logs?

To see if there is a failure that contains the text in the links above that point to where the code is failing



> Or in the HA logs?

In the HA logs you confirmed that the state is coming as `unknown` so we will only see a failure or no failure in the app. If you don't see a failure then its just an API issue and we dont have control over that.

> Anything I can filter on?

The failure will show with the following tag `GeocodeSM` if its actually failing that is

**Comment by dreimer1986** [comment] 2022-02-10 13:47
I can confirm the same problem in OP7T Pro with official Andoid 11. It worked with LineageOS, but I had to hop back to Official and now I have the same issue. I could try to get some logs, too, but not before weekend.

**Comment by dnedeltchev** [comment] 2022-02-10 14:04
Apologies for the radio silence on this. I tried for many days and late evenings to identify the exact point at which the geocoded location fails but I am unable to see anything in the logs. Maybe you’d have more luck with it but I would put this down as a OnePlus 7T thing. Sadly OnePlus 7T is coming to the end of support so I do not expect this to be fixed.

**Comment by dshokouhi** [comment] 2022-02-10 23:11
remember its possible that it doesn't fail and that it simply doesnt have an address provided by the API in which case things are working as expected.

**Comment by adromir** [comment] 2022-02-12 04:39
I have the same Problem on OOS. My Tablet at home reports its location correctly, but my Phone doesnt (when both staying at the same location)

**Comment by dnedeltchev** [comment] 2022-02-12 09:54
Looks like a oneplus special "feature". My 7T is now on security updates only, I think, so it's game over. I'm not sure if it's worth keeping this open. Even if we find that it's the API failing, as Daniel pointed out, there is nothing that can be done.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dreimer1986** [comment] 2022-02-12 11:44
Likely this will happen. But we already had some geocoded location problem in the past and we found a way. Was a while ago, but maybe...
So, I have a log for you and a logcat. Quite not filtered, so handle with care ^^

[logcat.txt](https://github.com/home-assistant/android/files/8053280/logcat.txt)
[home-assistant.log](https://github.com/home-assistant/android/files/8053281/home-assistant.log)
.

**Comment by dreimer1986** [comment] 2022-02-12 11:46
The sensor passed information all the time and I walked while it was logging. That's why I passed the whole thing.

**Comment by dshokouhi** [comment] 2022-02-21 17:06
There are no failures in the logs related to the geocoded sensor, this is a case where simply the API has no results.

**Comment by dshokouhi** [comment] 2022-02-21 17:09
here is a thread of other one plus users where certain apps are messing with the geocode API, seems to be a device or manufacturer specific issue.

https://forums.oneplus.com/threads/android-location-geocoder-getfromlocation-stops-working-after-32-successfull-results.1458581/

you guys dont happen to have pokemon go or pikmin installed do you?

**Comment by dnedeltchev** [comment] 2022-02-22 10:22
Hi Daniel,
I do not have these games installed.

**Comment by dreimer1986** [comment] 2022-02-22 18:03
I do, but I never had these problems with LOS. And I removed all apps from Game Mode because it causes the GPS to be TERRIBLE in Pokemon Go.

**Comment by dshokouhi** [comment] 2022-02-22 18:10
> I do, but I never had these problems with LOS.

This points to a bug in the official ROM, and as we see in the link they already accepted the issue and notified their development team. Very specific testing done there and that is indeed the API we use

https://github.com/home-assistant/android/blob/master/app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt#L79

I think we may need to close this issue until we hear back from One Plus on what their development team said because this bugs behavior mimics the post in their forums.

**Comment by dnedeltchev** [comment] 2022-02-22 18:21
Yep, agreed. I'm OK to close this.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Closed** 2022-02-22 18:25 UTC
Labels: bug, sensor-tracking
