### ISSUE TITLE
Lights groups can't be dimmed up or down in Android Power Menu

### ISSUE THREAD

**Issue by lepeli** [home-assistant/android#1571] opened 2021-05-28 22:35 UTC
**Home Assistant Android version:**
2021.5.1-full
**Android version:**
11
**Phone model:**
Oneplus Nord (AC2003)
**Home Assistant version:**
core-2021.5.5
**Last working Home Assistant release (if known):**

**Description of problem:**

You are not able to dim a group of lights (with dimmable lights) in the new power menu.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/24854702/120047772-b9dc4980-c015-11eb-88d8-e04181478f87.png)
![image](https://user-images.githubusercontent.com/24854702/120047785-c1035780-c015-11eb-85e7-cafd35eb9695.png)

**Additional information:**
In the screenshots the lights group is called "Chambre Yvan"

**Comment by dshokouhi** [comment] 2021-05-28 22:46
duplicate of #1546 and already fixed in the latest beta

**Closed by dshokouhi** 2021-05-28 22:46 UTC
Labels: bug
