### ISSUE TITLE
Device not connected to local push notifications

### ISSUE THREAD

**Issue by dfsx1** [home-assistant/android#2312] opened 2022-02-24 12:46 UTC
**Home Assistant Android version:** 2022.2.1 minimal
**Home Assistant version:** 2022.2.9

**Description of problem:**
Calling service notify.mobile_app_<device_id> returns error: 
> Device not connected to local push notifications

**Additional information:**
In Companion app:
- localUrl is: false and usesInternalSsid is: false
- I can't configure "Internal" HomeAssistant URL (it's greyed out)
  HomeAssistant URL is set to https://.local:8123/ (with self-signed SSL certificate)
- Persistent Connection Settings is set to: always
- I never see persistent notification about websocket connection?
  
In Android:
- Google Play services disabled
- Sensors Off (Developer Options)
- Connected to Wifi, but can only make local connections (no internet)
  Possibly related to: #2273
  
Everything else works in the companion app, no connection issue to the HomeAssistant instance.
Only local push notifications are not working.

**Comment by dshokouhi** [comment] 2022-02-24 14:34
> * I never see persistent notification about websocket connection?
> * Connected to Wifi, but can only make local connections (no internet)


this is a duplicate of #2273

the persistent connection has a constraint that a valid network connection needs to be established.

The error message you see is because you are sending a notification to a device that is not connected via local push so that is correct.

**Closed by dshokouhi** 2022-02-24 14:34 UTC
Labels: bug

**Comment by dfsx1** [comment] 2022-02-24 16:10
@dshokouhi 

> this is a duplicate of #2273

But creator of that ticket reports that he initially has a working websocket.
I never get a websocket (probably also not when I bypass the valid network connection contraint).

https://github.com/home-assistant/android/blob/9861462a1732fc8e372c7d60db4b088a5d9a0c26/app/src/main/java/io/homeassistant/companion/android/websocket/WebsocketManager.kt#L57

I think my problem is that the Companion app does not allow me to configure a "Internal" HomeAssistant URL.
(because of self-signed SSL?)

localUrl is: false and usesInternalSsid is: false
and because of that isInternal() and shouldWeRun() in WebsocketManager.kt return false
and the socket is never created?!

https://github.com/home-assistant/android/blob/6994eacf375063246978af7e8ce1da47c0c07ac5/common/src/main/java/io/homeassistant/companion/android/common/data/url/UrlRepositoryImpl.kt#L127-L134

https://github.com/home-assistant/android/blob/953374a0ba0dfc317b9e48acdfd5c0d286208579/app/src/main/java/io/homeassistant/companion/android/websocket/WebsocketManager.kt#L116-L118

https://github.com/home-assistant/android/blob/953374a0ba0dfc317b9e48acdfd5c0d286208579/app/src/main/java/io/homeassistant/companion/android/websocket/WebsocketManager.kt#L127-L138

**Comment by dfsx1** [comment] 2022-02-24 16:17
> you can only configure internal URL after defining Home WiFi SSID just above the Internal URL.

Configuring WiFi SSID complains about Location sensor disabled, because I have Sensors Off (Developer Options).
I'll try to disable that for now, configure it and hopefully I can disable it again afterwards :)

**Comment by dfsx1** [comment] 2022-02-24 16:24
> That is not correct.

The popup really tells me to first enable the Location sensor and says if I don't enable, the sensor and settings also won't work.
Nothing about app permissions yet at this stage :)

**Comment by dshokouhi** [comment] 2022-02-24 16:31
> The popup really tells me to first enable the Location sensor and says if I don't enable, the sensor and settings also won't work. Nothing about app permissions yet at this stage :)

This is the pop-up text that shows up when the app does not have location permission and you attempt to add a Home Wifi SSID:
https://github.com/home-assistant/android/blob/953374a0ba0dfc317b9e48acdfd5c0d286208579/common/src/main/res/values/strings.xml#L264


![image](https://user-images.githubusercontent.com/1634145/155566176-6d583d1d-97ba-4ea2-9bd6-019865e2812a.png)


Did you take a moment to click on Yes on the pop-up to see what it does? Because if you did you would've seen the permission prompt and not anything about the android app location sensors.

![image](https://user-images.githubusercontent.com/1634145/155566382-ecb18d88-fd1a-48da-b552-ff9e3720746a.png)

**Comment by dfsx1** [comment] 2022-02-24 17:21
> This is the pop-up text that shows up...

Yes, that was a 2nd popup I got after first having to enable the global Location sensor/setting 😊

I configured my *hidden SSID (had to type it manually) and see the Internal HomeAssistant url in settings again.
Also enabled the prioritize Internal Url setting, which hints me about typically leaving location off 👍
Unfortunately Companion logs show me something is still wrong with localUrl:
```
UrlRepository: localUrl is: false and usesInternalSsid is: true
UrlRepository: Using external URL
```

**Comment by dshokouhi** [comment] 2022-02-24 17:25
> Unfortunately Companion logs show me something is still wrong with localUrl:

the internal URL is either null or blank when it see's this. If the field was prefilled in can you try adjusting it slightly?

https://github.com/home-assistant/android/blob/6994eacf375063246978af7e8ce1da47c0c07ac5/common/src/main/java/io/homeassistant/companion/android/common/data/url/UrlRepositoryImpl.kt#L132

**Comment by dfsx1** [comment] 2022-02-24 17:30
> If the field was prefilled in can you try adjusting it slightly?

Yes that worked!👍
`localUrl is: true and userInternalSsid is: true`

**Comment by dfsx1** [comment] 2022-02-24 17:39
However, still don't see a persistent notification about any websocket connection.
(Also tried toggling the Persistent Connection Never/Always).

Still error: `Device not connected to local push notifications.`
I think you're right about #2273 being my (final) issue.
I'll do some more testing/debugging on this.

Thank you for your help so far @dshokouhi, much appreciated!
Unbelievable how fast you responded 😎
