### ISSUE TITLE
Swipe to refresh at Android App

### ISSUE THREAD

**Issue by Cosmicbase** [home-assistant/android#3476] opened 2023-04-16 09:02 UTC
Home Assistant Android app version(s):
beta-9942-64ee62b8-full 

Android version(s):
13

Device model(s):
Samsung Galaxy S22 Ultra (SM-S908B) 

Home Assistant version:
Home Assistant 2023.4.4
Supervisor 2023.04.0
Operating System 9.5
Frontend 20230411.1 - latest 
 

Last working Home Assistant release (if known): 
Never

Description of problem, include YAML if issue is related to notifications:

I want useful Feature. 
With Home Assistant ios there is a swipe to refresh function in the app.  Can this also be installed in the Android app?

**Comment by dshokouhi** [comment] 2023-04-16 09:07
Duplicate of #31

**Closed** 2023-04-16 09:07 UTC
Labels: enhancement

**Comment by monte-monte** [comment] 2023-10-07 18:18
@dshokouhi please reconsider.

**Comment by dshokouhi** [comment] 2023-10-07 18:21
@monte-monte please dont tag me in old and closed issues
