### ISSUE TITLE
Companion app crashes on new section dashboard type, since 2024.9.0

### ISSUE THREAD

**Issue by LukeMondy** [home-assistant/android#4615] opened 2024-09-08 12:03 UTC
**Home Assistant Android app version(s):**

**Android version(s):**
8.1.0

**Device model(s):**
SONOFF NSPanel Pro Smart, px30_evb

**Home Assistant version:**
2024.9.1

**Last working Home Assistant release (if known):**
2024.8.3

**Description of problem, include YAML if issue is related to notifications:**

When my companion app tries to load a dashboard that uses the new Sections interface, the app freezes, and essentially reboots. It will keep rebooting unless I manually quit the app via Android.

This was not an issue on 2024.8, but when I upgraded to 2024.9.0, and also .1, it happens. Other dashboard types seem to work OK.

**Companion App Logs:**
[homeassistant_companion_log_8-8-2024_21-50-25_095045.txt](https://github.com/user-attachments/files/16922020/homeassistant_companion_log_8-8-2024_21-50-25_095045.txt)

```

```

**Screenshot or video of problem:**

https://github.com/user-attachments/assets/56af0fb5-7074-47c7-a5dc-4a728bd4241d

**Additional information:**

**Comment by ivorsmorenburg** [comment] 2024-09-08 13:17
Looks like for the traces you gave point to an issue with WebView `android/webkit/PacProcessor` when using CookieManager  for non wear devices... 

Here is some info about the WebView, I feel you might need to update it or install chrome. https://stackoverflow.com/a/70867926

**Comment by jpelgrom** [comment] 2024-09-08 13:20
Probably a duplicate of: home-assistant/frontend#21900

**Comment by dshokouhi** [comment] 2024-09-08 16:27
closing as duplicate of the above frontend issue, same device and behavior

**Closed by dshokouhi** 2024-09-08 16:27 UTC
Labels: bug, webview
