### ISSUE TITLE
Encrypted notifications

### ISSUE THREAD

**Issue by iulko** [home-assistant/android#4444] opened 2024-06-09 13:48 UTC
From what I gather, the notifications in homeassitant are not end to end encrypted. This means that if you use notifications thru google or apple service than they can read the conent. Signal app on the other hand is using notifications only to wake up the app, to keep things private, there is a whole mastodon thread where the CEO explain how they do it. Is something like this possible with companion app for HA?

**Comment by dshokouhi** [comment] 2024-06-09 14:54
Duplicate of #97

**Closed by dshokouhi** 2024-06-09 14:55 UTC
Labels: enhancement
