### ISSUE TITLE
Android Automotive Support

### ISSUE THREAD

**Issue by andynash** [home-assistant/android#3402] opened 2023-03-06 13:30 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Availability of the Home Assistant app for cars running [Android Automotive OS (AAOS)](https://en.wikipedia.org/wiki/Android_Automotive).

The end result would be similar to Android Auto, though more access to car data/functionality may be possible, and larger screens are generally available. Example functionality might include:

- Provide a prominent "Assist" button, allowing the [recording of voice commands/queries](https://developer.android.com/training/cars/apps#record_from_the_car_microphone) to be processed directly via HA's Assist
  - In an ideal world, allow a driver to replace Google Assistant with HA Assist as default when pressing the vehicle's 'talk' button, or allow HA to listen for a keyword!

- A car-optimised dashboard (as already envisaged for AA) for relevant/appropriate entities/actions, e.g. driveway lighting, home heating etc that need to be triggered manually rather than via automation.
    - Ideally this should be a dynamic list, controllable within HA, showing entities/action based on e.g. location, fuel/charge level, driver identity etc.

- Display a (safe) subset of Home Assistant notifications as notifications or toasts within AAOS.

- As close to full access to HA as possible, whilst parked, as the car is then just another touchscreen.
    - N.b. I believe this can allow access to media so long as this stops when the car is on the move.

- In an ideal world it would be great to be able to trigger a specific application to open in the car (e.g. nav when you get in, a charging app when stopped at a public charge point, or HA when nearing home etc). This would of course add rather than detract to safety - an example of how HA can contribute positively to the car technology ecosystem.

- Providing the live location of the car to HA as a device_tracker.

- Providing other vehicle data to HA, such as fuel, battery charge info, via the [available Android APIs](https://developer.android.com/training/cars/apps#car-hardware).

The latter two allow for numerous automation possibilities based on information received from the car.

**Describe alternatives you've considered, if any**

Android Auto (AA): Volvo AAOS cars do not support AA. Other brands may do, though I'm not aware of any personally.

Google Assistant: Voice control is great but has obvious limitations. Sometimes a screen is better at providing information, and even at receiving commands, if e.g. buttons are displayed in a context-aware manner and are one-touch actions.

As for Voice, HA Assist would also handle some requests for status better than GA, as well as custom statements/responses based on the panoply of bespoke data HA has to hand, such as "who is at home?" or "where is so-and-so?" (response: "so-and-so is at xxxxx, directions have been sent to the car?") etc.

**Additional context**

While abiding by very similar (though not identical) rules as Android Auto, an Android app can be made available for cars running AAOS.

AAOS has been deployed or announced by major brands such as Volvo/Polestar, Renault/Nissan/Mitsubishi, Ford/Lincoln, Lucid, Honda, BMW and likely more.

Brands that use AAOS are switching to the platform for their entire model range rather than here and there. For example, the first was the first Polestar in 2018, and all Volvos have been AAOS since mid 2022. More recently Volkswagen and BMW announced their next car OSs would be based on AAOS.

AAO is likely to become a (if not the) dominant car infotainment operating system.

For iPhone users CarPlay is deployed as an AAOS app, and can then 'take over' the entire screen. The concept of CarPlay as an OS does not appear to be taking off.

AAOS looks set to supercede AA over time, though of course AA cars will remain in use for many years (and AA itself may remain in order to provide access to additional apps/functionality on a phone, on top of AAOS, similar to CarPlay). AA appears to me to be seen by Google as a stepping stone/stopgap solution to buy time while AAOS is developed and embedded with cars and also to provide a 'way in' to manufacturers, beating others such as Apple to the punch.

Google's documentation seems to suggest that an app made ready for Android Auto is essentially ready for Android Automotive - the process for making an AAOS app appears to be similar/the same, though as mentioned some rules/guidelines differ a little.

There may of course be some amount of additional work required to adapt the app for AAOS.

If not, or after this work is complete, my understanding is that it is then up to the vehicle manufacturers to 'admit' the HA app into 'their' Google Play store.

This is a crucial difference between AAO and AA - manufacturers have zero control over AA apps, however for better or worse, AAOS Play Store is a manufacturer 'walled garden'. For example I understand Polestar has YouTube and the Vivaldi browser, Volvo allows neither 🤦, and they are within the same automotive group.

Given the significance of the AAOS platform, and the speed with which Android Auto support was added to HA, my working assumption is that adding support to HA is only half of the battle. Getting manufacturers to include the app in their stores may be more challenging.

If so, then how can this be encouraged by us, as HA users and vehicle owners? Is there a submission process/route from the development/Google end of things to the manufacturers, or is it simply a case of trying to find a way to the people who matter at each manufacturer?

Presumably representatives of HA can also directly approach the manufacturers at that point. It may be wise to coordinate these approaches?

Given each manufacturer will decide for themselves, is there anything we can provide such decision-makers with, to help persuade them - e.g. boxes already ticked by the app, attainment of any specific standards defined by Google?

In my case I'm thinking of Volvo for example. Anything that can be done to reassure them of the app's respectability and commitment to safety will likely help. For example we can highlight the prowess of the HA project as a whole (popularity, code quality, project size and activity etc), but what can we tell them from a safety or other point of view that may encourage them to include the app in their Play store?

These may be helpful:

1. [Android for Cars](https://developer.android.com/cars)
2. [Volvo Developer Website: In-Car Apps](https://developer.volvocars.com/in-car-apps/)
3. [Android Emulator](https://developer.volvocars.com/in-car-apps/android-emulator-xc40/) (based on Volvo C40)

**Comment by dshokouhi** [comment] 2023-03-06 18:38
This is a very detailed request listing many many features into the same request. For the purpose of this request we will be closing it once there is a first PR submitted for an MVP. Do not expect all features mentioned in this request to be completed when this issue closes.

**Comment by andynash** [comment] 2023-03-23 17:24
Sure, though the request itself (AAOS support) is pretty straightforward - I was just providing the additional context asked for in the template.

To simplify:

"I'd like to see the functionality now available for Android Auto made available for AAOS, arguably the more important of the two platforms."

There's certainly no expectation that everything mentioned will be included 👍 Sorry if that wasn't clear enough - I was just providing additional context and suggestions/vision around and beyond the basic request.

Some of the questions in the request are aimed at working out how simple this request is - perhaps very, perhaps not. If someone familiar with the work done on Android Auto is able to have a go at answering them to the best of their current knowledge that would be a great start perhaps?

Re PR/MVP etc, I'm not that familiar with Github, so I'm afraid I've no idea whether there is an ask for me in your comment, or where this goes from here?

**Comment by dshokouhi** [comment] 2023-03-23 18:42
If you haven't already seen it, there is an open PR to take care of this request :)

**Closed** 2023-03-31 21:54 UTC
Labels: enhancement

**Comment by andynash** [comment] 2023-04-10 14:56
Great progress! (I think? tbh not sure what I am looking at 😁) Regarding the referenced issue #3423, what does this mean for getting the app working in a real car?

For example: Does anything need to be published to the Play Store? Do we need to speak to manufacturers to get this approved within their stores? Do we need to wait for a future HA Android release?

**Comment by dshokouhi** [comment] 2023-04-10 14:58
@andynash we are working on those specifics. When we have something to announce we will announce it. As of now things are in internal testing until we move forward and we are not sure when that will happen.

**Comment by HWiese1980** [comment] 2023-05-27 21:15
Are there any news yet?

**Comment by josecarre** [comment] 2023-06-14 07:08
In yesterday's new android HA companion release I see some AAOS movevent, [in the release notes](https://github.com/home-assistant/android/releases/tag/2023.6.0) there is a note:

> Android Automotive Module by @googlvalenzuela in https://github.com/home-assistant/android/pull/3423

So it seems that [PR](https://github.com/home-assistant/android/pull/3423) was finally added, right? Now we depend on Volvo to take action and add it to their Play Store wallet garden? Or any way to manually install?

Thanks

**Comment by HWiese1980** [comment] 2023-06-14 07:42
@josecarre 

> Now we depend on Volvo to take action and add it to their Play Store wallet garden?

Probably... Unfortunate. Then all hope is lost...

**Comment by HWiese1980** [comment] 2023-06-14 17:10
> This was just added to Polestar!

Oh! Then, all hope is not lost?

**Comment by dshokouhi** [comment] 2023-06-14 17:30
Hey all so as of now we are live in 2 places. Google Play Store and also on Polestar (thanks to users for confirming!).

Some manufacturers do not include Google Automotive Services (GAS) for those manufacturers we probably need to wait for #3570 to merge so we can satisfy that need.

I am also not sure if you can side load an APK to the car, but if you are able to send data to it then it may work. It probably won't hurt to try if you are familiar with the process. But keep in mind its entirely possible side loading is blocked certain forks.

**Comment by thehedgefrog** [comment] 2023-06-14 17:32
Hi @dshokouhi - I did notice with my Polestar that my location works, however the battery state of charge reports 0.

**Comment by dshokouhi** [comment] 2023-06-14 17:35
All lets not add additional issues here please. It will get lost in the mix. Please file a new issue if you believe you found an issue.

This issue was related to the availability of the app itself which is now solved.

@thehedgefrog  battery state is for android itself not the same thing as the one in the car, if you need your EV status you still need to wait for #3399

**Comment by dshokouhi** [comment] 2023-06-14 18:03
@HWiese1980  have you tried searching for the app yet in your car? I believe Volvo uses the play store itself so it should show up there.

**Comment by HWiese1980** [comment] 2023-06-14 18:08
Not yet, gimme a second, I'll go look for it. 

Sorry, I'm in general a good bit disappointed about how car manufacturers seem to treat AAOS and the apps. I have had the car for a good month now and I had hoped there would be a few more apps already available for it. Especially Deezer for example, which seems to be the only music streaming app not available for AAOS on my XC40. 

Anyway, I'll go have a look and report back. Thanks for the hint.

**Comment by josecarre** [comment] 2023-06-14 18:13
> @HWiese1980 have you tried searching for the app yet in your car? I believe Volvo uses the play store itself so it should show up there.

wow, I've just checked and it's there in my 2023 XC60 PHEV! this is great!

Its listed in Play Store:
![image](https://github.com/home-assistant/android/assets/10371413/f91f4ec2-4818-4b9f-bcf7-21800b162c20)

![image](https://github.com/home-assistant/android/assets/10371413/0ab5df14-7f37-4d42-a3f8-c4b16e015a01)

And now I can see all HA stuff, car included with gipsy node-red flow hahaha

![image](https://github.com/home-assistant/android/assets/10371413/4a6b3d58-d8d7-48a6-a0f6-1e9cbc7e085d)

The sensors detected by HA as where the device companion is installed are not working fine, but its clearly a different problem, this one seems at leat on a very good path! thanks @dshokouhi

**Comment by HWiese1980** [comment] 2023-06-14 18:40
Holy shhh! Yeah, it's there and it works! 🥳🥳🥳

One thing that I noticed besides the battery sensors not working: when I start the app, I always have to manually switch to Native Mode. The "other" mode that starts when I open the app does not work that reliable, so I would like to have the option to always launch into the native view. Is that possible?

**Comment by dshokouhi** [comment] 2023-06-20 13:19
> @josecarre I also have a 2023 XC60, can you please share more information about your dashboard? I installed the app in the car but I don't have a sensor for the fuel or the mileage.

Those sensors don't exist yet 😉

**Comment by josecarre** [comment] 2023-06-20 13:48
> @josecarre I also have a 2023 XC60, can you please share more information about your dashboard? I installed the app in the car but I don't have a sensor for the fuel or the mileage.

Those sensors and car info are coming from a node-red flow that pulls the info from Volvo cloud API (the one that feeds the Volvo Cars app), you have the info here: https://github.com/home-assistant/core/issues/61785#issuecomment-1584970951

**Comment by andynash** [comment] 2023-06-26 10:47
This is great news - the car was away for a month or so with a repair, and I found HA ready to install when it came back!

Presumably any improvements or bugs should be filed separately as new issues.

I'll be setting up a dashboard specifically for use in the car - one thing I'll request when I get a moment is the ability to change the scale (e.g. to 200%), at least for the left-had navigation - native mode is a little small for the car screen. And of course favourites are needed for the non-native mode, but that I believe is a long-standing Android Auto request.

**Comment by TheSleepySlee** [comment] 2023-08-04 07:37
How are you able to generate nice views?
When I start the app on my car, I cannot choose which view is displayed, I have default view (Roller shutter, etc...)
I have create a specific dashboard, and assigned this dashboard to a HA user, which I used to log in from my car, but don't work.

**Comment by HWiese1980** [comment] 2023-08-04 07:54
As far as I know you can't. It's a limitation by Google, preemptive obedience, if you ask me, to "reduce distraction" and avoid accidents. In my opinion it's impracticable cow dung. 

The Companion App developers do a decent job, as far as I can tell, obeying these total crap rules, but they are forced to deliver this dead birth of a user experience.

**Comment by TheSleepySlee** [comment] 2023-08-04 08:02
Well, my understanding is that you can.

- Google is forcing look & feel to be drivingOptimized in their gridView
- I am talking about how the gridView is filled. When I start the app, it is showing ALL my elements by category. I would like to reduce the elements lists to just a few, instead of having all my switches, all my lamps, all...
- Being able to configure this either directly in the HA instance, or thru settings page than could be accessed while parked would be good too.

**Comment by HWiese1980** [comment] 2023-08-04 08:38
I think the app developers are working on a better gridView with favorites and such stuff. AFAIK it is already available in the beta channel.

**Comment by jpelgrom** [comment] 2023-08-04 09:25
Correct, favorites are available in the beta and replace the list of domains on the home screen, but there is no way to add favorites for Automotive from the Play Store yet (as managing those currently requires access to the normal non-template UI, which is not allowed).

**Comment by HWiese1980** [comment] 2023-08-04 09:29
Shaking my head... These requirements are seriously ridiculous... as if everyone who enabled the normal UI would immediately run over the next child... violently shaking my head here. 

My frustration, I'm sorry about it.

**Comment by TheSleepySlee** [comment] 2023-08-04 09:35
@HWiese1980 it's a question of liability
@jpelgrom I registered to beta, and need to check more, but why not fetch the list of devices from special dashboard, instead of favorites?

There are some things that are allowed while parked, details here: https://developer.android.com/docs/quality-guidelines/car-app-quality?category=iot#dec-22

Would need a dedicated activity, like settings page, that would only be accessible while parked.

**Comment by HWiese1980** [comment] 2023-08-04 09:39
@TheSleepySlee Of course it is! That's why we have invented something called non-liability clauses. I am a grown up man for eff's sake, I should be allowed to decide myself and not be patronized like that. I'm not a child. I know what I'm doing! And I can, and should, take full responsibility for it if anything goes wrong.

**Comment by jpelgrom** [comment] 2023-08-04 09:41
Notice how my comment says "yet" - there are improvements possible but this feature was only added in the last month and will take time and consideration, especially as we wish to share code with Android Auto.

**Comment by andynash** [comment] 2023-08-04 11:09
> Correct, favorites are available in the beta and replace the list of domains on the home screen, but there is no way to add favorites for Automotive from the Play Store yet (as managing those currently requires access to the normal non-template UI, which is not allowed).

Can I just check I've understood this correctly:

- the 'non-template' UI is the so-called 'native' view

- the native view that was working fine when parked in a previous version is now removed as it is not allowed? Interested in knowing whether this was self-policed or spotted by Google, just because I'm curious how this stuff works...

- as a result, unlike Auto, Automotive cannot (yet) configure favourites, so the favourites feature works in Auto but not Automotive?

**Comment by andynash** [comment] 2023-08-04 11:12
On what can and can't be done, liability etc, I think it's important to realise that with cars, it is not enough for the car owner to sign off on liability, as the consequences fall heavily on uninvolved third parties: those killed or injured are unlikely to be satisfied by a waiver and rightly so in my opinion.

That means manufacturers/Google are likely to be the ultimate arbiters of available functionality whether we like it or not.

That said I can't think of a good reason for removing native view whilst parked even now, and I also suspect it would eventually be possible to define something less rigid that the grid/list template currently available (e.g. by limiting the number, size, spacing etc of elements on a page, or by creating a qualitative approval process).

I don't expect the latter imminently though as Automotive itself is still relatively nascent.

Hopefully solving the favourites configuration will at least make Automotive functional again in due course...

**Comment by jpelgrom** [comment] 2023-08-04 11:13
> Can I just check I've understood this correctly:
> 
> * the 'non-template' UI is the so-called 'native' view
> * the native view that was working fine when parked in a previous version is now removed as it is not allowed? Interested in knowing whether this was self-policed or spotted by Google, just because I'm curious how this stuff works...
> * as a result, unlike Auto, Automotive cannot (yet) configure favourites, so the favourites feature works in Auto but not Automotive?

- Correct
- Yes, this was removed by request from Google from the Play Store version of the Automotive app
- It technically works in Automotive but there's no way to add favorites

**Comment by josecarre** [comment] 2023-08-04 15:45
> > Correct, favorites are available in the beta and replace the list of domains on the home screen, but there is no way to add favorites for Automotive from the Play Store yet (as managing those currently requires access to the normal non-template UI, which is not allowed).
> 
> Can I just check I've understood this correctly:
> 
> * the 'non-template' UI is the so-called 'native' view
> * the native view that was working fine when parked in a previous version is now removed as it is not allowed? Interested in knowing whether this was self-policed or spotted by Google, just because I'm curious how this stuff works...
> * as a result, unlike Auto, Automotive cannot (yet) configure favourites, so the favourites feature works in Auto but not Automotive?
> 
> I have 2023.7.5-full and am in the beta channel, so I presume I have the latest version.

Yes, [I asked why in the PR when they removed the native mode](https://github.com/home-assistant/android/pull/3612#issuecomment-1645753898) from it (very sad day :( ) and its confirmed thats it's coming from Google. Its a real pity because it was only allowed when car was not moving... but I guess anyone did like to have such amazing power even parked (like watching media videos...etc, I tested during those day and worked like a charm... and many other stuff that... will be missed a lot).

**Comment by HWiese1980** [comment] 2023-08-06 10:40
I wonder why there are actual games on the AAOS Play Store, when everything that might remotely distract the driver for the fraction of a millisecond and could potentially cause a fatal accident with multiple casualties even from a parked car, is forbidden. Double standards? 

I know, the whole discussion is in vain because Google doesn't give any fucks, and I probably annoy the hell out of you guys, which I apologize for. I simply do not know where else to effectively leave my deep and heavy frustration about this whole situation. I could try screaming it into my pillow, but I suppose that wouldn't feel as effective.

**Comment by Emacee** [comment] 2023-08-13 20:03
Any chance of the native app getting support to send sensor values (location, SoC, current status of locks/charging etc.) to Home Assistant? The CarStatsViewer app is able to send that data via webhook but is feels like some sort of workaround. Is this something that is allowed within the Playstore guidelines?

**Comment by dshokouhi** [comment] 2023-08-13 20:15
> Any chance of the native app getting support to send sensor values (location, SoC, current status of locks/charging etc.) to Home Assistant? The CarStatsViewer app is able to send that data via webhook but is feels like some sort of workaround. Is this something that is allowed within the Playstore guidelines?

Please don't comment on old closed issues with additional feature requests. Instead create a new request for each individual request. Location tracking is supported on cars with Google Automotive Services only.
