### ISSUE TITLE
Cannot login using external URL. No problem using via browser

### ISSUE THREAD

**Issue by bahamut657** [home-assistant/android#2306] opened 2022-02-22 15:36 UTC
**Home Assistant Android version:**
2022.2.1

**Android version:**
Android 11

**Phone model:**
Cubot Quest

**Home Assistant version:**
2022.2.9

**Description of problem:**
Cannot login using Android APP using external URL (no self-signed certificate). App crashes after pressing Complete once successfully login is done (in the last screen, where it asks for device name). No problem using http and internal URL.
It seems strange because APP crashes before showing changelogs.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
Attaching ADB results in this traceback:

```
02-22 16:30:22.320 15800 15800 D UrlRepository: localUrl is: false and usesInternalSsid is: false
02-22 16:30:22.326 15800 15800 D UrlRepository: localUrl is: false and usesInternalSsid is: false
02-22 16:30:22.327 15800 15800 D UrlRepository: Using external URL
02-22 16:30:22.840 15800 15800 I Sentry  : Not possible to read external files directory
02-22 16:30:22.946 15800 15800 E AndroidRuntime: FATAL EXCEPTION: main
02-22 16:30:22.946 15800 15800 E AndroidRuntime: Process: io.homeassistant.companion.android, PID: 15800
02-22 16:30:22.946 15800 15800 E AndroidRuntime: retrofit2.HttpException: HTTP 415 Unsupported Media Type
02-22 16:30:22.946 15800 15800 E AndroidRuntime:        at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
02-22 16:30:22.946 15800 15800 E AndroidRuntime:        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
02-22 16:30:22.946 15800 15800 E AndroidRuntime:        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
02-22 16:30:22.946 15800 15800 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-22 16:30:22.946 15800 15800 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-22 16:30:22.946 15800 15800 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:923)
02-22 16:30:22.982 15800 15800 I Process : Sending signal. PID: 15800 SIG: 9
02-22 16:30:23.088  2505  4943 I ActivityManager: Process io.homeassistant.companion.android (pid 15800) has died: prcp TOP 
02-22 16:30:23.093  2112  2112 I Zygote  : Process 15800 exited due to signal 9 (Killed)
02-22 16:30:23.134  2505  2533 I libprocessgroup: Successfully killed process cgroup uid 10223 pid 15800 in 45ms
02-22 16:30:23.154  2505  2525 W ActivityManager: setHasOverlayUi called on unknown pid: 15800
```

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by bahamut657** [comment] 2022-02-22 16:26
Version: 2022.1.1-full

I use a reverse proxy that provides SSL encryption. No problem at all using from browser (so I cannot understand the problem,even if could be in the proxy).

Another thing that point my head to the ChangeLog screen is:
If I use the local endpoint for the first access, showing the ChangeLog correctly, than I can use external endpoint with no problems.

Can you share if is there an HTTP request to retrieve ChangeLog screen content? 

Thanks and regards

**Comment by dshokouhi** [comment] 2022-02-22 16:31
> I use a reverse proxy that provides SSL encryption. No problem at all using from browser (so I cannot understand the problem,even if it could be in the proxy).

the app is more than  just a browser it also makes REST and Websocket requests, both of which are not done in a browser



> Can you share if is there an HTTP request to retrieve ChangeLog screen content?

There is no HTTP request, the changelog is just a local XML file that gets loaded upon a new version being installed



> If I use the local endpoint for the first access, showing the ChangeLog correctly, than I can use external endpoint with no problems.

there is something wrong with your reverse proxy setup, maybe this page will help: https://companion.home-assistant.io/docs/troubleshooting/networking#addendum-reverse-proxy-via-nginx

**Comment by bahamut657** [comment] 2022-02-22 16:50
My configuration.yaml is correct. I double checked in your link.
Websocket works great using via browser so I think it cannot be a problem at all.
What do u mean for REST Request (I see POST and GET request done by APP, no WS or other request are done before logging in)
Why these loglines?
```
02-22 16:30:22.326 15800 15800 D UrlRepository: localUrl is: false and usesInternalSsid is: false
02-22 16:30:22.327 15800 15800 D UrlRepository: Using external URL
02-22 16:30:22.840 15800 15800 I Sentry  : Not possible to read external files directory
02-22 16:30:22.946 15800 15800 E AndroidRuntime: FATAL EXCEPTION: main
```

Is it possible that the problem is reading the XML file? (no idea why with local insecure address it works...)

**Comment by dshokouhi** [comment] 2022-02-22 16:59
> Websocket works great using via browser so I think it cannot be a problem at all.

The frontend does its own websocket request which is separate from the apps



The app makes no distinction between internal and external URL, we use them exactly the same.  The fact that it works for you locally and not externally suggests the issue is with your proxy setup. The app cannot help you solve you networking setup.


> What do u mean for REST Request (I see POST and GET request done by APP, no WS or other request are done before logging in)

https://developers.home-assistant.io/docs/api/rest/



> Can you explain these loglines ?
> 
> ```
> 02-22 16:30:22.326 15800 15800 D UrlRepository: localUrl is: false and usesInternalSsid is: false
> 02-22 16:30:22.327 15800 15800 D UrlRepository: Using external URL
> 02-22 16:30:22.840 15800 15800 I Sentry  : Not possible to read external files directory
> 02-22 16:30:22.946 15800 15800 E AndroidRuntime: FATAL EXCEPTION: main
> ```

- first line is that there is no local URL and home wifi SSID is not configured, not a bug just a debug statement
- second line is that we are using the external URL
- third line is that Sentry is having an issue reading files in your device, not an issue on my pixel
- fourth line is a HTTP 415 failure, seems like your proxy malformed a response and the server rejected it, probably rejected at the proxy?



> Is it possible that the problem is reading the XML file? (no idea why with local insecure address it works...)

no because its a locally stored file in the app, it doesnt care about your HA URL



> The problem is affecting only if external_url is used for first login, otherwise it works (so it does not seem a PROXY problem)

Actually first login uses a API call to retrieve the token and other bits of information, as your error is a 415 error your proxy has malformed the response. When you use internal IP you bypass the proxy and therefore bypass that API call.

As you have mentioned this works locally then your issue is directly related to your network setup, as we do not solve individual network problems here I am closing this bug. You should try on the forums and discord and talk to others with a proxy setup to see where yours is not correct.

if you are having issues logging in with your external URL due to missing API responses then more than likely a lot of other features in the app are not working like widgets and sensor updates.

**Closed by dshokouhi** 2022-02-22 16:59 UTC
Labels: bug, onboarding
