### ISSUE TITLE
Expose HA devices to Android 11's new ControlsProviderService

### ISSUE THREAD

**Issue by gausie** [home-assistant/android#920] opened 2020-09-11 21:31 UTC
**Is your feature request related to a problem? Please describe.**
Android 11 comes with a new API for controlling physical devices (see [their announcement](https://www.android.com/android-11/#a11-device-controls-article) and [the API spec](https://developer.android.com/reference/android/service/controls/ControlsProviderService))

**Describe the solution you'd like**
I would like to be able to add HA devices to my Android device control screen.

**Describe alternatives you've considered, if any**
It's possible that another app could implement this, but it would be preferable to integrate with Android's new relevant APIs with the first-party app.

**Comment by dshokouhi** [comment] 2020-09-11 21:35
Duplicate of #619

**Closed by dshokouhi** 2020-09-11 21:35 UTC
Labels: enhancement
