### ISSUE TITLE
Multiple Home Assistant Connections

### ISSUE THREAD

**Issue by Mattias314** [home-assistant/android#1414] opened 2021-03-08 18:49 UTC
**Is your feature request related to a problem? Please describe.**

I run multiple home assistant instances at multiple locations, but can only connect one to the app!

**Describe the solution you'd like**

It would be great to log into multiple home assistant installations. 

**Describe alternatives you've considered, if any**

Just using the webapp/urls is not as nice.  haha  I want to do location tracking/presence detection etc at the various locations as well as enjoy the continence of them all within one app instead of shortcuts.

**Additional context**

That's about it!  Thanks for considering this, I'd assume I'm not the only one?   :)

**Comment by dshokouhi** [comment] 2021-03-08 18:50
duplicate of #296

**Closed by dshokouhi** 2021-03-08 18:50 UTC
Labels: enhancement
