### ISSUE TITLE
Horizontal / Vertical stack causing dashboard to incorrectly display.

### ISSUE THREAD

**Issue by andrew176** [home-assistant/android#4357] opened 2024-04-21 09:19 UTC
**Home Assistant Android app version(s):** 2024.4.1-full

**Android version(s):** 14 UP1A.231005.007

**Device model(s):** Redmi 12 23053RN02Y

**Home Assistant version:** 2024.4.3

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

Any dashboard with vertical or horizontal stack causes really bad distortion of the dashboard using the app. If accessing home assistant via web browser there are no issues.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

Here is the dashboard of a horizontal stack using Chrome:

![lights](https://github.com/home-assistant/android/assets/53002572/f7d1623b-a8b7-43eb-b249-6d5311cda95e)

Here is the same dashboard using Home assistant android app

![Phone1](https://github.com/home-assistant/android/assets/53002572/09dbd7d1-eb54-4de2-b322-1c3ec22357e5)

Another dashboard on android app:

![phone3](https://github.com/home-assistant/android/assets/53002572/e952cd24-7765-4d14-8784-60b7149fd6b5)

Not using a horizontal stack using android app:

![phone2](https://github.com/home-assistant/android/assets/53002572/52f65e6e-c509-41c2-90a7-6ce10f563361)

**Additional information:**

**Comment by dshokouhi** [comment] 2024-04-21 16:21
Is Android system WebView up to date? This most likely cannot be fixed by the app even though you can only replicate in app.

**Comment by dshokouhi** [comment] 2024-04-21 17:09
duplicate of https://github.com/home-assistant/frontend/issues/20192

**Closed by dshokouhi** 2024-04-21 17:09 UTC
Labels: bug, question, webview
