### ISSUE TITLE
RFE: Customizable text (and possibly more) for websocket persistent notification

### ISSUE THREAD

**Issue by mattdm** [home-assistant/android#2267] opened 2022-02-12 17:05 UTC
**Is your feature request related to a problem? Please describe.**

The new websocket persistent notification actually provides a nice, quick shortcut to Home Assistant. However, after seeing it for a few hours, being told "Listening to Home Assistant via Websocket" is no longer really useful information. Further, while it's convenient to have "Websocket settings" there initially, that is not something one will normally want to change frequently.

I know the persistent notification must stay in order to keep Android from killing the app under pressure. That's fine. But as it is, the notification is using some of the _most valuable and scarce_ UI real estate (and visible/attention space) to just show a basically useless static message and a rarely-useful configuration link.

**Describe the solution you'd like**

1. I would like to be able to replace the text of the notification with something dynamic from the server.(Perhaps the state of some sensor or some attribute?)
2. I would like "Websocket Settings" to be removed from the notification, or at least made into a small gear ⚙️ icon. (Possibly shown with full text until clicked once, and then after that reduced.
3. As an AMAZING bonus, it would be nice to be able to actually have customizable active controls here. They could be text, icons, or more advanced widgets.

For the third point, I am primarily thinking switches and indicators (for most commonly accessed lights and scenes, for example), but it would be also useful to just have links to specific dashboard panels. These could either be configured per-user in the app, or on my server.

**Describe alternatives you've considered, if any**

If dynamic customization is not possible, it would be at least nice to be able to customize the text once to say something different ("Home Assistant quick access") — and I still think the Websocket Settings -> ⚙️ icon idea is good.

**Additional context**

None at the moment, but I'll edit some in if it comes up!

**Comment by dshokouhi** [comment] 2022-02-12 17:06
Duplicate of #2266

**Closed** 2022-02-12 17:07 UTC
Labels: enhancement

**Comment by dshokouhi** [comment] 2022-02-12 17:09
There are also multiple requests in here. Please split each one up into it's own request instead of combining them into one. The change of the button text for example is a separate request from changing the text of the notification.
