### ISSUE TITLE
Navigation error on Home Assistant for Android Auto

### ISSUE THREAD

**Issue by SanchoMax** [home-assistant/android#3479] opened 2023-04-18 06:21 UTC
I am using android auto 9.2.631214 for my 2020 Ram truck.  I have the home assistant icon and when I select it I have options like scenes, lights, switches, and a few others.  They all seem to work and I can control my lights and such from my truck.  The last option is Navigation.  When I click it it pauses for a few seconds and then has an error saying Android Auto isn't responding.  On my home assistant I have 2 people and 2 phone trackers.  I have quite a few zones on the map, probably around 150 to 200.  Here is part of the errors that show up in my logs on the companion app on my phone (Galaxy 21):

04-17 21:22:06.092 18930 18962 D LogcatReader: Done reading logcat for pid 18930
04-17 21:22:09.310 18930 18930 I MainVehicleScreen: Navigation clicked
04-17 21:22:09.355 18930 18930 W BpBinder: Large outgoing transaction of 1666352 bytes, interface descriptor <uncached descriptor>, code 2
04-17 21:22:09.355 18930 18930 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1666352)
04-17 21:22:09.355 18930 18930 E CarApp.Dispatch: Host unresponsive when dispatching call getTemplate onSuccess

There is much more to it, but didn't want to post it all to save space.  I was sent here by [dshokouhi](https://community.home-assistant.io/u/dshokouhi) in the home assistant forums.  Hope I am in the right place :)

Any troubleshooting appreciated.  If any other info is needed, please let me know.

Brian

**Comment by dshokouhi** [comment] 2023-04-18 13:24
Can you please confirm the app version you have installed?

**Comment by SanchoMax** [comment] 2023-04-18 20:03
beta-9948-32a79333-full

**Comment by SanchoMax** [comment] 2023-04-19 09:06
Updated to 2023.4.5 on companion app.  Will check if any difference on the way home.

Brian

**Comment by SanchoMax** [comment] 2023-04-28 10:43
Updated to companion app operating system 10.1, same issue 

Brian

**Comment by SanchoMax** [comment] 2023-05-27 13:02
Updated to companion app version 2023.5.4 and still get the same errors.   Anyone else able to get this working in a ram truck or is it because I have so many zones on the map?

Brian

**Comment by dshokouhi** [comment] 2023-06-26 22:39
@SanchoMax can you please get us some more logs around this issue? I am not sure if there is anything else but there might be something helpful. Be mindful to mask GPS coordinates and your URL if sharing the log file.

**Comment by dshokouhi** [comment] 2023-07-18 21:06
Is this still an issue in the latest version? If it is we need more logs please.

**Comment by SanchoMax** [comment] 2023-07-20 21:01
Yes there is still an issue.  I can not seem to find the logs like before.  When it first happened i cleared my logs, started Home Assistant on my android auto in my truck, and then looked at the logs to see the errors.  I seemed to have misplace the proper logs.  I went to Settings, System, Logs.  Then there is Assistant, Supervisor, etc.  Could you please direct me to the proper place in the logs to look.

Brian

**Comment by dshokouhi** [comment] 2023-07-20 21:02
> Could you please direct me to the proper place in the logs to look.

Settings > Companion App > Troubleshooting > Show and share logs

**Comment by dshokouhi** [comment] 2023-07-20 21:30
@SanchoMax I can reproduce the crash now. Had a chat with @jpelgrom and we noticed theres a hard limit set which seems to be device specific. In an emulator its set to 100. Will need to add some logic to account for this. Unfortunately this means we will not be able to show all your zones in a list.

```
2023-07-20 14:26:54.984 30658-30658 BpBinder                io....stant.companion.android.debug  W  Large outgoing transaction of 2040128 bytes, interface descriptor <uncached descriptor>, code 2
2023-07-20 14:26:54.984 30658-30658 JavaBinder              io....stant.companion.android.debug  E  !!! FAILED BINDER TRANSACTION !!!  (parcel size = 2040128)
2023-07-20 14:26:54.986 30658-30658 CarApp.Dispatch         io....stant.companion.android.debug  E  Host unresponsive when dispatching call getTemplate onSuccess
                                                                                                    android.os.TransactionTooLargeException: data parcel size 2040128 bytes
                                                                                                    	at android.os.BinderProxy.transactNative(Native Method)
                                                                                                    	at android.os.BinderProxy.transact(BinderProxy.java:584)
                                                                                                    	at androidx.car.app.IOnDoneCallback$Stub$Proxy.onSuccess(IOnDoneCallback.java:118)
                                                                                                    	at androidx.car.app.utils.RemoteUtils.lambda$sendSuccessResponseToHost$3(RemoteUtils.java:223)
                                                                                                    	at androidx.car.app.utils.RemoteUtils$$ExternalSyntheticLambda0.call(Unknown Source:6)
                                                                                                    	at androidx.car.app.utils.RemoteUtils.dispatchCallToHostForResult(RemoteUtils.java:86)
                                                                                                    	at androidx.car.app.utils.RemoteUtils.dispatchCallToHost(RemoteUtils.java:105)
                                                                                                    	at androidx.car.app.utils.RemoteUtils.sendSuccessResponseToHost(RemoteUtils.java:221)
                                                                                                    	at androidx.car.app.utils.RemoteUtils.lambda$dispatchCallFromHost$0(RemoteUtils.java:149)
                                                                                                    	at androidx.car.app.utils.RemoteUtils$$ExternalSyntheticLambda1.run(Unknown Source:6)
                                                                                                    	at androidx.car.app.utils.ThreadUtils.runOnMain(ThreadUtils.java:39)
                                                                                                    	at androidx.car.app.utils.RemoteUtils.dispatchCallFromHost(RemoteUtils.java:146)
                                                                                                    	at androidx.car.app.utils.RemoteUtils.lambda$dispatchCallFromHost$1(RemoteUtils.java:185)
                                                                                                    	at androidx.car.app.utils.RemoteUtils$$ExternalSyntheticLambda2.run(Unknown Source:8)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7918)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by jpelgrom** [comment] 2023-07-20 21:35
>  we will not be able to show all your zones in a list

(you should add navigation targets in favorites in a future PR)

**Comment by SanchoMax** [comment] 2023-07-20 22:41
> > Could you please direct me to the proper place in the logs to look.
> 
> Settings > Companion App > Troubleshooting > Show and share logs

TY

Brian

**Comment by SanchoMax** [comment] 2023-07-20 22:45
So what is the limit of a Ram truck?  Is there a listing somewhere of all vehicles?  If I get to the limit of, say 100, will it be the closest 100 to me, or alphabetical, or how does it decide?

Brian

**Comment by dshokouhi** [comment] 2023-07-20 22:50
> So what is the limit of a Ram truck?

We won't know until the PR is merged and we look at the Companion App logs as I am printing that data too.

> Is there a listing somewhere of all vehicles?

its set by the vehicle so unless someone has curated a list I dont think one exists



> If I get to the limit of, say 100, will it be the closest 100 to me, or alphabetical, or how does it decide?

alphabetical by entity ID for all navigable entities

More than likely after the favorites PR is merged there will need to be a follow up PR to add navigation entities as the current PR is designed for toggleable entities. From there though you still need to keep in mind favorites will be imposed by the same limit

**Comment by SanchoMax** [comment] 2023-07-20 23:05
TY so much for the replies

Brian

**Closed** 2023-07-21 01:47 UTC
Labels: bug, question, Android Auto

**Comment by dshokouhi** [comment] 2023-07-27 22:16
> More than likely after the favorites PR is merged there will need to be a follow up PR to add navigation entities as the current PR is designed for toggleable entities. From there though you still need to keep in mind favorites will be imposed by the same limit

PR: #3725
