### ISSUE TITLE
Home assistant app keeps crashing

### ISSUE THREAD

**Issue by AalianKhan** [home-assistant/android#3968] opened 2023-10-23 10:36 UTC
**Home Assistant Android app version(s):** 2023.10.2-full

**Android version(s):** android 13 OneUI 5.1

**Device model(s):** SM-S901W

**Home Assistant version:** 2023.10.5

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
When I open my companion app, I am greeted with a "Deceptive site ahead message". I then click "visit this unsafe website" and home assistant loads for a second and I can see the default dashboard but after 1 second, the app crashes and a prompt pops up saying "uninstall WebView updates, home assistant has crashed because of new WebView updates, do you want to uninstall". I have uninstalled with no change in outcome. I have also tried clearing cache. I have also reported to google that my domain is not a deceptive website, however, I have revived this message a few times in the past without the app crashing.

I am able to access home assistant on my chrome browser on all my devices, just not the app.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![Screenshot_20231023_063410_Device care.jpg](https://github.com/home-assistant/android/assets/39784853/0857e7bb-1fb2-4df9-a55c-84bb0f9486dc)

**Additional information:**

**Comment by dshokouhi** [comment] 2023-10-23 14:09
duplicate of #3418

the fix is to wait for Google to remove the warning

**Closed by dshokouhi** 2023-10-23 14:09 UTC
