### ISSUE TITLE
Horizontal overflow/scroll

### ISSUE THREAD

**Issue by marcselman** [home-assistant/android#2093] opened 2021-12-30 20:59 UTC
**Home Assistant Android version:**
2021.12.3-full

**Android version:**
Android: 11
Update: 2021-10-01
Build: Oxygen OS 11.0.11.11.KB05BA

**Phone model:**
OnePlus 8T

**Home Assistant version:**
2021.12.7

**Last working Home Assistant release (if known):**

**Description of problem:**
On every dashboard it's possible to scroll horizontally a bit.
I don't see the issue in the browser and on other phones.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![photo_2021-12-30_21-56-40](https://user-images.githubusercontent.com/514683/147787500-16015768-563d-4a56-9b79-d89c20e8f972.jpg)

**Additional information:**
Nothing

**Comment by dshokouhi** [comment] 2021-12-30 21:06
So you see this issue using the default theme?

**Comment by marcselman** [comment] 2021-12-30 21:15
Yes, I tried that as well

**Comment by dshokouhi** [comment] 2021-12-30 21:29
Interesting I cannot reproduce. And it looks fine in chrome for Android? This still might be a frontend issue

**Comment by marcselman** [comment] 2021-12-30 21:39
Yeah, like I said, I don't see this issue in browsers or other phones. Only on this phone in the Android app.
Check the video:
https://user-images.githubusercontent.com/514683/147789663-80ed059f-ae2b-4c40-904b-88d9a20e0bf8.mp4

**Comment by dshokouhi** [comment] 2021-12-30 21:45
Is Android system WebView up to date? Not running a custom ROM right?

**Comment by marcselman** [comment] 2021-12-30 21:46
Yes, stock up-to-date Android on OnePlus 8T

**Comment by dshokouhi** [comment] 2021-12-30 22:23
> Yes, stock up-to-date Android on OnePlus 8T

Android system WebView is actually updated in the play store. Do you have any custom cards? If so try disabling them too. This still feels like a frontend issue since we don't make any adjustments to the webview.

**Comment by marcselman** [comment] 2021-12-30 22:35
Should I then not see the same issue in the browser and on other phones?
I only see the issue on this phone and only in the native Android app.

**Comment by dshokouhi** [comment] 2021-12-30 22:37
> Should I then not see the same issue in the browser and on other phones? I only see the issue on this phone and only in the native Android app.

every device is different in how they implement webview and other APIs which is why i normally ask the user to check that Android System Webview is up to date. Most issues are resolved by updating that app.

https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en_US&gl=US

**Comment by marcselman** [comment] 2021-12-30 23:03
Yeah it's the latest version 96.0.4664.104 atm.
I'll try the beta.

**Comment by marcselman** [comment] 2021-12-30 23:37
I installed the beta, the issue went away. I uninstalled the beta and the issue did not come back. Very weird. Maybe a good fix for other people with issues on the latest version.
I guess we can close this issue?

**Comment by dshokouhi** [comment] 2021-12-31 00:22
yup we can close it, probably some weird caching issue is my guess :)

**Closed by dshokouhi** 2021-12-31 00:22 UTC
Labels: bug, webview
