### ISSUE TITLE
WearOS app stopped working in wlan, works through public domain

### ISSUE THREAD

**Issue by luixal** [home-assistant/android#3852] opened 2023-09-08 11:51 UTC
**Home Assistant Android app version(s):**
2023.8.2-full (latest?)

**Android version(s):**
Phone:
 - Android 13
Smart Watch:
 - System Version 11
 - Android Wear OS 11

**Device model(s):**
Phone: Samsung Galaxy S20 Ultra 5G
Smartwatch: Samsung Galaxy Watch 5

**Home Assistant version:**
Home Assistant OS core-2023.8.4

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
I've been using HA wearOS app in a Samsung Galaxy Watch for some time and it has been working fine until now.

I have my HA instance pusblished using a duckdns domain and I use a second url (by ip) locally in my wlan. Mobile (Android) app works perfectly.

Right now, the wearOS app only works out of home (through the duckdns domain) and not when I'm at home (by ip). It does not connect at all: no login, once logged in outside the wlan, nothing works.

This could be solved by using a local dns server in my network, but seems weird that it worked so long and had suddenly stopped working.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2023-09-08 13:03
The Wear OS app is meant to only use the external URL. The watch doesn't stay connected long enough to Wi-Fi for it to work. Also duplicate of https://github.com/home-assistant/android/issues/3773

**Closed by dshokouhi** 2023-09-08 13:03 UTC
Labels: bug

**Comment by luixal** [comment] 2023-09-08 13:28
Hi @dshokouhi 

This was working until some weeks ago. Is this due to any changes?

I thought the watch was sending data to the android app on the phone and the app send it to HA server. If it worked like that, as the Android app use the proper url, it should work.

Thanks!

**Comment by dshokouhi** [comment] 2023-09-08 13:32
> Hi @dshokouhi 
> 
> This was working until some weeks ago. Is this due to any changes?
> 
> I thought the watch was sending data to the android app on the phone and the app send it to HA server. If it worked like that, as the Android app use the proper url, it should work.
> 
> Thanks!

For wear OS it was never working like that I think you are mistaken or just didn't notice. The watch proxies data to the phone not in the way you think.

**Comment by luixal** [comment] 2023-09-08 14:39
Well, I am positive I was toggling on/off lights and switches using my watch when at home until some weeks ago and I haven't changed anything in my network, maybe my domain was auto-resolving inside my network before.

Anyway, will have a look at the link and will try setitng up a local dns server.

Thanks!

**Comment by dshokouhi** [comment] 2023-09-08 14:42
> maybe my domain was auto-resolving inside my network before.

If you can enable NAT loopback on the router, usually helps with this. Personally I am just using my own domain to connect to with NAT loopback enabled on my router and it works both locally and remotely.

Did your watch get the update to Wear OS4 already? Was that when this stopped working?

**Comment by luixal** [comment] 2023-09-08 16:41
I have loopback enabled in my router but it doesn't work properly as I can get to HA web interface from a browser. Operator router, yes.

Can't say when this stopped working but adding a local dns server was on my route for other things so... I'll take that way :)

Thanks!

**Comment by luixal** [comment] 2023-09-12 08:23
Just adding a follow up here although it's closed:

I finally deployed a local DNS server (Adguard Home) and configure DNS rewrites. Now, my phone and all my devices can access my home assistant using the same URL externally and internally.

Anyway, wearOS app keeps not working externally and internally. It only accepts the url if out of my network, inside my networks it only works using ip address. This makes no sense, as all my devices can access HA internally and externally using the same url.

It seems like wearOS app was ignoring my local DNS server (which is configured in my router directly, no locally con the device).
