### ISSUE TITLE
Excessive data usage

### ISSUE THREAD

**Issue by R5fan** [home-assistant/android#1711] opened 2021-09-13 21:22 UTC
**Home Assistant Android version:**
2021.9.0 full
**Android version:**
10
**Phone model:**
Galaxy A51
**Home Assistant version:**
2021.8.8
**Description of problem:**

Excessive data usage, even when its "not running". I closed all apps in android, but Im still seeing 2GB per hour (!) data usage.  I think it stops eventually after an hour or after x hours, but I blew through my monthly data cap while jogging. I even tried removing companion background data permission (though the app correctly claims it does have permission to run in the background, which seems to override androids background data permission? I cant see where to revoke this).

I have several blue iris mjpeg camera streams on my front end, I understand its data hungry when Im actually looking at them, but companion seems to continue those streams even when its "not running".  I cant think of anything else using that much data.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2021-09-13 21:23
duplicate of #979

**Closed by dshokouhi** 2021-09-13 21:23 UTC
Labels: bug
