### ISSUE TITLE
Configuration button disappeared 

### ISSUE THREAD

**Issue by dflvunoooooo** [home-assistant/android#2017] opened 2021-12-15 10:11 UTC
**Home Assistant Android version:**
2021.10.0-full

**Android version:**
11

**Phone model:**
Zenfone 8

**Home Assistant version:**
2021.12.1

**Last working Home Assistant release (if known):**
2021.11.5

**Description of problem:**
I do not longer have the option to configure the app. The button disappeared.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

I did not understand where to find the logs.

**Screenshot of problem:**
![Screenshot_20211215-105534946](https://user-images.githubusercontent.com/32816598/146167017-aeb82fc4-f3f2-4154-8858-4058ccc61bbe.jpg)

**Additional information:**
I did reset the app, reinstalled it, followed the instructions from here https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs. I am at a loss.

**Comment by dshokouhi** [comment] 2021-12-15 16:02
duplicate of #2012 should be fixed in HA Core 2021.12.2

**Closed by dshokouhi** 2021-12-15 16:02 UTC
Labels: bug

**Comment by dflvunoooooo** [comment] 2021-12-16 09:26
Yes, works again with 2021.12.2. Thank you very much!
