### ISSUE TITLE
Ability to show video in notification as a gif not working

### ISSUE THREAD

**Issue by conorlap** [home-assistant/android#2352] opened 2022-03-08 15:12 UTC
**Home Assistant Android version:**
beta-2150-261ae31f]

**Android version:**
Android 12
**Phone model:**
Samsung S20+

**Home Assistant version:**
Home Assistant 2022.3.3
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**

I can't seem to get [video notifications](https://github.com/home-assistant/android/pull/2342) working. I've installed [beta-2150-261ae31f](https://github.com/home-assistant/android/releases/tag/beta-2150-261ae31f) but no image/gif is appearing. Here's how I'm calling the notification:

```
service: notify.mobile_app_s20
data:
  message: Test
  data:
    video: "https://download.samplelib.com/mp4/sample-20s.mp4"
```
The video is 20 seconds long.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2022-03-08 15:22
Please get us the logs too.

**Comment by dshokouhi** [comment] 2022-03-08 15:31
> Also, are you using websocket or firebase? I am not sure if the firebase change adding the `video` tag has been deployed yet

The tag has been deployed as soon as the PR was merged.

I think we need to see the logs to see what happened here.

**Comment by conorlap** [comment] 2022-03-08 15:34
[homeassistant_companion_log_2-8-2022_15-23-55 copy.txt](https://github.com/home-assistant/android/files/8207473/homeassistant_companion_log_2-8-2022_15-23-55.copy.txt)

Logs attached. Notifications are using Websocket

**Comment by NickM-27** [comment] 2022-03-08 16:09
Interesting as I don't see any errors, I will take a look. The 13-14 second delay implies that it was getting frames so I am not sure why it wouldn't be included in the notification. I am testing on a crappy Moto E so I don't think it is a performance issue. Will try my Pixel 6 and see if there is anything different.

**Comment by dshokouhi** [comment] 2022-03-08 16:13
I tried another video but same results on my end, shorter video here I think

```
03-08 08:09:23.494  6764  6764 D MessagingService: Creating notification with following data: {video=http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4, message=Test, title=Test}
03-08 08:09:23.513  6764  6764 D UrlRepository: localUrl is: false and usesInternalSsid is: false
03-08 08:09:23.513  6764  6764 D UrlRepository: Using external URL
03-08 08:09:23.517  6764  9897 V MediaHTTPService: MediaHTTPService(android.media.MediaHTTPService@3d87c1e): Cookies: null
03-08 08:09:23.518  6764  9897 V MediaHTTPService: makeHTTPConnection: CookieHandler (java.net.CookieManager@d019edf) exists.
03-08 08:09:23.518  6764  9897 V MediaHTTPService: makeHTTPConnection(android.media.MediaHTTPService@3d87c1e): cookieHandler: java.net.CookieManager@d019edf Cookies: null
03-08 08:09:27.943  6764  6764 D MessagingService: Show notification with tag "null" and id "1783289126"
```

**Comment by NickM-27** [comment] 2022-03-08 16:25
I will have a PR up shortly, luckily the MediaMetaDataRetriever includes the ability to directly pass BitmapOptions

**Comment by dshokouhi** [comment] 2022-03-08 16:25
This might be because of the video URL becuase this works.

![image](https://user-images.githubusercontent.com/1634145/157280842-83cba12b-b037-4966-a79f-b90626f292e5.png)


```
  message: Test
  title: Test
  data:
    video: "https://media.discordapp.net/attachments/765950015071715379/948449681778835496/spooked-dog.mp4"
```

**Comment by SkechyWolf** [comment] 2022-03-08 16:27
> This might be because of the video URL becuase this works.

I could reproduce the original issue trying with the new URL posted works

**Comment by NickM-27** [comment] 2022-03-08 18:21
Fix PR is up 👌

**Closed** 2022-03-10 18:55 UTC
Labels: bug, notifications
