### ISSUE TITLE
Can't filter entities, seems to be cut off at header 

### ISSUE THREAD

**Issue by qcasey** [home-assistant/android#659] opened 2020-07-09 03:43 UTC
**Home Assistant Android version:** 1.11.0-215

**Android version:** Android 10

**Phone model:** OnePlus 7 Pro

**Home Assistant version:** 0.112.0

**Last working Home Assistant release (if known):**

**Description of problem:**

Can't filter entities, seems to be cut off at header and below search bar. Closing the filter menu pushes the Search bar / Filter button up too high.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

![Screenshot_20200708-204151](https://user-images.githubusercontent.com/1429672/86994556-896c9200-c15b-11ea-9eae-2df0d282ecb2.jpg)
![Screenshot_20200708-204204](https://user-images.githubusercontent.com/1429672/86994576-97221780-c15b-11ea-8f77-04de758d703f.jpg)

**Additional information:**

**Comment by qcasey** [comment] 2020-07-09 03:49
Oddly enough, it works just fine in landscape

![Screenshot_20200708-204659__01](https://user-images.githubusercontent.com/1429672/86994878-6f7f7f00-c15c-11ea-852a-7d8988a46fcf.jpg)

**Comment by dshokouhi** [comment] 2020-07-09 06:18
Can you try updating to 0.112.4 and see if it persists? If it does happen again, try chrome for android to see if you get the same results.  That will help us understand where the issue is.

**Comment by qcasey** [comment] 2020-07-11 06:11
I pulled the latest release and unfortunately it's still an issue. This happens in chrome as well.

It would not surprise me if this is unique to OnePlus. But let me know if there's anything else I can help with

![Screenshot_20200710-230539__01.jpg](https://user-images.githubusercontent.com/1429672/87217834-9081d480-c302-11ea-9ce9-ff10d9822d68.jpg)

![Screenshot_20200710-230831.jpg](https://user-images.githubusercontent.com/1429672/87217836-94155b80-c302-11ea-8f1b-127778f383ea.jpg)

**Comment by dshokouhi** [comment] 2020-07-11 06:30
Ok so this is a front end issue. I see it myself on chrome for Android and the app.

**Comment by qcasey** [comment] 2020-07-11 06:42
Gotcha, should I post this over on https://github.com/home-assistant/frontend ?

**Comment by dshokouhi** [comment] 2020-07-11 20:19
@qcasey I just went ahead and opened a new issue and linked to this one.  Closing this as the frontend will need to be fixed to get this corrected.  Thanks for reporting the issue!

**Closed by dshokouhi** 2020-07-11 20:19 UTC
Labels: bug, webview
