### ISSUE TITLE
App crash when adding integration

### ISSUE THREAD

**Issue by AllardKatan** [home-assistant/android#4857] opened 2024-11-28 22:07 UTC
**Home Assistant Android app version(s):**
2024.10.3-full

**Android version(s):**
13

**Device model(s):**
Samsung galaxy Xcover pro

**Home Assistant version:**
2034.11.2

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

When I navigate to 'integrations' and tap 'add integration', the app crashes. Repeated 4 times, got the same result. One out of 3 restarts I got a message from Android asking if I wanted to clear the cache because there was a bug in the app

**Companion App Logs:**
(not posting here as it contains sensitive information, please contact me privately for them) 

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by jpelgrom** [comment] 2024-11-28 22:10
This is most likely a duplicate of #4761, which has been fixed in recent beta versions and will become the stable version of the app soon.

**Comment by AllardKatan** [comment] 2024-11-28 22:27
Ah, my quick search missed this. Seems a duplicate indeed.

**Closed** 2024-11-28 22:37 UTC
Labels: bug
