### ISSUE TITLE
[Beta Issue] New 'Battery_State' sensor goes from 'discharging' to 'not_charging'

### ISSUE THREAD

**Issue by mdegat01** [home-assistant/android#550] opened 2020-04-10 14:25 UTC
**Home Assistant Android version:** 
1.8.0-159
**Android version:** 
10
**Phone model:** 
Pixel 3
**Home Assistant version:**
 0.108.2
**Last working Home Assistant release (if known):** 
N/A (new in beta and just installed)
**Description of problem:**
In the latest beta there's a new sensor created for `battery_state` that is supposed to be used to track whether the phone is charging or not. The sensor's state goes from `discharging` (when not connected to a charger) to `not_charging` (when it is connected to a charger). In the attributes of this sensor there is also an `is_charging` attribute that is always `false` whether the charger is connected or not.

I would expect the state of this sensor to reflect the battery state better (like `charging` instead of `not_charging`) or have it converted to be a `binary_sensor` with `device_class: plug` instead of a `sensor`. Also `is_charging` should switch between `true` and `false` based on the state of the phone charger.

**Traceback (if applicable):**
N/A
```

```

**Screenshot of problem:**
![Screen Shot 2020-04-10 at 10 23 35 AM](https://user-images.githubusercontent.com/2037026/78997914-82f75b80-7b15-11ea-84b7-ae5cd21d398a.png)
![Screen Shot 2020-04-10 at 10 23 52 AM](https://user-images.githubusercontent.com/2037026/78997916-82f75b80-7b15-11ea-9551-827af75f6d60.png)

**Additional information:**
Note that I have signed up to be a beta tester on Google play and this is an issue that only affects the beta version, it is not an issue with the production version. If this is the wrong forum for issues with the beta version please let me know and I will use the correct forum going forward.

**Comment by dshokouhi** [comment] 2020-04-10 14:42
@mdegat01 the states of the battery sensor are `charging` `discharging` `not_charging` and `full` It takes about 15-20 minutes for the state to go to `charging` from `not_charging` as the device is verifying the power draw.  `is_charging` is also delayed here.  See #535 and #525 for more details.  Also the expected states and functionality is also found on the docs: https://companion.home-assistant.io/docs/core/sensors#battery-sensors

If you are facing issues where the sensor is not updating at all after teh update interval then try to clear data in the app.

**Comment by dshokouhi** [comment] 2020-04-10 14:44
Closing as duplicate of #535

**Closed by dshokouhi** 2020-04-10 14:44 UTC
Labels: bug, sensor-tracking

**Comment by mdegat01** [comment] 2020-04-10 15:25
Oh, ok.  So I'm basically in the same situation as the author of [this PR](https://github.com/home-assistant/android/pull/525).  I switched to beta basically to try out what was done there to see if it worked for me.

I do see the instant update of this sensor now but the `not_charging` label is really throwing me.  @dshokouhi Would you recommend I make my conditional based on whether this sensors value is not equal to `discharging` or `unknown`? Or should I instead rely on whether the attribute `charger_type` is not equal to `unknown` since that attribute seems to switch to `ac` immediately after I plug it in.

 I can't wait 15-20 minutes for the state to switch to `charging` as the lights need to go out pretty much as soon as we plug our phones in or the automation will just seem to be not working.  Plus I'm worried the `full` state might break things since I don't really care if the phones are full I just want to know if they're on the charger or not.

**Comment by dshokouhi** [comment] 2020-04-10 15:31
Yea I was using `is_charging` but since I use the pixel stand my device trickle charges over night so its not steady.  I found this template to work well to determine if the device is plugged in

`"{{ states('sensor.dannys_pixel_4_xl_battery_state') is in ['charging', 'full', 'not_charging'] }}"`

`charger_type` updates immediately for me as well and I have added this to its own sensor.  You get more control over here because you can be on `wireless` `ac` `usb` or `unknown`  

I am still figuring out how I want my automations to trigger as well once docked but this is how i've been making sense of things.
