### ISSUE TITLE
Cannot select client certificate, so app is useless as it cannot even connect to home assistant instance

### ISSUE THREAD

**Issue by niirvana-git** [home-assistant/android#1244] opened 2020-12-17 18:04 UTC
**Home Assistant Android version:**
3.0.2-full
**Android version:**
Oxygen OS 10.5.9.AC101BA
**Phone model:**
OnePlus Nord
**Home Assistant version:**
latest
**Last working Home Assistant release (if known):**
not working with any versions
**Description of problem:**
I want to keep my home assistant installation secure, so I'm using client certificates with NGINX Proxy Manager. It works nicely, but I cannot use this Android app at all, because there is no possibility to select my client certificate. Why? It's a trivial thing to implement. Notifications neither work because of this. App is totally unusable because of this small missing feature.
**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2020-12-17 18:11
Duplicate of #442 and #214, #127

**Closed by dshokouhi** 2020-12-17 18:11 UTC
Labels: bug

**Comment by niirvana-git** [comment] 2020-12-17 18:37
Yes, there seems to be duplicates. This has been requested quite many times. Can you specify why you don't want to implement it? It should be quite trivial thing to do. There shouldn't be any reason not implement it. Is it because you want people to buy license to Home Assistant Cloud? I can't think of any other reasons. It should be possible to use home assistant securely and without client certificates it surely isn't secure. I won't be taking that risk. Maybe I then have to create own forked private version or something.

**Comment by dshokouhi** [comment] 2020-12-17 18:51
> Can you specify why you don't want to implement it?

Please read the issues and all comments for the reasons given



> It should be quite trivial thing to do.

We would be happy to accept a PR or you can try to help out with https://github.com/home-assistant/android/pull/870 if that is what you are after



> Maybe I then have to create own forked private version or something.

You can also work on it and submit a PR and get it reviewed like the PR I linked to

**Comment by niirvana-git** [comment] 2020-12-18 10:57
Thanks. I didn't notice that PR while writing this. I just read some comments that client certificates would be an advanced functionality and was considerer niche and not important to implement. I disagree totally :-) I would never publish my HA instance to public internet without client certs.
