### ISSUE TITLE
Password manager not available at login

### ISSUE THREAD

**Issue by gotson** [home-assistant/android#189] opened 2019-12-22 11:09 UTC
**Home Assistant Android version:** 1.3.1

**Android version:** 9

**Phone model:** one plus 6t, Samsung galaxy tab s5e

**Home Assistant version:** 0.103.3

**Last working Home Assistant release (if known):** 

**Description of problem:** the password manager of android (bitwarden in my case) is not available at login

**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by tristandegroof** [comment] 2020-11-27 17:09
I can confirm this is still an issue in 3.0.2, as I had to reset the app after updating for some reason. Since passwords etc have become much more complicated, password manager support is important, I think :-)

**Comment by dshokouhi** [comment] 2020-11-27 17:13
Should've caught this earlier, duplicate of: https://github.com/home-assistant/frontend/issues/3133

**Closed by dshokouhi** 2020-11-27 17:13 UTC
Labels: webview
