### ISSUE TITLE
Widget Authentication Failure

### ISSUE THREAD

**Issue by myztillx** [home-assistant/android#4059] opened 2023-12-15 21:33 UTC
**Home Assistant Android app version(s):**
2023.10.2-full
**Android version(s):**
14 Build Number UQIA.231205.015.A1
**Device model(s):**
Pixel 7
**Home Assistant version:**
2023.12.3
**Last working Home Assistant release (if known):**
2023.11.2
**Description of problem, include YAML if issue is related to notifications:**
When clicking a widget that requires authentication, the authentication step no longer shows up. I had not used the widget since updating to HA 2023.12.3, but I also just updated Android as well. 

**Companion App Logs:**

```
Soon (filing from phone and hard to truncate correctly). 
```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2023-12-15 21:37
Strange I am unable to reproduce, can you check the widget configuration to see if its still set to show authentication? Just tested on a pixel 8 pro and it did the authentication properly.

We should look at both logs and widget configuration here.

**Comment by jpelgrom** [comment] 2023-12-15 21:39
This may also be a duplicate of #3893

**Comment by dshokouhi** [comment] 2023-12-15 21:43
> This may also be a duplicate of #3893

ah yes it could be, strange id expect the pixel 8 pro to hit the same issue as I am also on the QPR update

**Comment by myztillx** [comment] 2023-12-15 21:47
> This may also be a duplicate of #3893

I missed this issue when looking for duplicates. From the video link, this appears to be the same issue I am seeing, and the log output he included is similar to mine. I will include my logs shortly when I have a computer available. If you want to close this issue in favor of the other that is fine, I can include the information there instead.

**Comment by dshokouhi** [comment] 2023-12-15 22:02
> > This may also be a duplicate of #3893
> 
> I missed this issue when looking for duplicates. From the video link, this appears to be the same issue I am seeing, and the log output he included is similar to mine. I will include my logs shortly when I have a computer available. If you want to close this issue in favor of the other that is fine, I can include the information there instead.

you should also comment on the linked issue tracker as well to let Google konw you are impacted in the production build, please also attach a bug report for them so they can investigate

As you said its the same issue lets close this for now and track it in #3893

**Closed by dshokouhi** 2023-12-15 22:02 UTC
Labels: bug, question, widget
