### ISSUE TITLE
Next Alarm sensor for Samsung phone stops working

### ISSUE THREAD

**Issue by chertvl** [home-assistant/android#2811] opened 2022-08-21 16:25 UTC
**Home Assistant Android version:**  tried  beta-2534-90a9a27e   and   beta-2622-ebc6b76d

**Android version:** Android 12

**Phone model:** Samsung Galaxy S10

**Home Assistant version:**  Home Assistant 2022.8.6

**Last working Home Assistant release (if known):**  today at morning, same versions, before HA restart

**Description of problem:**  After manual restart of HA my Next Alarm sensor of phone becomes 'unavailable', I got an error in logger:

![image](https://user-images.githubusercontent.com/38353584/185801046-d601fcb1-9d17-4910-acde-46e46fd550e5.png)

**Additional information:**  Samsung Clock app version 12.1.21.1  of 21.07.2022, don't seems to been upgrade

**Comment by dshokouhi** [comment] 2022-08-21 16:26
can you share with us the state of the sensor from teh app?

**Comment by dshokouhi** [comment] 2022-08-21 16:27
also what are the results using the Google clock app as the samsung app has been known to cause issues

**Comment by chertvl** [comment] 2022-08-21 16:32
> can you share with us the state of the sensor from teh app?

Ah, in Companion app it seems ok 
![image](https://user-images.githubusercontent.com/38353584/185801162-c8549455-17bf-44ca-8a53-88de65e60c79.png)

> also what are the results using the Google clock app as the samsung app has been known to cause issues

Strange thing.
Installed Google Clock package from GPlay, it works.
Uninstalled it.
And now it works with Samsung Clock too. 
Issue is dissapeared. Will test few times now.

**Comment by dshokouhi** [comment] 2022-08-21 16:36
What is the app `com.samsung.android.app.routines` that does not sound like their clock app which is normally `com.sec.android.app.clockpackage`

Might be time to use the allow list, if you are able to get the data for the bad state that was sent that will be helpful but I am not sure what we can do here without that. First time I have seen that error.

**Comment by chertvl** [comment] 2022-08-21 16:43
> What is the app `com.samsung.android.app.routines` that does not sound like their clock app which is normally `com.sec.android.app.clockpackage`

 `com.samsung.android.app.routines` its Samsung built-in clock app package (alarm, timer, stopwatch, etc).
Just tested with Google Clock app from PlayMarket again.
It seems Next Alarm sensor becoms 'unavailable' when HA restarts, produce this error in log.
If I re-enable any alarm in any app (samsung or google) - next_alarm sensor in HA will get new actual state.
In HA Companion sensor's preview always is ok.

I will try to think how I can give you a "bad state".

![image](https://user-images.githubusercontent.com/38353584/185801719-1ec43126-ed30-4857-885e-95e19da32bf1.png)

**Comment by chertvl** [comment] 2022-08-21 16:47
> What is the app `com.samsung.android.app.routines` that does not sound like their clock app which is normally `com.sec.android.app.clockpackage`

Sorry, my bad! You are right.
`com.sec.android.app.clockpackage` - samsung clock app
`com.samsung.android.app.routines`  - samsung bixby routines (time when DnD mode will on automatically always flew in HA Next Alarm sensor with this package name). I noticed that reminders are also dragged in.

**Comment by dshokouhi** [comment] 2022-08-21 16:50
thats strange, I am unable to reproduce but based on the symptoms I would say this is a HA core bug and not app related. There were some HA core changes related to restoring a sensor which happens during a restart.

**Comment by chertvl** [comment] 2022-08-21 17:09
> There were some HA core changes related to restoring a sensor which happens during a restart.

That it!
Just downgraded HA Core to 2022.8.5 version and Next Alarm sensor now succesfly restore its state after Core restart.
I think I need to redirect issue.

**Comment by dshokouhi** [comment] 2022-08-21 17:16
Can you create a new issue there and complete the issue template so the right people get tagged? Definitely mention that rolling back fixes the issue :)

**Comment by dshokouhi** [comment] 2022-08-21 22:14
closing in favor of https://github.com/home-assistant/core/issues/77106

**Closed by dshokouhi** 2022-08-21 22:14 UTC
Labels: bug, sensor-tracking
