### ISSUE TITLE
Improved cache controls

### ISSUE THREAD

**Issue by RoboMagus** [home-assistant/android#3473] opened 2023-04-13 18:47 UTC
**Is your feature request related to a problem? Please describe.**

After the recent frontend changes of HA `2023.4.x` it became clear that the companion app is quite agressive in the way it caches e.g. custom frontend components. To receive any changes to these components one would have to go into the android settings menu and clear the HA Companion app cache.

**Describe the solution you'd like**

A _nice_ improvement would be to have the option to clear cache from inside the companion app settings itself (e.g. near the toggle switch for WebView remote debugging).

A **great** improvement would be the option to clear cache remotely through a service call. For instance, when the HA maintainer creates frontend changes they could enforce these changes to be loaded on all apps of family members without manual intervention.

**Describe alternatives you've considered, if any**

Manual effort. Not really aplicable for all users.

**Additional context**

**Comment by dshokouhi** [comment] 2023-04-13 18:54
Is this possibly a duplicate of https://github.com/home-assistant/android/issues/2460 ?  The end goal seems to be the same I think?

**Comment by RoboMagus** [comment] 2023-04-13 18:57
Damn, you're fast! 😄
Looking into it it seems similar, yes.

When searching `cache` related issues I did not go as far back as when that issue was created.

**Closed** 2023-04-13 18:58 UTC
Labels: enhancement, webview
