### ISSUE TITLE
App crashes on Android 7 with April release

### ISSUE THREAD

**Issue by HomeWiseAdmin** [home-assistant/android#4333] opened 2024-04-08 04:50 UTC
**Home Assistant Android app version(s):**

**Android version(s):**
Android 7
**Device model(s):**
Galaxy Tab S2 (9.7", LTE). SM-T818W
**Home Assistant version:**
April 2024
**Last working Home Assistant release (if known):**
December 4, 2023
**Description of problem, include YAML if issue is related to notifications:**

This 2024 update (specially the April update) crashes the Companion App on the Android 7 devices.
This happens either when the App is loaded, or usually after a few crashes it shows the login screen and when you login, it shows to enable Tracking and regardless, it crashes upon clicking on Next/continue button. 

**Companion App Logs:**

I am not sure how to get the log, the documentation does not mention anything.

**Screenshot or video of problem:**
Shows standard Android App has stopped dialog, 
**Additional information:**

**Comment by jpelgrom** [comment] 2024-04-08 04:56
Duplicate of #4323 - this is fixed in the next release and will be available soon

**Closed by jpelgrom** 2024-04-08 04:56 UTC
Labels: bug
