### ISSUE TITLE
Button entity: in an entities card, touching 'press' pulls up the entity details instead of triggering the button.

### ISSUE THREAD

**Issue by Vrobenmat** [home-assistant/android#2018] opened 2021-12-15 17:02 UTC
Checklist

I have updated to the latest available Home Assistant version.
I have cleared the cache of my browser.
I have tried a different browser to see if it is related to my browser.

Describe the issue you are experiencing

Using a button entity in a normal entities card, clicking 'press' through the browser interface triggers the button, as expected.
Through the android app interface, touching 'press' pulls up the entity details instead of triggering the button. This is not expected.
Describe the behavior you expected

touching 'press' of a button entity in a lovelace entities card, in the android app, should trigger the button.
Steps to reproduce the issue

    Create a button entity, in my case coming from ESPHome
    Add the button entity to an entities card
    attempt to touch 'press' through the android app
    ...

What version of Home Assistant Core has the issue?

2021.12.1
What was the last working version of Home Assistant Core?

No response
In which browser are you experiencing the issue with?

Android app - 2021.10.0-full
Which operating system are you using to run this browser?

Android 11
State of relevant entities

No response
Problem-relevant frontend configuration

No response
Javascript errors shown in your browser console/inspector

No response
Additional information

No response

**Comment by dshokouhi** [comment] 2021-12-15 17:08
what happens in chrome for android?

**Comment by dshokouhi** [comment] 2021-12-15 17:26
duplicate of https://github.com/home-assistant/frontend/issues/10907

@Vrobenmat pleaes dont create bugs in each repo and wait to hear from the first one.  For this error its more than likely a frontend issue.  Make sure to mention the results of Chrome for android.

**Closed by dshokouhi** 2021-12-15 17:26 UTC
Labels: bug, webview
