### ISSUE TITLE
Spinning circle on android widgets

### ISSUE THREAD

**Issue by kamikaze2112** [home-assistant/android#4781] opened 2024-11-02 22:55 UTC
**Home Assistant Android app version(s):**

version 2024.10.3-full
io.homeassistant.companion.android

**Android version(s):**

15

**Device model(s):**

Pixel 8 Pro

**Home Assistant version:**

Core
2024.10.4
Supervisor
2024.10.3
Operating System
13.2
Frontend
20241002.4

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

Sometimes the android widgets will spin forever. Editing and updating the widget fixes it, but it seems random.  Some widgets work well and some don't. 

**Companion App Logs:**

<details>
<summary>Logs</summary>

```
--------- beginning of main
11-02 16:49:47.911 13120 13120 D VRI[PopupWindow:6d8e4ef]: visibilityChanged oldVisibility=false newVisibility=true
11-02 16:49:47.911 13120 13120 D VRI[PopupWindow:dcf0464]: visibilityChanged oldVisibility=false newVisibility=true
11-02 16:49:47.916 13120 18662 E WebSocketRepository: Exception while sending message
11-02 16:49:47.916 13120 18662 E WebSocketRepository: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
11-02 16:49:47.916 13120 18662 E WebSocketRepository: 	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:188)
11-02 16:49:47.916 13120 18662 E WebSocketRepository: 	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
11-02 16:49:47.916 13120 18662 E WebSocketRepository: 	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:505)
11-02 16:49:47.916 13120 18662 E WebSocketRepository: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
11-02 16:49:47.916 13120 18662 E WebSocketRepository: 	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:105)
11-02 16:49:47.916 13120 18662 E WebSocketRepository: 	at java.lang.Thread.run(Thread.java:1012)
11-02 16:49:47.916 13120 18657 E WebSocketRepository: Exception while sending message
11-02 16:49:47.916 13120 18657 E WebSocketRepository: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
11-02 16:49:47.916 13120 18657 E WebSocketRepository: 	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:188)
11-02 16:49:47.916 13120 18657 E WebSocketRepository: 	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
11-02 16:49:47.916 13120 18657 E WebSocketRepository: 	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:505)
11-02 16:49:47.916 13120 18657 E WebSocketRepository: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
11-02 16:49:47.916 13120 18657 E WebSocketRepository: 	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:105)
11-02 16:49:47.916 13120 18657 E WebSocketRepository: 	at java.lang.Thread.run(Thread.java:1012)
11-02 16:49:47.917 13120 18664 E WebSocketRepository: Exception while sending message
11-02 16:49:47.917 13120 18664 E WebSocketRepository: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
11-02 16:49:47.917 13120 18664 E WebSocketRepository: 	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:188)
11-02 16:49:47.917 13120 18664 E WebSocketRepository: 	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
11-02 16:49:47.917 13120 18664 E WebSocketRepository: 	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:505)
11-02 16:49:47.917 13120 18664 E WebSocketRepository: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
11-02 16:49:47.917 13120 18664 E WebSocketRepository: 	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:105)
11-02 16:49:47.917 13120 18664 E WebSocketRepository: 	at java.lang.Thread.run(Thread.java:1012)
11-02 16:49:47.917 13120 13244 E WebSocketRepository: Exception while sending message
11-02 16:49:47.917 13120 13244 E WebSocketRepository: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
11-02 16:49:47.917 13120 13244 E WebSocketRepository: 	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:188)
11-02 16:49:47.917 13120 13244 E WebSocketRepository: 	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
11-02 16:49:47.917 13120 13244 E WebSocketRepository: 	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:505)
11-02 16:49:47.917 13120 13244 E WebSocketRepository: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
11-02 16:49:47.917 13120 13244 E WebSocketRepository: 	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:105)
11-02 16:49:47.917 13120 13244 E WebSocketRepository: 	at java.lang.Thread.run(Thread.java:1012)
11-02 16:49:47.917 13120 18658 E WebSocketRepository: Exception while sending message
11-02 16:49:47.917 13120 18658 E WebSocketRepository: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
11-02 16:49:47.917 13120 18658 E WebSocketRepository: 	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:188)
11-02 16:49:47.917 13120 18658 E WebSocketRepository: 	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
11-02 16:49:47.917 13120 18658 E WebSocketRepository: 	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:505)
11-02 16:49:47.917 13120 18658 E WebSocketRepository: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
11-02 16:49:47.917 13120 18658 E WebSocketRepository: 	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:105)
11-02 16:49:47.917 13120 18658 E WebSocketRepository: 	at java.lang.Thread.run(Thread.java:1012)
11-02 16:49:47.917 13120 13245 E WebSocketRepository: Exception while sending message
11-02 16:49:47.917 13120 13245 E WebSocketRepository: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
11-02 16:49:47.917 13120 13245 E WebSocketRepository: 	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:188)
11-02 16:49:47.917 13120 13245 E WebSocketRepository: 	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
11-02 16:49:47.917 13120 13245 E WebSocketRepository: 	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:505)
11-02 16:49:47.917 13120 13245 E WebSocketRepository: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
11-02 16:49:47.917 13120 13245 E WebSocketRepository: 	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:105)
11-02 16:49:47.917 13120 13245 E WebSocketRepository: 	at java.lang.Thread.run(Thread.java:1012)
11-02 16:49:47.917 13120 18663 E WebSocketRepository: Exception while sending message
11-02 16:49:47.917 13120 18663 E WebSocketRepository: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
11-02 16:49:47.917 13120 18663 E WebSocketRepository: 	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:188)
11-02 16:49:47.917 13120 18663 E WebSocketRepository: 	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
11-02 16:49:47.917 13120 18663 E WebSocketRepository: 	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:505)
11-02 16:49:47.917 13120 18663 E WebSocketRepository: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
11-02 16:49:47.917 13120 18663 E WebSocketRepository: 	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:105)
11-02 16:49:47.917 13120 18663 E WebSocketRepository: 	at java.lang.Thread.run(Thread.java:1012)
11-02 16:49:47.919 13120 13145 E WebSocketRepository: Exception while sending message
11-02 16:49:47.919 13120 13145 E WebSocketRepository: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
11-02 16:49:47.919 13120 13145 E WebSocketRepository: 	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:188)
11-02 16:49:47.919 13120 13145 E WebSocketRepository: 	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
11-02 16:49:47.919 13120 13145 E WebSocketRepository: 	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:505)
11-02 16:49:47.919 13120 13145 E WebSocketRepository: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
11-02 16:49:47.919 13120 13145 E WebSocketRepository: 	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:105)
11-02 16:49:47.919 13120 13145 E WebSocketRepository: 	at java.lang.Thread.run(Thread.java:1012)
11-02 16:49:47.920 13120 13245 E WebSocketRepository: Issue re-registering subscription with {type=subscribe_trigger, trigger={platform=state, entity_id=[switch.desk_lights]}}
11-02 16:49:47.920 13120 18657 E WebSocketRepository: Issue re-registering subscription with {type=subscribe_trigger, trigger={platform=state, entity_id=[light.kitchen_lights]}}
11-02 16:49:47.920 13120 13145 E WebSocketRepository: Issue re-registering subscription with {type=subscribe_trigger, trigger={platform=state, entity_id=[switch.first_led_hardware_instance_component_led_device]}}
11-02 16:49:47.922 13120 18658 E WebSocketRepository: Issue re-registering subscription with {type=subscribe_trigger, trigger={platform=state, entity_id=[light.kitchen_lights]}}
11-02 16:49:47.922 13120 13219 D WebviewActivity: External bus {"type":"connection-status","payload":{"event":"disconnected"},"id":13}
11-02 16:49:47.923 13120 18662 E WebSocketRepository: Issue re-registering subscription with {type=subscribe_trigger, trigger={platform=state, entity_id=[switch.desk_lights]}}
11-02 16:49:47.923 13120 18664 E WebSocketRepository: Issue re-registering subscription with {type=subscribe_trigger, trigger={platform=state, entity_id=[light.bedroom_lamps]}}
11-02 16:49:47.923 13120 18663 E WebSocketRepository: Issue re-registering subscription with {type=subscribe_trigger, trigger={platform=state, entity_id=[light.wled_main]}}
11-02 16:49:47.923 13120 13244 E WebSocketRepository: Issue re-registering subscription with {type=subscribe_trigger, trigger={platform=state, entity_id=[light.kitchen_lights]}}
11-02 16:49:47.923 13120 18658 D WebSocketRepository: Sending message 97: {type=subscribe_trigger, trigger={platform=state, entity_id=[switch.first_led_hardware_instance_component_led_device]}, id=97}
11-02 16:49:47.923 13120 19423 E WebSocketRepository: Exception while sending message
11-02 16:49:47.923 13120 19423 E WebSocketRepository: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
11-02 16:49:47.923 13120 19423 E WebSocketRepository: 	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:188)
11-02 16:49:47.923 13120 19423 E WebSocketRepository: 	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
11-02 16:49:47.923 13120 19423 E WebSocketRepository: 	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:505)
11-02 16:49:47.923 13120 19423 E WebSocketRepository: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
11-02 16:49:47.923 13120 19423 E WebSocketRepository: 	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:105)
11-02 16:49:47.923 13120 19423 E WebSocketRepository: 	at java.lang.Thread.run(Thread.java:1012)
11-02 16:49:47.923 13120 19423 E WebSocketRepository: Issue re-registering subscription with {type=subscribe_trigger, trigger={platform=state, entity_id=[light.kitchen_lights]}}
11-02 16:49:47.928 13120 13340 E WebSocketRepository: Websocket: onFailure
11-02 16:49:47.928 13120 13340 E WebSocketRepository: java.net.SocketException: Software caused connection abort
11-02 16:49:47.928 13120 13340 E WebSocketRepository: 	at java.net.SocketInputStream.socketRead0(Native Method)
11-02 16:49:47.928 13120 13340 E WebSocketRepository: 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
11-02 16:49:47.928 13120 13340 E WebSocketRepository: 	at java.net.SocketInputStream.read(SocketInputStream.java:173)
11-02 16:49:47.928 13120 13340 E WebSocketRepository: 	at java.net.SocketInputStream.read(SocketInputStream.java:143)
11-02 16:49:47.928 13120 13340 E WebSocketRepository: 	at okio.InputStreamSource.read(JvmOkio.kt:93)
11-02 16:49:47.928 13120 13340 E WebSocketRepository: 	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:153)
11-02 16:49:47.928 13120 13340 E WebSocketRepository: 	at okio.RealBufferedSource.request(RealBufferedSource.kt:210)
11-02 16:49:47.928 13120 13340 E WebSocketRepository: 	at okio.RealBufferedSource.require(RealBufferedSource.kt:203)
11-02 16:49:47.928 13120 13340 E WebSocketRepository: 	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:213)
11-02 16:49:47.928 13120 13340 E WebSocketRepository: 	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:124)
11-02 16:49:47.928 13120 13340 E WebSocketRepository: 	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:107)
11-02 16:49:47.928 13120 13340 E WebSocketRepository: 	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:307)
11-02 16:49:47.928 13120 13340 E WebSocketRepository: 	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
11-02 16:49:47.928 13120 13340 E WebSocketRepository: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:529)
11-02 16:49:47.928 13120 13340 E WebSocketRepository: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
11-02 16:49:47.928 13120 13340 E WebSocketRepository: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
11-02 16:49:47.928 13120 13340 E WebSocketRepository: 	at java.lang.Thread.run(Thread.java:1012)
11-02 16:49:47.929 13120 18658 D WebSocketRepository: Message number 97 sent
11-02 16:49:47.929 13120 18664 D WebSocketRepository: Sending message 98: {type=subscribe_trigger, trigger={platform=state, entity_id=[switch.desk_lights]}, id=98}
11-02 16:49:47.929 13120 18664 D WebSocketRepository: Message number 98 sent
11-02 16:49:47.929 13120 13145 D WebSocketRepository: Sending message 99: {type=subscribe_trigger, trigger={platform=state, entity_id=[light.kitchen_lights]}, id=99}
11-02 16:49:47.929 13120 13145 D WebSocketRepository: Message number 99 sent
11-02 16:49:47.929 13120 18657 D WebSocketRepository: Sending message 100: {type=subscribe_trigger, trigger={platform=state, entity_id=[light.bedroom_lamps]}, id=100}
11-02 16:49:47.929 13120 18657 D WebSocketRepository: Message number 100 sent
11-02 16:49:47.929 13120 18663 D WebSocketRepository: Sending message 101: {type=subscribe_trigger, trigger={platform=state, entity_id=[light.bedroom_lamps]}, id=101}
11-02 16:49:47.930 13120 18663 D WebSocketRepository: Message number 101 sent
11-02 16:49:47.930 13120 13245 D WebSocketRepository: Sending message 102: {type=subscribe_trigger, trigger={platform=state, entity_id=[switch.first_led_hardware_instance_component_led_device]}, id=102}
11-02 16:49:47.932 13120 13245 D WebSocketRepository: Message number 102 sent
11-02 16:49:47.932 13120 19431 D WebSocketRepository: Sending message 103: {type=subscribe_trigger, trigger={platform=state, entity_id=[light.bedroom_lamps]}, id=103}
11-02 16:49:47.932 13120 19431 D WebSocketRepository: Message number 103 sent
11-02 16:49:47.932 13120 19430 D WebSocketRepository: Sending message 104: {type=subscribe_trigger, trigger={platform=state, entity_id=[switch.first_led_hardware_instance_component_led_device]}, id=104}
11-02 16:49:47.932 13120 19430 D WebSocketRepository: Message number 104 sent
11-02 16:49:47.933 13120 18662 D WebSocketRepository: Sending message 105: {type=subscribe_trigger, trigger={platform=state, entity_id=[switch.first_led_hardware_instance_component_led_device]}, id=105}
11-02 16:49:47.933 13120 18662 D WebSocketRepository: Message number 105 sent
11-02 16:49:47.936 13120 13120 D WebviewActivity: Matter/Thread step changed to NOT_STARTED
11-02 16:49:47.938 13120 13120 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-02 16:49:47.939 13120 13120 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-02 16:49:47.939 13120 13120 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 0, currentMillis: 1730587787939)
11-02 16:49:48.039 13120 18663 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-02 16:49:48.042 13120 13153 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=224a8ba4-681b-406a-9803-89b16f5c78b7, tags={ io.homeassistant.companion.android.websocket.WebsocketManager } ]
11-02 16:49:48.045 13120 13153 I WM-Processor: Moving WorkSpec (eab6e475-af7d-4cf9-a32f-52888598e539) to the foreground
11-02 16:49:48.050 13120 13120 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-02 16:49:48.051 13120 13120 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 0, currentMillis: 1730587788051)
11-02 16:49:48.053 13120 19430 D SensorWorker: Updating all Sensors in foreground.
11-02 16:49:48.054 13120 19430 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-02 16:49:48.056 13120 13120 I WM-SystemFgDispatcher: Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService (has extras) }
11-02 16:49:48.063 13120 13120 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-02 16:49:48.063 13120 13120 D ServerConnectionInfo: Using external URL
11-02 16:49:48.063 13120 13120 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-02 16:49:48.063 13120 13120 D ServerConnectionInfo: Using external URL
11-02 16:49:48.071 13120 13219 D WebviewActivity: External bus {"type":"connection-status","payload":{"event":"connected"},"id":14}
11-02 16:49:48.109 13120 19430 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-02 16:49:48.110 13120 19430 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-02 16:49:48.119 13120 18251 D TrafficStats: tagSocket(102) with statsTag=0xffffffff, statsUid=-1
11-02 16:49:48.120 13120 13219 D WebviewActivity: External bus {"type":"theme-update","id":15}
11-02 16:49:48.142 13120 13120 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-02 16:49:48.156 13120 13120 D WebviewActivity: Color from webview is "#101e24-SPACER-#111111"
11-02 16:49:48.156 13120 13120 D WebviewActivity: Color from webview is "#101e24-SPACER-#111111"
11-02 16:49:48.157 13120 13245 D WebViewPresenterImpl: Try getting color from webview color "#101e24".
11-02 16:49:48.158 13120 13245 I WebViewPresenterImpl: Found color -15720924.
11-02 16:49:48.158 13120 13245 D WebViewPresenterImpl: Try getting color from webview color "#111111".
11-02 16:49:48.158 13120 13245 I WebViewPresenterImpl: Found color -15658735.
11-02 16:49:48.198 13120 18663 D SensorReceiver: Nothing to update for server 1 (Home)
11-02 16:49:48.198 13120 18663 I SensorReceiver: Sensor updates and sync completed
11-02 16:49:48.199 13120 13154 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=eab6e475-af7d-4cf9-a32f-52888598e539, tags={ io.homeassistant.companion.android.sensors.SensorWorker } ]
11-02 16:49:48.204 13120 13120 I WM-SystemFgDispatcher: Stopping foreground service
11-02 16:49:50.762 13120 13120 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=false callback=android.widget.PopupWindow$PopupDecorView$$ExternalSyntheticLambda1@3c75932
11-02 16:49:50.794 13120 13120 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=false callback=android.widget.PopupWindow$PopupDecorView$$ExternalSyntheticLambda1@3b2e7df
11-02 16:49:52.895 13120 13219 D WebviewActivity: External bus {"type":"config_screen/show","id":16}
11-02 16:49:52.906 13120 13120 D IntegrationRepository: setAppActive(): false
11-02 16:49:52.907 13120 13120 D IntegrationRepository: setAppActive(): false
11-02 16:49:52.911 13120 13120 D SensorReceiver: Received intent: io.homeassistant.companion.android.UPDATE_SENSORS
11-02 16:49:52.911 13120 18663 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-02 16:49:52.944 13120 18663 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-02 16:49:52.944 13120 18663 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-02 16:49:52.989 13120 13120 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 0, currentMillis: 1730587792989)
11-02 16:49:53.027 13120 18663 D SensorReceiver: Nothing to update for server 1 (Home)
11-02 16:49:53.027 13120 18663 I SensorReceiver: Sensor updates and sync completed
11-02 16:49:53.033 13120 18663 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-02 16:49:53.078 13120 18251 D TrafficStats: tagSocket(387) with statsTag=0xffffffff, statsUid=-1
11-02 16:49:53.155 13120 13120 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 0, currentMillis: 1730587793155)
11-02 16:49:53.155 13120 13120 D IntegrationRepository: setAppActive(): true
11-02 16:49:53.525 13120 13120 D VRI[WebViewActivity]: visibilityChanged oldVisibility=true newVisibility=false
11-02 16:49:53.552 13120 13120 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=false callback=androidx.activity.OnBackPressedDispatcher$Api34Impl$createOnBackAnimationCallback$1@8f77a39
11-02 16:49:57.938 13120 19430 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-02 16:49:57.938 13120 19430 D ServerConnectionInfo: Using external URL
11-02 16:49:57.940 13120 19430 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
11-02 16:49:57.940 13120 19430 D ServerConnectionInfo: Using external URL
11-02 16:49:57.946 13120 18251 D TrafficStats: tagSocket(125) with statsTag=0xffffffff, statsUid=-1
11-02 16:49:58.028 13120 13340 D WebSocketRepository: Websocket: onOpen
11-02 16:49:58.028 13120 13340 D WebSocketRepository: Websocket: onMessage (text)
11-02 16:49:58.033 13120 13340 D WebSocketRepository: Message number null received
11-02 16:49:58.036 13120 18663 D WebSocketRepository: Auth Requested
11-02 16:49:58.036 13120 13340 D WebSocketRepository: Websocket: onMessage (text)
11-02 16:49:58.037 13120 13340 D WebSocketRepository: Message number null received
11-02 16:49:58.039 13120 13245 D WebSocketRepository: Sending message 106: {type=supported_features, id=106, features={coalesce_messages=1}}
11-02 16:49:58.039 13120 13245 D WebSocketRepository: Resubscribing to active subscriptions...
11-02 16:49:58.040 13120 13245 D WebSocketRepository: Sending message 107: {type=subscribe_trigger, trigger={platform=state, entity_id=[switch.first_led_hardware_instance_component_led_device]}, id=107}
11-02 16:49:58.040 13120 13245 D WebSocketRepository: Message number 107 sent
11-02 16:49:58.046 13120 13340 D WebSocketRepository: Websocket: onMessage (text)
11-02 16:49:58.047 13120 13340 D WebSocketRepository: Message number 106 received
11-02 16:49:58.053 13120 13340 D WebSocketRepository: Websocket: onMessage (text)
11-02 16:49:58.054 13120 13340 D WebSocketRepository: Message number 107 received
11-02 16:49:58.055 13120 13245 W WebSocketRepository: Response continuation has already been invoked for 107, null
11-02 16:50:06.915 13120 13245 D LogcatReader: Read logcat for pid 13120
```

</details>

**Screenshot or video of problem:**

https://youtube.com/shorts/isffaqKTVuQ

**Additional information:**

Looking through the closed issues it seems like this is a recurring problem. The behaviour persists regardless of the widget background colour/style, and by editing one as seen in the video it updates the rest of them.

**Comment by dshokouhi** [comment] 2024-11-04 22:30
Duplicate of #4200 looks like this time a different error from teh server, this time its a timeout error.

```
11-02 16:49:47.916 13120 18662 E WebSocketRepository: Exception while sending message
11-02 16:49:47.916 13120 18662 E WebSocketRepository: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
11-02 16:49:47.916 13120 18662 E WebSocketRepository: 	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:188)
11-02 16:49:47.916 13120 18662 E WebSocketRepository: 	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
11-02 16:49:47.916 13120 18662 E WebSocketRepository: 	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:505)
11-02 16:49:47.916 13120 18662 E WebSocketRepository: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
11-02 16:49:47.916 13120 18662 E WebSocketRepository: 	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:105)
11-02 16:49:47.916 13120 18662 E WebSocketRepository: 	at java.lang.Thread.run(Thread.java:1012)
```

**Closed by dshokouhi** 2024-11-04 22:30 UTC
Labels: bug
