### ISSUE TITLE
Statistics reports unsupported state class for battery sensors for Android mobile devices.

### ISSUE THREAD

**Issue by nmeachen** [home-assistant/android#3298] opened 2023-02-02 01:59 UTC
**Home Assistant Android version:** 2023.1.1-full

**Android version:** 13

**Phone model:** Samsung Galaxy S22

**Home Assistant version:** Home Assistant 2023.1.7 Docker container

**Last working Home Assistant release (if known):** none

**Description of problem:** The statistics tab of Developer Tools reports that "The state class '' of this entity is not supported." for battery level, battery temperature and battery power. Clicking Fix Issue indicates a bug report should be submitted.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
No crash to be reported.
```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/68712447/216211135-03d0367d-a8af-4d3a-bd0a-d7f51f826096.png)
**Additional information:**
I have two Samsung tablets with the same entity issues.

**Comment by dshokouhi** [comment] 2023-02-02 02:01
duplicate of https://github.com/home-assistant/core/issues/83716

**Closed by dshokouhi** 2023-02-02 02:01 UTC
Labels: bug
