### ISSUE TITLE
Cannot connect to Home Assistant after upgrade to 2021.9

### ISSUE THREAD

**Issue by ngohaiitdog** [home-assistant/android#1704] opened 2021-09-09 03:41 UTC
**Home Assistant Android version:**
2021.9.0

**Android version:**
7.0

**Phone model:**
Samsung Galaxy S8

**Home Assistant version:**
2021.9.4

**Last working Home Assistant release (if known):**
2021.8.8

**Description of problem:**
Cannot login from Android app after updating App Ver to 2021.9.0 and HA to 2021.9.4. I try to downgrade HA back to 2021.8.8 but the Android app still cannot connect. I tried to clear cache, clear data, or re-install the app, but still won't connect.

After re-installing, it prompts me to enter the address of HA (https://xxxxxxx.duckdns.org:8123), then it asks me to enter username and password. After that, it prompts that "Error loading Home Assistant. Please check connection" (translated). If I use the same user and address in webpage using google chrome then I can connect. Also tried iOS and it can connect.

Thanks!

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2021-09-09 13:34
is your SSL cert valid? is chrome and/or webview fully up to date? Have you tried restarting your HA server?

**Comment by ngohaiitdog** [comment] 2021-09-09 14:39
@dshokouhi yes it is valid. Chrome and webview are all up to date. Refreshing them has no problem. I tried restarting the server (even physically turned off and then on), but the Android App still cannot connect.

**Comment by dshokouhi** [comment] 2021-09-09 14:43
you said this started after an app update? have you tried rolling back to see if it fixes the issue? has anything on your network changed recently?

**Comment by ngohaiitdog** [comment] 2021-09-10 15:52
Oh! Just tried going back to 2021.6 for the App, but also cannot connect.

**Comment by dshokouhi** [comment] 2021-09-10 16:02
what about your network setup? Anything changed there? Nothing changed in how the app connects. Are you using a proxy? Have you tried the troubleshooting steps in the docs?

https://companion.home-assistant.io/docs/troubleshooting/networking

**Comment by imonlinux** [comment] 2021-09-10 16:18
I was having this exact same problem. I uninstalled the 2010.9 version and installed the 2021.6 Full version and I was able to connect again. This fixed my S21+ and my wifes Note8 which was also affected.

HA:
core-2021.9.4
supervisor-2021.09.0
Home Assistant OS 6.3

**Comment by dshokouhi** [comment] 2021-09-10 16:24
> I was having this exact same problem. I uninstalled the 2010.9 version and installed the 2021.6 Full version and I was able to connect again. This fixed my S21+ and my wifes Note8 which was also affected.
> 
> HA:
> core-2021.9.4
> supervisor-2021.09.0
> Home Assistant OS 6.3

can you please upgrade and get us the ADB logs? The only way we can fix this is if we have proper logs as we are unable to reproduce the issue. We haven't made any changes to this area in a long time.

**Comment by imonlinux** [comment] 2021-09-10 17:16
> > I was having this exact same problem. I uninstalled the 2010.9 version and installed the 2021.6 Full version and I was able to connect again. This fixed my S21+ and my wifes Note8 which was also affected.
> > HA:
> > core-2021.9.4
> > supervisor-2021.09.0
> > Home Assistant OS 6.3
> 
> can you please upgrade and get us the ADB logs? The only way we can fix this is if we have proper logs as we are unable to reproduce the issue. We haven't made any changes to this area in a long time.

I have upgraded to 2021.9 again. It is currently working, but that was the case when it auto upgraded the last time as well. The problem didn't present until a number of days later. I will provide the logs if the issue returns.

**Comment by dshokouhi** [comment] 2021-09-10 18:03
ah then in your case it mustve been bad data that needed to be cleared out.  Not sure why it happens so frequently there would be interested to see the logs along with device info when you get that. Clearing data is a troubleshooting step that we have but getting the logs before that will help to prevent the issue in the future.

**Comment by imonlinux** [comment] 2021-09-10 18:32
> ah then in your case it mustve been bad data that needed to be cleared out. Not sure why it happens so frequently there would be interested to see the logs along with device info when you get that. Clearing data is a troubleshooting step that we have but getting the logs before that will help to prevent the issue in the future.

I'm not sure that is the case. I had deleted cache and data from the 2021.9 install prior to uninstalling it. It did not fix the issue.
Also, this happened on both my S21+ and my wife's Note8 at the same time.
But as I said, if it stops connecting again, I will add the logs here.

**Comment by ngohaiitdog** [comment] 2021-09-11 14:44
@dshokouhi it really is strange then! I don't think I have changed anything in my network. Tried rebooting the router but no luck. Cannot find any workaround yet except using Webview.

**Comment by dshokouhi** [comment] 2021-09-11 14:46
>  Cannot find any workaround yet except using Webview.


What do you mean by this?

**Comment by ngohaiitdog** [comment] 2021-09-11 14:47
Sorry! I just mean I have to use the webview for now, because the App won't work.

**Comment by dshokouhi** [comment] 2021-09-11 14:57
> Sorry! I just mean I have to use the webview for now, because the App won't work.

so the app uses webview, can you please get us the ADB logs so we can what the issue is?

**Comment by ngohaiitdog** [comment] 2021-09-11 15:01
Oh! My fault! I mean I am using the google chrome web version!
And I am not sure it is a networking problem, because after entering the address of the HA instance (https://xxxxx.duckdns.org:8123), it prompts me to enter username and password, which includes the name of my HA's instance (XX's home), so kind of it can somehow connect?

**Comment by ngohaiitdog** [comment] 2021-09-11 15:03
By the way, I have just tried to create another user account, but still failed to login from the App.

**Comment by dshokouhi** [comment] 2021-09-11 15:06
@ngohaiitdog we need the logs to proceed further, please get us the logs so we can see what the issue.  You will need to use a computer to grab them.

**Comment by ngohaiitdog** [comment] 2021-09-11 15:07
@dshokouhi OK! I am not too familiar with that, is there a quick reference how I can get the log?

**Comment by dshokouhi** [comment] 2021-09-11 15:10
I wish it were easier to describe but Google has this link https://developer.android.com/studio/command-line/logcat and there is also an app called Logcat Reader that will work but for both of these methods you need to plug the device into a computer

**Comment by mcv93us** [comment] 2021-09-12 21:43
Good morning,
I also have this problem.
I tried to uninstall the APP and delete cache and data and reinstall it (the latest version 2021.9.0-full) but I have not concluded anything, now it stops at the login page, I put username and password and then it tells me that it is impossible connect, if I try with the chrome browser of the smartphone, however, it works regularly.
My smartphone is a 64GB Xiaomi Redmi Note 4 with Android 7.0 NRD90M with MIUI 11.0.2.0
HAS:
core-2021.9.6
supervisor-2021.09.0
I have attached the complete log of 12 September taken with the Logcat Reader APP filtering only "homeassistant", if you need anything else let me know.
Thank you very much!!!
[logcat_09-12-2021_23-26-41.txt](https://github.com/home-assistant/android/files/7150336/logcat_09-12-2021_23-26-41.txt)

**Comment by ngohaiitdog** [comment] 2021-09-13 09:11
@dshokouhi thanks! will surely try when I have time

**Comment by dshokouhi** [comment] 2021-09-14 14:26
> Good morning,
> I also have this problem.
> I tried to uninstall the APP and delete cache and data and reinstall it (the latest version 2021.9.0-full) but I have not concluded anything, now it stops at the login page, I put username and password and then it tells me that it is impossible connect, if I try with the chrome browser of the smartphone, however, it works regularly.
> My smartphone is a 64GB Xiaomi Redmi Note 4 with Android 7.0 NRD90M with MIUI 11.0.2.0
> HA:
> core-2021.9.6
> supervisor-2021.09.0
> I have attached the complete log of 12 September taken with the Logcat Reader APP filtering only "homeassistant", if you need anything else let me know.
> Thank you very much!!!
> [logcat_09-12-2021_23-26-41.txt](https://github.com/home-assistant/android/files/7156257/logcat_09-12-2021_23-26-41.txt)

ok so took a look and I see the following error which unfortunately does not have the actual issue:

```
[09-12 23:15:51.328 13803:13836 E/SensorReceiver]
Issue registering sensor: battery_temperature
io.homeassistant.companion.android.common.data.integration.IntegrationException: Error calling integration request register_sensor
	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.registerSensor(IntegrationRepositoryImpl.kt:473)
	at io.homeassistant.companion.android.sensors.SensorReceiver.updateSensors(SensorReceiver.kt:172)
	at io.homeassistant.companion.android.sensors.SensorReceiver$onReceive$2.invokeSuspend(SensorReceiver.kt:133)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

Can you reproduce the error and grab the full logs? Maybe there is some other failure that we are not seeing here because the above is not helpful here.

**Comment by mcv93us** [comment] 2021-09-14 18:14
Here is the complete log; it is quite full-bodied, I tried to censor the sensitive parts but with so much data it is quite difficult.
However, after reinstalling the APP I always stop at the login screen, but if I specifically enter a wrong password I can see the HA notification on the PC, this means that it acquires the data but I don't understand where it stops.

[logcat_09-14-2021_19-44-51.txt](https://github.com/home-assistant/android/files/7164202/logcat_09-14-2021_19-44-51.txt)

**Comment by mcv93us** [comment] 2021-09-16 14:32
Good morning,
I did other tests by clearing the entire cache of the smartphone, at the next restart I arriavto to enter HA using the APP but only with internal address (192.168.xx), I discovered among other things that the names of the sensors have all changed after reinstalling the APP, they were previously in Italian and now they are in English despite having configured the APP with Italian.
After a couple of tests restarting the HA server I again entered the external address xxx.duckdns.org and strangely I got to enter HA but every now and then it tells me that it is impossible to connect, the strange thing is that from the PC I can see the HA notifications of a login attempt with wrong password; he doesn't always do it but every now and then and I can't understand why.
I haven't changed the password yet sometimes it goes and sometimes it doesn't; now if this happens to me I have to log in with the local address and then restart HA to make everything work again.

**Comment by mcv93us** [comment] 2021-09-19 18:07
After a few days the situation has not changed, I cannot access HA except from a local with wifi and only with the internal address (192.168.xx), once I have logged in and entered I can close the wifi and navigate between the pages using the external network, the only thing is that it does not detect the position it says that I am always at home despite the sensor management of the APP showing me the real position.
Every time I delete the token and try to log in, I have to repeat the above procedure.
Since I use the APP a lot in my automations, I'm sorry it doesn't work anymore.
I don't know if there is an alternative APP that does this and works with HA, I would bother having to switch to a new home automation software.
I have attached the log taken directly from the APP.

[homeassistant_companion_log_8-19-2021_17-25-24.txt](https://github.com/home-assistant/android/files/7192649/homeassistant_companion_log_8-19-2021_17-25-24.txt)

**Comment by dshokouhi** [comment] 2021-09-19 18:22
> Every time I delete the token and try to log in, I have to repeat the above procedure.

where did you find this as a valid troubleshooting step? The only steps you should be following is: https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

The errors in the logs are all over the place here.


This is a google play services error, never seen it before:

```
09-19 17:23:45.250  9577  9577 E ActivitySM: Failed to register for sleep updates
09-19 17:23:45.250  9577  9577 E ActivitySM: com.google.android.gms.common.api.ApiException: 16: 
09-19 17:23:45.250  9577  9577 E ActivitySM: 	at com.google.android.gms.common.api.internal.TaskUtil.setResultOrApiException(com.google.android.gms:play-services-base@@17.5.0:6)
09-19 17:23:45.250  9577  9577 E ActivitySM: 	at com.google.android.gms.common.api.internal.TaskUtil.setResultOrApiException(com.google.android.gms:play-services-base@@17.5.0:2)
09-19 17:23:45.250  9577  9577 E ActivitySM: 	at com.google.android.gms.location.zzi.onResult(com.google.android.gms:play-services-location@@18.0.0:1)
09-19 17:23:45.250  9577  9577 E ActivitySM: 	at com.google.android.gms.common.api.internal.IStatusCallback$Stub.zaa(com.google.android.gms:play-services-base@@17.5.0:11)
09-19 17:23:45.250  9577  9577 E ActivitySM: 	at com.google.android.gms.internal.base.zaa.onTransact(com.google.android.gms:play-services-base@@17.5.0:13)
09-19 17:23:45.250  9577  9577 E ActivitySM: 	at android.os.Binder.execTransact(Binder.java:569)
```

This means your device is unable to hit the HA firebase server:

```
09-19 17:23:45.307  9577  9631 E IntegrationRepository: Unable to get notification rate limits
```

This is similar if not the same as the above error, device is unable to hit an external service:

```
09-19 17:23:46.020  9577 10545 E NetworkSM: Error getting response from external service
```

This is another really bad error as your device is not able to get the authentication token from your HA server:

```
09-19 17:24:42.497  9577  9577 E WebViewPresenterImpl: Unable to retrieve external auth
```

is there anything special about this device? Custom ROM?  Something is not right with those logs up above. Maybe there is a DNS issue here since you said it works fine locally?

**Comment by mcv93us** [comment] 2021-09-19 22:15
The rom is original and the smartphone is not unlocked.
From a local, if I use the IP address to log in the first time it works, then it works for me even without using the wifi network, I don't know why ...
I will try again to delete everything and remove the integration from HA but first I make a security backup.

**Comment by arnishow** [comment] 2021-10-01 06:16
[https://github.com/home-assistant/addons/issues/2183](url)

**Comment by mcv93us** [comment] 2021-10-01 18:06
I solved it with the latest Duckdns update by setting the algorithm as prime256v1.

**Comment by dshokouhi** [comment] 2021-10-01 18:13
Are we good to close this issue? Doesn't seem to be an issue with the app.

**Comment by nagyrobi** [comment] 2021-10-01 20:25
Seems to be https://github.com/home-assistant/android/issues/1741#issuecomment-932474357

Lots of people use Let's Encrypt...

**Comment by dshokouhi** [comment] 2021-10-01 20:28
yea and they have made this announcement a while ago so plenty of time to update, as this is not something the app can solve going to close this now.  If any other issues come up please open a new issue with logs so we can investigate further.

**Closed by dshokouhi** 2021-10-01 20:28 UTC
Labels: bug

**Comment by sesquipedality** [comment] 2021-10-04 17:15
I am afraid you are wrong about this.  LetsEncrypt made an announcement in mid 2020 to say it was going to stop working, and then they found a work around.  The current workaround is due to continue to work until December 2024 (https://community.letsencrypt.org/t/production-chain-changes/150739). It is in fact something HA can solve, since both Google Chrome and Firefox for Android are able to detect Home Assistant's certificates as valid on Android 7.   As to updating, the cost of replacing 4 tablets is a little prohibitive, wouldn't you agree?  I suppose I can carry on using HA from within chrome if you're absolutely determined not to fix the bug since I certainly lack the knowledge of SSL to be able to do it myself, but I'm a bit surprised that that would be the line would be taken in a product whose very reason for being is to connect everything but the kitchen sink.

**Comment by dshokouhi** [comment] 2021-10-04 17:52
> I am afraid you are wrong about this.  LetsEncrypt made an announcement in mid 2020 to say it was going to stop working, and then they found a work around.  The current workaround is due to continue to work until December 2024 (https://community.letsencrypt.org/t/production-chain-changes/150739). It is in fact something HA can solve, since both Google Chrome and Firefox for Android are able to detect Home Assistant's certificates as valid on Android 7.   As to updating, the cost of replacing 4 tablets is a little prohibitive, wouldn't you agree?  I suppose I can carry on using HA from within chrome if you're absolutely determined not to fix the bug since I certainly lack the knowledge of SSL to be able to do it myself, but I'm a bit surprised that that would be the line would be taken in a product whose very reason for being is to connect everything but the kitchen sink.

Can you please open a new issue with the logcat error so we can investigate?

**Comment by sesquipedality** [comment] 2021-10-05 08:33
Sorry - looks like I posted this to the wrong bug.  The logs are in #1741 as referenced above.
