### ISSUE TITLE
Recent Crash: Websocket Concurrent Modification

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#3059] opened 2022-11-11 19:43 UTC
**Home Assistant Android version:**

latest master

**Android version:**

13

**Phone model:**

Pixel 7 Pro

**Home Assistant version:**

2022.11.2

**Last working Home Assistant release (if known):**

n/a

**Description of problem:**

Noticed the app crashed recently with the below stacktrace

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
2022-11-10 17:40:02.011: java.util.ConcurrentModificationException
    at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:760)
    at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:787)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.subscribeTo(WebSocketRepositoryImpl.kt:286)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.access$subscribeTo(WebSocketRepositoryImpl.kt:65)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl$subscribeTo$1.invokeSuspend(Unknown Source:18)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
    at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e3395c, Dispatchers.IO]
```

**Screenshot of problem:**

**Additional information:**

**Comment by jpelgrom** [comment] 2022-11-12 16:05
While trying to reproduce this I'm not able to get the app to crash but I am able to get the `activeMessages` map to break fairly reliably by quicly opening/closing device controls. At some point the app does still subscribe but isn't saving it correctly to the map due to modification from multiple coroutines and returns `null` for subscriptions.

**Closed** 2022-11-12 22:37 UTC
Labels: bug
