### ISSUE TITLE
Please rebuild the application by another way.

### ISSUE THREAD

**Issue by 1Misaka** [home-assistant/android#1353] opened 2021-02-07 14:39 UTC
hi,the application is made like webpage.
i mean,i could only control one home-assistant with the app,when i wanna use the app to control another hass server,the application crashed.

**Comment by dshokouhi** [comment] 2021-02-07 15:20
Please do not delete the template when you submit a request. Also duplicate of #296 .

**Closed by dshokouhi** 2021-02-07 15:20 UTC
Labels: enhancement
