### ISSUE TITLE
Android 5.0.1 - Home Assistant cannot be installed

### ISSUE THREAD

**Issue by Szbuli** [home-assistant/android#1226] opened 2020-12-06 08:40 UTC
**Home Assistant Android version:** Latest

**Android version:** 5.0.1

**Phone model:** Lenovo TB3-710F

**Home Assistant version:** 0.118.4

**Last working Home Assistant release (if known):** NA

**Description of problem:** When trying to install the app with Playstore, an error will be returned that: Home Assistant cannot be installed

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:** Found a forum post with same error: https://community.home-assistant.io/t/cannot-install-app/251332

I have sent the built in error report with the stack trace, but i am not sure who will get it. If you need more info let me know. I can try to copy it here if it helps.

**Comment by Szbuli** [comment] 2020-12-06 18:47
I tried to install the application from source. But got the same error

> 2-06 19:38:33.666 5026-5026/? I/AEE/AED: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-06 19:38:33.666 5026-5026/? I/AEE/AED: Build fingerprint: 'Lenovo/LenovoTB3-710F/TB3-710F:5.0.1/LRX21M/TB3-710F_S000028_170316_ROW:user/release-keys'
12-06 19:38:33.666 5026-5026/? I/AEE/AED: Revision: '0'
12-06 19:38:33.666 5026-5026/? I/AEE/AED: ABI: 'arm'
12-06 19:38:33.666 5026-5026/? I/AEE/AED: pid: 5018, tid: 5021, name: Compiler driver  >>> /system/bin/dex2oat <<<
12-06 19:38:33.666 5026-5026/? I/AEE/AED: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xdef1e801
12-06 19:38:33.667 536-819/? W/NativeCrashListener: Couldn't find ProcessRecord for pid 5018
12-06 19:38:33.680 132-132/? D/hwcomposer: [HWC] hdmi connect=0, isDecoupleOvl=0
12-06 19:38:33.680 132-132/? D/hwcomposer: [HWC] prepare_primary==
12-06 19:38:33.682 5026-5026/? I/AEE/AED:     r0 b1085e70  r1 def1e7fd  r2 def1e7fd  r3 ffff0094
12-06 19:38:33.682 5026-5026/? E/AEE/AED: AM write failure (32 / Broken pipe)
12-06 19:38:33.682 5026-5026/? I/AEE/AED:     r4 00000135  r5 b2dbd668  r6 b107302c  r7 b0c317d8
12-06 19:38:33.682 5026-5026/? I/AEE/AED:     r8 b107b5b0  r9 b0c31698  sl b2dbd740  fp b0eaf458
12-06 19:38:33.682 5026-5026/? I/AEE/AED:     ip b1073030  sp b2dbd638  lr b682681b  pc b68230b8  cpsr a00b0030
12-06 19:38:33.683 5026-5026/? I/AEE/AED: backtrace:
12-06 19:38:33.683 5026-5026/? I/AEE/AED:     #00 pc 0008b0b8  /system/lib/libart-compiler.so (_ZNSt3__13mapIytNS_4lessIyEEN3art27ScopedArenaAllocatorAdapterINS_4pairIKytEEEEE12emplace_hintIIRS6_RKtEEENS_14__map_iteratorINS_15__tree_iteratorINS_12__value_typeIytEEPNS_11__tree_nodeISH_PvEEiEEEENS_20__map_const_iteratorINS_21__tree_const_iteratorISH_SL_iEEEEDpOT_+247)
12-06 19:38:33.683 5026-5026/? I/AEE/AED:     #01 pc 0008e817  /system/lib/libart-compiler.so
12-06 19:38:33.683 5026-5026/? I/AEE/AED:     #02 pc 0008e885  /system/lib/libart-compiler.so
12-06 19:38:33.683 5026-5026/? I/AEE/AED:     #03 pc 00091b89  /system/lib/libart-compiler.so (_ZN3art19LocalValueNumbering10HandleIPutEPNS_3MIREt+32)
12-06 19:38:33.683 5026-5026/? I/AEE/AED:     #04 pc 00200d5d  /system/lib/libart-compiler.so (_ZN3art19LocalValueNumbering14GetValueNumberEPNS_3MIRE+956)
12-06 19:38:33.683 5026-5026/? I/AEE/AED:     #05 pc 001416b9  /system/lib/libart-compiler.so (_ZN3art8MIRGraph28ApplyGlobalValueNumberingEndEv+144)
12-06 19:38:33.683 5026-5026/? I/AEE/AED:     #06 pc 0020f7c7  /system/lib/libart-compiler.so (_ZN3art20MTK_PassDriverMEOpts9ApplyPassEPNS_14PassDataHolderEPKNS_4PassE+38)
12-06 19:38:33.683 5026-5026/? I/AEE/AED:     #07 pc 00206b87  /system/lib/libart-compiler.so
12-06 19:38:33.683 5026-5026/? I/AEE/AED:     #08 pc 0020606d  /system/lib/libart-compiler.so (_ZN3art13RunPassDriverEPNS_15CompilationUnitE+232)
12-06 19:38:33.683 5026-5026/? I/AEE/AED:     #09 pc 00144f51  /system/lib/libart-compiler.so
12-06 19:38:33.683 5026-5026/? I/AEE/AED:     #10 pc 00108895  /system/lib/libart-compiler.so (_ZNK3art13QuickCompiler7CompileEPKNS_7DexFile8CodeItemEjNS_10InvokeTypeEtjP8_jobjectRKS1_+80)
12-06 19:38:33.683 5026-5026/? I/AEE/AED:     #11 pc 0015c121  /system/lib/libart-compiler.so (_ZN3art14CompilerDriver13CompileMethodEPKNS_7DexFile8CodeItemEjNS_10InvokeTypeEtjP8_jobjectRKS1_NS_24DexToDexCompilationLevelE+928)
12-06 19:38:33.683 5026-5026/? I/AEE/AED:     #12 pc 0015c7e9  /system/lib/libart-compiler.so (_ZN3art14CompilerDriver12CompileClassEPKNS_26ParallelCompilationManagerEj+1240)
12-06 19:38:33.683 5026-5026/? I/AEE/AED:     #13 pc 00152d55  /system/lib/libart-compiler.so
12-06 19:38:33.684 5026-5026/? I/AEE/AED:     #14 pc 0022f811  /system/lib/libart.so (_ZN3art16ThreadPoolWorker3RunEv+36)
12-06 19:38:33.684 5026-5026/? I/AEE/AED:     #15 pc 00230061  /system/lib/libart.so (_ZN3art16ThreadPoolWorker8CallbackEPv+52)
12-06 19:38:33.684 5026-5026/? I/AEE/AED:     #16 pc 0001671b  /system/lib/libc.so (_ZL15__pthread_startPv+30)
12-06 19:38:33.684 5026-5026/? I/AEE/AED:     #17 pc 000147f7  /system/lib/libc.so (__start_thread+6)
12-06 19:38:33.793 5026-5026/? I/AEE/AED: Tombstone written to: /data/tombstones/tombstone_08
12-06 19:38:33.794 5026-5026/? E/AEE/AED: request.action: 0
12-06 19:38:33.794 5026-5026/? V/AEE/AED: dashboard_record_update() : rec->module = /system/bin/dex2oat 
12-06 19:38:33.794 5026-5026/? D/AEE/AED: Duplicated exception, cnt = 4 
12-06 19:38:33.794 5026-5026/? D/AEE/AED: Last exception time: 1607279311 
12-06 19:38:33.794 5026-5026/? D/AEE/AED: cur time: 1607279913 
12-06 19:38:33.794 5026-5026/? D/AEE/AED: Skip for Exp level'0'
12-06 19:38:33.794 536-560/? V/SettingsInterface:  from settings cache , name = dropbox:SYSTEM_TOMBSTONE , value = null
12-06 19:38:33.794 536-560/? I/BootReceiver: Copying /data/tombstones/tombstone_08 to DropBox (SYSTEM_TOMBSTONE)
12-06 19:38:33.795 141-141/? D/AEE/AED: $===AEE===AEE===AEE===$
12-06 19:38:33.795 141-141/? D/AEE/AED: p 0 poll events 1 revents 0
12-06 19:38:33.795 141-141/? D/AEE/AED: not know revents:0
12-06 19:38:33.795 141-141/? D/AEE/AED: p 1 poll events 1 revents 0
12-06 19:38:33.795 141-141/? D/AEE/AED: not know revents:0
12-06 19:38:33.795 141-141/? D/AEE/AED: p 2 poll events 1 revents 0
12-06 19:38:33.795 141-141/? D/AEE/AED: not know revents:0
12-06 19:38:33.795 141-141/? D/AEE/AED: p 3 poll events 1 revents 0
12-06 19:38:33.795 141-141/? D/AEE/AED: not know revents:0
12-06 19:38:33.795 141-141/? D/AEE/AED: p 4 poll events 1 revents 0
12-06 19:38:33.795 141-141/? D/AEE/AED: not know revents:0
12-06 19:38:33.795 141-141/? D/AEE/AED: p 5 poll events 0 revents 0
12-06 19:38:33.795 141-141/? D/AEE/AED: not know revents:0
12-06 19:38:33.796 536-1763/? E/SharedPreferencesImpl: Couldn't create directory for SharedPreferences file shared_prefs/log_files.xml
12-06 19:38:33.799 132-132/? D/hwcomposer: [HWC] hdmi connect=0, isDecoupleOvl=0
12-06 19:38:33.799 132-132/? D/hwcomposer: [HWC] prepare_primary==
12-06 19:38:33.808 536-560/? V/SettingsInterface:  from settings cache , name = dropbox:SYSTEM_TOMBSTONE , value = null
12-06 19:38:33.808 536-560/? V/SettingsInterface:  from settings cache , name = dropbox_age_seconds , value = null
12-06 19:38:33.809 536-560/? V/SettingsInterface:  from settings cache , name = dropbox_max_files , value = null
12-06 19:38:33.809 536-560/? V/SettingsInterface:  from settings cache , name = dropbox_quota_percent , value = null
12-06 19:38:33.809 536-560/? V/SettingsInterface:  from settings cache , name = dropbox_reserve_percent , value = null
12-06 19:38:33.809 536-560/? V/SettingsInterface:  from settings cache , name = dropbox_quota_kb , value = null
12-06 19:38:33.849 144-144/? E/installd: DexInv: --- END '/data/app/io.homeassistant.companion.android-1/base.apk' --- status=0x000b, process failed
12-06 19:38:33.850 536-571/? I/PackageManager: Dexopt done on: io.homeassistant.companion.android
12-06 19:38:33.851 144-144/? D/installd: do_remove : io.homeassistant.companion.android 0
12-06 19:38:33.851 144-144/? D/installd: uninstall : io.homeassistant.companion.android
12-06 19:38:33.853 536-571/? W/PackageManager: Package couldn't be installed in /data/app/io.homeassistant.companion.android-1
    com.android.server.pm.PackageManagerException: scanPackageLI
        at com.android.server.pm.PackageManagerService.scanPackageDirtyLI(PackageManagerService.java:6331)
        at com.android.server.pm.PackageManagerService.scanPackageLI(PackageManagerService.java:5641)
        at com.android.server.pm.PackageManagerService.installNewPackageLI(PackageManagerService.java:10765)
        at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:11320)
        at com.android.server.pm.PackageManagerService.access$2900(PackageManagerService.java:238)
        at com.android.server.pm.PackageManagerService$6.run(PackageManagerService.java:9209)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:194)
        at android.os.HandlerThread.run(HandlerThread.java:61)
        at com.android.server.ServiceThread.run(ServiceThread.java:46)
12-06 19:38:33.853 536-571/? I/PackageManager: Installation done for package: com.android.vending
12-06 19:38:33.862 536-536/? V/ActivityManager: Broadcast: Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } ordered=false userid=0 callerApp=ProcessRecord{13c64dfb 536:system/1000}
12-06 19:38:33.865 1316-1316/? D/ActivityThread: BDC-Calling onReceive: intent=Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 cmp=com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver (has extras) }, receiver=com.google.android.gms.stats.service.DropBoxEntryAddedReceiver@d072d38
12-06 19:38:33.867 132-132/? D/hwcomposer: [HWC] hdmi connect=0, isDecoupleOvl=0
12-06 19:38:33.867 132-132/? D/hwcomposer: [HWC] prepare_primary==
12-06 19:38:33.870 536-571/? V/PackageManager: + starting restore round-trip 4
12-06 19:38:33.870 536-571/? V/PackageManager: No restore - queue post-install for 4
12-06 19:38:33.870 536-571/? I/PackageManager: mcs_unbind
12-06 19:38:33.871 536-571/? I/PackageManager: calling disconnectService()
12-06 19:38:33.871 536-571/? I/PackageManager: disconnectService: false
12-06 19:38:33.873 1316-1316/? D/ActivityThread: BDC-RECEIVER handled : 0 / ReceiverData{intent=Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 cmp=com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver (has extras) } packageName=com.google.android.gms resultCode=-1 resultData=null resultExtras=null}
12-06 19:38:33.873 1316-1316/? D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@2d258111 className=com.google.android.gms.stats.service.DropBoxEntryAddedService packageName=com.google.android.gms intent=null}
12-06 19:38:33.876 536-571/? I/PackageManager: mcs_check
12-06 19:38:33.877 536-571/? I/PackageManager: mcs_check(false, 1)
12-06 19:38:33.877 536-571/? I/PackageManager: Trying to bind to DefaultContainerService
12-06 19:38:33.877 1316-1316/? D/ActivityThread: SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@2d258111 className=com.google.android.gms.stats.service.DropBoxEntryAddedService packageName=com.google.android.gms intent=null}
12-06 19:38:33.878 1316-1316/? D/ActivityThread: SVC-Calling onStartCommand: com.google.android.gms.stats.service.DropBoxEntryAddedService@a715276, flags=0, startId=1
12-06 19:38:33.878 1316-1316/? D/ActivityThread: SVC-SERVICE_ARGS handled : 0 / ServiceArgsData{token=android.os.BinderProxy@2d258111 startId=1 args=Intent { act=com.google.android.gms.stats.ACTION_UPLOAD_DROPBOX_ENTRIES pkg=com.google.android.gms (has extras) }}
12-06 19:38:33.878 4425-4425/? D/ActivityThread: SVC-UNBIND_SERVICE handled : 0 / BindServiceData{token=android.os.BinderProxy@2d5f58b3 intent=Intent { cmp=com.android.defcontainer/.DefaultContainerService }}
12-06 19:38:33.879 4425-4425/? D/ActivityThread: SVC-Destroying service: com.android.defcontainer.DefaultContainerService@2f32ab88
12-06 19:38:33.879 4425-4425/? D/ActivityThread: SVC-STOP_SERVICE handled : 0 / android.os.BinderProxy@2d5f58b3
12-06 19:38:33.881 1316-1316/? D/ActivityThread: BDC-Calling onReceive: intent=Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 cmp=com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver (has extras) }, receiver=com.google.android.gms.chimera.GmsIntentOperationService$PersistentTrustedReceiver@5501d4d
12-06 19:38:33.883 132-132/? D/hwcomposer: [HWC] hdmi connect=0, isDecoupleOvl=0
12-06 19:38:33.883 132-132/? D/hwcomposer: [HWC] prepare_primary==
12-06 19:38:33.888 536-571/? I/PackageManager: mcs_unbind
12-06 19:38:33.889 536-571/? I/PackageManager: calling disconnectService()
12-06 19:38:33.889 536-571/? I/PackageManager: disconnectService: false
12-06 19:38:33.891 4425-4425/? D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@3c06a921 className=com.android.defcontainer.DefaultContainerService packageName=com.android.defcontainer intent=null}
12-06 19:38:33.892 536-571/? V/PackageManager: Handling post-install for 4
12-06 19:38:33.895 4425-4425/? D/ActivityThread: SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@3c06a921 className=com.android.defcontainer.DefaultContainerService packageName=com.android.defcontainer intent=null}
12-06 19:38:33.897 1316-1562/? V/SettingsInterface:  from settings cache , name = multi_cb , value = 0
12-06 19:38:33.900 132-132/? D/hwcomposer: [HWC] hdmi connect=0, isDecoupleOvl=0
12-06 19:38:33.900 132-132/? D/hwcomposer: [HWC] prepare_primary==
12-06 19:38:33.906 536-559/? V/NetworkStats: setKernelCounterSet uid=10008 set=0
12-06 19:38:33.907 1316-1316/? D/ActivityThread: BDC-RECEIVER handled : 0 / ReceiverData{intent=Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 cmp=com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver (has extras) } packageName=com.google.android.gms resultCode=0 resultData=null resultExtras=null}
12-06 19:38:33.907 536-746/? D/ConnectivityService: onUidRulesChanged(uid=10008, uidRules=0)
12-06 19:38:33.907 4425-4425/? D/ActivityThread: SVC-BIND_SERVICE handled : 0 / BindServiceData{token=android.os.BinderProxy@3c06a921 intent=Intent { cmp=com.android.defcontainer/.DefaultContainerService }}
12-06 19:38:33.908 4425-4425/? D/ActivityThread: SVC-UNBIND_SERVICE handled : 0 / BindServiceData{token=android.os.BinderProxy@3c06a921 intent=Intent { cmp=com.android.defcontainer/.DefaultContainerService }}
12-06 19:38:33.908 4425-4425/? D/ActivityThread: SVC-Destroying service: com.android.defcontainer.DefaultContainerService@6e44146
12-06 19:38:33.908 4425-4425/? D/ActivityThread: SVC-STOP_SERVICE handled : 0 / android.os.BinderProxy@3c06a921
12-06 19:38:33.909 1475-1475/? D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@29943f05 className=com.google.android.gms.chimera.GmsIntentOperationService packageName=com.google.android.gms intent=null}
12-06 19:38:33.911 1475-1475/? D/ActivityThread: SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@29943f05 className=com.google.android.gms.chimera.GmsIntentOperationService packageName=com.google.android.gms intent=null}
12-06 19:38:33.912 1475-1475/? D/ActivityThread: SVC-Calling onStartCommand: com.google.android.gms.chimera.GmsIntentOperationService@22308b5a, flags=0, startId=1
12-06 19:38:33.914 1475-1475/? D/ActivityThread: SVC-SERVICE_ARGS handled : 0 / ServiceArgsData{token=android.os.BinderProxy@29943f05 startId=1 args=Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 pkg=com.google.android.gms cmp=com.google.android.gms/.chimera.GmsIntentOperationService (has extras) }}
12-06 19:38:33.915 1316-1316/? D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@2aeec7c className=com.google.android.gms.chimera.PersistentApiService packageName=com.google.android.gms intent=null}
12-06 19:38:33.915 536-1250/? V/AlarmManager: isAlarmNeedAlign : charging
12-06 19:38:33.917 1316-1316/? D/ActivityThread: SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@2aeec7c className=com.google.android.gms.chimera.PersistentApiService packageName=com.google.android.gms intent=null}
12-06 19:38:33.918 1316-1316/? D/BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.udc.service.START cmp=com.google.android.gms/.chimera.PersistentApiService }
12-06 19:38:33.919 1316-1316/? D/BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.udc.service.START cmp=com.google.android.gms/.chimera.PersistentApiService }
12-06 19:38:33.920 132-132/? I/SurfaceFlinger: [Built-in Screen (type:0)] fps:59.256657,dur:1012.54,max:19.91,min:16.51
12-06 19:38:33.920 132-132/? D/hwcomposer: [HWC] hdmi connect=0, isDecoupleOvl=0
12-06 19:38:33.920 132-132/? D/hwcomposer: [HWC] prepare_primary==
12-06 19:38:33.924 1316-1316/? D/ActivityThread: SVC-BIND_SERVICE handled : 0 / BindServiceData{token=android.os.BinderProxy@2aeec7c intent=Intent { act=com.google.android.gms.udc.service.START cmp=com.google.android.gms/.chimera.PersistentApiService }}
12-06 19:38:33.932 1316-1316/? D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@c703567 className=com.google.android.location.reporting.service.ReportingAndroidService packageName=com.google.android.gms intent=null}
12-06 19:38:33.933 1316-1316/? D/ActivityThread: SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@c703567 className=com.google.android.location.reporting.service.ReportingAndroidService packageName=com.google.android.gms intent=null}
12-06 19:38:33.934 132-132/? D/hwcomposer: [HWC] hdmi connect=0, isDecoupleOvl=0
12-06 19:38:33.934 132-132/? D/hwcomposer: [HWC] prepare_primary==
12-06 19:38:33.936 1316-1316/? D/ActivityThread: SVC-BIND_SERVICE handled : 0 / BindServiceData{token=android.os.BinderProxy@c703567 intent=Intent { act=com.google.android.gms.location.reporting.service.START pkg=com.google.android.gms }}
12-06 19:38:33.938 1316-1316/? D/ActivityThread: SVC-Destroying service: com.google.android.gms.stats.service.DropBoxEntryAddedService@a715276
12-06 19:38:33.938 1316-1316/? D/ActivityThread: SVC-STOP_SERVICE handled : 0 / android.os.BinderProxy@2d258111
12-06 19:38:33.941 1475-5029/? V/SettingsInterface:  from settings cache , name = package_verifier_user_consent , value = 1
12-06 19:38:34.060 536-571/? I/art: Explicit concurrent mark sweep GC freed 48606(2MB) AllocSpace objects, 11(1096KB) LOS objects, 19% free, 16MB/20MB, paused 2.142ms total 167.375ms
12-06 19:38:34.060 536-571/? V/ActivityManager: Broadcast: Intent { act=com.android.vending.INTENT_PACKAGE_INSTALL_COMMIT.819829082 flg=0x10 (has extras) } ordered=false userid=0 callerApp=null
12-06 19:38:34.064 2529-2529/? E/Finsky: [1] ylw.onReceive(15): Error -504 while installing io.homeassistant.companion.android: INSTALL_FAILED_DEXOPT: Package couldn't be installed in /data/app/io.homeassistant.companion.android-1: scanPackageLI
12-06 19:38:34.068 132-132/? D/hwcomposer: [HWC] hdmi connect=0, isDecoupleOvl=0
12-06 19:38:34.068 132-132/? D/hwcomposer: [HWC] prepare_primary==
12-06 19:38:34.076 536-920/? W/System.err: java.lang.SecurityException: Caller has no access to session 819829082
12-06 19:38:34.079 536-920/? W/System.err:     at com.android.server.pm.PackageInstallerService.abandonSession(PackageInstallerService.java:636)
12-06 19:38:34.079 536-920/? W/System.err:     at android.content.pm.IPackageInstaller$Stub.onTransact(IPackageInstaller.java:97)
12-06 19:38:34.080 536-920/? W/System.err:     at android.os.Binder.execTransact(Binder.java:451)
12-06 19:38:34.080 2529-2852/? W/Finsky: [351] yma.C(5): Unexpected error abandoning session=819829082. exception=java.lang.SecurityException: Caller has no access to session 819829082
12-06 19:38:34.081 2529-2529/? W/Finsky: [1] qsz.d(4): IT: Install failure of io.homeassistant.companion.android (isid: xGkhvxHERwGrswTDMwRwtw): -504, Exception: n/a

**Comment by dshokouhi** [comment] 2020-12-06 18:57
Duplicate of #538

**Closed by dshokouhi** 2020-12-06 18:57 UTC
Labels: bug
