### ISSUE TITLE
Back button in subview doesn't work after leaving the app I'm the background

### ISSUE THREAD

**Issue by guerda** [home-assistant/android#3186] opened 2022-12-30 07:06 UTC
**Home Assistant Android version:** 2022-12-minimal

**Android version:** 13

**Phone model:** Pixel 7

**Home Assistant version:**  Home Assistant 2022.12.8 Frontend 20221213.1 - latest 

**Last working Home Assistant release (if known):** none

**Description of problem:**
I set up sub views in my dashboard. If I enter a subview and lock the device or leaves the app and come back to the app later on, I'm stuck in this subview. The back button does not work at all, closing the app does not work and killing it neither. 
The back button seems to be pressed, but doesn't do anything 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
None
```

**Screenshot of problem:**
![Screenshot_20221230-080526.png](https://user-images.githubusercontent.com/230782/210043775-59daec38-3455-4d00-9372-72a42412a4ca.png)

**Additional information:**
I assume that the app lost the connection in between.
Clearing app cache didn't work, but clearing app storage did.

**Comment by dshokouhi** [comment] 2022-12-30 22:36
duplicate of https://github.com/home-assistant/frontend/issues/14041

**Closed by dshokouhi** 2022-12-30 22:36 UTC
Labels: bug

**Comment by guerda** [comment] 2022-12-31 06:01
Thanks!
