### ISSUE TITLE
Refresh option for companion app Please!

### ISSUE THREAD

**Issue by pdahollandaero** [home-assistant/android#4078] opened 2023-12-28 23:16 UTC
**Is your feature request related to a problem? Please describe.**

When using mobile app and streaming video, often the lovelace card / page will hang up.

On PC browser, it is possible to refresh page. On mobile browser it is possible to reload page.

But on mobile app, I am forced to change layout/page, then come back to the page I am trying to relead/refresh.  Using two identical pages seems like a cumbersome solutionm

The page initial load does the magic required to make the video work again.

I understand this request has been rejected over the past years, but it is inherent problem with video streaming and current HA server/consumer system.

**Describe the solution you'd like**

A reload or refresh page service that can be called.

The feature exists as it auto offers whenever the underlying page has been edited elsewhere.

**Describe alternatives you've considered, if any**

Two duplicate pages to enable page loading via page changing.

Replacing wall panel tablets with mini PCs to evade app limitations.

Tear out hair. :-) reading all the requests for this over last 4 years.

**Additional context**

HA admins are great! but this seems to be needed for a long time.  Pretty please!!!!

**Comment by dshokouhi** [comment] 2023-12-29 16:10
if you are having issues streaming video or loading hte frontend you should file a frontend issue. The app adding a refresh button will not fix the actual issue. There is also already a refresh button in the 3 dot menu, have you tried that already? This is also a duplicate of #31 

Please file a frontend issue for your videos not working

![image](https://github.com/home-assistant/android/assets/1634145/254233e1-d9c6-42a6-9723-ee1513afeeb4)

**Closed by dshokouhi** 2023-12-29 16:10 UTC
Labels: enhancement

**Comment by gianfrdp** [comment] 2025-03-31 00:26
I'm sorry, but there is no refresh button on android

![Image](https://github.com/user-attachments/assets/74160cc0-eb45-4d8e-ba9b-b2c38cdf39bd)

**Comment by jack3308** [comment] 2026-04-08 12:26
Yea - this needs to not be closed. There's currently no way to force a refresh on android, nor is there a way to reload resources. At least not readily from what I can tell. The 3 dot menu doesn't provide the options shown by @dshokouhi's screenshot.

**Comment by jpelgrom** [comment] 2026-04-08 12:44
> Yea - this needs to not be closed. There's currently no way to force a refresh on android, nor is there a way to reload resources. At least not readily from what I can tell. The 3 dot menu doesn't provide the options shown by @dshokouhi's screenshot.

Please dont respond to old issues as they're outdated. If something doesn't work, please create a new issue instead.

 - You can set up a gesture to refresh the page nowadays.
 - An option was added to clear the frontend cache / resources.
