### ISSUE TITLE
Request: Android Widget . An entity state that also has an action when pressed.

### ISSUE THREAD

**Issue by michpas** [home-assistant/android#3794] opened 2023-08-17 06:44 UTC
**Is your feature request related to a problem? Please describe.**
No, new feature request

**Describe the solution you'd like**

Currently an android widgets is either a value from a sensor (entitystate) or an action (service).
It would be great to have the entity-state widget also trigger an action when pressed.
Currently nothing is triggered when pressing a entity-state widget.

Use Case:
I have a widget that shows the battery percentage of e-car.  
Sometime I need to activate a script to have the values updated. (eg. refresh data)
So now I have 2 widgets (one that shows 70% accu-pack charged and a separate widget 'refresh car data')
It would be great to just have one widget that shows a value and when pressed triggers an action.

**Describe alternatives you've considered, if any**

Two seperate widgets on the screen.

**Additional context**

Having a widget that boths shows values and triggers an action when pressed could have more use cases in other automations as well.

**Comment by dshokouhi** [comment] 2023-08-17 13:38
duplicate of #3078 and #3488

**Closed by dshokouhi** 2023-08-17 13:38 UTC
Labels: enhancement
