### ISSUE TITLE
Assist support AT+BVRA command?

### ISSUE THREAD

**Issue by cobryan05** [home-assistant/android#4126] opened 2024-01-10 16:24 UTC
**Is your feature request related to a problem? Please describe.**
When "Home Assistant" is set to my default Voice Assistant and I push the "Voice Assistant" button on my Bluetooth headset it asks me to set up Google Voice Assistant instead of activating Home Assistant Assist

**Describe the solution you'd like**

When Home Assistant is my default voice assistant I would like the BT Voice Assistant button to enable it

**Describe alternatives you've considered, if any**

**Additional context**

The Bluetooth device sends the AT+BVRA command to activate the voice assistant. I believe the app needs to register to receive the BVRA intent 

```
<intent-filter>
    <action android:name="android.intent.action.VOICE_COMMAND"/>
    <category android:name="android.intent.category.DEFAULT" />
</intent-filter>
```

**Comment by dshokouhi** [comment] 2024-01-10 16:26
sounds like a duplicate of either #4046 or #3981

**Comment by jpelgrom** [comment] 2024-01-11 21:39
> sounds like a duplicate of either #4046 or #3981

Not quite a duplicate, but if the fix is to register for the suggested intent we'd need to register for the intent with an activity _only if HA is the active assistant_. So it is likely to be an alias we can enable/disable, just like those launcher icons.

**Closed** 2024-04-20 13:46 UTC
Labels: enhancement, Assist
