### ISSUE TITLE
Universal Media Player Artwork not shown

### ISSUE THREAD

**Issue by earion68** [home-assistant/android#566] opened 2020-04-22 13:22 UTC
**Home Assistant Android version:**
1.8.0-144

**Android version:**
10

**Phone model:**
Xperia XZ2

**Home Assistant version:**
0.108.8

**Last working Home Assistant release (if known):**
N/A

**Description of problem:**
In the Android app, the artwork for Universal Media Player (https://www.home-assistant.io/integrations/universal/) is not shown and replaced with a black background.

- Artwork is displayed correctly for non-universal media players
- Artwork is displayed correctly when accessing from Chrome for Android or Firefox for Android

**Traceback (if applicable):**
N/A

**Screenshot of problem:**
![WhatsApp Image 2020-04-22 at 15 20 41](https://user-images.githubusercontent.com/54678154/79986923-0ec19e00-84ad-11ea-9406-d15381cef794.jpeg)

**Additional information:**

**Comment by dshokouhi** [comment] 2020-08-30 23:38
Just noticed this appears to be a duplicate of #206 closing now

**Closed by dshokouhi** 2020-08-30 23:38 UTC
Labels: bug, webview
