### ISSUE TITLE
mobile_app_notification_action isnt triggered when clicking a URI action

### ISSUE THREAD

**Issue by mwilky** [home-assistant/android#2745] opened 2022-08-01 21:32 UTC
**Home Assistant Android version:**
2022.6.0-full

**Android version:**
12L

**Phone model:**
Pixel 6 Pro

**Home Assistant version:**
Frontend 20220707.1 - latest

**Last working Home Assistant release (if known):**

**Description of problem:**

`URI` action in a notification works but doesn't trigger the `mobile_app_notification_action` event. It also doesn't clear the notification when the `URI` is launched.

Example:

Notification gets sent with a `URI` action to open a webpage. You click the webpage action and it opens to the page fine, but the notification remains when you next pulldown the notifications shade. I was going to create an automation to clear the notification on the mobile_app_notification_action trigger, but this doesn't get triggered on `URI`  actions. Works fine on non `URI` actions.

Is there any other way of clearing the notification when pressing a `URI` action?

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2022-08-01 21:35
duplicate of #2275

**Closed by dshokouhi** 2022-08-01 21:35 UTC
Labels: bug
