### ISSUE TITLE
Images don't show in expanded notifications 2024.3.4-full

### ISSUE THREAD

**Issue by adamburgoyne** [home-assistant/android#4305] opened 2024-03-28 10:08 UTC
**Home Assistant Android app version(s):** 2024.3.4-full

**Android version(s):** 14

**Device model(s):** Samsung S22+

**Home Assistant version:** 2024.3.3

**Last working Home Assistant release (if known):** App version 2024.1.5.-full

**Description of problem, include YAML if issue is related to notifications:**

I use a HA blueprint to send notifications from HomeAssistant when Frigate detects someone at the doorbell. That has been working well for the past year or so now, the notification includes a thumbnail image from the doorbell camera. I've always been able to pull down on that notification in order to expand the image to get a much better view of who was at the door (standard android behaviour of expanding a notification), for some reason in the latest beta version of the app this no longer works. Expanding the notification shows the shortcuts but no image, compressing it then displays the small thumbnail again.

My partner is using the Latest version (2024.1.5-full) which doesn't display this problem, expanding the notification continues to show the full image which makes me believe it's not my HA instance or automation/blueprint causing the problem. I've been on the Beta quite some time now and use this functionality nearly daily so I'm guessing one of the very recent beta versions has caused this. Looks like someone else on the HA forums has reported the same problem using a Pixel 7 Pro too so I think the device can be ruled out.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

![Screenshot_20240328_100833_One UI Home](https://github.com/home-assistant/android/assets/1240218/205c64ce-0b04-4807-a1b3-c5d069ce5e01)
![Screenshot_20240328_100843_One UI Home](https://github.com/home-assistant/android/assets/1240218/6ee93b99-41d9-41d1-bef5-ba109a369044)

**Additional information:**

**Comment by jpelgrom** [comment] 2024-03-28 10:50
Duplicate of #4300 - this has been fixed and will be included in the next (beta) release

**Closed by jpelgrom** 2024-03-28 10:50 UTC
Labels: bug

**Comment by adamburgoyne** [comment] 2024-03-28 10:51
Ah I did attempt to search first but evidently not well enough.... thanks!
