### ISSUE TITLE
Widget icons are random Unicode characters

### ISSUE THREAD

**Issue by KaelWD** [home-assistant/android#4458] opened 2024-06-13 03:26 UTC
**Home Assistant Android app version(s):** 2024.6.1-full

**Android version(s):** 13 TKQ1.221114.001

**Device model(s):** xiaomi redmi note 11

**Home Assistant version:** 2024.5.4

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

The widget icon selector shows Unicode characters instead of mdi icons.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

![Screenshot_2024-06-13-13-21-11-555_io homeassistant companion android](https://github.com/home-assistant/android/assets/16421948/2d2b4588-91dc-49b0-9d5b-0791df1d6d99)

![Screenshot_2024-06-13-13-21-22-370_io homeassistant companion android](https://github.com/home-assistant/android/assets/16421948/362a2547-cfc4-4a43-841f-797dcaaa08bb)

![Screenshot_2024-06-13-13-22-11-645_com miui home-edit](https://github.com/home-assistant/android/assets/16421948/e30867cf-9dd9-4bdb-b84e-dc9648c8427c)

**Additional information:**

**Comment by dshokouhi** [comment] 2024-06-13 14:35
are you running a custom ROM by chance? was this working for you before? I cannot reproduce. Are there any errors in the logs when you open the icon selector?

![image](https://github.com/home-assistant/android/assets/1634145/0d51da13-fa9f-4a73-92a1-1bfc1d2716a0)

![image](https://github.com/home-assistant/android/assets/1634145/69376a9a-c97e-4b41-a43d-930c5b1ba92e)

**Comment by KaelWD** [comment] 2024-06-13 16:36
Worked out it was caused by having a custom font set, anything but the MIUI default breaks this and spotify.

Everything else in the app looked normal, except for some icons in the setup pages:
![Screenshot_2024-06-14-02-05-31-213_io homeassistant companion android-edit](https://github.com/home-assistant/android/assets/16421948/09adf101-7133-4076-aae2-d6cf1d117e15)

**Comment by dshokouhi** [comment] 2024-06-13 16:38
ok not sure this is something we can fix, were there any companion app errors when the issue occurs? not sure this is something we can fix

**Comment by KaelWD** [comment] 2024-06-13 16:44
The only error-looking thing in the logs was
```
W ziparchive: Unable to open '/data/app/~~PjucflwAprnfYF1O6eZoFw==/com.google.android.trichromelibrary_642216533-NFl4nfuAB6l5QKNgPsF-Fg==/base.dm': No such file or directory
W mpanion.android: Entry not found
D nativeloader: Configuring clns-5 for other apk /data/app/~~PjucflwAprnfYF1O6eZoFw==/com.google.android.trichromelibrary_642216533-NFl4nfuAB6l5QKNgPsF-Fg==/base.apk. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~kuppaOYMhkYtPcimePoQ7Q==/com.google.android.webview-AFHxqkO0vKaA4C_xtTdTxQ==/lib/arm64:/data/app/~~kuppaOYMhkYtPcimePoQ7Q==/com.google.android.webview-AFHxqkO0vKaA4C_xtTdTxQ==/base.apk!/lib/arm64-v8a:/data/app/~~PjucflwAprnfYF1O6eZoFw==/com.google.android.trichromelibrary_642216533-NFl4nfuAB6l5QKNgPsF-Fg==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand
D nativeloader: Extending system_exposed_libraries: libbinauralrenderer_wrapper.qti.so:libhoaeffects.qti.so:libQOC.qti.so:libmisys_jni.xiaomi.so:libxiaomi_modemdumpsdx55_jni.modem.so:libxiaomi_modemdump_jni.modem.so:libupdateprof.qti.so:libthermalclient.qti.so:libQOC.qti.so:libdiag_system.qti.so:libqape.qti.so:liblistenjni.qti.so
I mpanion.android: Failed to add image file: Dex cache count and dex file count mismatch while trying to initialize from image
D nativeloader: Configuring clns-6 for other apk /data/app/~~kuppaOYMhkYtPcimePoQ7Q==/com.google.android.webview-AFHxqkO0vKaA4C_xtTdTxQ==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~kuppaOYMhkYtPcimePoQ7Q==/com.google.android.webview-AFHxqkO0vKaA4C_xtTdTxQ==/lib/arm64:/data/app/~~kuppaOYMhkYtPcimePoQ7Q==/com.google.android.webview-AFHxqkO0vKaA4C_xtTdTxQ==/base.apk!/lib/arm64-v8a:/data/app/~~PjucflwAprnfYF1O6eZoFw==/com.google.android.trichromelibrary_642216533-NFl4nfuAB6l5QKNgPsF-Fg==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand
```

**Comment by dshokouhi** [comment] 2024-06-13 16:47
yea dont think we can fix that, strange that a custom font causes those issues

**Comment by dshokouhi** [comment] 2024-06-13 16:55
Closing as this is not something we can fix, especially if other apps are getting impacted by it. Most likely an OS issue.

**Closed by dshokouhi** 2024-06-13 16:55 UTC
Labels: bug, question, widget
