### ISSUE TITLE
Battery drainage when HA server not available

### ISSUE THREAD

**Issue by iulko** [home-assistant/android#4445] opened 2024-06-09 14:20 UTC
I have a companion app installed and pointed to a server.
I activated the constant connection option.
When im in some networks, my HA server is not reachable.
My problems is, when I look into my firewall on the phone I see that HA companion app is opening connections, trying to connect to the server but is never closing them if it cant connect properly.

Companion app -> Unreachable server (connection active)
Companion app -> Unreachable server (connection active)
Companion app -> Unreachable server (connection active)
Companion app -> Unreachable server (connection active)

I have 20 of them after running the app for some minutes, I think sometimes they get stuck and there is some error that makes alot more of them and than battery is running out fast.

I saw also couple of connections to firebase at the same time, but maybe thats normal.

Couldn't there be some timeout for the connection if it fails?

**Comment by dshokouhi** [comment] 2024-06-09 14:56
Duplicate of #2933

**Closed** 2024-06-09 14:56 UTC
Labels: bug
