### ISSUE TITLE
Slow gui loading in app

### ISSUE THREAD

**Issue by skynet-network** [home-assistant/android#4413] opened 2024-05-18 16:19 UTC
[error_log-4.txt](https://github.com/home-assistant/android/files/15366066/error_log-4.txt)
![Screenshot_20240518_181508_Home Assistant](https://github.com/home-assistant/android/assets/81412812/8f26330c-99f7-4f5e-b9b1-6f13103c5071)

**Home Assistant Android app version(s):**

**Android version(s):14

**Device model(s):samsung s23 

**Home Assistant version:2024.5.2

**Last working Home Assistant release (if known):2024.3.4

**Description of problem, include YAML if issue is related to notifications:gui load slow in app need to force close app and clear cache 

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2024-05-18 16:20
duplicate of https://github.com/home-assistant/android/issues/3396

**Closed by dshokouhi** 2024-05-18 16:20 UTC
Labels: bug
