### ISSUE TITLE
Stopped working on Android 7.1.1 since last update

### ISSUE THREAD

**Issue by AtmanActive** [home-assistant/android#4336] opened 2024-04-08 12:38 UTC
**Home Assistant Android app version(s):**

**Android version(s):**

7.1.1

**Device model(s):**

Lenovo TB-X704L

**Home Assistant version:**

2024.3.5-full

**Last working Home Assistant release (if known):**

previous

**Description of problem, include YAML if issue is related to notifications:**

Crashes on run

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

![20240408_133632](https://github.com/home-assistant/android/assets/7526717/09afd85c-2685-40c6-a485-1195b7ea5e4f)

**Additional information:**

Works fine on another device that runs on Android 14.

**Comment by jpelgrom** [comment] 2024-04-08 13:14
Duplicate of #4323 - this is fixed in the next release and will be available soon

**Closed by jpelgrom** 2024-04-08 13:14 UTC
Labels: bug
