### ISSUE TITLE
External authorization process loops (CloudFlare ZeroTrust)

### ISSUE THREAD

**Issue by ltupaj** [home-assistant/android#3205] opened 2023-01-08 18:09 UTC
**Is your feature request related to a problem? Please describe.**

My home assistant is protected by CloudFlare ZeroTrust solution. CF requires authentication before it exposes HA API. Simply when we try to access https://myHAlocation.domain.com, CF first displays own authentication page and then redirects to HA. 
The funny thing is that initial authentication in HA companion android app works perfectly. When url is provided, it displays CF page and then standard HA logon. However problem occurs when CF token expires after a month. Then CF wants to again reauthorize user and this process cannot be accomplished in HA companion app. From my observation it looks like that:
1. HA app tries to get data from HA
2. instead HA response CF authorization page is served
3. HA companion app opens >!external!< web browser and authorization process is continued in that external browser
4. Even if correct authorization data is provided in pages displayed in exterl browser page, authorization process never returns back to   HA companion
5. Restart of HA companion gets back to point 1 and we have authorization loop 

**Describe the solution you'd like**

I just need whole process to be performed in HA app instead external browser. I have analysed this issue in the code and found that in class:
io.homeassistant.companion.android.webview.WebViewActivity
TLSWebViewClient as webViewClient. In initialization there are several methods overridden and one of them is "shouldOverrideUrlLoading". In code of this method I found following condition:
`                            } else if (!webView.url.toString().contains(it.toString())) {
                                Log.d(TAG, "Launching browser")
                                val browserIntent = Intent(Intent.ACTION_VIEW, it)
                                startActivity(browserIntent)
                                return true;
                            }`
which is root cause of the problem. When I replaced it by simple "return false", authentication process can be completed in HA app.

**Describe alternatives you've considered, if any**

I really tried to find workarround which does not require code changes but i havent found any.

**Additional context**

**Comment by jpelgrom** [comment] 2023-01-08 18:27
Duplicate of #2650 (and many others)

There are multiple reasons as to why simply doing everything inside the app's webview is undesirable, and it also won't work with many external identity providers for security reasons. The app currently only supports HA's default authentication system. Please see the linked issue(s) for more information.

**Closed by jpelgrom** 2023-01-08 18:27 UTC
Labels: enhancement

**Comment by spacebares** [comment] 2023-01-31 22:47
> Duplicate of #2650 (and many others)
> 
> There are multiple reasons as to why simply doing everything inside the app's webview is undesirable, and it also won't work with many external identity providers for security reasons. The app currently only supports HA's default authentication system. Please see the linked issue(s) for more information.

HA Does support cloudflare Zero trust auth... just during initial install of the app and not after token expires. Its a bug in HA.
