### ISSUE TITLE
Feature request: Make pictures zoomable

### ISSUE THREAD

**Issue by sotima** [home-assistant/android#1256] opened 2020-12-26 10:38 UTC
I love the companion app! Great work! One thing I am missing though is the possibility to enlarge my camera pictures as I can do when using HA via Chrome. It would be great if you could make the picture of a camera stream "zoomable" as it is in Chorme browser. So if you tap on a camera picture (Thumbnail) and the stream is shown, you can enlarge it by using the two finger gesture. Or at least allow the use of landscape by turning the phone.

Thank you very much for your great work! 

Matthias

**Comment by dshokouhi** [comment] 2020-12-26 17:32
when you say chrome browser are you referring to desktop or mobile?  Also there is nothing in the app preventing switching to landscape mode, that might be your device preventing it.

**Comment by dshokouhi** [comment] 2020-12-26 17:32
Also please do not delete the feature request template, it is there for a reason.

**Comment by T-bond** [comment] 2020-12-27 17:26
I think he wants the same thing as me: #1117

**Comment by sotima** [comment] 2020-12-28 16:52
Hi, I am referring to the mobile chrome. I was using HA in the mobile chrome browser prior to switching to the companion app. There I was able to zoom into the streaming-view. And sorry for deleting the template! And yes could be the same as T-bond requested. Sorry, did not find it, although I have searched if there was already such a request.

**Comment by dshokouhi** [comment] 2020-12-28 16:58
Closing as duplicate of #1117

**Closed by dshokouhi** 2020-12-28 16:58 UTC
Labels: enhancement
