### ISSUE TITLE
pause location detection while staying in known WLANs

### ISSUE THREAD

**Issue by jubie25** [home-assistant/android#4013] opened 2023-11-13 10:58 UTC
**Is your feature request related to a problem? Please describe.**

Detemining location by the App for controling and automation purposes is a rich and wanted feature. But it consumes extremely much power: my smartphone's run time is reduced to half the time until charging is needed.  
On the other hand private WLANs are usually limited to small areas where more granular location is not needed.

**Describe the solution you'd like**

An option where GPS/other power consuming location services are disabled automatically while staying in selectables WLANs. The latest location information is freezed or can be preselected for being reported to home assistant.

**Describe alternatives you've considered, if any**

**Additional context**

I personally think it's no loss of comfort or functionality if location service is not asked during stay in certain WLANs. Because this is the fact in most of the time power consumption should reduce a lot.

**Comment by dshokouhi** [comment] 2023-11-13 15:45
duplicate of https://github.com/home-assistant/android/issues/620

**Closed by dshokouhi** 2023-11-13 15:45 UTC
Labels: enhancement
