### ISSUE TITLE
App drains battery when using Android (WireGuard) VPN and airplane mode is enabled

### ISSUE THREAD

**Issue by daviessm** [home-assistant/android#3636] opened 2023-07-05 03:48 UTC
**Home Assistant Android app version(s):**
Home Assistant 2023.6.0-full
**Android version(s):**
13
**Device model(s):**
Google Pixel 6 Pro
**Home Assistant version:**
Home Assistant 2023.6.2
Frontend 20230608.0 - latest
**Last working Home Assistant release (if known):**
Unknown
**Description of problem, include YAML if issue is related to notifications:**
If my WireGuard VPN is connected and I enable airplane mode in Android, HomeAssistant drains the device battery. If the VPN is not connected and the device is in airplane mode the battery usage is minimal (correct).

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by daviessm** [comment] 2023-07-05 04:44
I'm not an Android developer but a search suggests [this check](https://github.com/home-assistant/android/blob/be022a5272c8198750686308b4935da6a894d7bd/app/src/main/java/io/homeassistant/companion/android/websocket/WebsocketManager.kt#L142) might be causing the issue - the VPN network connection reports as connected even if all other connections are not.

**Comment by dshokouhi** [comment] 2023-07-05 15:26
duplicate of #3464 



> I'm not an Android developer but a search suggests [this check](https://github.com/home-assistant/android/blob/be022a5272c8198750686308b4935da6a894d7bd/app/src/main/java/io/homeassistant/companion/android/websocket/WebsocketManager.kt#L142) might be causing the issue - the VPN network connection reports as connected even if all other connections are not.

This check is required because Persistent Notification can happen when there is no data connection but network is still connected so we need to check that.

**Closed by dshokouhi** 2023-07-05 15:26 UTC
Labels: bug

**Comment by daviessm** [comment] 2023-07-05 23:34
Ok, that might not be the cause but the problem still exists.
