### ISSUE TITLE
Unable to connect Home Assistant App

### ISSUE THREAD

**Issue by TEWhites** [home-assistant/android#3395] opened 2023-03-03 23:38 UTC
**Home Assistant Android app version(s):**

**Android version(s):**9 Knox 3.2.1 Knox API level 27 

**Device model(s):**Model SM-G965Y

**Home Assistant version:**  Home Assistant 2023.3.1 Supervisor 2023.01.1 Operating System 9.5 Frontend 20230302.0 - latest 

**Last working Home Assistant release (if known):** Don't remember last time it worked, within the last month and last update

**Description of problem, include YAML if issue is related to notifications:**
App was working, now its not.  
1) I have uninstalled and reinstalled the app.
2) I have rebooted the phone
3) I have rebooted the router
4) I installed a fresh raspberry PI 4 with the original downloaded configuration. No special cards or configuration.
And still the app will not connect.
Error Unable to connect to Home Assistant
Server or proxy hostname lookup failed, please check that the URL is a valid Home Assistant URL

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2023-03-03 23:40
Based on the error message have you tried the URL in a browser to see if it will work? Try to disable your proxy as well. This error is not one the app can solve.

**Comment by TEWhites** [comment] 2023-03-03 23:41
Yes, it is accessible with the browser

**Comment by dshokouhi** [comment] 2023-03-03 23:43
Please test by disabling the proxy and/or using the IP address directly. The app is receiving a specific type of connection error which can only be fixed by the user.

**Comment by TEWhites** [comment] 2023-03-03 23:51
Yes, it is accessible with the browser
Just disabled my proxy server.  Did not help.

Does this mean, there is no fix.
Any idea why it quit working

**Comment by dshokouhi** [comment] 2023-03-03 23:56
So you checked using a browser on the same device right? Like Chrome for android? You also tried the IP address too making sure to enter the proper protocol keeping in mind `https` will not work with local IP?

This is the exact error we are receiving: 
https://developer.android.com/reference/android/webkit/WebViewClient#ERROR_HOST_LOOKUP

you can also try the start fresh steps which are different from uninstall and reinstall
https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

Also more on companion app networking (in case you have not seen it)
https://companion.home-assistant.io/docs/troubleshooting/networking

**Comment by TEWhites** [comment] 2023-03-04 00:04
Ok, I will keep trying. If I find something I will get back with you.
Thanks for your help

**Comment by TEWhites** [comment] 2023-03-04 00:06
One more question, is the problem in the phone or my computer.

**Comment by dshokouhi** [comment] 2023-03-04 00:09
Judging by the error either server or network related since the device cannot look up the hostname used, that was why I asked to try the IP too. Testing on Chrome for Android on the same device will probably have the same error as Android System WebView is based on Chromium so the functionality should be the same except the app also uses HA APIs for additional communication.

**Comment by TEWhites** [comment] 2023-03-04 14:06
Good morning,
Here is what I have found so far.   I can connect to HA via IP address from my phone.  I'm not real knowledgeable about networking, but it appears to me to be a DCHP problem.

I went to my router and looked at the logs there.  Here are the error messages that I get when I try to connect with my phone.  I hope this is of value to you.

Tom

<html><body>


IGD[13223]: igd.info IGD_pii_get_portmapping_entry_specific: Remote Host: , External Port: 49592, PortMapping Protocol: TCP | 2023/3/4 09:00:27 | Notice
-- | -- | --
IGD[13223]: igd.info IGD_pii_get_portmapping_entry_specific: Lock released | 2023/3/4 09:00:27 | Notice
IGD[13223]: igd.info IGD_pii_get_portmapping_entry_specific: Lock acquired | 2023/3/4 09:00:27 | Notice
IGD[13223]: igd.info EXIT IGD_get_SpecificPortMapping_entry... | 2023/3/4 09:00:27 | Notice
IGD[13223]: igd.info ENTER IGD_get_SpecificPortMapping_entry... | 2023/3/4 09:00:27 | Notice
IGD[13223]: config.utapi s_find_portmapdyn: found dynamic port map: entry 1 (:49592<->10.0.0.6:4430) | 2023/3/4 09:00:27 | Notice
IGD[13223]: igd.info _get_external_ip_address: state variables ExternalIPAddress: 68.84.249.74 | 2023/3/4 09:00:23 | Notice


</body>
</html>

**Comment by TEWhites** [comment] 2023-03-04 14:23
If I turn UPnP off those messages don't appear but still cannot connect using http:\\homeassistant.local:8123

If this information is of no value and you wish me to stop, just tell me so
Tom

**Comment by dshokouhi** [comment] 2023-03-04 15:17
If you can't connect using that host name then you need to use the IP address. At this point we will not be able to assist as the issue is not with the app.

**Closed by dshokouhi** 2023-03-04 15:17 UTC
Labels: bug, question
