### ISSUE TITLE
Mobile App issue with multiple YAML dashboards

### ISSUE THREAD

**Issue by Masterz69** [home-assistant/android#1385] opened 2021-02-28 19:41 UTC
**Home Assistant Android version:**
2021.2.2-full
**Android version:**
9
**Phone model:**
Samsung S8
**Home Assistant version:**
core-2021.2.3

**Last working Home Assistant release (if known):**

**Description of problem:**
Added second YAML dashboard. Looks fine in Browser.
On next Mobile App run - just white screen appears and nothing more.
Reinstalled application - not starting, crash on start.
Rebooted phone - working again.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2021-02-28 21:12
So you see it crash but no crash logs as the template requested? We need the crash logs to actually the fix the issue. Also complete steps to reproduce the issue. This is not enough to go by.

**Comment by Masterz69** [comment] 2021-03-07 21:05
Steps to reproduce.

1. Create Lovelace YAML dashboard;
2. Assign it as default in Android Mobile App;
3. Change dashboard URL (not Title);
4. Start Mobile App -> White screen, no UI access.
5. Cure: Android Settings -> Apps -> Clear Data for App.

**Comment by dshokouhi** [comment] 2021-03-07 21:07
@Masterz69 do you see the same issue in chrome for android?

**Comment by Masterz69** [comment] 2021-03-08 21:31
> @Masterz69 do you see the same issue in chrome for android?

Yes, just tried on Chrome - same behaviour: 
* white screen after default (configured on client in Chrome) dashboard URL changed on HA server.

In Chrome (comparing to App), I can easily enter another dashboard URL, and voila - I'm in. 
Application just goes anyway to white screen.

**Comment by dshokouhi** [comment] 2021-03-09 17:54
Thanks for reporting back @Masterz69 since you had seen this in chrome as well that means it was ultimately a frontend issue.  I had reached out to them and they had provided a fix that will be in the next HA release.  Might not be the next point release.  As the app does not allow a way to remove the cookies we will be dependent on this change.

https://github.com/home-assistant/frontend/pull/8593

**Closed by dshokouhi** 2021-03-09 17:54 UTC
Labels: bug
