### ISSUE TITLE
Unable to connect with app local or distant

### ISSUE THREAD

**Issue by micclfr** [home-assistant/android#4597] opened 2024-08-28 11:51 UTC
**Home Assistant Android app version(s):**

**Android version(s):**
Last
**Device model(s):**
S22
**Home Assistant version:**
Last
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
Unable to connect, local or distant. If i delete the server and recreate in app, works for ten minutes
<!--
- For Wear OS devices we will need the LogCat logs from the device.
- For Android Auto the logs can be retrieved from the connected device.
- Logs from the device can be taken from Settings > Companion App Troubleshooting > Show and Share Logs

**Companion App Logs:**

...
[homeassistant_companion_log_7-28-2024_11-2-57.txt](https://github.com/user-attachments/files/16782839/homeassistant_companion_log_7-28-2024_11-2-57.txt)

```

**Screenshot or video of problem:**
![image](https://github.com/user-attachments/assets/c47612d3-4a1e-4f0c-8c85-4c5407752fa5)

**Additional information:**

**Comment by dshokouhi** [comment] 2024-08-28 13:16
Please get the device logs when the issue occurs otherwise we can't help here.

**Comment by micclfr** [comment] 2024-08-28 14:46
It seems there is noting in the log when this happens.
Date de début
28 août 2024 à 15:00
Date de fin
28 août 2024 à 18:00
Entité
Solarman status_lastUpdate a changé en 08/28/2024, 16:41:42
16:41:43 - Il y a 3 minutes
Solarman status_lastUpdate a changé en 08/28/2024, 16:41:12
16:41:12 - Il y a 3 minutes
Date & Time (UTC) a changé en 2024-08-28, 14:41
16:41:00 - Il y a 4 minutes
Time (UTC) a changé en 14:41
16:41:00 - Il y a 4 minutes
Time a changé en 16:41
16:41:00 - Il y a 4 minutes
Time & Date a changé en 16:41, 2024-08-28
16:41:00 - Il y a 4 minutes
Date & Time a changé en 2024-08-28, 16:41
16:41:00 - Il y a 4 minutes
Date & Time (ISO) a changé en 2024-08-28T16:41:00
16:41:00 - Il y a 4 minutes
Solarman status_lastUpdate a changé en 08/28/2024, 16:40:42
16:40:42 - Il y a 4 minutes
Solarman status_lastUpdate a changé en 08/28/2024, 16:40:12
16:40:13 - Il y a 5 minutes
Time a changé en 16:40
16:40:00 - Il y a 5 minutes
Time & Date a changé en 16:40, 2024-08-28
16:40:00 - Il y a 5 minutes
Date & Time (UTC) a changé en 2024-08-28, 14:40
16:40:00 - Il y a 5 minutes
Time (UTC) a changé en 14:40
16:40:00 - Il y a 5 minutes
Date & Time a changé en 2024-08-28, 16:40
16:40:00 - Il y a 5 minutes
Date & Time (ISO) a changé en 2024-08-28T16:40:00
16:40:00 - Il y a 5 minutes
Solarman status_lastUpdate a changé en 08/28/2024, 16:39:54
16:39:54 - Il y a 5 minutes
Solarman

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dshokouhi** [comment] 2024-08-28 14:50
those are not the logs, the logs were mentioned as part of the issue template that you had skipped over and deleted for some reason.

Settings > companion app > troubleshooting > show and share logs

first reproduce the issue, then grab the logs so we can see what the issue is.

please make sure to fill out hte issue template completely I can still see data missing. We need actual version numbers too, latest does not help us here.

**Comment by micclfr** [comment] 2024-08-28 16:19
[Image]


Here you are. I have to be home to grab the logs after reconfiguring Companion App.


Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dshokouhi** [comment] 2024-08-28 16:29
those logs dont contain any error, youll need to reproduce the error then grab teh logs for them to contain the actual error message so we can see what needs to be done.

also if you tried attaching a screenshot it is not visible in your comment

**Comment by micclfr** [comment] 2024-08-28 16:59
I did that, reproduce the problem, grabed the logs and this is it.
As for the versions :
Core

2024.8.3

Supervisor

2024.08.0

Operating System

13.1

Interface utilisateur

20240809.0

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dshokouhi** [comment] 2024-08-29 16:49
yea those logs still dont contain the actual error when the unable to connect pop-up occurs. your logs seem to indicate that the device was registering but dont show the actual cause of the pop-up. Can you wait for the error to pop-up again and then grab those logs for us? That would be most helpful to determine what happened.

**Comment by xrxca** [comment] 2024-09-01 19:27
Glad I'm not alone on this one, new tablet will not connect locally or remote, direct address, through nabucasa or via apache proxy.  All of which work just fine using web interface on the tablet, and on phone via app.  I have no WebView option other than 111.0.5563.116.  nothing in the logs, but I have logging at a very limited level, will try to enable more logs when I'm back from the weekend.   Ha core version 2024.8.3, and I've tried app versions from 2024.7.3 on both full and minimal.   It is VERY frustrating that there is no way to get to app settings before connection when you can't connect.  I don't know that there is anything in the settings that would help, but it would be nice to be able to check, or manually set things.

**Comment by ViperRNMC** [comment] 2024-09-07 21:07
I have same problem with cor 2024.9 and andriod companion 2024.7 on a Nspanel, reverse back to core 2024.8 solved problem. On other devices with iOS companion no problem both core versions.

**Comment by dshokouhi** [comment] 2024-09-07 21:12
We are still waiting on companion app logs of the issue in order to help out. However if the issue is related to a core update then this may not be an issue for the companion app. The device logs will help here.

**Comment by ViperRNMC** [comment] 2024-09-07 21:33
Can’t get any log, the app hangs and reboot every x sec

**Comment by dshokouhi** [comment] 2024-09-07 21:53
> Can’t get any log from the android companion, the app hangs and reboot every x sec

that sounds a lot like this issue: https://github.com/home-assistant/frontend/issues/21900 is that what you everyone is  experiencing?

**Comment by oldwomanjosiah** [comment] 2024-09-08 16:52
I'm experiencing the same issue, so I can provide an app log.

[homeassistant_companion_log_8-8-2024_11-48-56.txt](https://github.com/user-attachments/files/16923001/homeassistant_companion_log_8-8-2024_11-48-56.txt)

**Comment by dshokouhi** [comment] 2024-09-08 17:05
hmm strange apparnetly its getting an error from teh server and we are not get authentication?

```
09-08 11:41:31.530 20015 20015 E WebViewPresenterImpl: Unable to retrieve external auth
```

also looks like you may have a server unreachable?

```
09-08 11:41:33.096 20015 21559 W SensorReceiver: Exception while updating sensors: IntegrationException: java.net.UnknownHostException
```

**Comment by oldwomanjosiah** [comment] 2024-09-08 17:41
yeah it's rather odd

**Comment by xrxca** [comment] 2024-09-09 06:28
this is a new tablet hence a new install of the companion app, since I cannot log in I can't get to the menu to share logs (or is there a way I'm missing).   Since my system is coming up 5 years old I wondered if an unused or dead integration could be at fault so have spent my spare time on server cleanup instead of the tablet issue, my ha instance restart times have improved as has interface responsiveness on connected devices, but still unable to connect using app on new tablet.

**Comment by dshokouhi** [comment] 2024-09-09 21:02
> this is a new tablet hence a new install of the companion app, since I cannot log in I can't get to the menu to share logs (or is there a way I'm missing).

in your case please share a screenshot of the error message, its honesty probably unrelated to this issue as these users are able to login whereas you are not.

**Comment by ViperRNMC** [comment] 2024-09-10 09:55
i solved it to update the web view version on my nspanel pro

https://github.com/home-assistant/frontend/issues/21900#issuecomment-2336824836

**Comment by dshokouhi** [comment] 2024-10-07 22:43
There seems to be multiple different issues combined into this one. Some seem to be solved outside the companion app and others seem to be related to networking setup. I am going to close this issue for now. If you still experience an issue please create a new one and provide screenshots of the error and companion app logs.

**Closed by dshokouhi** 2024-10-07 22:43 UTC
Labels: bug, question
