### ISSUE TITLE
Slow requests to server (mobile app is slow in general)

### ISSUE THREAD

**Issue by ahlstromanton** [home-assistant/android#4001] opened 2023-11-06 10:57 UTC
**Home Assistant Android app version(s):**
2023.10.2-full

**Android version(s):**
14

**Device model(s):**
Google Pixel 7 Pro

**Home Assistant version:**
Core
2023.11.1
Supervisor
2023.10.1
Operating System
11.1
Frontend
20231030.1

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
All requests to the server seems slow. When opening the app, the HA logo shows for a while, then for 1-2 seconds I get the "could not connect" prompt which then disappears, then my dashboards loads very slowly (about 5 sec on a quick connection).

Everything in the app is slow; opening different pages, opening logs, navigating the menues etc.

In the mobile browser (and on other devices), everything is fast as per usual, ergo, problem seems to be related to the companion app itself.

Unfortunately nothing related to the issues in the logs; there are no timeouts etc, just very slow loading. 

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by jpelgrom** [comment] 2023-11-06 11:31
Duplicate of #3396

**Comment by jpelgrom** [comment] 2023-11-06 14:52
Reopened by request

There's nothing about notifications in this description though, please add more information like an example of the notification data used.

**Comment by Mincka** [comment] 2023-11-06 15:03
This is exactly the same issue as #3396 which describes both slow startup and navigation:
>  slow to startup (5-10 seconds to start) and slow when navigating in the app

**Comment by dshokouhi** [comment] 2023-12-13 17:25
Closing due to lack of response from author, we need more information to go by

**Closed by dshokouhi** 2023-12-13 17:25 UTC
Labels: bug, question
