### ISSUE TITLE
Massive battery consumption regardless of settings

### ISSUE THREAD

**Issue by hofst** [home-assistant/android#2668] opened 2022-07-10 21:06 UTC
**Home Assistant Android version:**
2022.6.0-full

**Android version:**
12

**Phone model:**
Pixel 6

**Home Assistant version:**
2022.5.5

**Last working Home Assistant release (if known):**
unknown

**Description of problem:**
The Homeassistant app has massive battery consumption (see screenshot). This is despite having the following settings configured:
- sensor refresh interval is 15minutes
- always use google notifications / never direct web socket
- android battery setting for HomeAssistant is "restricted", i.e. it should not even be possible to run in the background. I have no explanation how the app circumvents that. Maybe because I have some sensor widgets on my home screen? Even if the display is turned off, Homeassistant will always have a foreground activity.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![Screenshot_20220710-214525~2](https://user-images.githubusercontent.com/2535762/178162024-4a70153c-ac4c-4ae8-b1ea-7dd87f2efa58.png)

**Additional information:**

**Comment by dshokouhi** [comment] 2022-07-10 21:18
Double check these points: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-app-battery-drain

You can also start fresh if that doesnt work: https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by hofst** [comment] 2022-07-11 15:40
Thank you for the quick feedback. Unfortunately, the battery problems persist.
I now have additionally disabled almost all sensors and updated and restarted my phone, without any effect.

I'm hesitant to reset the app because I would lose my widgets which were quite some work to create...

**Comment by dshokouhi** [comment] 2022-07-11 17:39
To start with what sensors do you have enabled now? 

Other than that the reason why we ask to start with fresh and clean data is because in the event of bad data we need to rule that out. There have been lots of cases where bad data led to unexpected results so we do ask to start fresh as part of troubleshooting.

Without being able to reproduce the issue or having precise steps to reproduce we can only troubleshoot and see what is causing the issue.

**Comment by hofst** [comment] 2022-07-11 20:55
I have basically only enabled the "battery percentage" sensor for testing right now.
I will upgrade HomeAssistant core from 2022.5.5 to 2022.6 tomorrow and disable all sensors in the app tomorrow for further testing.

> Other than that the reason why we ask to start with fresh and clean data is because in the event of bad data we need to rule that out. 

I understand that and usually that is a good workaround. However, data usually doesn't get bad on its own, so there is likely a bug involved that created the bad data. In any case, I will do the two things I mentioned above and if that doesn't help, I will reset the app and report back here.

**Comment by hofst** [comment] 2022-07-12 18:09
I think I made some progress for the first time. After disabling all sensors, I managed to evict HA from the battery consumption summary for the first time ever. Then I only re-enabled the "battery percentage" and the consumption still seems to be negligible. I will further experiment with other sensors.
However, I also tried to experiment with the "sensor refresh rate". I set it from 15 minutes to 1 minute for testing, but it doesn't seem to have any effect (so far). When will a change of that setting apply? Only after a restart? Or only after the next 15minute trigger?

**Comment by dshokouhi** [comment] 2022-07-12 18:12
> I set it from 15 minutes to 1 minute for testing, but it doesn't seem to have any effect (so far). When will a change of that setting apply? Only after a restart?

Only after a app restart, we also mention this in the description on the update frequency page.

**Comment by hofst** [comment] 2022-07-12 18:26
> Only after a app restart, we also mention this in the description on the update frequency page.

Thanks, Indeed! Since it is the last sentence in a longer paragraph of explanations, this is rather easy to miss.
Maybe as a small improvement there: I believe other apps will display an overlay once you change such a setting that says "Restart the app to apply new settings. Do you want to restart now? Yes/no". But that's only a minor improvement and this issue is about something different after all.
I will give another update once I found out what actually caused the battery consumption (if I'm able to repro it again)

**Comment by dshokouhi** [comment] 2022-07-13 02:39
> Maybe as a small improvement there: I believe other apps will display an overlay once you change such a setting that says "Restart the app to apply new settings. Do you want to restart now? Yes/no". But that's only a minor improvement and this issue is about something different after all.

Yea I agree it can be improved, the only other place this is required is when we are adding intents to listen for via Last Update Trigger Sensor. Feel free to submit a feature request for this so it doesn't get lost in this issue :)

**Comment by dshokouhi** [comment] 2022-07-22 15:34
Its been 10 days, I assume if you still had excessive battery drain we would've heard from you by now that the start fresh steps did not help. Going to close this issue now.

**Closed by dshokouhi** 2022-07-22 15:34 UTC
Labels: bug, question

**Comment by hofst** [comment] 2022-07-22 18:40
Hi,
I did make some more progress:
- I updated the HA server to 2022.7 and disabled all sensors.
Result: The HA app has no battery consumption.
- I enabled the battery sensor
Result: The HA app has no battery consumption (nice!)
- I enabled the background location sensor (every 15 minutes and not with high resolution):
Result: The HA app has significant battery consumption and shows as having foreground activity 100% of the time. Not sure if that is expected? I would expect that a background location update with low resolution (no gps) every 15 minutes would not cause significant battery consumption or foreground activity all the time. This is on Android 12 and a Pixel 6. My wife has the same config on a Huawei Mate 20 Pro but there is not much battery consumption there. I wonder if either Huawei has implemented a better battery manager or if this is a problem with Android 12.

**Comment by dshokouhi** [comment] 2022-07-22 18:43
> * I enabled the background location sensor (every 15 minutes and not with high resolution):
>   Result: The HA app has significant battery consumption and shows as having foreground activity 100% of the time. Not sure if that is expected? I would expect that a background location update with low resolution (no gps) every 15 minutes would not cause significant battery consumption or foreground activity all the time. This is on Android 12 and a Pixel 6. My wife has the same config on a Huawei Mate 20 Pro but there is not much battery consumption there. I wonder if either Huawei has implemented a better battery manager or if this is a problem with Android 12.

I think you need to give this page a read: https://companion.home-assistant.io/docs/core/location#android-location-sensors

It is not every 15 minutes but every minute.
