### ISSUE TITLE
App gets itself banned when it didn't like the ocsp response

### ISSUE THREAD

**Issue by fallingcats** [home-assistant/android#3275] opened 2023-01-27 01:57 UTC
**Home Assistant Android version:**
2022.12.0-full

**Android version:**
11

**Phone model:**
OnePlus 7, 6T

**Home Assistant version:**
2023.1.7

**Last working Home Assistant release (if known):**
Probably never, at least 2y

**Description of problem:**
When the companion app receives an https response that "must staple" and doesn't like it's ocsp info (neither firefox, chrome nor ssllabs.com complain) it will send invalid login attempts to the websocket endpoint.

*App to /api/websocket*
```json
{"type":"auth","access_token":""}
```
Response
```json
{"type":"auth_invalid","message":"Invalid access token or password"}
```
Only happens sporadically, on average about every 1 in 5 times.

**Logs:**
The packet capture and companion app logs time frame does not overlap, which is why the home assistant log has sections for both of them.

[View homeassistant log](https://get.fallingcats.net/homeassistant/server_log.txt)

[Download packet capture](https://get.fallingcats.net/homeassistant/websocket_invalid_auth.pcapng)

[View companion log](https://get.fallingcats.net/homeassistant/homeassistant_companion_log_0-27-2023_1-42-2.txt)

**Additional information:**
This only happens on the external url which only works sometimes for me (because of aforementioned ocsp problems with the companion app)

Probably related: #2782, most bugs coming up for searches "ban", "ocsp" apparently, but it seems to me that nobody made the connection.

**Comment by dshokouhi** [comment] 2023-01-27 02:20
We actually always send auth with each request. This issue seems to be related to the app trying the URL and thus failing because we do not accept any SSL errors. I am not sure what the app can do here to solve the issue. The app does not know if an SSL error is going to happen so it will try. I dont think we can stop the banning.

What can you tell us about your network setup? Are you using a proxy or anything? If the SSL certificate works sometimes then that suggests a networking error. All the app does is try the URL and hope it does not have an SSL error.

If the ban is the issue due to an SSL failure then that might be an HA core issue to solve or this is just expected behavior due to the SSL error.

I have also seen a user mention that the most recent HA core beta (2023.2) solves the ban issue seen by some users.

**Comment by fallingcats** [comment] 2023-01-27 03:44
> We actually always send auth with each request. This issue seems to be related to the app trying the URL and thus failing because we do not accept any SSL errors. I am not sure what the app can do here to solve the issue. The app does not know if an SSL error is going to happen so it will try. I dont think we can stop the banning.

But that's the thing - SSL didn't fail for the websocket or else the server wouldn't respond http "101 switching connections", then get follow up request from the client over that websocket, would it? Please see the packet capture (captured between home assistant and nginx)

Put another way: Why would the client ever intentionally send an invalid auth request? There was no token in there.

**Comment by dshokouhi** [comment] 2023-01-27 04:29
> But that's the thing - SSL didn't fail for the websocket

According to the app and android it indeed did fail. Here is one of many examples from logcat.

```
01-27 01:41:26.294  8459  3014 E SensorReceiver: Issue registering sensor battery_power
01-27 01:41:26.294  8459  3014 E SensorReceiver: io.homeassistant.companion.android.common.data.integration.IntegrationException: javax.net.ssl.SSLHandshakeException: Chain validation failed
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.registerSensor(IntegrationRepositoryImpl.kt:708)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$registerSensor$1.invokeSuspend(Unknown Source:15)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
01-27 01:41:26.294  8459  3014 E SensorReceiver: Caused by: javax.net.ssl.SSLHandshakeException: Chain validation failed
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:731)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at java.lang.Thread.run(Thread.java:923)
01-27 01:41:26.294  8459  3014 E SensorReceiver: Caused by: java.security.cert.CertificateException: Chain validation failed
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:724)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:554)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:575)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:620)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:643)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:510)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:428)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:356)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:254)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1644)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:568)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	... 27 more
01-27 01:41:26.294  8459  3014 E SensorReceiver: Caused by: java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:222)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:720)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	... 43 more
01-27 01:41:26.294  8459  3014 E SensorReceiver: Caused by: java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at sun.security.provider.certpath.OCSPResponse.verify(OCSPResponse.java:619)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at sun.security.provider.certpath.RevocationChecker.checkOCSP(RevocationChecker.java:709)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:363)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:337)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	... 48 more
01-27 01:41:26.294  8459  3014 E SensorReceiver: 	Suppressed: java.security.cert.CertPathValidatorException: Could not determine revocation status
01-27 01:41:26.294  8459  3014 E SensorReceiver: 		at sun.security.provider.certpath.RevocationChecker.buildToNewKey(RevocationChecker.java:1092)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 		at sun.security.provider.certpath.RevocationChecker.verifyWithSeparateSigningKey(RevocationChecker.java:910)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 		at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:577)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 		at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:465)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 		at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:394)
01-27 01:41:26.294  8459  3014 E SensorReceiver: 		... 50 more
```

> There was no token in there.

Tokens are always added on each websocket connection

https://github.com/home-assistant/android/blob/master/common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt#L420

In this case the error itself is not solvable so we will not be able to proceed with a SSL validation error. I suspect when that issue is fixed on your end this issue will also be fixed. If we never sent a token then we would see this issue more frequently.

More than likely this is stemming from how Android handles SSL errors, it probably errors out and then proceeds to send invalid data. In our case we make an attempt to communicate with the server and if it fails, it fails and we try again later. We do not proceed nor handle SSL errors, those are for the user to handle.

The way the OS handles certificates is different from a browser so the experience will not be the same there. The behavior can vary from device to device.

**Comment by fallingcats** [comment] 2023-01-27 05:12
> More than likely this is stemming from how Android handles SSL errors, it probably errors out and then proceeds to send invalid data. In our case we make an attempt to communicate with the server and if it fails, it fails and we try again later. We do not proceed nor handle SSL errors, those are for the user to handle.

That's sounds deeply weird and very wrong. Why would any https library **ever** send data over a TLS connection it knows is not secure/trusted? Either the connection is good or you just sent private data to an attacker playing MITM.

I get that this doesn't seem to concern you because it works (mostly) and _this_ time there isn't actually private data in there, but I am very certain that something in this approach here is wrong (beside the actual an OCSP reponse)

**Comment by dshokouhi** [comment] 2023-01-27 05:26
> That's sounds deeply weird and very wrong. Why would any https library **ever** send data over a TLS connection it knows is not secure/trusted? Either the connection is good or you just sent private data to an attacker playing MITM.

I am not sure but we are not removing the token when we send it over 🤷‍♂️ 

> I get that this doesn't seem to concern you because it works (mostly) and this time there isn't actually private data in there, but I am very certain that something in this approach here is wrong (beside the actual an OCSP reponse) if it leads to ANY data being sent.

I am pretty sure if the SSL error is corrected it will fix this issue. For the app we need to solve the errors and as of now your symptoms point to a SSL error which is not something the app can solve.

> PS: I know the companion log contains a lot of noise, but the quoted error occured 10s before the one that lead to my main point of concern (at 01:41:36.760 according to HA).

The one logged by the app at this time in question is the exact same error. Timing may be off but honestly every single error in the companion app logs is identical.

```
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: Unable to retrieve external auth
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: javax.net.ssl.SSLHandshakeException: Chain validation failed
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:731)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at java.lang.Thread.run(Thread.java:923)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: Caused by: java.security.cert.CertificateException: Chain validation failed
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:724)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:554)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:575)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:620)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:643)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:510)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:428)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:356)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:254)
01-27 01:41:36.884  8459  8459 E WebViewPresenterImpl: 	at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1644)
01-27 01:41:36.886  8459  8459 E WebViewPresenterImpl: 	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
01-27 01:41:36.886  8459  8459 E WebViewPresenterImpl: 	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:568)
01-27 01:41:36.886  8459  8459 E WebViewPresenterImpl: 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
01-27 01:41:36.886  8459  8459 E WebViewPresenterImpl: 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
01-27 01:41:36.886  8459  8459 E WebViewPresenterImpl: 	... 27 more
01-27 01:41:36.886  8459  8459 E WebViewPresenterImpl: Caused by: java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date
01-27 01:41:36.886  8459  8459 E WebViewPresenterImpl: 	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
01-27 01:41:36.886  8459  8459 E WebViewPresenterImpl: 	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:222)
01-27 01:41:36.886  8459  8459 E WebViewPresenterImpl: 	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
01-27 01:41:36.886  8459  8459 E WebViewPresenterImpl: 	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
01-27 01:41:36.886  8459  8459 E WebViewPresenterImpl: 	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
01-27 01:41:36.886  8459  8459 E WebViewPresenterImpl: 	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:720)
01-27 01:41:36.886  8459  8459 E WebViewPresenterImpl: 	... 43 more
01-27 01:41:36.886  8459  8459 E WebViewPresenterImpl: Caused by: java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date
01-27 01:41:36.886  8459  8459 E WebViewPresenterImpl: 	at sun.security.provider.certpath.OCSPResponse.verify(OCSPResponse.java:619)
01-27 01:41:36.886  8459  8459 E WebViewPresenterImpl: 	at sun.security.provider.certpath.RevocationChecker.checkOCSP(RevocationChecker.java:709)
01-27 01:41:36.886  8459  8459 E WebViewPresenterImpl: 	at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:363)
01-27 01:41:36.886  8459  8459 E WebViewPresenterImpl: 	at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:337)
01-27 01:41:36.886  8459  8459 E WebViewPresenterImpl: 	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
01-27 01:41:36.886  8459  8459 E WebViewPresenterImpl: 	... 48 more
01-27 01:41:36.886  8459  8459 E WebViewPresenterImpl: 	Suppressed: java.security.cert.CertPathValidatorException: Could not determine revocation status
01-27 01:41:36.886  8459  8459 E WebViewPresenterImpl: 		at sun.security.provider.certpath.RevocationChecker.buildToNewKey(RevocationChecker.java:1092)
01-27 01:41:36.886  8459  8459 E WebViewPresenterImpl: 		at sun.security.provider.certpath.RevocationChecker.verifyWithSeparateSigningKey(RevocationChecker.java:910)
01-27 01:41:36.886  8459  8459 E WebViewPresenterImpl: 		at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:577)
01-27 01:41:36.886  8459  8459 E WebViewPresenterImpl: 		at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:465)
01-27 01:41:36.886  8459  8459 E WebViewPresenterImpl: 		at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:394)
01-27 01:41:36.886  8459  8459 E WebViewPresenterImpl: 		... 50 more
```

**Comment by fallingcats** [comment] 2023-01-27 05:39
> I am pretty sure if the SSL error is corrected it will fix this issue. For the app we need to solve the errors and as of now your symptoms point to a SSL error which is not something the app can solve.

Sorry to ask so explicitly but you seem to evade an answer: Are you not at all concerned about the mentioned security implications of the app/library behaving that way?

I could make the error go away by using a tls cert that doesn't require "ocsp must staple", but that's not at all what I was getting at here...

**Closed** 2023-10-25 22:18 UTC
Labels: bug
