### ISSUE TITLE
Mobilní aplikace padá 

### ISSUE THREAD

**Issue by mirbusak** [home-assistant/android#4878] opened 2024-12-05 07:10 UTC
**Home Assistant Android app version(s):**
2024.10.3-full
**Android version(s):**
14UP1A231005.007
**Device model(s):**
22101316G
**Home Assistant version:**
HA OS 14.0
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
Aplikace začala padat po kliknutí na "Zařízení a služby.

**Companion App Logs:**
[homeassistant_companion_log_11-5.txt](https://github.com/user-attachments/files/18018766/homeassistant_companion_log_11-5.txt)

```

```

**Screenshot or video of problem:**

https://github.com/user-attachments/assets/c0096272-afd7-4c5b-abca-94d845653b9a

**Additional information:**

**Comment by jpelgrom** [comment] 2024-12-05 07:14
We only accept bug reports in English, sorry.

It looks like your app is crashing when opening Devices & services on 2024.12 - this is a duplicate of #4761 and fixed in the next version of the app, which should be released this week.

**Closed as not planned by jpelgrom** 2024-12-05 07:14 UTC
Labels: bug
