### ISSUE TITLE
Crash when poor or no connection with widgets

### ISSUE THREAD

**Issue by soccerarenadev** [home-assistant/android#2421] opened 2022-04-03 14:51 UTC
**Home Assistant Android version:**
2022.3.0-full

**Android version:**
12

**Phone model:**
Pixel 5

**Home Assistant version:**
2022.3.8

**Last working Home Assistant release (if known):**
??

**Description of problem:**
I have several widgets. One of them to display an entity and 22 service calls. Quite a few times, when I loose connection with the HA or recover it (when I have poor coverage, in the garage, when toggling back from Airplane Mode to normal mode ...), I have one or several crashes.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![Screenshot_20220404-071458~2](https://user-images.githubusercontent.com/99416733/161570790-0419e71d-6261-42e5-9420-c9d7aa209415.png)

**Additional information:**

**Comment by dshokouhi** [comment] 2022-04-04 19:41
Are you by chance able to get us the crash logs? You won't be able to get it from the app logs but possibly Logcat Reader or Android Studio.

**Comment by soccerarenadev** [comment] 2022-04-05 05:43
The logs from the app aren't valid?
I'll try to get them in next crash.

**Comment by dshokouhi** [comment] 2022-04-05 06:05
> The logs from the app aren't valid?

The app won't get them if it's crashing unfortunately

**Comment by soccerarenadev** [comment] 2022-04-10 07:06
Hopefully this helps:

```
--------- beginning of crash

04-07 05:44:20.548 29007 29007 E AndroidRuntime: FATAL EXCEPTION: main

04-07 05:44:20.548 29007 29007 E AndroidRuntime: Process: io.homeassistant.companion.android, PID: 29007

04-07 05:44:21.257  1059  1146 E android.hardware.sensors@1.0-service: ERROR: Fix ultrasound sensor so it does not return error from poll()

04-07 05:44:26.106 30209 30209 E mpanion.androi: Not starting debugger since process cannot load the jdwp agent.

04-07 05:44:26.305 30209 30277 E WebSocketRepository: Websocket: onFailure

04-07 05:44:26.309 30209 30238 E IntegrationRepository: Issue getting new version from core.

04-07 05:44:26.322 30209 30277 E WebSocketRepository: Websocket: onFailure

04-07 05:44:26.323 30209 30293 E IntegrationRepository: Issue getting new version from core.

04-07 05:44:26.372 30209 30293 E SensorReceiver: Issue registering sensor: battery_temperature

04-07 05:44:26.429 30209 30236 E LocBroadcastReceiver: Error receiving zones from Home Assistant

04-07 05:44:26.431 30209 30236 E LocBroadcastReceiver: Issue requesting zone updates.

04-07 05:44:26.431 30209 30236 E LocBroadcastReceiver: java.lang.IllegalArgumentException: No geofence has been added to this request.

04-07 05:44:26.431 30209 30236 E LocBroadcastReceiver: 	at com.google.android.gms.common.internal.Preconditions.checkArgument(com.google.android.gms:play-services-basement@@18.0.0:2)

04-07 05:44:26.431 30209 30236 E LocBroadcastReceiver: 	at com.google.android.gms.location.GeofencingRequest$Builder.build(com.google.android.gms:play-services-location@@18.0.0:2)

04-07 05:44:26.431 30209 30236 E LocBroadcastReceiver: 	at io.homeassistant.companion.android.sensors.LocationSensorManager.createGeofencingRequest(LocationSensorManager.kt:684)

04-07 05:44:26.431 30209 30236 E LocBroadcastReceiver: 	at io.homeassistant.companion.android.sensors.LocationSensorManager.access$createGeofencingRequest(LocationSensorManager.kt:41)

04-07 05:44:26.431 30209 30236 E LocBroadcastReceiver: 	at io.homeassistant.companion.android.sensors.LocationSensorManager$createGeofencingRequest$1.invokeSuspend(Unknown Source:14)

04-07 05:44:26.431 30209 30236 E LocBroadcastReceiver: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

04-07 05:44:26.431 30209 30236 E LocBroadcastReceiver: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)

04-07 05:44:26.431 30209 30236 E LocBroadcastReceiver: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)

04-07 05:44:26.431 30209 30236 E LocBroadcastReceiver: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)

04-07 05:44:26.431 30209 30236 E LocBroadcastReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)

04-07 05:44:26.431 30209 30236 E LocBroadcastReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)

04-07 05:44:26.431 30209 30236 E LocBroadcastReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)

04-07 05:44:26.431 30209 30236 E LocBroadcastReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

04-07 05:44:28.516 27769 27769 E fsv     : ComposeActivity: Race condition: Message has not been initialized [CONTEXT android_log_tag="ComposeActivity" ]

04-07 05:44:28.770 27769 30322 E acjn    : Job(ItemsSyncControlService:sync#0.667) Sync scheduled after applying or undoing changes failed

04-07 05:44:28.770 27769 30322 E acjn    : aago: [/sync/i/s] 3: Not connected to internet: aing: NO_NETWORK: es: Exception in CronetUrlRequest: net::ERR_INTERNET_DISCONNECTED, ErrorCode=2, InternalErrorCode=-106, Retryable=false

04-07 05:44:28.770 27769 30322 E acjn    : 	at aagl.a(PG:1)

04-07 05:44:28.770 27769 30322 E acjn    : 	at aagq.a(PG:6)

04-07 05:44:28.770 27769 30322 E acjn    : 	at aajo.a(PG:103)

04-07 05:44:28.770 27769 30322 E acjn    : 	at ajjj.a(PG:2)

04-07 05:44:28.770 27769 30322 E acjn    : 	at ajhm.qJ(PG:2)

04-07 05:44:28.770 27769 30322 E acjn    : 	at alpt.run(PG:7)

04-07 05:44:28.770 27769 30322 E acjn    : 	at alpd.execute(Unknown Source:0)

04-07 05:44:28.770 27769 30322 E acjn    : 	at ajju.execute(PG:3)

04-07 05:44:28.770 27769 30322 E acjn    : 	at aloa.m(PG:1)

04-07 05:44:28.770 27769 30322 E acjn    : 	at aloa.i(PG:8)

04-07 05:44:28.770 27769 30322 E acjn    : 	at aloa.setException(Unknown Source:17)

04-07 05:44:28.770 27769 30322 E acjn    : 	at com.google.common.util.concurrent.SettableFuture.setException(Unknown Source:0)

04-07 05:44:28.770 27769 30322 E acjn    : 	at aiox.a(PG:3)

04-07 05:44:28.770 27769 30322 E acjn    : 	at ajhm.qJ(PG:2)

04-07 05:44:28.770 27769 30322 E acjn    : 	at alpt.run(PG:7)

04-07 05:44:28.770 27769 30322 E acjn    : 	at xqq.run(PG:74)

04-07 05:44:28.770 27769 30322 E acjn    : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)

04-07 05:44:28.770 27769 30322 E acjn    : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

04-07 05:44:28.770 27769 30322 E acjn    : 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)

04-07 05:44:28.770 27769 30322 E acjn    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)

04-07 05:44:28.770 27769 30322 E acjn    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

04-07 05:44:28.770 27769 30322 E acjn    : 	at java.lang.Thread.run(Thread.java:920)

04-07 05:44:28.770 27769 30322 E acjn    : Caused by: aing: NO_NETWORK: es: Exception in CronetUrlRequest: net::ERR_INTERNET_DISCONNECTED, ErrorCode=2, InternalErrorCode=-106, Retryable=false

04-07 05:44:28.770 27769 30322 E acjn    : 	at aipf.a(PG:3)

04-07 05:44:28.770 27769 30322 E acjn    : 	at aiui.onFailed(PG:6)

04-07 05:44:28.770 27769 30322 E acjn    : 	at fh.onFailed(:com.google.android.gms.dynamite_cronetdynamite@220920097@22.09.20 (190400-0):0)

04-07 05:44:28.770 27769 30322 E acjn    : 	at ej.run(:com.google.android.gms.dynamite_cronetdynamite@220920097@22.09.20 (190400-0):1)

04-07 05:44:28.770 27769 30322 E acjn    : 	... 7 more

04-07 05:44:28.770 27769 30322 E acjn    : Caused by: aitz: es: Exception in CronetUrlRequest: net::ERR_INTERNET_DISCONNECTED, ErrorCode=2, InternalErrorCode=-106, Retryable=false

04-07 05:44:28.770 27769 30322 E acjn    : 	at aiui.onFailed(PG:5)

04-07 05:44:28.770 27769 30322 E acjn    : 	... 9 more

04-07 05:44:28.770 27769 30322 E acjn    : Caused by: es: Exception in CronetUrlRequest: net::ERR_INTERNET_DISCONNECTED, ErrorCode=2, InternalErrorCode=-106, Retryable=false

04-07 05:44:28.770 27769 30322 E acjn    : 	at org.chromium.net.impl.CronetUrlRequest.onError(:com.google.android.gms.dynamite_cronetdynamite@220920097@22.09.20 (190400-0):4)

04-07 05:44:29.263  1059  1146 E android.hardware.sensors@1.0-service: ERROR: Fix ultrasound sensor so it does not return error from poll()

04-07 05:44:31.014 30367 30367 E ugnb.rlxllcdhm: Not starting debugger since process cannot load the jdwp agent.

04-07 05:44:31.066  1677  4306 E system_server: Invalid class loader spec: =UnsupportedClassLoaderContext=

04-07 05:44:31.066  1677  4306 E PackageDexUsage: Unsupported context?

04-07 05:44:37.272  1059  1146 E android.hardware.sensors@1.0-service: ERROR: Fix ultrasound sensor so it does not return error from poll()

---- Apr 7, 2022 05:44:53 ----
```

**Comment by jpelgrom** [comment] 2022-04-12 21:36
Unfortunately, it looks like your log doesn't include the details of the crash. When viewing the output, it should be directly after these lines:
```
04-07 05:44:20.548 29007 29007 E AndroidRuntime: FATAL EXCEPTION: main
04-07 05:44:20.548 29007 29007 E AndroidRuntime: Process: io.homeassistant.companion.android, PID: 29007
```
Maybe the filter you used for the logs removed the lines that included the details. In that case, if you spot something like above, change the filter to show all output and search by the number after "PID" instead (so for this crash, that would've been 29007).

**Comment by dshokouhi** [comment] 2022-04-14 15:48
@soccerarenadev these logs are also incomplete, you will need to adjust your search just as @jpelgrom  mentioned. If you are filtering by `homeassistant` or something similar you are cutting out a lot of important lines from the traceback.

```
04-14 15:54:28.019 27335 27335 E AndroidRuntime: Process: io.homeassistant.companion.android, PID: 27335
```

We need to see the full traceback for this error, so once you do your search you need to do it again with the PID so we can get the complete error message instead of the lines that just contain our app name.

**Comment by jpelgrom** [comment] 2022-06-13 07:45
@soccerarenadev Hi, are you still experiencing this issue? The latest version of the app (2022.6.0-full) includes some improvements and if it crashes it will now try to save the required log in Settings > Companion app > Show and share logs > Recent crash.

**Comment by soccerarenadev** [comment] 2022-06-14 15:06
> @soccerarenadev Hi, are you still experiencing this issue? The latest version of the app (2022.6.0-full) includes some improvements and if it crashes it will now try to save the required log in Settings > Companion app > Show and share logs > Recent crash.

So far I haven't found any crash yet. If it crashes again I'll use that option.

Thank you!

**Comment by soccerarenadev** [comment] 2022-06-15 05:30
> @soccerarenadev Hi, are you still experiencing this issue? The latest version of the app (2022.6.0-full) includes some improvements and if it crashes it will now try to save the required log in Settings > Companion app > Show and share logs > Recent crash.

Another crash this morning.
However, I couldn't find the "Recent crash" option.

I attach some images:
Crash:
![image](https://user-images.githubusercontent.com/99416733/173745356-fa3b91f4-994b-433a-810f-1097857f1b3e.png)

App information:
![image](https://user-images.githubusercontent.com/99416733/173745525-34a1ec00-c79a-4b05-a9b6-39c6407eff7e.png)

Logs:
![image](https://user-images.githubusercontent.com/99416733/173745620-c7166166-0c33-4909-851b-ccbff4bd5a0e.png)


However, I don't find the option to see the "Recent crash".

**Comment by jpelgrom** [comment] 2022-06-15 06:41
> Another crash this morning.
> However, I couldn't find the "Recent crash" option.

If there is no option for 'recent crash' that suggests that the app wasn't able to record the crash, sorry. To continue you would have to get the crash log from logcat as previously requested.

**Comment by soccerarenadev** [comment] 2022-06-15 07:11
> > Another crash this morning.
> > However, I couldn't find the "Recent crash" option.
> 
> If there is no option for 'recent crash' that suggests that the app wasn't able to record the crash, sorry. To continue you would have to get the crash log from logcat as previously requested.

Any recommendation of logcat app?
I could submit before because the log was so large. That's why I sent you a smaller subset.

**Comment by jpelgrom** [comment] 2022-06-15 10:50
[Logcat Reader](https://play.google.com/store/apps/details?id=com.dp.logcatapp) is usually recommended and should work. Try to use it after the app has recently crashed, if it's been several hours the logs might not include the error anymore.

**Comment by soccerarenadev** [comment] 2022-06-16 09:51
> [Logcat Reader](https://play.google.com/store/apps/details?id=com.dp.logcatapp) is usually recommended and should work. Try to use it after the app has recently crashed, if it's been several hours the logs might not include the error anymore.

I got one this morning:
https://a.tmp.ninja/dxYXnVfM.zip (link valid for 48 hours)

I hope this logcat is fine.

**Comment by jpelgrom** [comment] 2022-06-17 15:43
Not seeing the expected crash in the logs, but what is interesting is that it appears that the system is killing the app because of an ANR during the _screen off_ broadcast. Maybe the dialog shown when unlocking the phone is actually for a 'crash' when the screen is turned off?

Maybe that is why the crash isn't recorded by Sentry? Although I expected the 'fatal exception' message to follow almost immediately after turning on the screen and use the same pid as before (25028 instead of 26220), the only message in the log for pid 26220 before the fatal exception is for the notification listener service.

@soccerarenadev You mentioned that you have 1 entity (state) widget and a lot of button widgets. Could you temporarily remove the entity widget to see if you still get the crash? (That widget should be the only one actually doing something during screen off.)

<details>
<summary>Relevant log entries</summary>

```
[06-16 07:57:52.454 1684:1684 I/PowerManagerService]
Powering off display group due to power_button (groupId= 0, uid= 1000)...

(...)

[06-16 07:57:52.990 1684:1833 I/PowerManagerService]
Dozing...

(...)

[06-16 07:58:03.070 1684:1813 W/BroadcastQueue]
Timeout of broadcast BroadcastRecord{84cd855 u-1 android.intent.action.SCREEN_OFF} - receiver=android.os.BinderProxy@a7c4647, started 10003ms ago

[06-16 07:58:03.071 1684:1813 W/BroadcastQueue]
Receiver during timeout of BroadcastRecord{84cd855 u-1 android.intent.action.SCREEN_OFF} : BroadcastFilter{a099f9d 10222/u0 ReceiverList{63dbe74 25028 io.homeassistant.companion.android/10222/u0 remote:a7c4647}}

(...)

[06-16 07:58:03.335 1684:26208 E/ActivityManager]
ANR in io.homeassistant.companion.android
PID: 25028
Reason: Broadcast of Intent { act=android.intent.action.SCREEN_OFF flg=0x50200010 }
Frozen: false
Load: 0.0 / 0.0 / 0.0
----- Output from /proc/pressure/memory -----
some avg10=0.08 avg60=0.02 avg300=0.00 total=2305140201
full avg10=0.00 avg60=0.00 avg300=0.00 total=1159562646
----- End output from /proc/pressure/memory -----

(...)

[06-16 07:58:03.338 1684:26208 I/ActivityManager]
Killing 25028:io.homeassistant.companion.android/u0a222 (adj 0): bg anr

[06-16 07:58:03.339 1684:26208 D/ActivityManager]
Completed ANR of io.homeassistant.companion.android in 265ms, latency 2ms

(...)

[06-16 07:58:03.361 1684:6481 D/NotificationListeners]
Removing active service ComponentInfo{io.homeassistant.companion.android/io.homeassistant.companion.android.sensors.NotificationSensorManager}

[06-16 07:58:03.362 1684:1684 V/NotificationListeners]
0 notification listener connection lost: ComponentInfo{io.homeassistant.companion.android/io.homeassistant.companion.android.sensors.NotificationSensorManager}

[06-16 07:58:03.363 1684:1983 W/ActivityManager]
Scheduling restart of crashed service io.homeassistant.companion.android/.sensors.NotificationSensorManager in 1000ms for connection

(...)

[06-16 07:58:04.378 1684:1814 I/ActivityManager]
Start proc 26220:io.homeassistant.companion.android/u0a222 for service {io.homeassistant.companion.android/io.homeassistant.companion.android.sensors.NotificationSensorManager}

[06-16 07:58:04.543 1684:1684 V/NotificationListeners]
0 notification listener service connected: ComponentInfo{io.homeassistant.companion.android/io.homeassistant.companion.android.sensors.NotificationSensorManager}

(...)

[06-16 07:58:43.027 1684:1983 I/PowerManagerService]
Powering on display group fromDozing (groupId=0, uid=10184, reason=WAKE_REASON_GESTURE, details=android.policy:BIOMETRIC)...

[06-16 07:58:43.028 1684:1983 I/PowerManagerService]
Waking up from Dozing (uid=10184, reason=WAKE_REASON_GESTURE, details=android.policy:BIOMETRIC)...

(...)

[06-16 07:58:59.477 26220:26220 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: io.homeassistant.companion.android, PID: 26220

(...)

[06-16 07:59:03.712 1684:4778 I/ActivityManager]
Killing 26220:io.homeassistant.companion.android/u0a222 (adj 0): crash

[06-16 07:59:03.714 1684:1684 V/NotificationListeners]
0 notification listener connection lost: ComponentInfo{io.homeassistant.companion.android/io.homeassistant.companion.android.sensors.NotificationSensorManager}

[06-16 07:59:03.714 1684:1684 W/NotificationListeners]
0 notification listener binding died: ComponentInfo{io.homeassistant.companion.android/io.homeassistant.companion.android.sensors.NotificationSensorManager}
```
</details>

For the button widgets I would have expected to see the `Intent.ACTION_SCREEN_ON` broadcast in the logs, but it's not there.

https://github.com/home-assistant/android/blob/f5f2cc66d93f97ae78ba8fa3506d3237fd411286/app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidget.kt#L120-L125

**Comment by soccerarenadev** [comment] 2022-06-19 08:08
I removed the entity and still got crashes.

To simulate, I just changed the internal and external address to fake addresses. And crashes kept coming.
Here the logs: https://a.tmp.ninja/oiNVmtqi.zip

Furthermore, I've seen several bugs (they've been always present), like trying to add a Widget and have some information from other widgets instead of a blank template, or updating widgets and get all the values messed and unusable after the update.

**Comment by soccerarenadev** [comment] 2022-06-19 08:12
@jpelgrom I removed the entity and still got crashes.

To simulate, I just changed the internal and external address to fake addresses. And crashes kept coming.
Here the logs: https://a.tmp.ninja/oiNVmtqi.zip

Furthermore, I've seen several bugs (they've been always present), like trying to add a Widget and have some information from other widgets instead of a blank template, or updating widgets and get all the values messed and unusable after the update.

**Comment by soccerarenadev** [comment] 2022-06-19 08:55
Another one.

This one IS from within the app. 
Crash 01: https://a.tmp.ninja/wtOzeSoz.zip
Crash 04: https://a.tmp.ninja/keBVWYsQ.zip
I got from the "Settings > Companion app > Show and share logs > Recent crash"

How did the error happen?
I went into the "Companion app", and opened "Manage Widgets".
Every-time I do that, the app crashes.

I think this may be related to the other issue, when I try to add a widget and info already appears.
My guess?
I restored the phone from a previous phone, and widgets were restored in the app, but not in the launcher. When I re-added them, keys were duplicated due to a wrong handing of the app.

**Comment by soccerarenadev** [comment] 2022-06-19 09:07
I've realized that it crashes when reaching the "Entity State Widgets" section:
![image](https://user-images.githubusercontent.com/99416733/174473737-9604ee4e-687f-4fd8-ae56-3fad67ed97c0.png)

If I don't reach that, there is no crash inside the app.

**Comment by jpelgrom** [comment] 2022-06-19 16:15
Thanks for all the additional logs!

Your first log after changing the internal/external URL shows a crash due to not being able to make a connection which is unexpected because there should be no widgets that connect to the network on screen on/off.

However, the second and third logs + your description suggests that there is some old/corrupt data in the database which might be causing the crashes. It could be that during restore the app's data was restored but the widgets weren't, which incorrectly results in the app thinking there are certain widgets when they don't exist.

Unfortunately this can't really be resolved except for starting fresh: https://companion.home-assistant.io/docs/troubleshooting/faqs#starting-fresh-with-the-android-app. You will have to set up your widgets again. Please try this and let us know if there are still background crashes.

<details>
<summary>Crash after changing internal to external address</summary>

```
[06-19 09:58:37.811 11855:11855 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: io.homeassistant.companion.android, PID: 11855
java.net.SocketTimeoutException: failed to connect to [domain.tld]/[ip address] (port 38123) from /10.210.82.103 (port 39490) after 10000ms
	at libcore.io.IoBridge.connectErrno(IoBridge.java:236)
	at libcore.io.IoBridge.connect(IoBridge.java:180)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:621)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8d698c0, Dispatchers.Main]
```
</details>

<details>
<summary>Crash in settings > Manage Widgets</summary>

```
2022-06-19 10:51:42.806: java.lang.IllegalArgumentException: Key 42 was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:411)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:732)
	at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw(LazyLayoutMeasureScope.kt:118)
	at androidx.compose.foundation.lazy.LazyMeasuredItemProvider.getAndMeasure-ZjPyQlc(LazyMeasuredItemProvider.kt:47)
	at androidx.compose.foundation.lazy.LazyListMeasureKt.measureLazyList-7Xnphek(LazyListMeasure.kt:150)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke-0kLqBqw(LazyList.kt:267)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(LazyList.kt:194)
	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$2$1.invoke-0kLqBqw(LazyLayout.kt:74)
	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$2$1.invoke(LazyLayout.kt:70)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:590)
	at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.kt:44)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:405)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:53)
	at androidx.compose.foundation.layout.FillModifier.measure-3p2s80s(Size.kt:658)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:53)
	at androidx.compose.ui.node.LayoutNode$performMeasure$1.invoke(LayoutNode.kt:1420)
	at androidx.compose.ui.node.LayoutNode$performMeasure$1.invoke(LayoutNode.kt:1419)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2098)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:112)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:78)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:66)
	at androidx.compose.ui.node.LayoutNode.performMeasure-BRTryo0$ui_release(LayoutNode.kt:1419)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:94)
	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(LayoutNode.kt:1373)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(MeasureAndLayoutDelegate.kt:185)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout-0kLqBqw(MeasureAndLayoutDelegate.kt:226)
	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout-0kLqBqw(AndroidComposeView.android.kt:750)
	at androidx.compose.ui.node.LayoutNode.forceRemeasure(LayoutNode.kt:1449)
	at androidx.compose.foundation.lazy.LazyListState.onScroll$foundation_release(LazyListState.kt:298)
	at androidx.compose.foundation.lazy.LazyListState$scrollableState$1.invoke(LazyListState.kt:170)
	at androidx.compose.foundation.lazy.LazyListState$scrollableState$1.invoke(LazyListState.kt:170)
	at androidx.compose.foundation.gestures.DefaultScrollableState$scrollScope$1.scrollBy(ScrollableState.kt:134)
	at androidx.compose.foundation.gestures.ScrollingLogic.dispatchScroll-f0eR0lY(Scrollable.kt:305)
	at androidx.compose.foundation.gestures.ScrollingLogic$doFlingAnimation$2$outerScopeScroll$1.invoke-MK-Hz9U(Scrollable.kt:347)
	at androidx.compose.foundation.gestures.ScrollingLogic$doFlingAnimation$2$outerScopeScroll$1.invoke(Scrollable.kt:346)
	at androidx.compose.foundation.gestures.ScrollingLogic$doFlingAnimation$2$scope$1.scrollBy(Scrollable.kt:352)
	at androidx.compose.foundation.gestures.DefaultFlingBehavior$performFling$2.invoke(Scrollable.kt:444)
	at androidx.compose.foundation.gestures.DefaultFlingBehavior$performFling$2.invoke(Scrollable.kt:442)
	at androidx.compose.animation.core.SuspendAnimationKt.doAnimationFrame(SuspendAnimation.kt:321)
	at androidx.compose.animation.core.SuspendAnimationKt.access$doAnimationFrame(SuspendAnimation.kt:1)
	at androidx.compose.animation.core.SuspendAnimationKt$animate$9.invoke(SuspendAnimation.kt:262)
	at androidx.compose.animation.core.SuspendAnimationKt$animate$9.invoke(SuspendAnimation.kt:261)
	at androidx.compose.animation.core.SuspendAnimationKt$callWithFrameNanos$2.invoke(SuspendAnimation.kt:287)
	at androidx.compose.animation.core.SuspendAnimationKt$callWithFrameNanos$2.invoke(SuspendAnimation.kt:286)
	at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)
	at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:71)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:461)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:454)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:775)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@b7798eb, androidx.compose.runtime.BroadcastFrameClock@345e648, StandaloneCoroutine{Cancelling}@49d2ce1, AndroidUiDispatcher@19eda06]
```
</details>

---

 - The first log contains entries with `StaticWidget: Unable to fetch entity` which shouldn't be possible if all entity widgets were removed, which suggests old widgets in the database from before a restore. This will then be used on screen on/off, so #2615 might potentially fix the background crash.
 - If data was restored but the widgets weren't, it is possible that the app will receive a request for a new widget with an ID that was previously used. Because IDs are stored per widget type instead of globally this could create a duplicate ID for the manage widgets screen. They should be prefixed with the widget type to prevent this from happening, opening a PR soon.

**Comment by jpelgrom** [comment] 2022-06-20 10:39
> it should treat the crashes more gracefully and be transparent to the user, with no visible crash

I agree, and the PR mentioned in my previous comment + the linked PR should prevent two crashes you were experiencing and makes it possible to recover from them.

> Furthermore, the "edition" of a widget is not working correctly, both for "entity states" and "service buttons" are broken when editing.

Please open a new issue for this with more details so we can look into it. Possibly a duplicate of #2604?

**Comment by soccerarenadev** [comment] 2022-06-23 06:23
@jpelgrom I got a few crashes these days. They are less frequent as before, but I still get crashes after the fresh reinstall.
Logcat: https://a.tmp.ninja/jJfBxxlb.zip

**Comment by dshokouhi** [comment] 2022-09-06 02:59
Is this still an issue in the latest release?

**Comment by soccerarenadev** [comment] 2022-09-06 06:41
> Is this still an issue in the latest release?

I haven't got any issue yet.
I'll let you know if this changes.

**Comment by dshokouhi** [comment] 2022-09-06 15:45
ok lets close this issue for now as the latest release contained #2615 which may have fixed this issue

**Closed by dshokouhi** 2022-09-06 15:45 UTC
Labels: bug, widget
