### ISSUE TITLE
avoid entity id localization / translation

### ISSUE THREAD

**Issue by jedi7** [home-assistant/android#1089] opened 2020-10-21 19:41 UTC
**Home Assistant Android version:**
2.5.0-full

**Android version:**
9

**Phone model:**
LG G6

**Home Assistant version:**
0.116.4

**Last working Home Assistant release (if known):**

**Description of problem:**
The sensors entity_id names from application are localized (translated)
For example: 
now: "sensor.mobil_hlasitost_budiku"
expected: "sensor.mobil_volume_level_alarm"

So entity name can be localized, but not the entity_id, which should stay in English.

You can image the problem, if somebody use for example Chinese ;-)

If needed I can explain it more. 
Thanks for nice app.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2020-10-21 19:53
Duplicate of #971

**Closed by dshokouhi** 2020-10-21 19:53 UTC
Labels: bug
