### ISSUE TITLE
Keyboard collapse on every input_datetime change

### ISSUE THREAD

**Issue by Schluggi** [home-assistant/android#2471] opened 2022-04-24 12:37 UTC
**Home Assistant Android version:**2022.3.0-full

**Android version:** 11

**Phone model:** OnePlus 7 

**Home Assistant version:**  2022.4.6 

**Last working Home Assistant release (if known):** -

**Description of problem:**
The keyboard collapse after every input_datetime input. So its very hard to change the time. 
For example if I want to change the minutes of an input_datetime to `25`: After typing the a `2` the keyboard collapses. So I can't enter the second digit. 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/43608073/164976816-53807b32-faa8-446f-badd-a4310ae544c1.gif)

**Additional information:**
This also happens on iPhone and works fine in the web frontend (at both devices).

**Comment by dshokouhi** [comment] 2022-04-24 22:58
duplicate of https://github.com/home-assistant/android/issues/2384 please check HA frontend open issues. If you don't see it there then please open a new issue as the android app cannot fix this.

**Closed by dshokouhi** 2022-04-24 22:58 UTC
Labels: bug

**Comment by Schluggi** [comment] 2022-04-25 08:55
HA frontend issue: [#11861](https://github.com/home-assistant/frontend/issues/11861)
