### ISSUE TITLE
Can't play videos in android tablet

### ISSUE THREAD

**Issue by cso2020** [home-assistant/android#1355] opened 2021-02-09 14:08 UTC
Hi. I have videos from Arlo cameras that can't be played in home assistant in my desktop, in my iOS phone and even in the android tablet if I open home assistant in Chrome. But they dont play the app in the android tablet. It's a Lenovo m8 (TB_8505F) with android 10. The  app versión Is 2021.1.1 full, and home assistant Is core 2021.1.5. Thanks.

**Comment by dshokouhi** [comment] 2021-02-09 17:36
can you check that android system webview is up to date?

**Comment by cso2020** [comment] 2021-02-09 19:24
Yes. It’s version 88.0.4324.152

**Comment by dshokouhi** [comment] 2021-02-09 19:26
What errors do you see on screen?  This issue is missing the issue template where we usually request screenshots and crash logs and I don't see that here.

what steps have you tried to resolve the issue? have you tried clearing app data?

**Comment by dshokouhi** [comment] 2021-02-09 19:44
First try: https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

if issue persists please post a screenshot along with steps taken to reproduce.

Crash logs in case there is a background crash: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs

**Comment by mathmaniac43** [comment] 2021-03-06 14:09
Good morning,

I just received and set up a brand new Android tablet this week and am experiencing the same problem. I know there is not a template for the initial issue here, but I will try to provide the same sort of information here for my situation.

The tablet is a Samsung Galaxy A7 (SM-T500), running Android 10

The HA app is version 2021.3.1, and the HA version is 2021.3.2 (running in a Docker container).

All camera streams (mine are provided from the reolink-dev integration via HACS) have both their default view in Lovelace, as well as their focused view when clicked, as the gray square with the play button in it, indicating that the stream cannot be loaded for some reason.

The really interesting part to me is that when I press on it, it looks like it is buffering SOMETHING (the time on the right number above the scrubber increases), but there is no way to make it play or get past the gray play button.

Hope that helps.

**Comment by dshokouhi** [comment] 2021-03-06 16:46
@mathmaniac43 do you see the same issue in chrome for android? if not did you try the above steps?

**Comment by mathmaniac43** [comment] 2021-03-06 21:57
I just tested on the tablet in the most up-to-date Google Chrome. It did not have the gray square and play button, but did not play either. It was just black. Same situation where it would still buffer, but nothing shows up.

**Comment by dshokouhi** [comment] 2021-03-07 01:44
If you see the same behavior in chrome then it is a HA frontend issue and not an app issue.

**Comment by mathmaniac43** [comment] 2021-03-07 02:10
OK, I will create an issue there and link back. Thank you!

**Comment by dshokouhi** [comment] 2021-04-02 00:44
Closing as it doesnt seem like something the app can solve based on the Chromium bug and linked frontend issue

**Closed by dshokouhi** 2021-04-02 00:44 UTC
Labels: bug, webview
