### ISSUE TITLE
Unavailable device/entities when app does not provide updates

### ISSUE THREAD

**Issue by ThomDietrich** [home-assistant/android#2935] opened 2022-10-01 14:20 UTC
**Home Assistant Android version:**

2022.9.1-full

**Android version:**

12

**Phone model:**

OnePlus 6T and OnePlus Nord

**Home Assistant version:**

2022.9.7

**Last working Home Assistant release (if known):**

**Description of problem:**

Hello,
TL;DR; please mark sensors as `unknown` or `unavailable` when the phone doesn't send updates.

I've observed this issue a couple of times, on multiple phones, over many months. Occasionally the status of all phone sensors stay unchanged over the course of hours and days. I assume this happens because the android app was killed in the background or for some other reason. Irrespective of why the phone does this and how I would go about fixing this, it is imho an error to retain outdated states in Home Assistant.

Example: This phone was actively used the last couple of days, including over-night charging etc. For the last three days the sensor value stayed unchanged:

![image](https://user-images.githubusercontent.com/2870104/193413745-76df9ed0-0657-4ab8-bcd5-45373079091d.png)

Other active sensors are equally stale. I would expect all of these sensors to switch to "unknown" or "unavailable" in my Home Assistant server some time around 28. Sept. 20:00 latest.

Please let me know how I can help!

Cheers, Thomas

 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2022-10-01 15:36
Duplicate of https://github.com/home-assistant/android/issues/411

You may want to check that you granted the app access to run in the background if you notice updates stopping.

**Closed by dshokouhi** 2022-10-01 15:37 UTC
Labels: bug

**Comment by ThomDietrich** [comment] 2022-10-01 16:39
Had a look at the discussion there. Did the situation potentially change since 2020?? Please reopen and let's discuss. This is currently one of the major issues my family experiences with Home Assistant and imho should be solved at the source rather than with additional template sensors to deal with shortcomings of the Home Assistant system.

As specifically mentioned, I don't think the reason for the stopped updates should be relevant here. My phone could have fallen in a volcano.


I think you nailed down the source of the issue correctly:

> so HA core should be responsible for this behavior due to that alone.

I agree. Here I am lost in implementation details. The MQTT integration supports `expire_after` and `availability` topics. Other integrations have their own individual ways to determine whether a device or gateway is `unavailable`. How does the companion app integrate with Home Assistant, hence which Home Assistant component would be responsible to mark states as `unavailable` upon certain conditions?

**Comment by dshokouhi** [comment] 2022-10-01 16:42
@ThomDietrich you need to take this request up with HA core as it needs to happen in the integration level.  The app deals with sending data and reading data from the HA server. It has no control over what happens to an entity if the app did not send an update.

**Comment by ThomDietrich** [comment] 2022-10-01 16:47
As long as the app provides everything needed to make that decision, I would agree. Otherwise I think this is indeed deeply linked to the app (Android and iOS).

Anyhow, do you know which component is relevant here and who would be a suited developer to mention to look into this?

Please reopen the issue. This is a real "bug" in relation to the app, even though you might have limited control over it. We should still track it.

**Comment by dshokouhi** [comment] 2022-10-01 16:49
> Anyhow, do you know which component is relevant here and who would be a suited developer to mention to look into this?

its the `mobile_app` integration



> Please reopen the issue. This is a real "bug" in relation to the app, even though you might have limited control over it. We should still track it.

sorry the code for this change is not going to be done in the app so we will not be reopening this issue.  It is also not an issue but an enhancement so you need to take it up as a feature request.

**Comment by ThomDietrich** [comment] 2022-10-01 16:55
Certainly a bug from a product perspective. Open source projects often lack sensitivity for that.

Anyhow, thanks for pointing me in the right direction. I will raise an issue there.
