### ISSUE TITLE
SIP Project: Issue with H264 video codec, while VP8 codec works

### ISSUE THREAD

**Issue by pergolafabio** [home-assistant/android#2034] opened 2021-12-20 18:04 UTC
**Home Assistant Android version:**  
HA Beta 1792

**Android version:** 
Android 10

**Phone model:** 
Oneplus 6T 

**Home Assistant version:**
2012.12.x

**Description of problem:**
We are working on a SIP project with Asteriks, trying to get video support working... Some softphone clients are sening VP8 video codec, then video works in the Companion app... but if the orginator is sending h264 video codec, the call fails, below the logs wehere you can see the 
first call test 16:18 , with h264 => this fails
second call test 16:19 , with vp8 => this succeeds...

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
12-20 16:18:12.571 31654 31654 D PhoneWindow: setNavigationBarColor: ff171717
12-20 16:18:12.612 31654 31870 D WebviewActivity: External bus {"type":"config/get","id":3}
12-20 16:18:12.614 31654 31654 D WebviewActivity: externalBus({"id":3,"type":"result","success":true,"result":{"hasSettingsScreen":true,"canWriteTag":true,"hasExoPlayer":true}});
12-20 16:18:12.654 31654 31654 D WebviewActivity: Callback null
12-20 16:18:12.655 31654 31654 D WebviewActivity: Color from webview is "rgb(23, 23, 23)-SPACER-rgb(23, 23, 23)"
12-20 16:18:12.655 31654 31654 D WebviewActivity: Color from webview is "rgb(23, 23, 23)-SPACER-rgb(23, 23, 23)"
12-20 16:18:12.655 31654 31699 D WebViewPresenterImpl: Try getting color from webview color "rgb(23, 23, 23)".
12-20 16:18:12.655 31654 31699 I WebViewPresenterImpl: Found color -15263977.
12-20 16:18:12.661 31654 31698 D WebViewPresenterImpl: Try getting color from webview color "rgb(23, 23, 23)".
12-20 16:18:12.662 31654 31698 I WebViewPresenterImpl: Found color -15263977.
12-20 16:18:12.662 31654 31654 D PhoneWindow: setNavigationBarColor: ff171717
12-20 16:18:14.398 31654 31870 D WebviewActivity: External bus {"type":"haptic","payload":{"hapticType":"light"},"id":4}
12-20 16:18:14.399 31654 31654 D WebviewActivity: Processing haptic tag for light
12-20 16:18:14.734 31654 31654 E SensorManager: registerListenerImpl sensorName:Game Rotation Vector  Wakeup,isWakeUpSensor:true,callingApp: io.homeassistant.companion.android,callingPid:31654,callingUid:10243
12-20 16:18:14.925 31654 31654 E SensorManager: unregisterListenerImpl sensorName:Game Rotation Vector  Wakeup,isWakeUpSensor:true,callingApp: io.homeassistant.companion.android,callingPid:31654,callingUid:10243
12-20 16:18:24.317 31654 31844 W VideoCapabilities: Unsupported mime image/vnd.android.heic
12-20 16:18:24.319 31654 31844 W VideoCapabilities: Unsupported mime video/divx
12-20 16:18:24.319 31654 31844 W VideoCapabilities: Unsupported mime video/divx4
12-20 16:18:24.321 31654 31844 W VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
12-20 16:18:24.321 31654 31844 W VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
12-20 16:18:24.322 31654 31844 W VideoCapabilities: Unsupported mime video/x-ms-wmv
12-20 16:18:24.387 31654 31774 I AudioManager: In isBluetoothScoOn(), calling application: io.homeassistant.companion.android
12-20 16:18:24.387 31654 31774 I AudioManager: In startbluetoothSco(), calling application: io.homeassistant.companion.android
12-20 16:18:24.396 31654 31774 I AudioManager: In isSpeakerphoneOn(), calling application: io.homeassistant.companion.android
12-20 16:18:24.400 31654 31774 I AudioManager: In setMode(), mode: 3, calling application: io.homeassistant.companion.android
12-20 16:18:24.447 31654 31774 I libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x1, using default mask 0x10 based on channel count of 1)
12-20 16:18:24.461 31654 31774 I AudioRecord: createRecord_l(6553714): AUDIO_INPUT_FLAG_FAST successful; frameCount 0 -> 4096
12-20 16:18:24.464 31654 31654 E chromium: [ERROR:web_contents_delegate.cc(228)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
12-20 16:18:24.586 31654 31774 I AudioManager: In isBluetoothScoOn(), calling application: io.homeassistant.companion.android
12-20 16:18:24.586 31654 31774 E cr_media: Unable to stop BT SCO since it is already disabled
12-20 16:18:24.587 31654 31774 I AudioManager: In isSpeakerphoneOn(), calling application: io.homeassistant.companion.android
12-20 16:18:24.587 31654 31774 I AudioManager: In setMode(), mode: 0, calling application: io.homeassistant.companion.android
12-20 16:18:33.620 31654 31870 D WebviewActivity: External bus {"type":"config_screen/show","id":5}
12-20 16:18:33.640 31654 31654 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@d199e76



12-20 16:19:11.405 31654 31654 I Surface : opservice is null false
12-20 16:19:11.555 31654 31675 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@b72524d[WebViewActivity]
12-20 16:19:11.582 31654 31654 D UrlRepository: localUrl is: false and usesInternalSsid is: false
12-20 16:19:11.583 31654 31654 D UrlRepository: Using external URL
12-20 16:19:11.601 31654 31699 D SensorWorker: Updating all Sensors.
12-20 16:19:11.603 31654 31701 I WM-Processor: Moving WorkSpec (93b01dd3-c535-4c68-9d24-89750392514b) to the foreground
12-20 16:19:11.604 31654 31654 D LocBroadcastReceiver: Received location update.
12-20 16:19:11.606 31654 31654 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = false
12-20 16:19:11.606 31654 31654 D LocBroadcastReceiver: Last Location: 
12-20 16:19:11.606 31654 31654 D LocBroadcastReceiver: Coords:(50.9964134, 5.2475992)
12-20 16:19:11.606 31654 31654 D LocBroadcastReceiver: Accuracy: 13.724
12-20 16:19:11.606 31654 31654 D LocBroadcastReceiver: Bearing: 0.0
12-20 16:19:11.606 31654 31654 D LocBroadcastReceiver: Begin evaluating if location update should be skipped
12-20 16:19:11.606 31654 31654 D LocBroadcastReceiver: Received location that is 72 milliseconds old, 1640013551534 compared to 1640013551606 with source fused
12-20 16:19:11.606 31654 31654 D LocBroadcastReceiver: Duplicate location received, not sending to HA
12-20 16:19:11.628 31654 31654 I WM-SystemFgDispatcher: Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService (has extras) }
12-20 16:19:11.771 31654 31699 D SensorReceiver: Nothing to update
12-20 16:19:11.772 31654 31696 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=93b01dd3-c535-4c68-9d24-89750392514b, tags={ io.homeassistant.companion.android.sensors.SensorWorker } ]
12-20 16:19:11.774 31654 31654 I WM-SystemFgDispatcher: Stopping foreground service
12-20 16:19:12.906 31654 31654 E SensorManager: registerListenerImpl sensorName:Game Rotation Vector  Wakeup,isWakeUpSensor:true,callingApp: io.homeassistant.companion.android,callingPid:31654,callingUid:10243
12-20 16:19:13.029 31654 31654 E SensorManager: unregisterListenerImpl sensorName:Game Rotation Vector  Wakeup,isWakeUpSensor:true,callingApp: io.homeassistant.companion.android,callingPid:31654,callingUid:10243
12-20 16:19:14.047 31654 31870 D WebviewActivity: External bus {"type":"haptic","payload":{"hapticType":"light"},"id":6}
12-20 16:19:14.051 31654 31654 D WebviewActivity: Processing haptic tag for light
12-20 16:19:14.080 31654 31654 E SensorManager: registerListenerImpl sensorName:Game Rotation Vector  Wakeup,isWakeUpSensor:true,callingApp: io.homeassistant.companion.android,callingPid:31654,callingUid:10243
12-20 16:19:14.248 31654 31654 E SensorManager: unregisterListenerImpl sensorName:Game Rotation Vector  Wakeup,isWakeUpSensor:true,callingApp: io.homeassistant.companion.android,callingPid:31654,callingUid:10243
12-20 16:19:23.298 31654 31774 I AudioManager: In isBluetoothScoOn(), calling application: io.homeassistant.companion.android
12-20 16:19:23.299 31654 31774 I AudioManager: In startbluetoothSco(), calling application: io.homeassistant.companion.android
12-20 16:19:23.312 31654 31774 I AudioManager: In isSpeakerphoneOn(), calling application: io.homeassistant.companion.android
12-20 16:19:23.326 31654 31774 I AudioManager: In setMode(), mode: 3, calling application: io.homeassistant.companion.android
12-20 16:19:23.386 31654 31774 I libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x1, using default mask 0x10 based on channel count of 1)
12-20 16:19:23.404 31654 31774 I AudioRecord: createRecord_l(3114): AUDIO_INPUT_FLAG_FAST successful; frameCount 0 -> 4096
12-20 16:19:23.408 31654 31654 E chromium: [ERROR:web_contents_delegate.cc(228)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
12-20 16:19:23.508 31654 31774 I AAudio  : AAudioStreamBuilder_openStream() called ----------------------------------------
12-20 16:19:23.508 31654 31774 I AudioStreamBuilder: rate   =  48000, channels  = 2, format   = 5, sharing = SH, dir = OUTPUT
12-20 16:19:23.508 31654 31774 I AudioStreamBuilder: device =      0, sessionId = -1, perfMode = 12, callback: ON with frames = 192
12-20 16:19:23.508 31654 31774 I AudioStreamBuilder: usage  =      2, contentType = 0, inputPreset = 0, allowedCapturePolicy = 0
12-20 16:19:23.508 31654 31774 D         : PlayerBase::PlayerBase()
12-20 16:19:23.509 31654 31774 D AudioStreamTrack: open(), request notificationFrames = -8, frameCount = 0
12-20 16:19:23.514 31654 31774 I AudioTrack: createTrack_l(0): AUDIO_OUTPUT_FLAG_FAST successful; frameCount 0 -> 1536
12-20 16:19:23.514 31654 31774 D AudioTrack: Uid 10243 AudioTrack::setVolume left 1.000000 right 1.000000
12-20 16:19:23.514 31654 31774 W AudioStreamTrack: open() flags changed from 0x00000104 to 0x00000004
12-20 16:19:23.515 31654 31774 I AAudio  : AAudioStreamBuilder_openStream() returns 0 = AAUDIO_OK for s#1 ----------------
12-20 16:19:23.516 31654 31654 E chromium: [ERROR:web_contents_delegate.cc(228)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
12-20 16:19:23.517 31654 31774 D AAudio  : AAudioStream_requestStart(s#1) called --------------
12-20 16:19:23.517 31654 31774 D AudioTrack: ClientUid 10243 AudioTrack::start 
12-20 16:19:23.525 31654 31774 D         : PlayerBase::start() from IPlayer
12-20 16:19:23.525 31654 31774 D AAudio  : AAudioStream_requestStart(s#1) returned 0 ---------
12-20 16:19:23.525 31654 31671 D AudioStreamLegacy: onAudioDeviceUpdate() devId 2 => 2
12-20 16:19:23.677 31654 31760 I cr_MediaCodecBridge: create MediaCodec video decoder, mime video/x-vnd.on2.vp8
12-20 16:19:23.677 31654 31760 D MediaCodec:  name = video/x-vnd.on2.vp8
12-20 16:19:23.685 31654 32447 I OMXClient: IOmx service obtained
12-20 16:19:23.705 31654 32446 I MediaCodec: MediaCodec will operate in async mode
12-20 16:19:23.707 31654 31760 W MediaCodec: RETYR:0
12-20 16:19:23.707 31654 32446 D SurfaceUtils: connecting to surface 0x7b072c7010, reason connectToSurface
12-20 16:19:23.707 31654 32446 I MediaCodec: [OMX.qcom.video.decoder.vp8] setting surface generation to 32413697
12-20 16:19:23.707 31654 32446 D SurfaceUtils: disconnecting from surface 0x7b072c7010, reason connectToSurface(reconnect)
12-20 16:19:23.708 31654 32446 D SurfaceUtils: connecting to surface 0x7b072c7010, reason connectToSurface(reconnect)
12-20 16:19:23.709 31654 32447 I ExtendedACodec: setupVideoDecoder()
12-20 16:19:23.710 31654 32447 I ExtendedACodec: Decoder will be in frame by frame mode
12-20 16:19:23.751 31654 32447 D SurfaceUtils: set up nativeWindow 0x7b072c7010 for 640x480, color 0x7fa30c06, rotation 0, usage 0x20002900
12-20 16:19:23.760 31654 32447 W Gralloc3: allocator 3.x is not supported
12-20 16:19:23.776 31654 32447 D SurfaceUtils: set up nativeWindow 0x7b072c7010 for 576x480, color 0x7fa30c06, rotation 0, usage 0x20002900
12-20 16:19:23.789 31654 31843 D NdkImageReader: acquireImageLocked: Overriding buffer format YUV_420_888 to 0x7fa30c06.
12-20 16:19:23.796 31654 31654 W AudioManager: Use of stream types is deprecated for operations other than volume control
12-20 16:19:23.796 31654 31654 W AudioManager: See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
12-20 16:19:24.700 31654 31671 D AudioStreamLegacy: onAudioDeviceUpdate() devId 2 => 3001
12-20 16:19:24.700 31654 31671 D AudioStreamLegacy: onAudioDeviceUpdate() request DISCONNECT in data callback due to device change
12-20 16:19:24.701 31654 32443 D AudioStreamLegacy: checkForDisconnectRequest() mRequestDisconnect acknowledged
12-20 16:19:24.701 31654 32443 W AudioStreamLegacy: processCallbackCommon() data, stream disconnected
12-20 16:19:24.701 31654 32443 E AudioTrack: processAudioBuffer(3119): EVENT_MORE_DATA requested 1536 bytes but callback returned -1 bytes
12-20 16:19:24.702 31654 31774 D AAudio  : AAudioStream_requestStop(s#1) called
12-20 16:19:24.702 31654 31774 E AAudioStream: setState(1) tried to set to 9 but already DISCONNECTED
12-20 16:19:24.702 31654 31774 D AudioTrack: ClientUid 10243 AudioTrack::stop 
12-20 16:19:24.702 31654 31774 D AudioTrack: stop(3119): called with 51648 frames delivered
12-20 16:19:24.702 31654 31774 D         : PlayerBase::stop() from IPlayer
12-20 16:19:24.702 31654 31774 D AAudio  : AAudioStream_close(s#1) called ---------------
12-20 16:19:24.870 31654 31774 D AudioTrack: ClientUid 10243 AudioTrack::stop 
12-20 16:19:24.923 31654 31774 D AAudio  : AAudioStream_close(s#1) returned 0 ---------
12-20 16:19:24.925 31654 31774 I AAudio  : AAudioStreamBuilder_openStream() called ----------------------------------------
12-20 16:19:24.925 31654 31774 I AudioStreamBuilder: rate   =  48000, channels  = 2, format   = 5, sharing = SH, dir = OUTPUT
12-20 16:19:24.925 31654 31774 I AudioStreamBuilder: device =      0, sessionId = -1, perfMode = 12, callback: ON with frames = 192
12-20 16:19:24.925 31654 31774 I AudioStreamBuilder: usage  =      2, contentType = 0, inputPreset = 0, allowedCapturePolicy = 0

```

**Comment by dshokouhi** [comment] 2021-12-20 18:07
CC: @uvjustin in case he has any ideas on what could be the cause :)

**Comment by pergolafabio** [comment] 2021-12-20 18:22
thnx! :-)

**Comment by uvjustin** [comment] 2021-12-21 07:29
The issue is a bit unclear to me and I don't have any expertise here. Since it's going through the webview I would expect it to behave similar to a chrome browser. Perhaps it's a device specific issue? Have you tried on other devices? Maybe try a lower H.264 profile?

**Comment by pergolafabio** [comment] 2021-12-21 07:35
Hi,

thats the issue, most intercom devices only send h264 codec.... on a chrome browser on desktop it works fine
gonna test asap, what happens if i use the chrome browser on android


Other devices same behaviour

**Comment by pergolafabio** [comment] 2021-12-21 08:16
ok, tried on browser on android, that didnt work either
works only on browser on workstation it seems

soi not sure, if its indeed device related, maybe i need to add a codec driver on android?

**Comment by dshokouhi** [comment] 2021-12-21 13:34
Closing as the issue also exists in the browser on the device which means its not an app issue

**Closed by dshokouhi** 2021-12-21 13:34 UTC
Labels: bug, webview
