### ISSUE TITLE
Esphome 2022.9 new editor scroll

### ISSUE THREAD

**Issue by tiimsvk** [home-assistant/android#2905] opened 2022-09-22 19:04 UTC
**Home Assistant Android version:**
2022.9.1
**Android version:**
9
**Phone model:**
A8 samsung
**Home Assistant version:**
2022.9.6, 
Esphome 2022.9.1
**Last working Home Assistant release (if known):**

**Description of problem:**
No scrolling editor yaml in esphome addon.
Almost impossible to navigate in the editor.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2022-09-22 19:05
Can you reproduce the issue using chrome for android on the same device?

**Comment by tiimsvk** [comment] 2022-09-23 07:03
Yes, it makes the same error in the chrome browser as well.
When you touch the editor with your finger and then scroll, the editor does not move.
It is obvious that the new function of the slider in the corners makes a mistake.

**Comment by jpelgrom** [comment] 2022-09-23 10:47
Thanks for checking in Chrome! Because this issue also appears in the browser, it is not an app-specific issue but an issue for the ESPHome Editor instead. I see you've already found a related issue there so I'm going to close this one.

**Closed by jpelgrom** 2022-09-23 10:47 UTC
Labels: bug, question, webview
