### ISSUE TITLE
Internal url wont work

### ISSUE THREAD

**Issue by antoweb** [home-assistant/android#2602] opened 2022-06-10 19:34 UTC
**Home Assistant Android version:**
2022.0.6-full
**Android version:**
11
**Phone model:**
Xiaomi mi 10t
**Home Assistant version:**
2022.6.4
**Last working Home Assistant release (if known):**
Never
**Description of problem:**
Internal url wont work and receive an error. Same url in chrome browser work good

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![IMG_20220610_213410](https://user-images.githubusercontent.com/32364871/173137525-c91860eb-9116-4dc9-8b93-0e86a983544d.jpg)

**Additional information:**

**Comment by dshokouhi** [comment] 2022-06-10 19:39
I see the internal URL has `https` please note that the SSL certificate needs to be valid otherwise the app will not load the URL. If you have to accept the certificate in chrome then it won't work in the app. SSL certificates are usually only valid on the domain name.

**Comment by dshokouhi** [comment] 2022-06-10 19:41
Also double check if it loads when you click refresh URL, if you turned on prioritize internal try turning that off too (it is only meant for users who leave location off on their device)

**Comment by antoweb** [comment] 2022-06-10 19:47
Hi,
The certificate is wildcard public and valid. same used for external and internal, no need to accept in chrome because the cerificate is from a ca autoritative.. In my domain (personal domain) i have teo record one for external public url lime hasssio.mydomain.it abd ine for internal ip lime hassiolocal.mydomain.it.

Also click on refresh url home assistant load correctly

**Comment by dshokouhi** [comment] 2022-06-10 19:49
It sounds like an internal DNS issue then if internal URL fails to load with the same error in your screenshot. That is not an error the app can solve.



> Also click on refresh url home assistant load correctly

Did you enable prioritize internal URL? If so please disable it then.

**Comment by dshokouhi** [comment] 2022-06-10 20:18
> Why? The same url (internal) works good in chrome for android so cannot be a internal dns issue. The hostname is in a public zone but resolved with a private ip.

The app loads URLs just like chrome does, there is just additional logic as to which URL is to be used.

> If i turn off prioritize i cannot are sure that is used my internal url when i use my wifi ssid

URL switching occurs by the app reading the connected SSID. If you have location enabled and the app has permission (which happens when you enter your WiFi SSID) the app will automatically switch for you and you don't need to worry about it.

Prioritize Internal is meant for users who leave location turned off on their device, as a result the app cannot read the SSID and those users will need to click on the refresh button to get the page to load properly. The reason for the refresh is because those users need to cycle through their URLs as the last URL used may no longer work.

You can always check the logs to see which URL is being used as well.

**Comment by antoweb** [comment] 2022-06-10 20:22
> 



> > Why? The same url (internal) works good in chrome for android so cannot be a internal dns issue. The hostname is in a public zone but resolved with a private ip.
> 
> The app loads URLs just like chrome does, there is just additional logic as to which URL is to be used.
> 
Ok but wont work

> > If i turn off prioritize i cannot are sure that is used my internal url when i use my wifi ssid
> 
> URL switching occurs by the app reading the connected SSID. If you have location enabled and the app has permission (which happens when you enter your WiFi SSID) the app will automatically switch for you and you don't need to worry about it.
> 
> Prioritize Internal is meant for users who leave location turned off on their device, as a result the app cannot read the SSID and those users will need to click on the refresh button to get the page to load properly. The reason for the refresh is because those users need to cycle through their URLs as the last URL used may no longer work.
> 
> You can always check the logs to see which URL is being used as well.

Also turning off prioritize the first attempt fail

**Comment by dshokouhi** [comment] 2022-06-10 20:25
can you please attach the companion app logs so we can see what is going on? Just hide the domain name and any GPS data please. Also please reproduce the issue before grabbing the logs.

Configuration > Companion App > Show and share logs 

You can also click on 'Settings' in the pop-up and then go to Show and share logs

**Comment by antoweb** [comment] 2022-06-10 20:38
Log attached
[log-companion.txt](https://github.com/home-assistant/android/files/8882150/log-companion.txt)

**Comment by dshokouhi** [comment] 2022-06-10 20:51
I see in the log

```
06-10 22:27:35.361 14172 14172 D UrlRepository: Using internal URL
06-10 22:27:35.447 14172 14172 E WebviewActivity: onReceivedError: errorCode: -2 
```

which translates to:

https://developer.android.com/reference/android/webkit/WebViewClient#ERROR_HOST_LOOKUP

These are the errors the app cannot solve which normally points to something needing to be fixed on the host side. You can try taking a look at: https://companion.home-assistant.io/docs/troubleshooting/networking

If all else fails, maybe try starting fresh? Its possible something just needs to be cleaned up

https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by antoweb** [comment] 2022-06-12 16:15
Ok,
i have  read all network chapterbutnofindany solution. My installationa simply have a public dns name that point to a publicip and a public dns name that point to a private ip, both are in the same domain, for this rewason a wildcard certificate should work.  In fact from chrome browser both  domain names (public and private) works good but from Home Assistant Companion app not.

I have tried also uninstalling and reinstalling the app, and also in a new android phone.

nothing to do. problem still remain

**Comment by dshokouhi** [comment] 2022-06-12 16:35
The error message given by the android API is not one the app can/will solve, it points to a networking error. Even though Chrome works fine in this case Android WebView API returns an error for the host name.  That is an error for the client side to fix.

Try to bypass your local setup and do a straight connection to the local IP, does it work then?

**Comment by antoweb** [comment] 2022-06-12 16:45
Whit local ip the connection work also with chrome, with the app cant be work because there is not a valid certificate, remeber: my installation is ssl directly yo HA without reverse proxy, for this reason my HA listen directly to https

**Comment by dshokouhi** [comment] 2022-06-12 16:49
> For this reason i'm tring a public dns nane thath point to a private ip :-)

And that would be the reason as to why the webview is failing with cannot find host error.  This is not an error the app can solve as I had mentioned previously.  You will need to solve that error on your own and find the routing issue that causes the host lookup failure.

```
Server or proxy hostname lookup failed
```

Closing this issue as the error message is not one the app can fix.

**Closed by dshokouhi** 2022-06-12 16:49 UTC
Labels: bug

**Comment by antoweb** [comment] 2022-06-12 16:50
Sorry but why the same public dns name (that point to a private ip) works good in chrome ?
