### ISSUE TITLE
Doesn't register (Samsung) navigation gestures and so "clicks" in the app.

### ISSUE THREAD

**Issue by werra11** [home-assistant/android#2949] opened 2022-10-03 20:54 UTC
**Home Assistant Android version:**
2022.9.1-full
**Android version:**
Android 12 (OneUI 4.1)
**Phone model:**
Samsung Galaxy S22 Ultra 
**Home Assistant version:**
2022.9.7
**Last working Home Assistant release (if known):**
None
**Description of problem:**
When using gesture navigation on Samsung (3 options from the bottom, no side gestures) the app thinks I am clicking inside the app, this leads to opening menu's, toggeling switches, etc. See attached GIF.
**Traceback**
Not applicable
**Screenshot of problem:**
GIF: https://imgur.com/a/5XJgA6p
**Additional information:**
Doesn't seem to happen on Samsung Galaxy S8, Android 9, OneUI 1.0

**Comment by dshokouhi** [comment] 2022-10-03 21:24
duplicate of https://github.com/home-assistant/frontend/issues/10348

**Closed by dshokouhi** 2022-10-03 21:24 UTC
Labels: bug
