### ISSUE TITLE
Sensors and notifications stop working after few hours

### ISSUE THREAD

**Issue by kukulich** [home-assistant/android#976] opened 2020-09-24 22:09 UTC
**Home Assistant Android version:**
2.4.1

**Android version:**
10

**Phone model:**
Ulefone Armor X7 Pro

**Home Assistant version:**
0.115.2

**Last working Home Assistant release (if known):**
This is the first installation on this phone.

**Description of problem:**

There are two problems:
- Phone stops reporting sensor states after few hours.
- Notifications stop coming to the phone.

Everything starts working again when I open the app - but only for few hours, then it's stop working again.

I did not find anything on the phone that can cause this.

**Comment by dshokouhi** [comment] 2020-09-24 22:12
Please check that you have battery optimizations disabled for the application to prevent it from being killed in the background.  Did you leave the Sensor Worker notification channel enabled?

**Comment by dshokouhi** [comment] 2020-09-24 22:14
If you have not disabled the sensor worker notification channel and have disabled battery optimizations for the app then this would be a duplicate of #551

**Comment by kukulich** [comment] 2020-09-25 06:58
I hope I checked everything from the troubleshooting docs. I've tried to disable the battery optimizator completly. 

I see there's new release 2.5.0 so I'll check it and try everything again.

**Comment by dshokouhi** [comment] 2020-09-25 15:05
Closing as battery optimizations were not enabled, if you are still experiencing an issue after checking these things: 

https://companion.home-assistant.io/docs/troubleshooting/faqs/#location-is-not-updating-in-android-app

And double checkign that you did not turn off the sensor worker notification channel then please comment on #551

**Closed by dshokouhi** 2020-09-25 15:05 UTC
Labels: bug, question
