### ISSUE TITLE
Cannot remove device_tracker from Person

### ISSUE THREAD

**Issue by jgverweij** [home-assistant/android#2911] opened 2022-09-24 18:27 UTC
**Home Assistant Android version:** 2022.8.0-full

**Android version:** 11

**Phone model:** moto g8 power (XT2041-3)

**Home Assistant version:** 2022.9.6

**Last working Home Assistant release (if known):**?

**Description of problem:**
In Settings -> Persons after selecting a person, multiple device_trackers may be present. When pressing the 'cross' to remove a device, it seems that the field becomes emptied. However the input box stays visible (contrary to the experience in a browser on a pc), and the change is not saved.

So in a browser (Firefox) on a pc, the input box vanishes when deleting a device_tracker from a Person, and the change is saved.
But using the Companion app the input box becomes empty but stays visible, and the change is not saved.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:** Seems to be the same problem on iPhone / iPad: https://community.home-assistant.io/t/can-t-change-devices-that-belong-to-a-person/402831/3

**Comment by dshokouhi** [comment] 2022-09-24 19:01
I think this is a known frontend issue, you should be able to reproduce in chrome for Android

**Comment by dshokouhi** [comment] 2022-09-24 19:39
Duplicate of https://github.com/home-assistant/frontend/issues/13351

**Closed by dshokouhi** 2022-09-24 19:39 UTC
Labels: bug
