### ISSUE TITLE
URL is automatically stripped so I can't use redirects

### ISSUE THREAD

**Issue by Nightenom** [home-assistant/android#1805] opened 2021-10-19 12:45 UTC
**Is your feature request related to a problem? Please describe.**

I have hass instance at one house on a server that is connected to the router in my second house using OpenVPN. In my second house, I have a server (behind the router which has static public IP) used for MQTT etc, on this server I've made a URL redirect that uses nginx geo component - from `https://myserver.anywhere/redirect/hass` it goes at `http://10.0.0.2:8123/lovelace/0` or `http://10.0.1.6:8123/lovelace/0` which are both addresses of the same hass server mentioned above, but the first IP is only reachable at the first house and the second IP is only reachable at the second house.
The connection works properly and using it inside a browser is flawless.
If in app I set the URL to `https://myserver.anywhere/redirect/hass` then it gets stripped to `https://myserver.anywhere/` which obviously does not work as the redirect URL is not reached.

**Describe the solution you'd like**

Allow for full URLs and follow all redirects, then strip the last URL. If URL is not reachable also try to strip the URL just like now.

**Describe alternatives you've considered, if any**

Surely, my setup is somewhat weird, but it works in any browser, so why it shouldn't work in the app?

**Additional context**

Android 11, app version 2021.10.0-full

**Comment by dshokouhi** [comment] 2021-10-19 14:45
duplicate of #1651

**Closed as completed by dshokouhi** 2021-10-19 14:45 UTC
Labels: enhancement
