### ISSUE TITLE
Mobile app crashed after update 3.5

### ISSUE THREAD

**Issue by Anton-Ka** [home-assistant/android#4328] opened 2024-04-06 14:08 UTC
**Home Assistant Android app version(s):** 3.5

**Android version(s):** 7

**Device model(s):** Samsung SM-A310F

**Home Assistant version:** 2024.3.3

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

**Companion App Logs:**

```
I can't get log because app don't start normally
```

**Screenshot or video of problem:** 

https://github.com/home-assistant/android/assets/74901464/02d237da-590d-46bb-9893-a944ed026907

**Additional information:**
After auto update from play market app stop running.

**Comment by jpelgrom** [comment] 2024-04-06 14:10
Duplicate of #4323 - this is fixed in the next release and will be available soon

**Closed by jpelgrom** 2024-04-06 14:10 UTC
Labels: bug
