### ISSUE TITLE
more_info autoplay

### ISSUE THREAD

**Issue by tunerooster** [home-assistant/android#1368] opened 2021-02-20 14:50 UTC
First some background...

I have an Android tablet which I use as a wall mounted Home Assistant dashboard.  I have an automation which invokes more_info on the front door camera entity when motion is detected.  The effect is to be able to see who is at the front door from a distance without any required interaction.

The problem...

I have found that more_info works flawlessly when Home Assistant is run in Chrome (and indeed other browsers).

However, it *does not* work in Home Assistant Companion for Android.
The autoplay option, I can see, *is* specified, but the player pops up and display only the *PLAY* icon in the middle of the popup.

I would attribute this to "webkit" or "browser" behavior, outside the control of the HA App, except for the fact that it *works* in browsers, and also, in PWAs generated from Chrome etc... 

It seems to me that this issue would be a problem for a growing number of users who are implementing mounted dashboards with HA, so to me, this would be an important priority.  I do not want to have to run HA in a browser for several reasons I won't go into here.

Although I am using browser_mod.more_info for the automation, the problem occurs directly with the standard Picture Entity *and* Picture Glance cards when more_info is invoked manually by clicking on the camera image.

I am running Android 10 on a Teclast M40 tablet and Home Assistant Companion *beta-585-91fcd5b-full* installed from the Play Store and version 2021.2.1 of the server (hass) on gentoo with kernel 5.10.7 on an Intel machine.

Please tell me this is something that can be fixed, in time...

Thanks!

**Comment by dshokouhi** [comment] 2021-02-20 19:01
is android system webview up to date? I am not sure if we want to fix this given #979

**Comment by tunerooster** [comment] 2021-02-21 02:40
What is webview and how do I determine if it is up to date?  I use wifi in
my house, so data usage is not an issue.  What do you think?

**Comment by tunerooster** [comment] 2021-02-21 05:02
So I found out webview is an app and I have 88.0.4324.181 installed.

I take it that this is the underlying v8 engine being used by HA, correct?

I could try updating to canary webview...  Might that help?

**Comment by tunerooster** [comment] 2021-02-21 08:43
I tried installing Webview Canary, but for some reason it would not install.  I installed  Webview DEV (90.0.4420.2), and selecting it as the default system webview, but it made no difference.

I not entirely what the risk is with issue #979, but I would be perfectly happy with an option to allow/disable "immediate start of play on autoplay".  Would that resolve the conflict?

**Comment by tunerooster** [comment] 2021-02-21 10:06
I found this if it is relevant:
```
myWebView.getSettings().setMediaPlaybackRequiresUserGesture(false);

https://developer.android.com/reference/android/webkit/WebSettings.html#setMediaPlaybackRequiresUserGesture(boolean)
```

**Comment by dshokouhi** [comment] 2021-02-21 17:43
> I found this if it is relevant:
> 
> ```
> myWebView.getSettings().setMediaPlaybackRequiresUserGesture(false);
> 
> https://developer.android.com/reference/android/webkit/WebSettings.html#setMediaPlaybackRequiresUserGesture(boolean)
> ```

the default is `true` and we do not override this

> I'm not entirely clear on what the risk is with issue #979, but I would be perfectly happy with an option to allow/disable "immediate start of play on autoplay". Would that resolve the conflict?

The risk is that its a really bad bug and it needs to be fixed draining battery and causing huge spikes in data usage is not cool. We need to consider all use cases and the primary focus of the app is for a mobile phone and not a wall mounted tablet

**Comment by tunerooster** [comment] 2021-02-22 02:56
Are you saying you would not consider making it an option?

**Comment by tunerooster** [comment] 2021-02-25 13:58
Is anyone willing to consider adding a config option to:

```
myWebView.getSettings().setMediaPlaybackRequiresUserGesture(false);
```
allow playback without interaction?

**Comment by dshokouhi** [comment] 2021-02-25 14:07
@tunerooster your issue is 5 days old please have patience and wait. There are many issues that are around much longer. Also before we do this the other bug needs to be fixed first.

**Comment by tunerooster** [comment] 2021-02-26 02:33
Ok, thank you!

**Comment by jaytea33** [comment] 2021-03-22 07:46
+1 on this issue. I understand the bug is more of a priority but really hoping there's a workaround. Having to manually smash play to view my Amcrest camera's RTSP streams is throwing a wrench in my security setup. In addition to my phone I also use the app on my NVidia Shield to view my doorbell cam on my TV and like this automation is out the window

**Comment by tunerooster** [comment] 2021-10-14 21:28
I am using webrtc and it still doesn't work.  But only when the trigger is
via automation, eg the doorbell rings.  Does it work for you via automation?

**Comment by tunerooster** [comment] 2021-10-14 21:43
Also, I am not using more-info, I am browser_mod navigating to another view
which plays using webrtc (or I should say, doesn't play).    :)

**Comment by jaytea33** [comment] 2021-10-14 23:50
I can't comment on whether it works via automation but if it fails for you I'll likely experience the same result. Although that's odd it behaves differently for you when browsing manually vs with the automation. I gave up on monitoring for doorbell presses and triggering automations based on that since the Amcrest AD110 doorbell is so damn temperamental. I will probably circle back to it once I get around to throwing a tablet in the wall. I'm actually using this rather than stock WebRTC and since it's going through Frigate, it could behave slightly differently, but I couldn't say https://github.com/dermotduffy/frigate-hass-card

**Comment by dshokouhi** [comment] 2021-10-16 18:29
I am having some issues reproducing this issue using the latest beta version of the app. My amcrest, ring and generic cameras do indeed start auto playing when the more info panel is opened (i.e. I click on picture entity card to open the dialog).  What integration do you guys see this issue with? Or am I misunderstanding where this issue lies?

Another thing you can look at that will be helpful is look at the App Configuration logs and show me the output from this line:

https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt#L554

mine is: 

```
2021-10-16 11:28:04.767 5675-5675/? D/WebviewActivity: Current webview package com.google.android.webview and version 94.0.4606.85

```

**Comment by tunerooster** [comment] 2021-10-16 21:41
I am trying to recreate a problem from a simple case.  My case is more involved, but in creating a simpler case, I can reproduce "a" problem, not necessarily "my" problem.  It may or may not be the same issue, but it is easy to reproduce and fixing this in a general way could fix my problem as well.

All I do is:
- Create a new view
- Select "Panel mode" (may be irrelevant)
- Add a "Picture entity" card
- Select a camera entity (mine uses platform: ffmpeg with rtsp)
- Save it

Then when I click on the "picture" (i.e., to invoke "more_info"), the video screen appears, but with a PLAY arrow in the middle.  _It does not autoplay._  Clicking PLAY plays as expected.

Side note: Running in chrome **does autoplay**.

I am running the latest: beta-1534-9f3f552

Here is my Webview package info from the HA Companion Log:
```
10-16 15:29:11.985 24536 24536 D WebviewActivity: Current webview package com.google.android.webview and version 94.0.4606.85
```
Thank you for your help on this!

**Comment by dshokouhi** [comment] 2021-10-16 21:51
> * Create a new view
> * Select "Panel mode" (may be irrelevant)
> * Add a "Picture entity" card
> * Select a camera entity (mine uses platform: ffmpeg with rtsp)
> * Save it

even when I follow these steps the video auto plays the moment the more info panel is loaded, I wonder if its related to the integration. Are you able to try another camera integration like `generic`?

**Comment by dshokouhi** [comment] 2021-10-16 21:57
I just noticed that  this issue is missing the issue template.  Just out of curiosity which devices do you guys see this issue on? For reference I am on a Pixel 4 XL.

**Comment by tunerooster** [comment] 2021-10-16 22:40
I am seeing the issue on all my Android devices:

- Oneplus N10
- Teclast M40
- Teclast M20

**Comment by tunerooster** [comment] 2021-10-16 22:57
I have never used the generic camera platform, but I just set a test case up as follows:

```
  - platform: generic
    name: generic_garage
    still_image_url: http://garage:8080/cgi-bin/snapshot.sh
    stream_source: rtsp://garage/ch0_0.h264
```
However, when I click to get more_info, I just get a spinning circle in the video element.  Have you tried it with the ffmpeg camera platform?

**Comment by dshokouhi** [comment] 2021-10-16 23:00
> Have you tried it with the ffmpeg camera platform?

I have not, check to make sure the `rtsp` url works in other apps like VLC to confirm its correct.  The good news is that it is indeed attempting to auto play so that suggests the issue might be with the integration itself. I think I also saw up above the WebRTC card works too?

**Comment by dshokouhi** [comment] 2021-10-16 23:09
Lets ignore chrome desktop and only compare against chrome android please.  So you do not see the same behavior as my recording?

https://photos.app.goo.gl/SPG3t43FDEw7ZRqo8

**Comment by dshokouhi** [comment] 2021-10-16 23:12
As of now I see auto play working as expected, the video just starts playing as you can see in the video up above.  So adding that setting will have no impact based on what I am seeing.

**Comment by tunerooster** [comment] 2021-10-16 23:19
I can try to create a simple case using automation and webrtc if you are willing to try to reproduce via this avenue.

**Comment by tunerooster** [comment] 2021-10-16 23:23
PS, Does it work for you using the ffmpeg camera platform?

**Comment by dshokouhi** [comment] 2021-10-16 23:44
@tunerooster ok try out the debug APK from https://github.com/home-assistant/android/actions/runs/1350185048 it will install side by side the production version of the app. Once you login to HA go to App Configuration and turn on the Auto play toggle. Hope it works for you! 🤞

**Comment by tunerooster** [comment] 2021-10-17 00:41
WOW!  It works!  ...at least on the first device I tested it on.  I will install it on the other devices and test and if they all work I will close this issue!

THANK YOU SO MUCH FOR YOUR WORK ON THIS

Will you add this to the production release, e.g, in the next beta, or what?

When I install the "released" version, will the debug version automatically go away?

Best regards!

**Comment by tunerooster** [comment] 2021-10-17 00:49
All of a sudden, it is no longer working...  I tested it five time in a row with it working.  I am in the process of troubleshooting how/why.  I will keep you posted.

**Comment by tunerooster** [comment] 2021-10-17 01:00
I have a sinking feeling that I was testing the Webapk version, that I somehow had it running in the background and it got brought forward, not the Companion version. 

As I mentioned, it works when I create a Webapk (i.e., "Add to Home Screen" from the chrome menu).

I will try it on my other devices just to be sure.  I apologize for the confusion.  I was sure I was testing the Companion because I had to re-login and set up the Autoplay Option.  In any case I will continue testing...

**Comment by dshokouhi** [comment] 2021-10-17 01:17
try restarting the device?

We are setting the API to whatever the state of the toggle is

https://github.com/home-assistant/android/pull/1792/files#diff-76bbedb2918a5db79c7070e9bb2e01d9241388745f60b0719c0d1f74123d89bdR220

**Comment by tunerooster** [comment] 2021-10-17 02:37
I did a hard restart, but no luck.

I don't know the code, but from the link you provided, I can't see where
```
setMediaPlaybackRequiresUserGesture(false);
```
is called.

Are you sure it is being called somewhere with a value of "false"?
or does this supposedly do the same thing:
```
settings.mediaPlaybackRequiresUserGesture = presenter.isAutoPlayVideoEnabled()
```
I uninstalled all versions, including the Webapk and apk-full-debug.apk.  I reinstalled apk-full-debug.apk so it is the only HA app on the device.  I logged in and DID NOT SET THE AUTOPLAY option.  Low and behold, it works!  I ran it multiple times, restarting the app after a force stop, cleared the cache, and again without restarting and it has not failed yet.

Next, I SET the AUTOPLAY Option, and now it fails.  So I turn AUTOPLAY back OFF, and it works.  It seems that the tense of the autoplay option is backwards.

Can you investigate this?

I am however **thrilled** that it seems like it will work in the end!

**Comment by dshokouhi** [comment] 2021-10-17 02:43
Oh I need to switch the condition my bad, will update the PR in a bit

**Comment by dshokouhi** [comment] 2021-10-17 03:05
new apk to try :) https://github.com/home-assistant/android/actions/runs/1350499886

**Comment by dshokouhi** [comment] 2021-10-17 16:20
> I will expect to see this in the Play Store next Saturday.

given its been reviewed by then and there were no comments to address etc...



> I assume I will need to reinstall it manually. Being a debug version, I expect it will not be auto-installed.

if you have the production/beta version installed already it will update as usual, the debug version is treated like a separate app and will not behave like that so you can safely remove it.

**Comment by dshokouhi** [comment] 2021-10-17 23:05
Wait for this issue to close and if the PR is merged then you can install the next beta release or you can sign up for the beta releases and just wait until it's ready

**Comment by dshokouhi** [comment] 2021-10-18 02:52
Ok so just wait until the PR is merged then following Saturday it will be in the play store. You can also grab the APK from the releases section on GitHub once the PR had been merged to get it as soon as possible.

**Closed** 2021-10-20 22:17 UTC
