### ISSUE TITLE
Upon clicking Settings -> Devices & services, the app crashes

### ISSUE THREAD

**Issue by TheCarpetMerchant** [home-assistant/android#4882] opened 2024-12-05 19:51 UTC
**Home Assistant Android app version(s):** 2024.10.3-full

**Android version(s):** 13

**Device model(s):** A55 5G

**Home Assistant version:** Don't know where to find it, Raspberry 4 version

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
Upon clicking Settings -> Devices & services, the app crashes.

**Companion App Logs:** Not sharing since it includes location data, apparently. Please provide anonymized logging. Having seen the logs, it seems they get deleted upon restart of the app and this is a crash issue anyway.

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2024-12-05 19:52
Will be fixed in 2024.12.1 which was just submitted to the play store

**Closed by dshokouhi** 2024-12-05 19:52 UTC
Labels: bug

**Comment by edgimar** [comment] 2024-12-08 20:03
@dshokouhi, is there a way to reference the specific changes / situation related to this problem, to make it easier to avoid it in the future?

**Comment by dshokouhi** [comment] 2024-12-08 20:05
> to make it easier to avoid it in the future?

join the app beta, its already fixed there or wait for Google to approve our build

**Comment by edgimar** [comment] 2024-12-08 20:08
> > to make it easier to avoid it in the future?
> 
> join the app beta, its already fixed there or wait for Google to approve our build

The reason for my inquiry is for the sake of future development / developers.  Pointing to an entire new release doesn't explain the specific factor(s) that caused the crash, which makes it easier to repeat the mistake in the future.  Is there a particular commit or two that corrected the issue?

**Comment by dshokouhi** [comment] 2024-12-08 20:13
> Pointing to an entire new release doesn't explain the specific factor(s) that caused the crash, which makes it easier to repeat the mistake in the future. Is there a particular commit or two that corrected the issue?

The crash is related to a new feature for connected Improv Wi-Fi devices. Some devices for some reason report they dont have a bluetooth adapter and it caused the app to crash unexpectedly. The PR that fixed the issue is: https://github.com/home-assistant/android/pull/4740

There is no real way to avoid it other than updating so the app does not crash in these edge cases, I say edge case because the dev team was unable to reproduce it at the time.
