### ISSUE TITLE
SimpleIcons disappear from Lovelace UI and Sidebar.

### ISSUE THREAD

**Issue by FeromonDE** [home-assistant/android#835] opened 2020-08-27 21:10 UTC
**Home Assistant Android version:**
2.21-29-g5ee23a7-303-full
**Android version:**
Emui 10 Android 10
**Phone model:**
Huawei Mate 20
**Home Assistant version:**
0.114.4
**Last working Home Assistant release (if known):**
not known
**Description of problem:**
SimpleIcons disappear from Lovelace UI and Sidebar.
**Traceback (if applicable):**

```
no
```

**Screenshot of problem:**
![Screenshot_20200827_225520_io homeassistant companion android](https://user-images.githubusercontent.com/18047972/91495008-1f9a7a00-e8ba-11ea-8d0e-f121ff06a6e0.jpg)
![Screenshot_20200827_225525_io homeassistant companion android](https://user-images.githubusercontent.com/18047972/91495011-20cba700-e8ba-11ea-8a4b-e867f2520a4b.jpg)

**Additional information:**
Problem does not exist in Google Chrome Mobile.

**Comment by dshokouhi** [comment] 2020-08-27 21:12
Is `simpleicons` a custom integration or something?

**Comment by ludeeus** [comment] 2020-08-27 21:13
It is https://github.com/vigonotion/hass-simpleicons

**Comment by FeromonDE** [comment] 2020-08-27 21:23
> It is https://github.com/vigonotion/hass-simpleicons

Yes

**Comment by dshokouhi** [comment] 2020-08-27 21:29
This seems to be a caching issue, I just added `si:gatsby` and it loaded in the emulator.  Try to clear app cache and see if that works.

![image](https://user-images.githubusercontent.com/1634145/91496853-bbec5e80-e871-11ea-9a1e-c9dbe48bda6c.png)

**Comment by JBassett** [comment] 2020-08-27 21:30
Can you replicate on Android's Chrome browser?

**Comment by FeromonDE** [comment] 2020-08-27 21:34
> This seems to be a caching issue, I just added `si:gatsby` and it loaded in the emulator. Try to clear app cache and see if that works.
> 
> ![image](https://user-images.githubusercontent.com/1634145/91496853-bbec5e80-e871-11ea-9a1e-c9dbe48bda6c.png)

After clearing app cache it load, until i force stop the app.

**Comment by FeromonDE** [comment] 2020-08-27 21:35
> Can you replicate on Android's Chrome browser?

No, there is no Problem on Android's Chrome.

**Comment by dshokouhi** [comment] 2020-08-27 21:36
Just tested it on my Pixel 4 XL and even if I force stop the app and open it the icon is still there.

![image](https://user-images.githubusercontent.com/1634145/91497292-9ca20100-e872-11ea-8f99-b33594f7a49d.png)

**Comment by FeromonDE** [comment] 2020-08-27 21:44
> Just tested it on my Pixel 4 XL and even if I force stop the app and open it the icon is still there.
> 
> ![image](https://user-images.githubusercontent.com/1634145/91497292-9ca20100-e872-11ea-8f99-b33594f7a49d.png)
Hmm... 
I even reinstalled but to no avail. Problem still exist.

**Comment by dshokouhi** [comment] 2020-08-27 21:48
can you check that android system webview is up to date?

**Comment by FeromonDE** [comment] 2020-08-27 21:58
> can you check that android system webview is up to date?

85.0.4183.81 25.08.20

**Comment by dshokouhi** [comment] 2020-08-27 22:01
I was able to reproduce this on a desktop in Chrome incognito mode.  This is probably an issue with the custom integration itself.  Notice the missing icon in the sidebar next to `testing`

![image](https://user-images.githubusercontent.com/1634145/91499387-30c19780-e876-11ea-8fc5-6bec5a0199c0.png)

**Comment by FeromonDE** [comment] 2020-08-27 22:05
There is no Problem if i switch from Wifi to 4G.
I dont understand. Why?

**Comment by dshokouhi** [comment] 2020-08-27 22:10
This is a caching issue and since I saw it on my desktop its either an issue with the HA frontend (which @ludeeus would know I think :P ) or an issue with the custom integration.

**Comment by ludeeus** [comment] 2020-08-27 22:17
Most likely the integration, if you look at the screenshots, you see the hacs logo, that is a custom icon as well and that works

**Comment by FeromonDE** [comment] 2020-08-27 22:18
Sorry. There is a Problem on Android's Chrome too. :(

**Comment by FeromonDE** [comment] 2020-08-27 22:19
> Most likely the integration, if you look at the screenshots, you see the hacs logo, that is a custom icon as well and that works

Yes, Icons from mdi works fine.

**Comment by dshokouhi** [comment] 2020-08-27 22:20
@FeromonDE please open an issue with the custom integration, going to close this one now.

**Comment by ludeeus** [comment] 2020-08-27 22:20
mdi is shipped with the frontend, simple icon's and the hacs logo is not

**Closed by dshokouhi** 2020-08-27 22:20 UTC
Labels: bug, webview
