### ISSUE TITLE
websocket handshake error with Android 10 (HUAWEI) but not with Android 12 (xiaomi)

### ISSUE THREAD

**Issue by math322** [home-assistant/android#3309] opened 2023-02-04 13:19 UTC
**Home Assistant Android version:**

Home Assistant/2023.1.1-3124

**Android version:**

Android 10

**Phone model:**

Huawei

**Home Assistant version:**

Home Assistant 2023.1.6
Frontend 20230110.0 - latest

**Last working Home Assistant release (if known):**

-

**Description of problem:**

Websocket connection handshake failed and random fallback to api/webhook

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
-
```

**Screenshot of problem:**

-

**Additional information:**

I use a reverse proxy to connect to my HA instance with a Android 12 phone. Now i tried to use a phone with Android 10 and it failed badly. The app says there is a connection problem and i can press retry. After some random time it will finally connect to the HA instance or not, just random. Digging deeper into this problem and comparing the reverse proxy logs and the http traffic to the HA instance from the 2 phones i finally found the problem.

The main source is a websocket handshake error with the HA instance. Randomly the phone switched to the webhook api and the app was running. I can't figure out why or when this switchover from websocket to webhook happens, for me its just random.

Digging deeper into the websocket handshake traffic i saw that the Android 12 phone always changed the "Sec-WebSocket-Key" but the Android 10 phone used always the same key:

```
Sec-WebSocket-Key: MDAwMDAwMDAwMDAwMDAwMAo=
```

and the response from the HA instance was:

```
Handshake error: 'MDAwMDAwMDAwMDAwMDAwMAo='
```

The base64 encode shows a raw key of "0000000000000000" ...

Here is a full anon request header from the Android 10 phone:

```
GET /api/websocket HTTP/1.1
Host: <ANON>
pragma: no-cache
cache-control: no-cache
user-agent: Mozilla/5.0 (Linux; Android 10; <ANON> Build/HUAWEI<ANON>; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.118 Mobile Safari/537.36 Home Assistant/2023.1.1-3124 (Android 10; <ANON>)
origin: <ANON>
sec-websocket-version: 13
accept-encoding: gzip, deflate
accept-language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
sec-websocket-extensions: permessage-deflate; client_max_window_bits
Forwarded: <ANON>
X-Forwarded-For: <ANON>
X-Host: <ANON>
X-Forwarded-Host: <ANON>
X-Forwarded-Proto: https
Sec-WebSocket-Key: MDAwMDAwMDAwMDAwMDAwMAo=
Upgrade: websocket
Connection: close, upgrade
```

And from the Android 12 phone:

```
GET /api/websocket HTTP/1.1
Host: <ANON>
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Linux; Android 12; <ANON> Build/SKQ1.211006.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.85 Mobile Safari/537.36 Home Assistant/2023.1.1-3124 (Android 12; <ANON>)
Upgrade: websocket
Origin: <ANON>
Sec-WebSocket-Version: 13
Accept-Encoding: gzip, deflate
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
Sec-WebSocket-Key: <ANON>
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Forwarded: <ANON>
X-Forwarded-For: <ANON>
X-Host: <ANON>
X-Forwarded-Host: <ANON>
X-Forwarded-Proto: https
Connection: close, upgrade
```

If you need more information's let me know.

**Comment by math322** [comment] 2023-02-04 14:40
Update:

The key is actually:

```
b'0000000000000000\n'
```

and not 16 bytes long, this will raise the error in aiohttp/web_ws.py line 192

**Comment by dshokouhi** [comment] 2023-02-04 16:36
Where are the companion app logs?

**Comment by math322** [comment] 2023-02-04 17:54
There is the log from the app

![image](https://user-images.githubusercontent.com/71439852/216782012-c7267032-deda-4aad-b1c7-07feec39bc63.png)

**Comment by dshokouhi** [comment] 2023-02-04 18:06
That log does not look complete. Make sure to reproduce the issue and grab the logs again. The app does not switch to websocket. All the APIs are used for many different features. We use websocket for somethings and webhook for others. Try to bypass the reverse proxy and see if it works to rule out a proxy configuration issue.

**Comment by math322** [comment] 2023-02-04 18:20
There is only one time i see the popup to enter the settings, i tried it twice and the log is not different. No clue why there is no simple menu or button to enter the settings. Anyway i have only limited access to the phone.

**Comment by dshokouhi** [comment] 2023-02-04 18:26
> No clue why there is no simple menu or button to enter the settings.

Settings > Companion App > Show and Share logs

without the full logs when the issue happens we will not be able to help

If the logs are always the same then there might be an issue with how your device reads logcat, we will need the logcat logs form when the issue occurs.

**Comment by math322** [comment] 2023-02-04 19:32
Yes, i will try it but it seems something is wrong with the phone or the "huawei ws lib". I tried a Android 10 emulator and it worked, both, direct and over the proxy. The huawei phone also produce lower case html headers, what a bs bingo ...

**Comment by math322** [comment] 2023-02-04 19:38
I also "fixed" the aiohttp/web_ws.py to accept the wrong key size (overwrite the variable with a correct key) and the connection was established. Basically the App works ...

**Comment by dshokouhi** [comment] 2023-02-04 19:43
So you fixed it by making a change in HA core? Interesting

**Comment by math322** [comment] 2023-02-04 20:27
This was a quick and dirty hack ;-)

Did the android app use the android system ws implementation or did they use a native one? In the first case i would guess it's the self made buggy huawei implementation because the us export rules. In the worst case the phone is compromised but this is not very likely.

**Comment by dshokouhi** [comment] 2023-02-05 04:34
> Did the android app use the android system ws implementation or did they use a native one?

We are using `okhttp` library which is fairly popular and comes recommended by Google

**Comment by dshokouhi** [comment] 2023-03-01 19:24
Going to close this issue as it looks like the fix was done in the HA core side.

**Closed by dshokouhi** 2023-03-01 19:25 UTC
Labels: bug, question
