### ISSUE TITLE
Change tab sliding left or right

### ISSUE THREAD

**Issue by McGiverGim** [home-assistant/android#549] opened 2020-04-09 18:48 UTC
**Is your feature request related to a problem? Please describe.**
It seems slow to me to search the tab in lovelace and press it, specially when the tab is out of the screen and I need to press the arrows.

**Describe the solution you'd like**
My instinct says that sliding right or left I will move to the earlier/next tab. But nothing happens...

**Describe alternatives you've considered, if any**
None. Is an additional feature to what we have.

**Additional context**
None.

**Comment by dshokouhi** [comment] 2020-04-09 18:51
duplicate of #202 #225 #328 and #315

**Closed by dshokouhi** 2020-04-09 18:51 UTC
Labels: enhancement
