### ISSUE TITLE
Heartbeat sensor / connection home sensor

### ISSUE THREAD

**Issue by Hellis81** [home-assistant/android#4454] opened 2024-06-12 12:49 UTC
**Is your feature request related to a problem? Please describe.**

No, it's an enhancement.

**Describe the solution you'd like**

I would like a heartbeat sensor that wither just ticks up 1, 2, 3, etc. or if it's easier just places a bunch of random characters as the state every time sensors update.
This could then be used in an automation with `for: 5 minutes` as trigger as an example that would trigger when the heartbeat sensor does not update anymore. 
The action could be send a whatsapp message to yourself and tell you the app has crashed or some how lost connection.

**Describe alternatives you've considered, if any**

Current sensors could be stale for a good reason therefore I don't think there are any alternatives.

**Additional context**

None.

**Comment by dshokouhi** [comment] 2024-06-12 14:28
duplicate of https://github.com/home-assistant/android/issues/1033

**Closed by dshokouhi** 2024-06-12 14:28 UTC
Labels: enhancement

**Comment by Hellis81** [comment] 2024-06-12 14:39
#1033 seems to be the other way around.
That request is to know when your HA server is down.
This request is to know when the phone is down/unreachable

**Comment by Hellis81** [comment] 2024-06-12 14:43
As I wrote in the first post.
If the app creates a sensor that it changes every minute or 5 or 15 whichever you chose.
When this state has been stale in HA server for more than the selected time then we know the connection is lost

**Comment by dshokouhi** [comment] 2024-06-12 14:48
you can use the device tracker `last-changed` or `last-updated` attributes to decipher that. Or any sensor that you know that updates frequently like battery level?
