### ISSUE TITLE
switching between internal and external connection url

### ISSUE THREAD

**Issue by kkplein** [home-assistant/android#1361] opened 2021-02-12 12:14 UTC
Latest android companion app. I would like to ask:

Is switching between the internal & external URL supposed to work 'automatically'?

I'm running HA from my pixel 4a, and I can connect to both internal/external URLs fine, but switching between the two requires me to shutdown the HA app.
When leaving the Home Network Wifi, th HA app gives: "Connection lost. Reconnecting..." until I shutdown the HA app and start it again.

This happens in both directions:
- coming home after the phone switches to the wifi
- leaving the house the phone switches to 4G

If this is a bug (which I believe it is): Is there anything I can do to help and solve this?
(or is this working for others, in which case I will close this bug report again)

**Comment by dshokouhi** [comment] 2021-02-12 20:11
So the app should actually do the switch for you the next time you launch the app.  Meaning that if you had the app open during that time it won't switch until you opened  the app the next time.  We rely on android to tell us if the focus has changed or not so we can properly reload the interface

We just had a PR merged that actually lets the user switch between URL's when one of them fails, this will be in the next beta.  When you see the connection lost message do you get a prompt?

Also next time please do not delete the issue template all requested information is important to help you out.

**Comment by kkplein** [comment] 2021-02-15 08:39
Apologies for remiving the issue. I wanted to ask first if this was actualy supposed to work.
Anyway: I am NOT getting a prompt to switch between the two URLs. Perhaps that explains.
I have now made the two URLs identical (inside and outside the same URL:port) and even then HA looses the connection, when switching wifi from on to off, or the other direction. Restarting the app confirms that actually both URLs DO work, so it's really somethign related to the switch over.
Looking forward to te next beta, to check if the button does work. How can I get access to it..?

**Comment by dshokouhi** [comment] 2021-02-15 17:58
> Apologies for removing the issue template. I wanted to ask first if this was actually supposed to work.

We are still missing a lot of information like what app version you are on, what HA version you are on etc...  You skipped over alot of that.


> Looking forward to the next beta,

What beta version are you on? and please keep in mind the app has its own beta version separate from HA.  Both versions that are requested in the issue template are important.

**Comment by kkplein** [comment] 2021-02-16 08:05
Hi, ok, here is the filled out form:

- Make sure you run the latest version of the Android app
2021.1.1-full

- Make sure you run the latest version of Home Assistant
hassio on pi4: core-2021.2.3 / supervisor-2021.02.9

- Make sure to check the Companion docs for troubleshooting and configuration: https://companion.home-assistant.io/
Done.

**Home Assistant Android version:**
answered.

**Android version:**
11

**Phone model:**
Pixel 4a

**Home Assistant version:**
answered

**Last working Home Assistant release (if known):**
n/a

**Screenshot of problem:**
Attached

**Additional information:**
None.
![WhatsApp Image 2021-02-16 at 09 03 55](https://user-images.githubusercontent.com/5812542/108034605-09ce6c00-7036-11eb-9c32-1acd4b284a1d.jpeg)

**Comment by dshokouhi** [comment] 2021-02-16 13:40
Ok you are actually not getting the pop-up so this is a separate issue and not related to the URL switching.  This is the HA frontend unable to reconnect itself.  Do you see the same behavior in chrome for android?  I have a feeling this is not an app issue but something that needs to be resolved by the HA frontend.

**Comment by kkplein** [comment] 2021-02-16 14:40
Ok, I find it surprising to read that this could be about the HA frontend. Anyway: Chrome for android just gives a very short "connection lost, reconnecting", and poof: reconnected again.

**Comment by dshokouhi** [comment] 2021-02-16 18:34
So the app does not do anything here other than rendering the web page.  This connection lost message is something the HA frontend will show when it thinks its disconnected.  The apps pop-up is dependent on the HA [external bus](https://developers.home-assistant.io/docs/frontend/external-bus) messaging system to tell us its disconnected, at that point the app knows to handle things and that is where the beta fix is located.  In your screenshot everything is still the HA frontend so this bug should actually be opened over there.  If you want to try the latest android app beta you can do so [here](https://play.google.com/apps/testing/io.homeassistant.companion.android).

The pop-up that comes from the app will look like: 

![image](https://user-images.githubusercontent.com/1634145/108106118-63d52e80-7042-11eb-942e-5f3cc9a646ca.png)

**Comment by dshokouhi** [comment] 2021-02-26 02:52
Closing since the pop-up is now in the latest production version, if you still have an issue please comment back and be precise on steps to reproduce

**Closed by dshokouhi** 2021-02-26 02:52 UTC
Labels: bug

**Comment by Gifford47** [comment] 2024-03-23 10:08
hey there! @dshokouhi @kkplein 

the same issue exists also in current version on android. i have two different URLs. The internal is "mydomain.de" and the external "mydomain.de:8123". If i leave my home wlan, the connection is lost and the app doesn´t reconnect until i close it. It appears the above pop-up but nothing changes with these options. After closing the app it connects to the external URL when i`m connected to GSM.
If i dont close the app and reconnect to my home wlan, the app connects to homeassistant successfully. so i think the app never tries to connect to the external URL.
The issue is exists at least for one year for me.

How is the connection logic behind the app? do i have a mistake in my config?

Homeassistant: 2024.3.3
Companion App: 2024.1.5-full

![screen2](https://github.com/home-assistant/android/assets/49484063/59a5dde1-5849-4667-bd5a-aa2f9a6ea4a3)
![screen1](https://github.com/home-assistant/android/assets/49484063/10927a69-3bb4-4c25-807f-99498cc6bbc2)

**Comment by dshokouhi** [comment] 2024-03-23 13:54
@Gifford47 this issue is 3 years old. Please create a new issue and fill out the issue template.
