### ISSUE TITLE
Alarm time in sensor differs from the alarm application

### ISSUE THREAD

**Issue by Chuckame** [home-assistant/android#3835] opened 2023-08-31 23:35 UTC
**Home Assistant Android app version(s):**
2023.8.2-full
**Android version(s):**
11 RKQ1.200826.02
Miui 12.5.6.0
**Device model(s):**
Xiaomi mi note 10 lite
**Home Assistant version:**
2023.3.3
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
The alarm time is not the same as the alarm application time expected. 

While doing the ticket, the "switch point" when the time step of 15 minutes is when I'm reaching the "in 1 hour" on the alarm ui. 

- when alarm is in strictly less than 1h, then the time is 15 minutes ahead the expected time
- when it's at least 1h after the current time, the the reported time is 1h ahead the expected time. 

All the checks confirm the same value between app companion logs and home assistant sensor. The problem seems during parsing the ts from the NEXT_ALARM_CLOCK_CHANGED intent, or the intent itself (some xiaomi fun?) 

The time is set by package `com.android.deskclock`

**Companion App Logs:**

```
D SensorReceiver: Received intent: android.app.action.NEXT_ALARM_CLOCK_CHANGED
D NextAlarm: Next alarm is scheduled by com.android.deskclock with trigger time 1693549800000
```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2023-08-31 23:38
duplicate of #1526 #3451 and a few others as well.

unfortunately Xiaomi apps are known to send incorrect times to the API and we cannot control that nor skip it. The only recommendation is to use another app like Google Clock or Sleep as Android as those apps are known to send real updates ot the API

**Closed by dshokouhi** 2023-08-31 23:38 UTC
Labels: bug

**Comment by Chuckame** [comment] 2023-08-31 23:47
Wow, sorry I searched but surely with the bad words, what a common issue 😮
