### ISSUE TITLE
Companion app crashes when hitting Add Integration button

### ISSUE THREAD

**Issue by tramperb** [home-assistant/android#4782] opened 2024-11-03 05:35 UTC
If you are reporting an issue for Wear OS please list both devices for the below 3 fields -->
**Home Assistant Android app version(s):**
2024.10.3-full
**Android version(s):**
V13
**Device model(s):**
Samsung S6lite (SM-P610)
**Home Assistant version:**
2024.10.4
**Last working Home Assistant release (if known):**
Did previously work but can't be certain of version
**Description of problem, include YAML if issue is related to notifications:**
In Settings - Devices & Services, when I hit '+ Add Integration' button, companion app crashes.
This occurs on a Samsung S6 lite tablet running Android v13 (latest for this device).  However, the crash does not occur on this device when accessing HA through a browser.  It does not occur when using the companion app on phones running Android V14 and V13.  I've restarted the tablet multiple times (inc power off, restart).  I've deleted & reloaded vanilla companion app - still the same crash.
I have added integrations to HA from this tablet previously (although not for quite a few months).

**Companion App Logs:**  As the app crashes, restarting the app clears the troubleshooting log.  Crash reporting was enabled so maybe useful logs were uploaded?

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by jpelgrom** [comment] 2024-11-03 06:15
This sounds like a duplicate of #4761. Would you be willing to try the app beta to see if that resolves the issue for you as well?

**Comment by tramperb** [comment] 2024-11-03 06:30
Oh, sorry I didn't see the bug report #4761 (although I looked !).  Reading #4740 I see this comment "Also added a quick check in case the issue is caused by no BLE support but that seems unlikely" so I checked my device and bluetooth was disabled.  I enabled bluetooth and the bug is resolved !  So, yes, the crash only occurs if bluetooth is disabled.
Beta not needed for me but I can load it if you wish - please advise.

**Comment by jpelgrom** [comment] 2024-11-03 06:33
> Also added a quick check in case the issue is caused by no BLE suppor

This referred to a device with no Bluetooth at all - Bluetooth off was tested and already had a check in place but apparently not good enough for your device.

If the workaround of turning Bluetooth on works for you that's fine, no need to install the beta. I expect it to come to release as a stable in the coming weeks.

**Comment by tramperb** [comment] 2024-11-03 06:37
Great - thanks for the _very_ swift resolution !

**Closed** 2024-11-03 06:40 UTC
Labels: bug
