### ISSUE TITLE
When Two Last Notification States Are Reported at the Same Time One of Them Is Ignored

### ISSUE THREAD

**Issue by ars4l4n** [home-assistant/android#4487] opened 2024-06-29 18:25 UTC
**Home Assistant Android app version(s):** 2024.6.1-full

**Android version(s):** 8, 12

**Device model(s):** Samsung Galaxy S7, Google Pixel 3

**Home Assistant version:**
Core 2024.6.4
Supervisor 2024.06.2
Operating System 12.4

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:** When I set two Calendar notifications at the same time the Companion App only reports one of them to HA, according to HA's History page. 

**Companion App Logs:**

```
6-29 20:21:00.294 22773 22773 D SensorReceiver: Received intent: android.intent.action.SCREEN_ON
06-29 20:21:00.294 22773 22773 D SensorReceiver: Sensor(s) [is_interactive] corresponding to received event android.intent.action.SCREEN_ON are disabled, skipping sensors update
06-29 20:21:00.295 22773 22773 D ButtonWidget: Broadcast received: 
06-29 20:21:00.295 22773 22773 D ButtonWidget: Broadcast action: android.intent.action.SCREEN_ON
06-29 20:21:00.295 22773 22773 D ButtonWidget: AppWidgetId: -1
06-29 20:21:00.297 22773 22773 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
06-29 20:21:00.298 22773 22773 D MediaPlayCtrlsWidget: Broadcast received: 
06-29 20:21:00.298 22773 22773 D MediaPlayCtrlsWidget: Broadcast action: android.intent.action.SCREEN_ON
06-29 20:21:00.298 22773 22773 D MediaPlayCtrlsWidget: AppWidgetId: -1
06-29 20:21:00.298 22773 22773 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
06-29 20:21:00.299 22773 22773 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
06-29 20:21:00.306 22773 22835 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
06-29 20:21:00.307 22773 22828 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=d7f2d911-63c4-4d1d-9b8a-9b8bfafacf55, tags={ io.homeassistant.companion.android.websocket.WebsocketManager } ]
06-29 20:21:05.856 22773 22773 D SensorReceiver: Received intent: android.app.action.NEXT_ALARM_CLOCK_CHANGED
06-29 20:21:05.856 22773 22773 D SensorReceiver: Sensor(s) [next_alarm] corresponding to received event android.app.action.NEXT_ALARM_CLOCK_CHANGED are disabled, skipping sensors update
06-29 20:21:05.875 22773 22835 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
06-29 20:21:05.876 22773 22828 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=2fc44a9f-870a-4b5f-bbb6-db883690b091, tags={ io.homeassistant.companion.android.websocket.WebsocketManager } ]
06-29 20:21:14.744 22773 22773 D SensorReceiver: Received intent: io.homeassistant.companion.android.UPDATE_SENSORS
06-29 20:21:14.745 22773 22835 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
06-29 20:21:14.760 22773 22773 D SensorReceiver: Received intent: io.homeassistant.companion.android.UPDATE_SENSORS
06-29 20:21:14.761 22773 22840 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
06-29 20:21:14.811 22773 22835 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
06-29 20:21:14.812 22773 22835 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
06-29 20:21:14.823 22773 22840 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
06-29 20:21:14.824 22773 22840 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
06-29 20:21:14.909 22773 22840 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
06-29 20:21:14.910 22773 27976 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
06-29 20:21:14.931 22773 27976 I SensorReceiver: Sensor updates and sync completed
06-29 20:21:14.932 22773 27976 I SensorReceiver: Sensor updates and sync completed
06-29 20:21:28.554 22773 22773 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 1719684872427, currentMillis: 1719685288554)
06-29 20:21:28.586 22773 22773 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 1719684872427, currentMillis: 1719685288586)
06-29 20:21:28.586 22773 22773 D IntegrationRepository: setAppActive(): true
06-29 20:21:31.354 22773 22773 D IntegrationRepository: setAppActive(): false
06-29 20:21:31.355 22773 22773 D IntegrationRepository: setAppActive(): false
```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2024-07-02 15:08
duplicate of https://github.com/home-assistant/android/issues/3364

**Closed by dshokouhi** 2024-07-02 15:08 UTC
Labels: bug
