### ISSUE TITLE
Pinch to zoom

### ISSUE THREAD

**Issue by nissse** [home-assistant/android#1425] opened 2021-03-11 08:02 UTC
**Is your feature request related to a problem? Please describe.**
I use iframe in ha to get to my ip cam recording and need to be able to zoom in

**Describe the solution you'd like**
adding the possibility to pinch to zoom like ios app discussed here https://community.home-assistant.io/t/ios-pinch-to-zoom-removed/288066  

**Describe alternatives you've considered, if any**
I used web page now but they remove the pinch to zoom option in update Version:core-2021.3.2. So now i'm stuck and cant update.

**Additional context**
Thanks for a great app

**Comment by T-bond** [comment] 2021-03-12 01:43
Maybe related to #1117

**Comment by dshokouhi** [comment] 2021-03-12 19:26
ah actually this is a duplicate of #1117 upon review

**Closed by dshokouhi** 2021-03-12 19:26 UTC
Labels: enhancement, webview
