### ISSUE TITLE
Location update with zone name only doesnt update state of zones

### ISSUE THREAD

**Issue by swegn** [home-assistant/android#3361] opened 2023-02-22 11:05 UTC
**Home Assistant Android app version(s): **2023.1.1-full

**Android version(s):** 12

**Device model(s):** OnePlus Nord

**Home Assistant version:** 2023.2.5

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
Problem is when using the location tracking with zone name only.

This works but it sets the person state to the **Entity ID** of the zone.
But my zones have friendly names and the zones do not update its state with the person in the zone.

It works if I manually set the state of the person to the friendly name of the zone.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
Different state on the person (person.micke) when changing from exact location to zone name only:
<img width="195" alt="image" src="https://user-images.githubusercontent.com/58164514/220598839-95e686fb-3d07-49b4-862a-2c50f015a166.png">

State of the zone when using zone name only:
<img width="566" alt="image" src="https://user-images.githubusercontent.com/58164514/220599399-8f639afe-6536-4a12-9f8d-1677e93f421c.png">

State of the zone when using exact location:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/58164514/220600014-84f4c218-3f60-4bb9-bd35-8e0c04965e05.png">

**Additional information:**

**Comment by jpelgrom** [comment] 2023-02-22 12:23
The app isn't responsible for updating the person entity, I think this is a core issue.

**Comment by dshokouhi** [comment] 2023-02-22 16:29
> It works if I manually set the state of the person to the friendly name of the zone.

This does not mean it works, it just means you were able to override it just like you can override any entity state. It does not mean that is how it is supposed to work. 

Also if you look at the state tab for when a `person` entity is considered `home` its still lower case instead of upper case indicating it is not the friendly name in the state. This is also not the entity ID, just part of it.

![image](https://user-images.githubusercontent.com/1634145/220691262-cad9cf97-97bc-49a2-8b70-69d9b84e22e7.png)

To me this does not sound like an issue at all.

**Comment by swegn** [comment] 2023-03-13 12:03
It seems to be a chain of states that will set the zone state to be the number of users in it.
The device_tracker state is the zone name in some format. And that is set as the person state too. The zone picks up that state and counts that person as in the zone.

But the state of the zone is only changed if the person state is the friendly name as the zone.
(The home zone seems to be an exception and works event if it isn't friendly name)

So it may be a core-issue... I don't know. 
But it is still strange that the device_tracker is reporting different states when changing from exact location to zone name only in the settings.

**Comment by tjorim** [comment] 2023-06-16 19:46
Also seeing this after switching from precise location to zone-only. Both on Android and iOS.
Does not seem to be a problem for the 'home'-zone?
This reports a similar issue? https://github.com/home-assistant/core/issues/94694

**Comment by lingfish** [comment] 2023-07-28 06:17
I'm having this issue too, and another outcome is that people/devices then don't show up on maps either.

**Comment by jpelgrom** [comment] 2023-07-30 17:10
Closing this as a duplicate of the previously mentioned home-assistant/core#94694 - updating states of zones is not something handled by the app, but by core.

> another outcome is that people/devices then don't show up on maps either

This is correct, you can't put a person/device on a map if you don't have an exact location.

**Closed by jpelgrom** 2023-07-30 17:10 UTC
Labels: bug, question, location-tracking
