### ISSUE TITLE
Search Logs Bar

### ISSUE THREAD

**Issue by milandzuris** [home-assistant/android#3873] opened 2023-09-17 18:27 UTC
**Home Assistant Android app version(s):**
Newest Beta

**Android version(s):**
Android 13

**Device model(s):**
Samsung

**Home Assistant version:**
2023.9.2

**Last working Home Assistant release (if known):**
Hmm 

**Description of problem, include YAML if issue is related to notifications:**
Search Logs bar is not working when im tap

**Screenshot or video of problem:**
![image](https://github.com/home-assistant/android/assets/42905545/1850ec75-0f5c-4a1f-9ead-31fafdf328d0)

**Comment by dshokouhi** [comment] 2023-09-17 18:30
possible duplicate of https://github.com/home-assistant/frontend/issues/16394

can you reproduce the issue using chrome for android on the same device?

**Comment by milandzuris** [comment] 2023-09-17 19:00
> possible duplicate of https://github.com/home-assistant/frontend/issues/16394
> 
> can you reproduce the issue using chrome for android on the same device?

Same on Chrome![Screenshot_20230917_205916_Chrome.jpg](https://github.com/home-assistant/android/assets/42905545/e2db3f74-d6f1-494c-aab3-d01ad6a46cde)

**Comment by dshokouhi** [comment] 2023-09-17 19:05
Ok please open a new frontend issue as the app can't fix this. The issue I linked to appears to be different here. You'll need to fill out the issue template in their repo to give proper data.

**Closed by dshokouhi** 2023-09-17 19:05 UTC
Labels: bug
