### ISSUE TITLE
Add option to refresh

### ISSUE THREAD

**Issue by rchovan** [home-assistant/android#1106] opened 2020-10-25 10:29 UTC
**Is your feature request related to a problem? Please describe.**
Some widgets are not loaded, or are not actual. Add option to reload current page/view/layout/dashboard.

**Describe the solution you'd like**
Options are with swipe, or with item in upper right menu, where is "Edit Dashboard and Help"

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment] 2020-10-25 15:28
Duplicate of #31

**Closed by dshokouhi** 2020-10-25 15:28 UTC
Labels: enhancement

**Comment by JBassett** [comment] 2020-10-26 13:29
@rchovan as a side note the latest HA Core has a refresh option in the top right menu.

**Comment by rchovan** [comment] 2020-10-26 14:30
Hi, @JBassett thanks for info, but I can't find it. I'm running 0.116.4 and I still see only Edit and Help. 

![image](https://user-images.githubusercontent.com/6713920/97185125-fc982380-179f-11eb-9b6c-89178430fce3.png)

Where should I look ?

**Comment by JBassett** [comment] 2020-10-26 14:34
@rchovan Latest Beta HA Core has the option.  Forgot I am on the beta for my production server!
