### ISSUE TITLE
Notifications without FCM

### ISSUE THREAD

**Issue by 1RandomDev** [home-assistant/android#1652] opened 2021-07-29 10:34 UTC
**Is your feature request related to a problem? Please describe.**

On none of my mobile devices without the Google Play Services I can receive push notifications. I also don't want any of my notification data getting sent to google.

**Describe the solution you'd like**

I'd like a way of receiving push notifications that don't require google services.

**Describe alternatives you've considered, if any**

I don't have much experience with app development, but maybe the socket connection that the app uses to communicate with the server can also be used for that.

**Additional context**

\-/\-

**Comment by dshokouhi** [comment] 2021-07-29 12:43
Duplicate of #1480

**Closed by dshokouhi** 2021-07-29 12:43 UTC
Labels: enhancement
