### ISSUE TITLE
Network sensors: IP Address not detected while WI-FI connected on HUAWEI Mate 10 Pro

### ISSUE THREAD

**Issue by jodomi** [home-assistant/android#3986] opened 2023-10-30 21:02 UTC
**Home Assistant Android app version(s):**

**Android version(s):**EMUI 12

**Device model(s):**HUAWEI Mate 10 Pro

**Home Assistant version:**2023.10.02-full

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**Hello ,
I have a HUAWEI Mate 10 Pro and in the App Companion network sensors I don't have a Wi-fi IP address < not connected > (I'm connected on 5Ghz, but same on 2.4Ghz) and the other sensors are correct (Wi-Fi network status: True, Network type: Wi-Fi and connection name OK). 
The Network Public IP is also correct, but not transmitted to HA. 

**Companion App Logs:**

```
[homeassistant_companion_log_9-30-2023_21-47-3.txt](https://github.com/home-assistant/android/files/13209768/homeassistant_companion_log_9-30-2023_21-47-3.txt)

```

**Screenshot or video of problem:**
![Screenshot_20231030_215744](https://github.com/home-assistant/android/assets/98644988/f0331846-9aa1-458b-885c-1dcf6af86623)
![Screenshot_20231030_215822_io homeassistant companion android](https://github.com/home-assistant/android/assets/98644988/60ba258b-9756-4769-8e25-5e6c64e33c44)

**Additional information:**

**Comment by dshokouhi** [comment] 2023-10-30 21:34
duplicate of #3969  and fixed in #3970

**Closed by dshokouhi** 2023-10-30 21:34 UTC
Labels: bug
