### ISSUE TITLE
Android widgets causing IP Bans within HA.

### ISSUE THREAD

**Issue by dougle03** [home-assistant/android#4786] opened 2024-11-06 07:15 UTC
**Home Assistant Android app version(s):**

**Android version(s):**
14
**Device model(s):**
Pixel 6 Pro
**Home Assistant version:**
2024.10.4
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
Regular ip bans for my phones IP address...
First happened a few months ago when I added a number of widgets.
I removed the widgets two days ago and no more IP bans on my IP address...

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2024-11-06 14:52
we need more data to go by Logs are required and also which widgets and your network setup

**Comment by dshokouhi** [comment] 2024-11-06 14:53
potential duplicate of https://github.com/home-assistant/core/issues/114575 once we confirm teh log error

**Comment by dougle03** [comment] 2024-11-06 17:27
I have no idea how to extract logs from the app. I used a sensor widget and a camera widget. Network is local IP or Zerotier when away from home. Every ban instance has been when home on local connection. Hope this helps.

**Comment by dshokouhi** [comment] 2024-11-06 17:30
> have no idea how to extract logs from the app

it was actually mentioned in the issue template, you skipped over this section while filling out the template

Settings > companion app > troubleshooting > show and share logs

**Comment by smart7324** [comment] 2024-11-08 20:22
Same problem on the iOS companion app. I am getting the same error if any normal user (non admin) is using a widget with templates. The /api/templates endpoint should definitely not be restricted to admins only. Normal users should also have the permission to access the endpoint. So I think this is a HA core problem. Can someone create/find an issue there?

**Comment by dshokouhi** [comment] 2024-11-08 21:02
> The /api/templates endpoint should definitely not be restricted to admins only. Normal users should also have the permission to access the endpoint.

templates have access to everything so that is why it is admin only IIRC



> So I think this is a HA core problem. Can someone create/find an issue there?

i assume everyone has teh same error from: https://github.com/home-assistant/core/issues/114575 which then leads to the ban

**Comment by smart7324** [comment] 2024-11-08 21:16
> templates have access to everything so that is why it is admin only IIRC

Okay, thanks for clarifying that. This makes sense!

**Comment by dshokouhi** [comment] 2024-11-11 01:36
closing in favor https://github.com/home-assistant/core/issues/114575

**Closed by dshokouhi** 2024-11-11 01:36 UTC
Labels: bug, question, widget

**Comment by dougle03** [comment] 2024-11-11 07:53
`i assume everyone has teh same error from: https://github.com/home-assistant/core/issues/114575 which then leads to the ban`
Not so, these ip bans have been going on for years, not just the start of 114575
