### ISSUE TITLE
Errors at startup concerning the Android app reporting wrong type

### ISSUE THREAD

**Issue by jean-paullizotte** [home-assistant/android#3344] opened 2023-02-17 17:44 UTC
**Home Assistant Android app version(s):**

**Android version(s):**
11
**Device model(s):**
be2026/One plus Nord 10 5G
**Home Assistant version:**
Home Assistant 2023.2.3
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
[homeassistant.components.sensor] Sensor sensor.be2026_high_accuracy_update_interval_2 has device class None, state class None and unit seconds thus indicating it has a numeric value; however, it has the non-numeric value:  (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mobile_app%22

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment] 2023-02-17 17:47
This is fixed in the latest app beta also duplicate of #3265

**Closed by dshokouhi** 2023-02-17 17:47 UTC
Labels: bug
