### ISSUE TITLE
SQL Insert error

### ISSUE THREAD

**Issue by Nornode** [home-assistant/android#1219] opened 2020-11-29 18:14 UTC
**Home Assistant Android version:**
beta-525-c7bd83c-full

**Android version:**
10

**Phone model:**
OnePlus 6 

**Home Assistant version:**
0.117.1

**Description of problem:**
Additional sensors activated on App side causing SQL errors on the HA server side.

"Incorrect string value: '\\xF0\\x9F\\x98\\x82' for column 'state' at row 1") 

**Traceback (if applicable):**
Home Assistant log:
```
[SQL: INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created, old_state_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('sensor', 'sensor.rl_oneplus_a6003_last_notification', 'All-in advent!!! 😂', '{"android.appInfo": "ApplicationInfo{cd0c4ab com.facebook.orca}", "android.car.EXTENSIONS": "Bundle[mParcelledData.dataSize=956]", "android.hiddenCon ... (796 characters truncated) ... Bundle[mParcelledData.dataSize=856]", "package": "com.facebook.orca", "friendly_name": "RL ONEPLUS A6003 Last Notification", "icon": "mdi:bell-ring"}', 39066694, datetime.datetime(2020, 11, 29, 14, 6, 50, 362175, tzinfo=datetime.timezone.utc), datetime.datetime(2020, 11, 29, 14, 6, 50, 362175, tzinfo=datetime.timezone.utc), datetime.datetime(2020, 11, 29, 14, 6, 50, 362191, tzinfo=datetime.timezone.utc), 38461815)]
(Background on this error at: http://sqlalche.me/e/13/e3q8). (retrying in 3 seconds)
2020-11-29 20:03:43 ERROR (Recorder) [homeassistant.components.recorder] Error executing query: (MySQLdb._exceptions.OperationalError) (1366, "Incorrect string value: '\\xF0\\x9F\\x98\\x82' for column 'state' at row 1")
[SQL: INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created, old_state_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('sensor', 'sensor.rl_oneplus_a6003_last_notification', 'All-in advent!!! 😂', '{"android.appInfo": "ApplicationInfo{cd0c4ab com.facebook.orca}", "android.car.EXTENSIONS": "Bundle[mParcelledData.dataSize=956]", "android.hiddenCon ... (796 characters truncated) ... Bundle[mParcelledData.dataSize=856]", "package": "com.facebook.orca", "friendly_name": "RL ONEPLUS A6003 Last Notification", "icon": "mdi:bell-ring"}', 39066694, datetime.datetime(2020, 11, 29, 14, 6, 50, 362175, tzinfo=datetime.timezone.utc), datetime.datetime(2020, 11, 29, 14, 6, 50, 362175, tzinfo=datetime.timezone.utc), datetime.datetime(2020, 11, 29, 14, 6, 50, 362191, tzinfo=datetime.timezone.utc), 38461815)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
2020-11-29 20:03:43 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity during commit: (MySQLdb._exceptions.OperationalError) (1366, "Incorrect string value: '\\xF0\\x9F\\x98\\x82' for column 'state' at row 1")
[SQL: INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created, old_state_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('sensor', 'sensor.rl_oneplus_a6003_last_notification', 'All-in advent!!! 😂', '{"android.appInfo": "ApplicationInfo{cd0c4ab com.facebook.orca}", "android.car.EXTENSIONS": "Bundle[mParcelledData.dataSize=956]", "android.hiddenCon ... (796 characters truncated) ... Bundle[mParcelledData.dataSize=856]", "package": "com.facebook.orca", "friendly_name": "RL ONEPLUS A6003 Last Notification", "icon": "mdi:bell-ring"}', 39066694, datetime.datetime(2020, 11, 29, 14, 6, 50, 362175, tzinfo=datetime.timezone.utc), datetime.datetime(2020, 11, 29, 14, 6, 50, 362175, tzinfo=datetime.timezone.utc), datetime.datetime(2020, 11, 29, 14, 6, 50, 362191, tzinfo=datetime.timezone.utc), 38461815)]
(Background on this error at: http://sqlalche.me/e/13/e3q8). (retrying in 3 seconds)
2020-11-29 20:07:20 ERROR (Recorder) [homeassistant.components.recorder] Error executing query: (MySQLdb._exceptions.OperationalError) (1366, "Incorrect string value: '\\xF0\\x9F\\x98\\x82' for column 'state' at row 1")
[SQL: INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created, old_state_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('sensor', 'sensor.rl_oneplus_a6003_last_notification', 'All-in advent!!! 😂', '{"android.appInfo": "ApplicationInfo{cd0c4ab com.facebook.orca}", "android.car.EXTENSIONS": "Bundle[mParcelledData.dataSize=956]", "android.hiddenCon ... (796 characters truncated) ... Bundle[mParcelledData.dataSize=856]", "package": "com.facebook.orca", "friendly_name": "RL ONEPLUS A6003 Last Notification", "icon": "mdi:bell-ring"}', 39066694, datetime.datetime(2020, 11, 29, 14, 6, 50, 362175, tzinfo=datetime.timezone.utc), datetime.datetime(2020, 11, 29, 14, 6, 50, 362175, tzinfo=datetime.timezone.utc), datetime.datetime(2020, 11, 29, 14, 6, 50, 362191, tzinfo=datetime.timezone.utc), 38461815)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
2020-11-29 20:07:20 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity during commit: (MySQLdb._exceptions.OperationalError) (1366, "Incorrect string value: '\\xF0\\x9F\\x98\\x82' for column 'state' at row 1")
[SQL: INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created, old_state_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('sensor', 'sensor.rl_oneplus_a6003_last_notification', 'All-in advent!!! 😂', '{"android.appInfo": "ApplicationInfo{cd0c4ab com.facebook.orca}", "android.car.EXTENSIONS": "Bundle[mParcelledData.dataSize=956]", "android.hiddenCon ... (796 characters truncated) ... Bundle[mParcelledData.dataSize=856]", "package": "com.facebook.orca", "friendly_name": "RL ONEPLUS A6003 Last Notification", "icon": "mdi:bell-ring"}', 39066694, datetime.datetime(2020, 11, 29, 14, 6, 50, 362175, tzinfo=datetime.timezone.utc), datetime.datetime(2020, 11, 29, 14, 6, 50, 362175, tzinfo=datetime.timezone.utc), datetime.datetime(2020, 11, 29, 14, 6, 50, 362191, tzinfo=datetime.timezone.utc), 38461815)]
(Background on this error at: http://sqlalche.me/e/13/e3q8). (retrying in 3 seconds)
2020-11-29 20:08:22 ERROR (Recorder) [homeassistant.components.recorder] Error executing query: (MySQLdb._exceptions.OperationalError) (1366, "Incorrect string value: '\\xF0\\x9F\\x98\\x82' for column 'state' at row 1")
[SQL: INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created, old_state_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('sensor', 'sensor.rl_oneplus_a6003_last_notification', 'All-in advent!!! 😂', '{"android.appInfo": "ApplicationInfo{cd0c4ab com.facebook.orca}", "android.car.EXTENSIONS": "Bundle[mParcelledData.dataSize=956]", "android.hiddenCon ... (796 characters truncated) ... Bundle[mParcelledData.dataSize=856]", "package": "com.facebook.orca", "friendly_name": "RL ONEPLUS A6003 Last Notification", "icon": "mdi:bell-ring"}', 39066694, datetime.datetime(2020, 11, 29, 14, 6, 50, 362175, tzinfo=datetime.timezone.utc), datetime.datetime(2020, 11, 29, 14, 6, 50, 362175, tzinfo=datetime.timezone.utc), datetime.datetime(2020, 11, 29, 14, 6, 50, 362191, tzinfo=datetime.timezone.utc), 38461815)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
2020-11-29 20:08:22 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity during commit: (MySQLdb._exceptions.OperationalError) (1366, "Incorrect string value: '\\xF0\\x9F\\x98\\x82' for column 'state' at row 1")
[SQL: INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created, old_state_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('sensor', 'sensor.rl_oneplus_a6003_last_notification', 'All-in advent!!! 😂', '{"android.appInfo": "ApplicationInfo{cd0c4ab com.facebook.orca}", "android.car.EXTENSIONS": "Bundle[mParcelledData.dataSize=956]", "android.hiddenCon ... (796 characters truncated) ... Bundle[mParcelledData.dataSize=856]", "package": "com.facebook.orca", "friendly_name": "RL ONEPLUS A6003 Last Notification", "icon": "mdi:bell-ring"}', 39066694, datetime.datetime(2020, 11, 29, 14, 6, 50, 362175, tzinfo=datetime.timezone.utc), datetime.datetime(2020, 11, 29, 14, 6, 50, 362175, tzinfo=datetime.timezone.utc), datetime.datetime(2020, 11, 29, 14, 6, 50, 362191, tzinfo=datetime.timezone.utc), 38461815)]
(Background on this error at: http://sqlalche.me/e/13/e3q8). (retrying in 3 seconds)
```

**Additional information:**
The app has Humongous battery consumption, causing me needing to recharge my phone several times a day.
Home Assistant App is constantly as no1 on my Battery usage list.

**Comment by dshokouhi** [comment] 2020-11-29 18:44
Duplicate of #1204 please see https://github.com/home-assistant/android/issues/1204#issuecomment-730246773 for tips on how to resolve.  Please comment back in #1204 if the fix worked for you.  

also you can set an allow list for this sensor if you don't require facebook notifications as part of the sensor data.

**Closed by dshokouhi** 2020-11-29 18:44 UTC
Labels: bug
