### ISSUE TITLE
Unable to connect: WAIT, REFRESH, SETTINGS

### ISSUE THREAD

**Issue by tunerooster** [home-assistant/android#1337] opened 2021-01-31 13:29 UTC
I am trying to configure Home Assistant Companion to run continuously (like on the wall) 24/7, i.e., like a dashboard.  I have four different tablets running 3 different android versions (8, 9, and 10) and experience the same problem on all four machines.

When I start HA Companion app, it loads fine, then after anywhere from 1 to 6 hours, if fails putting up a popup-box saying:

```
Unable to connect to Home Assistant.

There was an error loading Home Assistant, please review
the connection settings and try again.

WAIT					REFRESH	SETTINGS
```
The message stays there  indefinitely until I click REFRESH, then it loads without any problem... until it happens again 1-6 hours later.

HOWEVER, when I run Home Assistant in **Chrome** (with the exact same URL, authentication and configuration) it runs for days without any problem.

Is there any way around this?  I need to be able to run Home Assistant Companion App because I need to auto-start it at boot time (as an app) and I cannot do this with chrome.  Plus I want to use the extra features in HA Companion.

Application Version: beta-568-9ccae48-full

Also fails on all other versions I have tried.

Thanks for a great APP and for any help offered!

P.S.  If it can't be prevented, it should at lease "REFRESH" itself after a while (rather than requiring human intervention).

**Comment by dshokouhi** [comment] 2021-01-31 15:21
Duplicate of #1310

**Closed by dshokouhi** 2021-01-31 15:21 UTC

**Comment by tunerooster** [comment] 2021-01-31 16:08
Thank you for the link.  However, what is the resolution.  Does this mean it is being worked on?

**Comment by tunerooster** [comment] 2021-01-31 16:10
What is the status on this.  What are the chances it will be fixed?

Thanks!
