### ISSUE TITLE
Location update swaps between home and away

### ISSUE THREAD

**Issue by praveen12bnitt** [home-assistant/android#937] opened 2020-09-15 01:48 UTC
**Home Assistant Android version:** beta-376-60ecbaf-full

**Android version:** Android 11

**Phone model:** pixel 2 

**Home Assistant version:** 0.114.4

**Last working Home Assistant release (if known):**

**Description of problem:** when I leave home or reach home, my state jumps between. Away - home - away. When I reach home it goes from home - away - home 

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

Screenshot when I left home at 5.55.
![Screenshot_20200914-214627](https://user-images.githubusercontent.com/931290/93155308-cca32e00-f6d3-11ea-8ec3-936b206a7c36.png)

Then I reached home at 8 pm
![Screenshot_20200914-214738](https://user-images.githubusercontent.com/931290/93155377-f2c8ce00-f6d3-11ea-8e45-772a1d3d2653.png)

I see the same behavior for my wife too.

**Additional information:**

**Comment by praveen12bnitt** [comment] 2020-09-15 01:53
Here is a screenshot from my wife phone

Pixel 3
Android 10.

My wife left home at around 7.49
![Screenshot_20200914-215109](https://user-images.githubusercontent.com/931290/93155576-71257000-f6d4-11ea-8531-f64de4a8d5ce.png)

She reached home at around 8.28
![Screenshot_20200914-215256](https://user-images.githubusercontent.com/931290/93155713-b21d8480-f6d4-11ea-97a0-ab0face2e4e3.png)

**Comment by dshokouhi** [comment] 2020-09-15 02:43
Duplicate of #929

**Closed by dshokouhi** 2020-09-15 02:43 UTC
Labels: bug
