### ISSUE TITLE
Going back (slide from border) glitch

### ISSUE THREAD

**Issue by ErSeraph** [home-assistant/android#3802] opened 2023-08-19 16:56 UTC
**Home Assistant Android app version(s):** 2023.8.2-full

**Android version(s):** 13

**Device model(s):** Pixel 7

**Home Assistant version:** 2023.8.3

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:** For some reason, if you go back (slide from the border of the phone, not the button) the app intercept a tap on the screen and will execute everything from where you go back.

I uploaded a video, in this example I am on the registry, next I open my dashboard, I want to see some A/C buttons, next I slide from the right because I want to go back, you can see that going back I pressed a button, we can verify that on the registry with the time of execution

**Companion App Logs:**

```

```

**Screenshot or video of problem:** https://github.com/home-assistant/android/assets/30057980/981ae623-ffb8-433c-b929-710ba3ba01a2

**Additional information:**

**Comment by jpelgrom** [comment] 2023-08-19 18:10
Closing as duplicate of #3565

**Closed by jpelgrom** 2023-08-19 18:10 UTC
