### ISSUE TITLE
One screen is oversized after open Settings/Location and Zones/Zones/"+ Add zone"

### ISSUE THREAD

**Issue by misa1515** [home-assistant/android#3689] opened 2023-07-21 09:06 UTC
**Home Assistant Android app version(s):**
15.7.2023

**Android version(s):**
13 TKQ1.220829.002

**Device model(s):**
Xiaomi 11T Pro 2107113SG

**Home Assistant version:**
2023.7.2

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
After open Settings/Location and Zones/Zones/"+ Add zone" is showed window, which is much more bigger like phone screen (you can see it in attachement).

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![1689918344704_OverSizeWindow](https://github.com/home-assistant/android/assets/61636045/61ecc790-ca8b-4091-9407-92de5898f524)

**Additional information:**

**Comment by jpelgrom** [comment] 2023-07-21 09:13
Do you see the same when using Home Assistant in a browser on the same phone? Any custom code that might be interfering?

Also using 2023.7.2 and the dialog looks fine here:
![Screenshot_20230721-111230.png](https://github.com/home-assistant/android/assets/8148535/8030820c-f135-4e66-b5d0-ea255b088649)

**Comment by jpelgrom** [comment] 2023-07-21 18:19
Actually managed to reproduce this in a browser on my computer. It looks like it depends on the screen width, and widths between 450 and 600px aren't handled correctly. That means this is a frontend issue and a [new issue should be created there](https://github.com/home-assistant/frontend/issues/new/choose) instead, closing this issue.

**Closed by jpelgrom** 2023-07-21 18:19 UTC
Labels: bug, question, webview
