### ISSUE TITLE
turning DND off broken with 2022.8.0-full

### ISSUE THREAD

**Issue by HenningGithub** [home-assistant/android#2828] opened 2022-08-27 11:33 UTC
**Home Assistant Android version:**
2022.8.0-full

**Android version:**
12

**Phone model:**
Samsung Galaxy S10

**Home Assistant version:**
2022.8.7

**Last working Home Assistant release (if known):**
2022.8.7

**Description of problem:**
I got the App version 2022.8.0-full tonight. DND off messages are now delivered as regular notification.

  - service: notify.mobile_app_...
    data:  
      message: command_dnd
      title: 'off'

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

**Screenshot of problem:**
github claims it cannot process the screenshot, jpg or png format :/

**Additional information:**

**Comment by dshokouhi** [comment] 2022-08-27 11:41
Duplicate of #2826

**Closed** 2022-08-27 11:41 UTC
Labels: bug
