### ISSUE TITLE
Notification with image is not working

### ISSUE THREAD

**Issue by scastiello** [home-assistant/android#3943] opened 2023-10-16 19:25 UTC
**Home Assistant Android app version(s):** 2023.10.2-full

**Android version(s):**  13

**Device model(s):** Xiaomi 13

**Home Assistant version:** 2023.10.2

**Last working Home Assistant release (if known):** Unknown

**Description of problem, include YAML if issue is related to notifications:**
I´m not able to send an image in the notification, it never get shown in the device. The image is there because i´m using the same one with telegram integration. Any clue?

```yaml
service: notify.notify
data:
  data:
    color: red
    image: /media/local/camera-motion-detected.jpg
  message: Camera motion detected
```

**Companion App Logs:**

```
10-16 21:56:24.268  1269  1269 D MessagingService: Creating notification with following data: {color=red, image=/media/local/camera-motion-detected.jpg, webhook_id=14d96db4b97f1c75b0e709beaa84fb377fb13327fd1512228275dcc1bd42dd53, message=Camera motion detected, server_id=1}
10-16 21:56:24.271  1269  1269 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: false
10-16 21:56:24.271  1269  1269 D ServerConnectionInfo: Using external URL
10-16 21:56:24.272  1269  1683 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: false
10-16 21:56:24.272  1269  1683 D ServerConnectionInfo: Using external URL
10-16 21:56:24.392  1269  1683 D TrafficStats: tagSocket(208) with statsTag=0xffffffff, statsUid=-1
10-16 21:56:24.983  1269  1683 D OpenGLRenderer: --- Failed to create image decoder with message 'unimplemented'
10-16 21:56:24.987  1269  1269 D MessagingService: Show notification with tag "null" and id "974102347"
```

**Screenshot or video of problem:**
![image](https://github.com/home-assistant/android/assets/1845439/6900aca3-ad86-4dc2-8e59-79fb965da609)

**Additional information:**

**Comment by dshokouhi** [comment] 2023-10-16 19:51
please check the companion app logs for errors so we can see if there is a failure

**Comment by scastiello** [comment] 2023-10-16 19:59
@dshokouhi Sorry, I miss that. done!

**Comment by dshokouhi** [comment] 2023-10-16 20:07
ok can you also check that you can load the URL in a browser? Use your external URL along with the relative path so it should be like `https://haurl/media/local/image.jpg`

This is also sounding like a duplicate of #3933 but depends on the outcome of the URL test

```
10-16 21:56:24.983  1269  1683 D OpenGLRenderer: --- Failed to create image decoder with message 'unimplemented'
```

**Comment by scastiello** [comment] 2023-10-16 20:13
It works but I need the auth (like: `https://haurl/media/local/local/camera-motion-detected.jpg?authSig={thekey}`), if not i get 403 response

**Comment by dshokouhi** [comment] 2023-10-16 20:17
> **UPDATE:**
> I realize about the url that I get from the ha ui has two local folders, so i try to change it and it works now, just setting the image to `/media/local/local/camera-motion-detected.jpg`

that was my next ask, thanks for confirming. Closing this issue now :)

**Closed by dshokouhi** 2023-10-16 20:17 UTC
Labels: bug, question, notifications
