### ISSUE TITLE
Home Assistant app crashes One UI

### ISSUE THREAD

**Issue by EmilZackrisson** [home-assistant/android#2287] opened 2022-02-15 12:41 UTC
**Home Assistant Android version:**
2022.2.1-full
**Android version:**
12 One UI 4.1
**Phone model:**
Samsung Galaxy S22 Ultra
**Home Assistant version:**
2022.2.6
**Last working Home Assistant release (if known):**

**Description of problem:**
I got my new S22 Ultra today and I tried the new Device Control in the drop down menu. But when I tried to click on a device från home assistant the whole phone hangs and stops working. The only way to get back to the homescreen is to reboot the phone. It happens when I click on the big button and if I hold down, but the small button in the upper corner works great.
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
Pastebin: https://pastebin.com/4DvTCunJ

```

**Screenshot of problem:**
Just blank screen, only wallpaper is visible.
**Additional information:**

**Comment by dshokouhi** [comment] 2022-02-15 17:57
duplicate of #2286

**Comment by dshokouhi** [comment] 2022-02-15 17:58
oops wrong issue :)

**Comment by EmilZackrisson** [comment] 2022-02-15 18:06
> If you remove all but one control does it work as expected? Trying to see if this is a duplicate of another bug that we had reported to Google

If I remove all but one control, it doesn't toggle the light but it opens Home Assistant app in a popup screen. It doesnt work but it does not crash either.

**Comment by dshokouhi** [comment] 2022-02-15 18:08
> > If you remove all but one control does it work as expected? Trying to see if this is a duplicate of another bug that we had reported to Google
> 
> If I remove all but one control, it doesn't toggle the light but it opens Home Assistant app in a popup screen. It doesnt work but it does not crash either.

Can you check for errors in either HA core and Companion App > Logs to see if there is an error? Also does a service call to `turn_on` or `turn_off` the light work if you call it manually? All the app is doing is making service calls when you click on it.

**Comment by EmilZackrisson** [comment] 2022-02-15 18:19
> > > If you remove all but one control does it work as expected? Trying to see if this is a duplicate of another bug that we had reported to Google
> > 
> > If I remove all but one control, it doesn't toggle the light but it opens Home Assistant app in a popup screen. It doesnt work but it does not crash either.
> 
> Can you check for errors in either HA core and Companion App > Logs to see if there is an error? Also does a service call to `turn_on` or `turn_off` the light work if you call it manually? All the app is doing is making service calls when you click on it.
> 
> Edit: Under Companion App > Logs I would expect to see an error like: https://github.com/home-assistant/android/blob/bee5116d3d688c70e44fb2d83aa0ac14357c53b3/app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt#L199

I doesn't see anything obvious in either logs.

**Comment by EmilZackrisson** [comment] 2022-02-15 18:30
I took some screenshots to show
![Screenshot_20220215-192354_One UI Home](https://user-images.githubusercontent.com/51415707/154125841-f96b75fc-0f21-4a49-bf91-319019277518.jpg)
.
after this the Home Assistant app crashes and opens in this wierd view and has the light opened.
![Screenshot_20220215-192414_Home Assistant](https://user-images.githubusercontent.com/51415707/154125954-89e4be21-0dbf-4c75-9f70-6def987190b4.jpg).

Here are the app logs
[homeassistant_companion_log_1-15-2022_19-25-15.txt](https://github.com/home-assistant/android/files/8073667/homeassistant_companion_log_1-15-2022_19-25-15.txt).

Nothing in the home assistant logs about this.

**Comment by dshokouhi** [comment] 2022-02-15 18:39
Do these logs contain when you click on the tile or just a long press? If you are clicking on the tile then I am not even seeing Android send over the click event to the app because this line is missing and it should definitely show up.  If it does not then that may not be an app issue.

https://github.com/home-assistant/android/blob/bee5116d3d688c70e44fb2d83aa0ac14357c53b3/app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt#L190

If you only long pressed it then the below applies:

> after this the Home Assistant app crashes and opens in this wierd view and has the light opened.

This is not a crash, the app opens a new instance of the frontend and then a few seconds later shows the details view of the light. This is standard long press behavior.

**Comment by dshokouhi** [comment] 2022-02-15 18:48
ok were going to need logs from another app like Logcat Reader or Android Studio in order to continue here so we can see the cause of the failure for when you click on a tile. Either method will require you to hook up your phone to a PC with a USB cable to grant permissions. If you could get us the logs after you reproduce the issue that would great. Make sure to only test clicking on the tile as those logs will be different than long press

**Comment by EmilZackrisson** [comment] 2022-02-15 19:02
Logcat log from when i clicked on the light once
[logcat_02-15-2022_20-01-25.txt](https://github.com/home-assistant/android/files/8073876/logcat_02-15-2022_20-01-25.txt)

**Comment by dshokouhi** [comment] 2022-02-15 19:21
yup our log line is missing for performing the action which is strange because your device should tell the app its going to perform the action however I do not see that at all.  I also do not see a crash either, just really strange because on my Pixel this is working as expected

https://developer.android.com/reference/android/service/controls/ControlsProviderService#performControlAction(java.lang.String,%20android.service.controls.actions.ControlAction,%20java.util.function.Consumer%3Cjava.lang.Integer%3E)

Unfortunately I cannot reproduce this error, have you tried another entity to see if that will work?

**Comment by EmilZackrisson** [comment] 2022-02-15 19:28
Now I tested another entity, a switch, it didn't work either.

Logcat log:
[logcat_02-15-2022_20-26-19.txt](https://github.com/home-assistant/android/files/8074050/logcat_02-15-2022_20-26-19.txt)

**Comment by dshokouhi** [comment] 2022-02-15 19:35
yup the log looks identical here, I honestly would expect to see something similar to lines like this:

```
02-15 11:30:49.927 21579 21579 D HaConProService: publisherFor [input_boolean.baby_sleeping, light.bathroom_lights, light.patio, climate.thermostat, light.toshs, light.tv_lights]
02-15 11:30:49.981 21579 21596 D HaConProService: request 100000
02-15 11:30:54.399 21579 21579 D HaConProService: Control: light.den_lights_level, action: android.service.controls.actions.FloatAction@e6b1810
02-15 11:30:57.411 21579 21595 D HaConProService: cancel
```

Instead for you I only see

```
[02-15 20:26:13.585 15570:15570 D/HaConProService] publisherFor [light.taklampor, switch.fonsterlampa_2]
[02-15 20:26:13.586 15570:22866 D/HaConProService] request 100000
[02-15 20:26:17.918 15570:16183 D/HaConProService] cancel
```

the control line is missing so your device is not even telling the app its ready to make a change 😕

**Comment by EmilZackrisson** [comment] 2022-02-15 19:38
So it is a Android or One UI problem?

**Comment by dshokouhi** [comment] 2022-02-15 19:42
So there was a couple issues here. The first crash that disappeared when you used only 1 control is more than likely a duplicate of #2251 which is a Google issue to solve as it was introduced in the February security update.  We have already notified Google about the bug and they are looking into it.

The issue related to the control not doing anything is tough to tell where its coming from. On my Pixel controls are working as expected so I assume its device related there. Very tough to tell when the logs don't show what happened. The app is supposed to perform the action based on the control provided by the OS and at this point we are not getting that data at all as evidenced by no action log lines.  As of now it seems like a device specific issue, I wonder if another user with the same device has the same problem or not?

**Comment by Mick51** [comment] 2022-02-16 17:54
Hi everyone, no such problem on my S21, the only problem noticed is that home assistant despite all the possible settings drains my battery, whereas before the last update no ....

**Comment by dshokouhi** [comment] 2022-02-16 17:57
> the only problem noticed is that home assistant despite all the possible settings drains my battery, whereas before the last update no ....

Please do not comment in one issue about another issue, instead create a new issue. Also ensure you are on 2022.2.1 to fix the battery drain issue, if it still exists then go to Configuration > Companion App > Persistent Connection and set the option to Never

**Comment by Mick51** [comment] 2022-02-16 18:05
> > the only problem noticed is that home assistant despite all the possible settings drains my battery, whereas before the last update no ....
> 
> Please do not comment in one issue about another issue, instead create a new issue. Also ensure you are on 2022.2.1 to fix the battery drain issue, if it still exists then go to Configuration > Companion App > Persistent Connection and set the option to Never

I first replied to the author of the post having the same phone and everything up to date on the S21 side as a home assistant, I don't have a problem like the author, your solutions for battery drain don't work on the  S21 I tried everything, however I use an admin account on my S21, my wife who has a user account has no battery drain, is this normal?

**Comment by dshokouhi** [comment] 2022-02-16 18:09
> I first replied to the author of the post having the same phone and everything up to date on the S21 side as a home assistant

that was fine and we appreciate letting us konw you dont have that issue



> I don't have a problem like the author, your solutions for battery drain don't work on the S21 I tried everything, however I use an admin account on my S21, my wife who has a user account has no battery drain, is this normal?

Please create a new issue instead of asking about it in an unrelated issue

**Comment by EmilZackrisson** [comment] 2022-05-09 17:02
> @EmilZackrisson Hi, would you be able to install a test version of the app to see if it fixes the issues? Download the file `app-full-debug.apk` from [here](https://github.com/home-assistant/android/actions/runs/2294853655) (you need to be logged in), you can install it alongside the existing app and will need to re-add the controls for the test version of the app.

I installed the app and it doesn't crash. On click the app opens and takes me to the entity. On hold can I drag them around. It works!

**Comment by jpelgrom** [comment] 2022-05-09 17:12
> On click the app opens and takes me to the entity. On hold can I drag them around. It works!

Thanks, sounds good! Just to confirm because Samsung seems to have changed how controls work a bit: can you also still toggle entities such as lights/switches using the smaller button on the tile?

**Comment by dshokouhi** [comment] 2022-07-22 18:21
Closing due to lack of response

**Closed by dshokouhi** 2022-07-22 18:21 UTC
Labels: bug
