### ISSUE TITLE
Virtual HA, PC can connect (browser) but mobile (browser of app) can not

### ISSUE THREAD

**Issue by RensDuijsens** [home-assistant/android#2013] opened 2021-12-14 17:39 UTC
Hallo all,

I see a lot of people that have difficulties with the Home Assistant on the App.
I have read as much as I could on the forum, but can not find any solution that will work.

I run HA on a VmWare instance.
All runs fine on the PC and I can connect from any browser to http://homeassistant.local:8123 or the local address http://192.168.1.15:8123 Both entries work just fine.

However.....
when I try the same on my phones or tablets, then I can not reach these URL's, hence the HA-App can not find it also.
Yes, all devices including the PC are all on the same wifi network.

**Why can't the mobile devices find the URL? 
Not in the app and not even in a browser?**

**Comment by dshokouhi** [comment] 2021-12-14 17:41
HI the issue template that gets presented when an issue is created is missing here and we need all requested information. Please copy the template from a new issue and add back all relevant information. We will need application logs to investigate further.

**Comment by RensDuijsens** [comment] 2021-12-14 18:08
> Hallo all,
> 
> I see a lot of people that have difficulties with the Home Assistant on the App. I have read as much as I could on the forum, but can not find any solution that will work.
> 
> I run HA on a VmWare instance. All runs fine on the PC and I can connect from any browser to http://homeassistant.local:8123 or the local address http://192.168.1.15:8123 Both entries work just fine.
> 
> However..... when I try the same on my phones or tablets, then I can not reach these URL's, hence the HA-App can not find it also. Yes, all devices including the PC are all on the same wifi network.
> 
> **Why can't the mobile devices find the URL? Not in the app and not even in a browser?**

Sorry........no template is presented.
How do I obtain it please?

**Comment by dshokouhi** [comment] 2021-12-14 18:11
> How do I obtain it please?

by creating a new issue once logged into github you can copy the template and add in all relevant info, including device logs which are required to troubleshoot a connection issue.

https://github.com/home-assistant/android/issues/new?assignees=&labels=bug&template=Bug_report.md&title=

**Comment by dshokouhi** [comment] 2021-12-14 18:18
One important note, if you are unable to connect using a Chrome for Android on the device then indeed the app will not work and this is not an app issue if that is the case.

**Comment by dshokouhi** [comment] 2021-12-14 18:39
duplicate of #2014

**Closed by dshokouhi** 2021-12-14 18:39 UTC
