### ISSUE TITLE
input_number (slider) value not always displayed

### ISSUE THREAD

**Issue by Youpimatin** [home-assistant/android#1215] opened 2020-11-26 14:42 UTC
**Home Assistant Android version:** 3.0.2-full
**Android version:** 7.0
**Phone model:** Huawei Honor 5C
**Home Assistant version:** 0.118.3
**Last working Home Assistant release (if known):** -
**Description of problem:**
When app is started in portrait mode, the values are never displayed at the right of the sliders, even if I switch to landscape mode.

When app is started in landscape mode, the values are displayed at the right of the sliders, even if I switch to portrait mode.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
When app is started in portrait mode, the values are never displayed at the right of the sliders, even if I switch to landscape mode.
![Screenshot_20201126-153321 - P1](https://user-images.githubusercontent.com/55438591/100363842-97815900-2ffd-11eb-8667-6c9ac304e8e9.png) ![Screenshot_20201126-153339 - P2](https://user-images.githubusercontent.com/55438591/100363846-98b28600-2ffd-11eb-8a0a-684a1611ef0c.png)

.

When app is started in landscape mode, the values are displayed at the right of the sliders, even if I switch to portrait mode.
![Screenshot_20201126-153512 - L1](https://user-images.githubusercontent.com/55438591/100363870-a10ac100-2ffd-11eb-9598-0c574304c594.png) ![Screenshot_20201126-153524 - L2](https://user-images.githubusercontent.com/55438591/100363882-a49e4800-2ffd-11eb-961c-b7d83329c376.png)

**Additional information:**

**Comment by dshokouhi** [comment] 2020-11-26 15:29
Does this exist in chrome for Android?

**Comment by Youpimatin** [comment] 2020-11-26 15:38
Yes, it's the same on Chrome for Android, and on Firefox for Android

**Comment by dshokouhi** [comment] 2020-11-26 15:49
This is not an issue with the app but with the front end of HA.

**Comment by Youpimatin** [comment] 2020-11-26 15:54
OK, can I (or somebody with the permissions) move the topic to the good category ?

**Comment by dshokouhi** [comment] 2020-11-26 16:04
Would you say your issue is a duplicate of <https://github.com/home-assistant/frontend/issues/2905>? Its always a good idea to search before assuming the issue does not exist.

**Comment by Youpimatin** [comment] 2020-11-26 16:07
It may be linked !

I did seached, but only on the android sub-section.

**Comment by dshokouhi** [comment] 2020-11-26 16:08
Closing as duplicate of the above.

**Closed by dshokouhi** 2020-11-26 16:08 UTC
Labels: bug

**Comment by Youpimatin** [comment] 2020-11-26 16:14
Can't we merge the subjects, because the problem is linked, but the effet is slightly different, since the scrren size is fixed, and there is no resize possible ?
