### ISSUE TITLE
Add a sensor for whether Work Profile is enabled

### ISSUE THREAD

**Issue by nielsrowinbik** [home-assistant/android#1728] opened 2021-09-28 12:10 UTC
**Is your feature request related to a problem? Please describe.**
I have created a so called "work mode" (see [code](https://github.com/nielsrowinbik/home/blob/master/packages/work_mode.yaml)) in my Home Assistant instance that turns on the lights at my desk, sends a push notification through my phone, etc. I currently have no way of syncing this work mode (and, in turn, the lights at my desk) with the [work profile](https://developer.android.com/work/managed-profiles) on my android phone, which can be toggled on and off.

**Describe the solution you'd like**
I would like a sensor that reflects the state of the [work profile](https://developer.android.com/work/managed-profiles) on my phone in Home Assistant (could be a `binary_sensor` since it is either `on` or `off`), so that I can sync the state of my phone's work profile with my Home Assistant's work mode.

**Describe alternatives you've considered, if any**
I do not see any alternatives. Suggestions are welcome!

**Additional context**
I suppose the sensor could work much like the [Do Not Disturb sensor](https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/sensors/DNDSensorManager.kt), assuming there is a similar variable.

**Comment by dshokouhi** [comment] 2021-09-28 13:48
Looking online this will be a binary sensor as we can only check if any app is opened in work profile or not. If any app is opened in the work profile then we know the profile is enabled.

Here is the stackoverflow link to get the answer: https://stackoverflow.com/a/50869390

**Comment by nielsrowinbik** [comment] 2021-09-28 15:11
Thanks for the comment @dshokouhi. If that's the only way to know whether the profile is turned on or not then it kind of defeats the purpose for me. I'd also have to get my employer to enable the Home Assistant app to be downloaded from the work profile's Play Store which I doubt I'll be able to do ;).

The ideal solution would allow for the sensor to indicate whether the work profile is turned on or off from within the "personal" profile. I'll have a look online later to see if this can be done at all on Android.

**Comment by dshokouhi** [comment] 2021-09-28 15:26
@nielsrowinbik to my understanding all the app does is query each app to see if its running in the work profile and if it is then that means the work profile is enabled. There is no direct API to check, each app has to be checked individually.  Its not checking the HA app by itself, its checking every app on the device so it should work as intended I would imagine.  Heres a link to the actual API that would be used.

https://developer.android.com/reference/android/app/admin/DevicePolicyManager#isDeviceOwnerApp(java.lang.String)

This might be as good as it gets if there is no direct API that we can find in Androids documentation.

**Comment by dshokouhi** [comment] 2021-10-01 21:51
@nielsrowinbik can you try the debug APK from: https://github.com/home-assistant/android/actions/runs/1296716604

Let me know if it works for you, if it doesn't I can try to add some debugging lines to see if we can figure it out. I don't have a work profile so won't be easy for me to test. You can install it side by side the production app for testing, just change the device name so its easier to remove later.

**Comment by nielsrowinbik** [comment] 2021-10-02 06:27
@dshokouhi So it turns out that as part of enabling the work profile (which installs some policies on my device and allows the managing organisation to set some rules in terms of security and such) the ability to install APK's not from the Play Store was disabled. 😕

I'll try to remove the work profile entirely, install the app, and add the work profile again to see if that works. Probably won't het around to doing that today, but I'll get back to you ASAP!

**Comment by dshokouhi** [comment] 2021-10-02 16:37
yea I was thinking about that, if the apps background process can't run then not much we can do here in terms of detecting the work profile state, look forward to your test results hopefully it will just work like those on stackoverflow have mentioned :)

**Comment by nielsrowinbik** [comment] 2021-10-08 06:40
@dshokouhi It's take me a while but I've finally gotten around to testing this. I'm afraid it does not work. What I've done:

1. Installed the APK on a freshly reset Pixel 2XL running Android 11, connected it to my Home Assistant instance, and enabled the work profile sensor that you added.
2. Installed the [Test DPC](https://play.google.com/store/apps/details?id=com.afwsamples.testdpc&hl=en&gl=US) app to create a work profile (maybe you can use this to further debug the issue).
3. Checked the sensor's state, it was `off`.
4. Toggled the work profile off (thus pausing all the apps). Sensor was still `off`.
5. Toggled the work profile back on. Sensor was still `off`.

Let me know if there's anything else I can do.

**Comment by dshokouhi** [comment] 2021-10-08 15:22
@nielsrowinbik  does the app continue to update the other sensors when your work profile is enabled?

**Comment by nielsrowinbik** [comment] 2021-10-11 05:03
@dshokouhi I checked using the next alarm sensor: yes it does.

**Comment by dshokouhi** [comment] 2021-10-11 19:39
Not having much luck with the above intents nor is there anything useful in ADB logcat :(

**Comment by zmarties** [comment] 2021-12-19 12:44
The intents mentioned above are the correct ones, but they won't be received automatically - you have to explicitly register to receive them.

I've coded a working version of the sensor in https://github.com/home-assistant/android/pull/2026.

**Comment by zmarties** [comment] 2022-01-08 11:32
Can someone with the correct permissions please close this issue - the work sensor is now available in the released app.

**Closed** 2022-01-08 15:39 UTC
Labels: enhancement, sensor-tracking
