### ISSUE TITLE
Wear OS Shortcuts Tile - Change Colour depending on state

### ISSUE THREAD

**Issue by seanmccabe** [home-assistant/android#3320] opened 2023-02-08 18:50 UTC
**Is your feature request related to a problem? Please describe.**
Not a problem per se.

**Describe the solution you'd like**
When viewing the shortcuts tile, the entities shown there should be HA blue (though I'm sure people will ask for a setting to customise the colour) to indicate the entity is in an on state.
This would work the same way as notification tiles on Android Phones, showing the state if off or on.
Same as the favourites, they indicate the state.

This would also help a lot knowing if you have tapped the tile and know it should go from off/on/off, and knowing the state has been updated.

I often find myself tapping the entity, but then having to check on my phone as to whether the state has changed (faster than trying to confirm on the watch as I'm not always sure what the original state was.

**Describe alternatives you've considered, if any**
No other options, other than not doing it.

**Comment by dshokouhi** [comment] 2023-02-08 18:59
duplicate of https://github.com/home-assistant/android/issues/2045

**Closed by dshokouhi** 2023-02-08 18:59 UTC
Labels: enhancement

**Comment by seanmccabe** [comment] 2023-02-08 19:10
Thanks, I did search, but searching shortcuts tile this relates to didn't bring up the other issue.
Prob could do with renaming the issue so it's not quite so generic.
