### ISSUE TITLE
Wrong Time in next_alarm

### ISSUE THREAD

**Issue by Sk0ppes** [home-assistant/android#1526] opened 2021-04-25 20:52 UTC
**Home Assistant Android version:** 2021.4.1-full

**Android version:** 11

**Phone model:** Xiaomi Mi 10T Pro

**Home Assistant version:** core-2021.4.6

**Last working Home Assistant release (if known):**

**Description of problem:** My Time zone is Europe/Berlin (UTC+02:00) and when i set an alarm on my phone, the value of the next_alarm sensor is off by 1 hour. The Alarm is set to 8 am and in the developer tools the next_alarm has a value of '07:00:00 GMT+02:00'.
I guess it could be because of the daylight saving time, but i don't really know.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![photo_2021-04-25_22-46-23](https://user-images.githubusercontent.com/23423180/116009149-3398a600-a618-11eb-839d-25ff0d088f13.jpg)
![image](https://user-images.githubusercontent.com/23423180/116009158-44e1b280-a618-11eb-976a-698eb5456e9b.png)

**Additional information:**

**Comment by dshokouhi** [comment] 2021-04-25 21:01
The date and time provided is what we get from the API. There is no other conversion going on.  Xiaomi stock apps are known not to report correct time so its best to avoid them.

Duplicate of #748 #799 #1085 #1109

**Closed by dshokouhi** 2021-04-25 21:01 UTC
Labels: bug
