### ISSUE TITLE
Swipe through tabs

### ISSUE THREAD

**Issue by SquaredCircleHunter** [home-assistant/android#1597] opened 2021-06-27 07:28 UTC
**Is your feature request related to a problem? Please describe.**

I have a lot of tabs in my dashboard. Scrolling trough them on the top is quite tedious.

**Describe the solution you'd like**

It would be nice if swiping to left or right anywhere on the screen switches tabs. Maybe require opt-in 
in App configuration to avoid breaking the app if swipe actions are already used somehow by some users.

**Describe alternatives you've considered, if any**

Official support for https://github.com/maykar/lovelace-swipe-navigation

**Additional context**

**Comment by dshokouhi** [comment] 2021-07-01 20:37
This would be more of a frontend request than an app request, I suggest you open a feature request/discussion there.  For the time being you are using what most users use.

duplicate of #202 #315 #328 #607

**Closed by dshokouhi** 2021-07-01 20:37 UTC

**Comment by SquaredCircleHunter** [comment] 2021-07-03 06:58
Sorry for the duplicate.

I was thinking that exposing 'native' gestures (ie directly registered by Android OS) to the frontend is a better approach than capturing them in javascript logic (and tuning all kind of parameters).

My knowledge of Android is insufficient, this might be already handled by the WebView component.
